xwiki-platform-core/xwiki-platform-mail/xwiki-platform-mail-send/xwiki-platform-mail-send-default/src/main/java/org/xwiki/mail/script/AbstractMailScriptService.java, xwiki-platform-core/xwiki-platform-mail/xwiki-platform-mail-send/xwiki-platform-mail-send-default/src/main/java/org/xwiki/mail/script/MailSenderScriptService.java, xwiki-platform-core/xwiki-platform-mail/xwiki-platform-mail-send/xwiki-platform-mail-send-storage/pom.xml, xwiki-platform-core/xwiki-platform-mail/xwiki-platform-mail-send/xwiki-platform-mail-send-storage/src/main/java/org/xwiki/mail/MailStorageScriptService.java, xwiki-platform-core/xwiki-platform-mail/xwiki-platform-mail-send/xwiki-platform-mail-send-storage/src/test/java/org/xwiki/mail/internal/DatabaseMailListenerTest.java, xwiki-platform-core/xwiki-platform-mail/xwiki-platform-mail-ui/src/main/resources/Mail/SendMailStatus.xml
* Create AbstractMailScriptService
* Minor fixes
* Update Admin UI
=> XWIKI-11486: Batch API to send large volumes of mail

xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-server/xwiki-platform-search-solr-server-data/src/main/resources/xwiki/conf/schema.xml
Correction of language code and adding remove accents for Czech language.
=> XWIKI-11897: Search not working through documents in Czech language

xwiki-platform-core/xwiki-platform-ratings/xwiki-platform-ratings-api/src/main/java/org/xwiki/ratings/internal/SeparatePageRating.java, xwiki-platform-core/xwiki-platform-ratings/xwiki-platform-ratings-ui/src/main/resources/XWiki/RatingsTranslations.xml
- save as minor edit
- provide a message when saving the rating document
=> XWIKI-11972 : Separate rating pages should have an author

xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/doc/XWikiDocument.java
* Refactor and simplify the code
=> XWIKI-10252: Add and/or edit objects in a page

xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-test-pageobjects/src/main/java/org/xwiki/appwithinminutes/test/po/AppWithinMinutesHomePage.java, xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-ui/src/main/resources/AppWithinMinutes/ClassEditSheet.xml
* Since the default space is configurable, I used $services.model method to find out the homepage.
=> XWIKI-11922: New App from AWM should have Main.WebHome as parent page

xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/js/xwiki/table/livetable.css
=> XWIKI-9924: Inconsistent font size and font weight in the tag cloud container header

xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/js/scriptaculous/dragdrop.js
dragdrop.js changed to pass event into onHover callback.
=> XWIKI-12340: Drag and drop UI needs better feedback for onHover event

xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-model/src/main/resources/xwiki.rest.model.xsd, xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-server/src/main/java/org/xwiki/rest/internal/ModelFactory.java, xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-server/src/main/java/org/xwiki/rest/internal/representations/pages/FormUrlEncodedPageReader.java
* return 'hidden' property when GET a page
* set 'hidden' property when PUT a page in 'application/xml'
* set 'hidden' property when PUT a page in 'application/x-www-form-urlencoded'
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/xwiki/xwiki-platform/445)
=> [XWIKI-12783] Add hidden property for pages in REST API

xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-server/src/main/java/org/xwiki/rest/internal/representations/TextPlainReader.java, xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-server/src/main/java/org/xwiki/rest/internal/representations/tags/TextPlainTagsReader.java
* Use IOUtils.toString() to convert from InputStream to String
* Add the possibility to have multi-lines plain text for adding multiple tags
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/xwiki/xwiki-platform/446)
=> XWIKI-12787: Keep new lines when PUT/POST text/plain

xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-macros/xwiki-platform-rendering-macro-rss/src/main/java/org/xwiki/rendering/internal/macro/rss/DefaultRomeFeedFactory.java
=> XWIIKI-13284 Add support for loading RSS feeds over HTTPS in the RSS macro

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-tests/pom.xml
=> XWIKI-13277: Add Rename operation Page Object & Tests

xwiki-platform-distribution/xwiki-platform-distribution-flavor/src/main/resources/Main/WebHome.xml, xwiki-platform-distribution/xwiki-platform-distribution-flavor/src/main/resources/XWiki/XWikiPreferences.xml
- Replacing the Dashboard include with help content
- Adding a SSX to style the used table
=> XWIKI-13478: On Homepage, replace Dashboard include with content

xwiki-platform-core/xwiki-platform-application/xwiki-platform-application-ui/src/main/resources/Applications/Macros.xml, xwiki-platform-core/xwiki-platform-application/xwiki-platform-application-ui/src/main/resources/Applications/WebHome.xml
Created Application.WebHome and Application.Macros
=> XWIKI-11423 : Create an Application Index

xwiki-platform-core/pom.xml, xwiki-platform-core/xwiki-platform-application/pom.xml, xwiki-platform-core/xwiki-platform-application/xwiki-platform-application-ui/pom.xml, xwiki-platform-core/xwiki-platform-application/xwiki-platform-application-ui/src/main/resources/Applications/Macros.xml, xwiki-platform-core/xwiki-platform-application/xwiki-platform-application-ui/src/main/resources/Applications/Translations.xml, xwiki-platform-core/xwiki-platform-application/xwiki-platform-application-ui/src/main/resources/Applications/WebHome.xml
Have a first iteration for the Application Index, by listing all the applications that have the ''org.xwiki.platform.panels.Applications" extensionPointId.
=> XWIKI-11423: Create an Application Index

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/macros.vm, xwiki-platform-core/xwiki-platform-web/src/main/webapp/templates/macros.vm
(merge/adapt with last macros.vm version)
=> XWIKI-6118: add boolean list to filter livetable

xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-ui/src/main/resources/XWiki/Registration.xml
* there is no reason to submit the form on Cancel action
=> XWIKI-13563 : Cancel button adds a new user instead of canceling the user creation

xwiki-platform-core/xwiki-platform-ratings/xwiki-platform-ratings-api/pom.xml, xwiki-platform-core/xwiki-platform-ratings/xwiki-platform-ratings-api/src/main/java/org/xwiki/ratings/ConfiguredRatingsManagerProvider.java, xwiki-platform-core/xwiki-platform-ratings/xwiki-platform-ratings-api/src/main/java/org/xwiki/ratings/ConfiguredReputationAlgorithmProvider.java, xwiki-platform-core/xwiki-platform-ratings/xwiki-platform-ratings-api/src/main/java/org/xwiki/ratings/RatingsConfiguration.java, xwiki-platform-core/xwiki-platform-ratings/xwiki-platform-ratings-api/src/main/java/org/xwiki/ratings/internal/AbstractRatingsManager.java, xwiki-platform-core/xwiki-platform-ratings/xwiki-platform-ratings-api/src/main/java/org/xwiki/ratings/internal/DefaultRatingsConfiguration.java, xwiki-platform-core/xwiki-platform-ratings/xwiki-platform-ratings-api/src/main/java/org/xwiki/ratings/internal/SeparatePageRatingsManager.java, xwiki-platform-core/xwiki-platform-ratings/xwiki-platform-ratings-api/src/main/java/org/xwiki/ratings/script/RatingsScriptService.java, xwiki-platform-core/xwiki-platform-ratings/xwiki-platform-ratings-api/src/main/resources/META-INF/components.txt, xwiki-platform-core/xwiki-platform-ratings/xwiki-platform-ratings-api/src/test/java/org/xwiki/ratings/internal/DefaultRatingsConfigurationTest.java, xwiki-platform-core/xwiki-platform-ratings/xwiki-platform-ratings-ui/src/main/resources/XWiki/Ratings.xml
This PR replaces [472](https://github.com/xwiki/xwiki-platform/pull/472) (there are also some comments).
=> XWIKI-13274 : Add NS support for Ratings space configuration

xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-profile/xwiki-platform-user-profile-ui/src/main/resources/XWiki/XWikiUserPreferencesSheet.xml
[misc] replaced ' with " for the HTML attribute values
=> XWIKI-6307: Add an explanation next to the fields in user profile

xwiki-platform-core/xwiki-platform-blog/xwiki-platform-blog-ui/src/main/resources/Blog/BlogCode.xml, xwiki-platform-core/xwiki-platform-blog/xwiki-platform-blog-ui/src/main/resources/Blog/BlogParameters.xml, xwiki-platform-core/xwiki-platform-blog/xwiki-platform-blog-ui/src/main/resources/Blog/BlogStyle.xml, xwiki-platform-core/xwiki-platform-blog/xwiki-platform-blog-ui/src/main/resources/Blog/Categories.xml, xwiki-platform-core/xwiki-platform-blog/xwiki-platform-blog-ui/src/main/resources/Blog/CategoriesCode.xml, xwiki-platform-core/xwiki-platform-blog/xwiki-platform-blog-ui/src/main/resources/Blog/CategoriesPanel.xml, xwiki-platform-core/xwiki-platform-blog/xwiki-platform-blog-ui/src/main/resources/Blog/CategorySheet.xml, xwiki-platform-core/xwiki-platform-blog/xwiki-platform-blog-ui/src/main/resources/Blog/CreatePost.xml, xwiki-platform-core/xwiki-platform-blog/xwiki-platform-blog-ui/src/main/resources/Blog/ManageCategories.xml
Previous commit (that I closed without purpose :-/). This one is correct
=> XWIKI-13818:Apply same flamingo icone on blog (I hate git)

xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/web/TempResourceAction.java
Added "force-filename" request parameter to specify the custom file name.
=> XWIKI-13869: Option to use custom file name for file download

xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-server/src/main/java/org/xwiki/rest/internal/representations/TextPlainReader.java
=> XWIKI-13919: Setting an xproperty to the empty string via REST fails

xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-ui/src/main/resources/XWiki/Registration.xml, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/XWiki.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/resources/ApplicationResources.properties
This pull request is a replacement for #535.
=> XWIKI-13679  User is still added after error registration has failed due to unknown reasons error code -10

xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-api/src/main/java/org/xwiki/notifications/NotificationConfiguration.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-api/src/main/java/org/xwiki/notifications/internal/DefaultNotificationConfiguration.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-api/src/main/java/org/xwiki/notifications/script/NotificationScriptService.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-api/src/main/resources/META-INF/components.txt, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-default/src/main/java/org/xwiki/notifications/internal/NotificationConfiguration.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-ui/src/main/resources/XWiki/Notifications/Code/NotificationsDisplayerUIX.xml, xwiki-platform-tools/xwiki-platform-tool-configuration-resources/src/main/resources/xwiki.properties.vm
Add `UIEnabled` flag for `xwiki-platform-notifications` extension
=> XWIKI-14218: Add the ability to disable the notifications

xwiki-platform-core/xwiki-platform-notifications/pom.xml, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-api/pom.xml, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-test/pom.xml, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-test/xwiki-platform-notifications-test-pageobjects/pom.xml, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-test/xwiki-platform-notifications-test-pageobjects/src/main/java/org/xwiki/platform/notifications/test/po/NotificationsTrayPage.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-test/xwiki-platform-notifications-test-pageobjects/src/main/java/org/xwiki/platform/notifications/test/po/NotificationsUserProfilePage.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-test/xwiki-platform-notifications-test-tests/pom.xml, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-test/xwiki-platform-notifications-test-tests/src/test/it/org/xwiki/platform/notifications/test/ui/AllTests.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-test/xwiki-platform-notifications-test-tests/src/test/it/org/xwiki/platform/notifications/test/ui/NotificationsTest.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-ui/pom.xml
* Add functional tests for the xwiki-platform-notifications module
=> XWIKI-14238: Create functional tests for the Notifications UI

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/pom.xml, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/macros.vm, xwiki-platform-core/xwiki-platform-livetable/xwiki-platform-livetable-ui/src/main/resources/XWiki/LiveTableResultsMacros.xml, xwiki-platform-core/xwiki-platform-oldcore/src/main/resources/ApplicationResources.properties, xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/js/xwiki/table/livetabledate.js
Adds pretty [date range pickers](http://daterangepicker.com) to filter dates in livetables.
=> XWIKI-10122 and XWIKI-11084: Livetable date filter

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/macros.vm, xwiki-platform-core/xwiki-platform-livetable/xwiki-platform-livetable-ui/src/main/resources/XWiki/LiveTableResultsMacros.xml, xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/js/xwiki/table/livetable.css, xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/js/xwiki/table/livetablemulti.js
Use a nice multiselect picker and be able to filter multilists.
Screenshot:
JIRA:
https://jira.xwiki.org/browse/XWIKI-13520
=> XWIKI-13520: Use bootstrap-select for multilists in livetable

xwiki-platform-core/xwiki-platform-eventstream/xwiki-platform-eventstream-default/pom.xml, xwiki-platform-core/xwiki-platform-eventstream/xwiki-platform-eventstream-default/src/test/java/org/xwiki/eventstream/internal/EventClassDocumentInitializerTest.java
* Fix code coverage
* Add unit tests
=> XWIKI-14348: Allow registration of custom events in wiki pages

xwiki-platform-core/xwiki-platform-activitystream/xwiki-platform-activitystream-api/src/main/java/com/xpn/xwiki/plugin/activitystream/eventstreambridge/BridgeEventStream.java, xwiki-platform-core/xwiki-platform-activitystream/xwiki-platform-activitystream-api/src/main/java/com/xpn/xwiki/plugin/activitystream/impl/ActivityStreamImpl.java, xwiki-platform-core/xwiki-platform-eventstream/xwiki-platform-eventstream-api/src/main/java/org/xwiki/eventstream/events/AbstractEventStreamEvent.java
* Add triggers in ActivityStreamImpl
=> XWIKI-14507: Allow actions in the event stream to be observed

xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/uicomponents/dashboard/dashboard.js
* Fix the bug by editing container classes
=> XWIKI-14504: Adding a new column in the dashboard editor does not work anymore

xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-api/src/main/java/org/xwiki/notifications/internal/email/AbstractMimeMessageIterator.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-api/src/main/java/org/xwiki/notifications/internal/email/live/LiveMimeMessageIterator.java
* Change scope of AbstractMimeMessageIterator#logger
=> XWIKI-14554: Live Notifications aren't sent, error in the console

xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-api/src/main/java/org/xwiki/notifications/script/NotificationScriptService.java
* Add permission check in NotificationScriptService#setStartDate
=> XWIKI-14531: NotificationScriptService#setStartDate(String, Date) should check user permissions

xwiki-platform-core/xwiki-platform-eventstream/xwiki-platform-eventstream-default/src/main/java/org/xwiki/eventstream/internal/DefaultUntypedRecordableEventDescriptor.java, xwiki-platform-core/xwiki-platform-eventstream/xwiki-platform-eventstream-default/src/main/java/org/xwiki/eventstream/internal/EventClassDocumentInitializer.java, xwiki-platform-core/xwiki-platform-eventstream/xwiki-platform-eventstream-default/src/test/java/org/xwiki/eventstream/internal/EventClassDocumentInitializerTest.java
* Add applicationId field in EventClass XClass
* Update DefaultUntypedRecordableEventDescriptor
=> XWIKI-14559: Add applicationId parameter to events defined in wiki pages

xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/uicomponents/widgets/gallery/gallery.css
Added max-width to prevent gallery to get out of container.
=> XWIKI-14590: Make Gallery Macro responsive

xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-ui/src/main/resources/XWiki/AdminExportSheet.xml, xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-ui/src/main/resources/XWiki/AdminInlineSheet.xml, xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-ui/src/main/resources/XWiki/AdminLocalizationSheet.xml, xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-ui/src/main/resources/XWiki/AdminRightsSheet.xml, xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-ui/src/main/resources/XWiki/ColorThemePropertyDisplayer.xml
Update the XML document format of 5 committed wiki pages
=> [Misc] xar format

xwiki-platform-core/xwiki-platform-xar/xwiki-platform-xar-model/src/main/java/org/xwiki/xar/internal/property/ListXarObjectPropertySerializer.java
Hey! I picked this issue for my GCI Task. The link to the issue is:
http://sonar.xwiki.org/issues/search#issues=72212d35-81ee-49e7-87a7-4db75137367c
And the link to my task is:
https://codein.withgoogle.com/dashboard/task-instances/5029182323032064/
Thanks!
=> [codestyle] Replace the synchronized class StringBuffer by an unsynchronized one such as StringBuilder.

xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/objects/BaseObject.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/objects/BaseStringProperty.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/objects/NumberProperty.java, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/objects/BaseObjectTest.java, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/objects/BaseStringPropertyTest.java, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/objects/NumberPropertyTest.java
Issues:
http://sonar.xwiki.org/issues/search#issues=a9a5d21b-472b-4e1a-8e1b-9e5307884480
http://sonar.xwiki.org/issues/search#issues=3aa0b3d9-cce9-4ca1-b6a0-62beab1e4769
http://sonar.xwiki.org/issues/search#issues=eecdcec7-0f0f-4a1b-a2ba-c97d972ec7d5
=> Add hashCode

xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/doc/XWikiLink.java, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/doc/XWikiLinkTest.java
Issues:
http://sonar.xwiki.org/issues/search#issues=1c2e5c3e-7e14-49bb-b048-1fad808f1a1b
http://sonar.xwiki.org/issues/search#issues=e98b2a06-7886-4bb7-bf7a-d4921ccce68c
http://sonar.xwiki.org/issues/search#issues=e00e0c50-ecf8-4016-85ef-52b71b5431a9
=> XWikiLink equals

xwiki-platform-core/xwiki-platform-mail/xwiki-platform-mail-send/xwiki-platform-mail-send-default/src/main/java/org/xwiki/mail/script/ScriptMimeMessage.java, xwiki-platform-core/xwiki-platform-mail/xwiki-platform-mail-send/xwiki-platform-mail-send-default/src/test/java/org/xwiki/mail/script/ScriptMimeMessageTest.java
I'm not completely sure if this is the way you wanted it, let me know what you were looking for.
=> XWiki-12180 : ScriptMimeMessage#addPart should support BodyPart

xwiki-platform-core/xwiki-platform-extension/xwiki-platform-extension-handlers/xwiki-platform-extension-handler-xar/src/main/resources/ApplicationResources.properties
I tried improving the translations, structuring the sentences in a more lucid way and fixed grammatical mistakes.
=> Fixed grammatical and syntax issues with translation

xwiki-platform-core/xwiki-platform-annotations/xwiki-platform-annotation-ui/src/main/resources/AnnotationCode/AnnotateMenuUIX.xml, xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-ui/src/main/resources/AppWithinMinutes/DateDisplayer.xml, xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-ui/src/main/resources/AppWithinMinutes/DeleteApplication.xml, xwiki-platform-core/xwiki-platform-extension/xwiki-platform-extension-ui/src/main/resources/XWiki/ExtensionHistory.xml, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-ui/src/main/resources/Main/Search.xml
=> Updated XML format of 5 files

xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-ui/src/main/resources/AppWithinMinutes/LiveTableClass.xml, xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-ui/src/main/resources/AppWithinMinutes/LiveTableEditSheet.xml, xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-ui/src/main/resources/AppWithinMinutes/LiveTableGenerator.xml, xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-ui/src/main/resources/AppWithinMinutes/LiveTableTemplate.xml, xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-ui/src/main/resources/AppWithinMinutes/LiveTableViewSheet.xml, xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-ui/src/main/resources/AppWithinMinutes/MetadataClass.xml, xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-ui/src/main/resources/AppWithinMinutes/Number.xml, xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-ui/src/main/resources/AppWithinMinutes/Pickers.xml, xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-ui/src/main/resources/AppWithinMinutes/Standard.xml, xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-ui/src/main/resources/AppWithinMinutes/StaticList.xml
I have run `mvn xar:format` on 10 files
=> Update 10 XML Files

xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-ui/src/main/resources/AppWithinMinutes/DBList.xml, xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-ui/src/main/resources/AppWithinMinutes/Document.xml, xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-ui/src/main/resources/AppWithinMinutes/DynamicMessageTool.xml, xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-ui/src/main/resources/AppWithinMinutes/FormFieldCategoryClass.xml, xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-ui/src/main/resources/AppWithinMinutes/FormFieldClass.xml, xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-ui/src/main/resources/AppWithinMinutes/Groups.xml, xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-ui/src/main/resources/AppWithinMinutes/String.xml, xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-ui/src/main/resources/AppWithinMinutes/TemplateProviderEditSheet.xml, xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-ui/src/main/resources/AppWithinMinutes/TextArea.xml, xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-ui/src/main/resources/AppWithinMinutes/Title.xml, xwiki-platform-core/xwiki-platform-mail/xwiki-platform-mail-ui/src/main/resources/Mail/GeneralMailConfigClass.xml, xwiki-platform-core/xwiki-platform-mail/xwiki-platform-mail-ui/src/main/resources/Mail/GeneralMailConfigSheet.xml, xwiki-platform-core/xwiki-platform-mail/xwiki-platform-mail-ui/src/main/resources/Mail/MailConfig.xml, xwiki-platform-core/xwiki-platform-mail/xwiki-platform-mail-ui/src/main/resources/Mail/SendMailConfigClass.xml, xwiki-platform-core/xwiki-platform-mail/xwiki-platform-mail-ui/src/main/resources/Mail/SendMailConfigSheet.xml
Applied an xar format on each file
=> Update format of 15 XML files

xwiki-platform-core/xwiki-platform-annotations/xwiki-platform-annotation-core/src/test/java/org/xwiki/annotation/AnnotationsMockSetup.java, xwiki-platform-core/xwiki-platform-component/xwiki-platform-component-multi/src/test/java/org/xwiki/component/internal/ContextComponentManagerTest.java, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/test/AbstractXWikiComponentTestCase.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/test/java/org/xwiki/refactoring/internal/AbstractRefactoringTestCase.java, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-macros/xwiki-platform-rendering-macro-rss/src/test/java/org/xwiki/rendering/macro/rss/IntegrationTests.java, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-wikimacro/xwiki-platform-rendering-wikimacro-api/src/test/java/org/xwiki/rendering/internal/macro/wikibridge/DefaultWikiMacroTest.java
For task "Replace calls to deprecated APIs by more up to date alternatives "
=> Change usages of DefaultComponentRole<T>'s setRole (deprecated) to setRoleType

xwiki-platform-core/xwiki-platform-index/xwiki-platform-index-ui/src/main/resources/XWiki/DeletedAttachments.xml, xwiki-platform-core/xwiki-platform-index/xwiki-platform-index-ui/src/main/resources/XWiki/DeletedDocumentsJSON.xml
for GCI task https://codein.withgoogle.com/dashboard/task-instances/6562152821293056/
=> Date Filter for Deleted Pages and Deleted Attachments

xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/js/xwiki/table/livetabledate.js
XWIKI-14909: Restore ability to filter dates manually in LiveTables for GCI Task https://codein.withgoogle.com/dashboard/task-instances/5619611946975232/
=> XWIKI-14909: Restore ability to filter dates manually in LiveTables

xwiki-platform-core/xwiki-platform-filter/xwiki-platform-filter-ui/src/main/resources/Filter/ApplicationsPanelEntry.xml, xwiki-platform-core/xwiki-platform-filter/xwiki-platform-filter-ui/src/main/resources/Filter/FilterStreamJobJSON.xml
Fixed [XWIKI-15035](https://jira.xwiki.org/browse/XWIKI-15035):
=> XWIKI-15035: Code pages in Filter application should be hidden

xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/store/XWikiHibernateStore.java
https://jira.xwiki.org/browse/XWIKI-15161
=> XWIKI-15161: XWikiHibernateStore ConcurrentModificationException

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/contentview.vm, xwiki-platform-core/xwiki-platform-web/src/main/webapp/templates/accessdenied.vm
JIRA reference: https://jira.xwiki.org/browse/XWIKI-15112
=> XWIKI-15112 - Add an XWiki.AccessDenied customization option

xwiki-platform-core/pom.xml, xwiki-platform-core/xwiki-platform-query/xwiki-platform-query-jpql-parser/pom.xml, xwiki-platform-core/xwiki-platform-query/xwiki-platform-query-jpql-parser/src/main/sablecc/JPQL.grammar, xwiki-platform-core/xwiki-platform-query/xwiki-platform-query-jpql-parser/src/test/java/org/xwiki/query/jpql/internal/JPQLParserTest.java
https://jira.xwiki.org/browse/XWIKI-15251
=> XWIKI-15251: XWQL queries do not support "group by 1" or "order by 1"

xwiki-platform-core/xwiki-platform-query/xwiki-platform-query-xwql/pom.xml, xwiki-platform-core/xwiki-platform-query/xwiki-platform-query-xwql/src/main/java/org/xwiki/query/xwql/internal/hql/PropertyPrinter.java, xwiki-platform-core/xwiki-platform-query/xwiki-platform-query-xwql/src/test/java/org/xwiki/query/xwql/internal/XWQLtoHQLTranslatorTest.java
See https://jira.xwiki.org/browse/XWIKI-15250
=> XWIKI-15250: XWQL group by not working on multiselect lists

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/macros.vm, xwiki-platform-core/xwiki-platform-web/src/main/webapp/templates/macros.vm
JIRA reference: https://jira.xwiki.org/browse/XWIKI-14799
=> XWIKI-14799: Automatically set the content to HTML when using doc.location in Livetables

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/editactions.vm, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/editwiki.vm, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/edit.less, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/layout.less, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/misc.less, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/preview.vm, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/previewactions.vm, xwiki-platform-core/xwiki-platform-oldcore/src/main/resources/ApplicationResources.properties, xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/js/xwiki/actionbuttons/actionButtons.css, xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/js/xwiki/actionbuttons/actionButtons.js, xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/js/xwiki/editors/autosave.css, xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/uicomponents/widgets/fullScreen.css, xwiki-platform-core/xwiki-platform-web/src/main/webapp/templates/editwysiwyg.vm
Design page: http://design.xwiki.org/xwiki/bin/view/Proposal/IdeaVisibleSave
Jira: https://jira.xwiki.org/browse/XWIKI-14162
*Wiki editor:*
*WYSIWYG editor:*
*Class/Objects editor:*
*Inline form editor:*
*Responsiveness: (we might want to do something for that)*
*Fullscreen:*
=>  XWIKI-14162: Position Save buttons on a fixed-bottom area

xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/js/xwiki/editors/dataeditors.js
Add missing event trigger from last PR (#751).
=> XWIKI-15366: Make the sticky save bar have a smoother transition

xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-api/src/main/java/org/xwiki/icon/IconManager.java, xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-api/src/main/java/org/xwiki/icon/IconRenderer.java, xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-api/src/main/java/org/xwiki/icon/IconSet.java, xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-default/src/main/java/org/xwiki/icon/internal/DefaultIconManager.java, xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-default/src/main/java/org/xwiki/icon/internal/DefaultIconRenderer.java, xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-default/src/main/java/org/xwiki/icon/internal/DefaultIconSetLoader.java, xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-default/src/test/java/org/xwiki/icon/internal/DefaultIconManagerTest.java, xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-default/src/test/java/org/xwiki/icon/internal/DefaultIconRendererTest.java, xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-default/src/test/java/org/xwiki/icon/internal/DefaultIconSetLoaderTest.java, xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-default/src/test/resources/test.iconset, xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-fontawesome/src/main/resources/IconThemes/FontAwesome.xml, xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-script/src/main/java/org/xwiki/icon/IconManagerScriptService.java, xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-ui/src/main/resources/IconThemes/Silk.xml, xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/icons/default.iconset
* Add a render custom method in the icon API and icon script service.
* Add a method to retreive the icon set used for an icon.
* Add a method to pull icon resources in the icon API and icon script
service.
* Write related tests.
See https://jira.xwiki.org/browse/XWIKI-15389
=> XWIKI-15389: Improve the icon API for REST API usage

xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-server/src/test/java/org/xwiki/rest/internal/resources/classes/AbstractListClassPropertyValuesProviderTest.java, xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-server/src/test/java/org/xwiki/rest/internal/resources/classes/DBListClassPropertyValuesProviderTest.java, xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-server/src/test/java/org/xwiki/rest/internal/resources/classes/GroupsClassPropertyValuesProviderTest.java, xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-server/src/test/java/org/xwiki/rest/internal/resources/classes/UsersClassPropertyValuesProviderTest.java
* Migrate class property provider tests to JUnit 5.
=> [Misc] Migrate some tests to JUnit 5

xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/po/SuggestInputElement.java, xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/uicomponents/suggest/xwiki.selectize.js, xwiki-platform-distribution/xwiki-platform-distribution-flavor/xwiki-platform-distribution-flavor-test/xwiki-platform-distribution-flavor-test-ui/src/test/it/org/xwiki/test/ui/appwithinminutes/UserClassFieldTest.java
=> XWIKI-15434: Create a displayer for the Page field that supports autocomplete

xwiki-platform-core/xwiki-platform-menu/xwiki-platform-menu-ui/src/main/resources/Menu/MenuTranslations.xml, xwiki-platform-core/xwiki-platform-menu/xwiki-platform-menu-ui/src/main/resources/Menu/WebHome.xml
-adding and finishing the changes made in the following PR: https://github.com/xwiki/xwiki-platform/pull/658
=> XWIKI-14037: The Menu application is missing some translations(continuation)

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/commentsinline.vm
* fixed some bugs about permalink modal
* removed some space after input in permalink modal
=> XWIKI-15422: Make comments modals consistent

xwiki-platform-core/xwiki-platform-menu/xwiki-platform-menu-ui/src/main/resources/Menu/MenuSheet.xml, xwiki-platform-core/xwiki-platform-menu/xwiki-platform-menu-ui/src/main/resources/Menu/MenuTranslations.xml, xwiki-platform-core/xwiki-platform-menu/xwiki-platform-menu-ui/src/main/resources/Menu/UIExtensionSheet.xml, xwiki-platform-core/xwiki-platform-menu/xwiki-platform-menu-ui/src/main/resources/Menu/WebHome.xml
In addition to: https://github.com/xwiki/xwiki-platform/pull/794 .
Also: changed from WIKI to GLOBAL to avoid the problem with multiple sub-wikis.
=> Menu translation resource is both on demand and automatically registered

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-themes/xwiki-platform-flamingo-theme-ui/src/main/resources/FlamingoThemesCode/ThemeClass.xml, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/objects/classes/TextAreaClass.java
https://jira.xwiki.org/browse/XWIKI-15486
* Set the editor of lessCode from FlamingoThemesCode.ThemeClass to Text.
=> XWIKI-15486: Broken less code when saving FlamingoThemesCode.ThemeClass

xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-test/xwiki-platform-administration-test-pageobjects/src/main/java/org/xwiki/administration/test/po/ConfirmationModal.java, xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-test/xwiki-platform-administration-test-pageobjects/src/main/java/org/xwiki/administration/test/po/ImportAdministrationSectionPage.java, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/po/BaseModal.java, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/po/CommentsTab.java, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/po/ConfirmationModal.java, xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/uicomponents/viewers/comments.js
* replaced a bad translation
* fixed tests due to modifications made on comments structure
=> XWIKI-15422:Make comments modals consistent

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/attachment_macros.vm, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/attachmentsinline.vm, xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/js/xwiki/viewers/attachments.js
XWIKI-15527: The number of files is not updated in More actions menu and Attachments tab
=> XWIKI-15528:  Improve Delete Attachments Modal

xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/internal/mandatory/XWikiUsersDocumentInitializer.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/objects/classes/BaseClass.java, xwiki-platform-distribution/xwiki-platform-distribution-ui/xwiki-platform-distribution-ui-admin-user/src/main/resources/XWiki/Admin.xml
https://jira.xwiki.org/browse/XWIKI-15452
* Add methods to create page fields.
* Use a Page field on the Skin property of the XWikiUsers class.
We might need another picker to suggest attachments on the Avatar field.
=> XWIKI-15452: Use auto-suggestion on xproperties that can support it

xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/po/AttachmentsPane.java
* updated the po of attachments so it could see the button from the new delete modal
* updated code style
=> XWIKI-15528: Improve Delete Attachments Modal

xwiki-platform-core/xwiki-platform-activeinstalls/xwiki-platform-activeinstalls-client/xwiki-platform-activeinstalls-client-api/pom.xml, xwiki-platform-core/xwiki-platform-activeinstalls/xwiki-platform-activeinstalls-client/xwiki-platform-activeinstalls-client-api/src/main/java/org/xwiki/activeinstalls/internal/client/data/DatePingDataProvider.java, xwiki-platform-core/xwiki-platform-activeinstalls/xwiki-platform-activeinstalls-client/xwiki-platform-activeinstalls-client-api/src/test/java/org/xwiki/activeinstalls/internal/client/data/DatePingDataProviderTest.java, xwiki-platform-core/xwiki-platform-activeinstalls/xwiki-platform-activeinstalls-client/xwiki-platform-activeinstalls-client-api/src/test/java/org/xwiki/activeinstalls/internal/client/data/JavaPingDataProviderTest.java
* Make private method protected and static to be able to test it
* Add a new test to check the pseudo tested method
* Move unit test class to the same package to be able to use the
protected method.
=> misc: fix pseudo-tested method in platform-activeinstalls-client-api

xwiki-platform-core/xwiki-platform-panels/xwiki-platform-panels-api/src/main/java/org/xwiki/panels/internal/AbstractPanelsUIExtensionManager.java
https://jira.xwiki.org/browse/XWIKI-15601
When possible retrieve directly the extension reference, instead of building it based on its ID. It also allows to keep the retrocompatibility with existing menu.
Another solution would have been to put an absolute name in the menu (i.e. with wiki name), but then it would break current behaviour: users currently don't have to put an absolute name in Panels config, unless they are in a subwiki.
=> XWIKI-15601: Global menus are not displayed in subwiki

xwiki-platform-core/xwiki-platform-panels/xwiki-platform-panels-api/src/main/java/org/xwiki/panels/internal/AbstractPanelsUIExtensionManager.java
https://jira.xwiki.org/browse/XWIKI-15601
* Fix by maintaining a map with the panel order and create a
well-ordered list.
=> XWIKI-15601: Order was no longer preserved in panels

xwiki-platform-core/xwiki-platform-panels/xwiki-platform-panels-api/pom.xml, xwiki-platform-core/xwiki-platform-panels/xwiki-platform-panels-api/src/main/java/org/xwiki/panels/internal/AbstractPanelsUIExtensionManager.java, xwiki-platform-core/xwiki-platform-panels/xwiki-platform-panels-api/src/test/java/org/xwiki/panels/internal/AbstractPanelsUIExtensionManagerTest.java, xwiki-platform-core/xwiki-platform-panels/xwiki-platform-panels-api/src/test/java/org/xwiki/panels/internal/TestablePanelsUIExtensionManager.java
* Add a new unit test to check the behaviour of
AbstractPanelsUIExtensionManager
=> XWIKI-15601: Global Left/Right menus are not displayed in subwikis

xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-ui/src/main/resources/XWiki/Notifications/Code/NotificationsDisplayerUIX.xml, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-ui/src/main/resources/XWiki/Notifications/Code/Translations.xml
https://jira.xwiki.org/browse/XWIKI-15719
* Add missing titles to inputs.
This approach was used: https://www.w3.org/WAI/tutorials/forms/labels/#using-the-title-attribute
=> XWIKI-15719: .notifications-toggles inputs are missing labels

xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/web/ExportAction.java
https://jira.xwiki.org/browse/XWIKI-15457
Add an explicit escape "!" to the clause. 
When testing the produced archive was named "Foo%21.xar" but it contained "Foo!.WebHome". Not sure if I should fix also the archive name or leave it as it is.
=> XWIKI-15457: XAR Export of a page with a bang (!) in the name fails

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-pageobjects/src/main/java/org/xwiki/flamingo/sking/test/po/ExportModal.java, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-pageobjects/src/main/java/org/xwiki/flamingo/sking/test/po/OtherFormatPane.java, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-tests/src/test/it/org/xwiki/flamingo/test/ui/XARExportTest.java, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/po/BaseModal.java
* Fix XARExportTest flickering test
=> XWIKI-15444: Export UI does not export child pages if there are many (and tree has pagination)

xwiki-platform-core/xwiki-platform-job/xwiki-platform-job-handler/src/main/java/org/xwiki/job/handler/internal/question/QuestionJobResourceReferenceHandler.java
=> XWIKI-15653: Prevent users from deleting/moving/renaming pages containing XClass

xwiki-platform-core/xwiki-platform-extension/xwiki-platform-extension-script/src/main/resources/ApplicationResources.properties, xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/uicomponents/extension/history.js, xwiki-platform-core/xwiki-platform-web/src/main/webapp/templates/extensionHistory.vm
=> XWIKI-15703: Missing submit input for .extension-history-source-upload form

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/rightsUI.vm, xwiki-platform-core/xwiki-platform-wiki/xwiki-platform-wiki-ui/xwiki-platform-wiki-ui-mainwiki/src/main/resources/WikiManager/AdminWikisRightsSheet.xml
https://jira.xwiki.org/browse/XWIKI-15704
* Add an hidden input submit
=> XWIKI-15704: Missing submit input for #usersandgroupstable form

xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/main/java/org/xwiki/refactoring/job/EntityRequest.java
=> XWIKI-15819: Refactor platform-refactoring to take document author into account.

xwiki-platform-core/xwiki-platform-oldcore/src/main/resources/ApplicationResources.properties, xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/js/xwiki/usersandgroups/usersandgroups.js
https://jira.xwiki.org/browse/XWIKI-15546
* Add a comment to the request
=> XWIKI-15546: "Prevent unregistered users from viewing pages..." option use bad comment when saving the document

xwiki-platform-core/xwiki-platform-extension/xwiki-platform-extension-handlers/xwiki-platform-extension-handler-xar/pom.xml
* allow the builds to pass on jenkins: related to the timeouts
=> [Misc] Lower the mutation threshold in xwiki-platform-extension-handler-xar

xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/main/java/org/xwiki/refactoring/internal/job/AbstractEntityJob.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/main/java/org/xwiki/refactoring/internal/job/MoveJob.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/test/java/org/xwiki/refactoring/internal/job/CreateJobTest.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/test/java/org/xwiki/refactoring/internal/job/DeleteJobTest.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/test/java/org/xwiki/refactoring/internal/job/MoveJobTest.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/test/java/org/xwiki/refactoring/internal/job/RenameJobTest.java
* Fix the check of authors when copying
=> XWIKI-15864: Deep copy is not working properly

xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-macros/xwiki-platform-rendering-macro-code/src/main/java/org/xwiki/rendering/internal/macro/code/CodeMacro.java
* CodeMacro now declare its content as optional
=> XWIKI-15877: CodeMacro should declare its content as optional

xwiki-platform-core/pom.xml, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-macros/xwiki-platform-rendering-macro-rss/src/main/java/org/xwiki/rendering/internal/macro/rss/RssMacro.java, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-macros/xwiki-platform-rendering-macro-rss/src/main/java/org/xwiki/rendering/macro/rss/RssMacroParameters.java
* Refactor RssMacro to use AbstractBoxMacro instead of BoxMacro
=> XWIKI-15878: RSS macro should use AbstractBoxMacro instead of BoxMacro

xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-macros/xwiki-platform-rendering-macro-rss/src/main/java/org/xwiki/rendering/internal/macro/rss/RssMacro.java
* Fix conditions for RssMacro#getImageReference
=> XWIKI-15882: RssMacro should rely on AbstractBoxMacro helper methods

xwiki-platform-core/xwiki-platform-oldcore/src/main/resources/ApplicationResources.properties, xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/js/xwiki/editors/autosave.js
* Create the appropriate keys and use them
=> XWIKI-15854: No translation key used in autosave.js

xwiki-platform-core/xwiki-platform-panels/xwiki-platform-panels-api/pom.xml, xwiki-platform-core/xwiki-platform-panels/xwiki-platform-panels-api/src/main/java/org/xwiki/panels/internal/AbstractPanelsUIExtensionManager.java, xwiki-platform-core/xwiki-platform-panels/xwiki-platform-panels-api/src/test/java/org/xwiki/panels/internal/AbstractPanelsUIExtensionManagerTest.java
https://jira.xwiki.org/browse/XWIKI-15898
* Sort panels at the end of the process.
=> XWIKI-15898: The order of left and right panels is undeterministic

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/copy.vm, xwiki-platform-core/xwiki-platform-legacy/pom.xml, xwiki-platform-core/xwiki-platform-legacy/xwiki-platform-legacy-refactoring/pom.xml, xwiki-platform-core/xwiki-platform-legacy/xwiki-platform-legacy-refactoring/xwiki-platform-legacy-refactoring-api/pom.xml, xwiki-platform-core/xwiki-platform-legacy/xwiki-platform-legacy-refactoring/xwiki-platform-legacy-refactoring-api/src/main/aspect/org/xwiki/refactoring/script/RefactoringScriptServiceAspect.aj, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/web/DeleteAction.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/web/SaveAction.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/web/UndeleteAction.java, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/web/UndeleteActionTest.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/pom.xml, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/main/java/org/xwiki/refactoring/internal/job/AbstractCopyOrMoveJob.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/main/java/org/xwiki/refactoring/internal/job/AbstractEntityJobWithChecks.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/main/java/org/xwiki/refactoring/internal/job/CopyJob.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/main/java/org/xwiki/refactoring/internal/job/MoveJob.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/main/java/org/xwiki/refactoring/internal/job/RenameJob.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/main/java/org/xwiki/refactoring/job/AbstractCopyOrMoveRequest.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/main/java/org/xwiki/refactoring/job/CopyRequest.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/main/java/org/xwiki/refactoring/job/MoveRequest.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/main/java/org/xwiki/refactoring/script/RefactoringScriptService.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/main/java/org/xwiki/refactoring/script/RequestFactory.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/main/resources/ApplicationResources.properties, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/main/resources/META-INF/components.txt, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/test/java/org/xwiki/refactoring/internal/job/CopyJobTest.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/test/java/org/xwiki/refactoring/internal/job/MoveJobTest.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/test/java/org/xwiki/refactoring/script/RefactoringScriptServiceTest.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/test/java/org/xwiki/refactoring/script/RequestFactoryTest.java, xwiki-platform-core/xwiki-platform-web/src/main/webapp/templates/rename.vm, xwiki-platform-distribution/xwiki-platform-distribution-war-legacydependencies/pom.xml
=> XWIKI-15912: Improper "rename log" string is displayed when user is performing a page copy

xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/test/java/org/xwiki/refactoring/script/RequestFactoryTest.java
The mutation score is now reaching 97% again.
=> [Misc] Fix pseudo-tested methods in refactoring-api

xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-server/src/main/java/org/xwiki/rest/internal/resources/classes/AbstractClassPropertyValuesProvider.java, xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-server/src/main/java/org/xwiki/rest/internal/resources/classes/DBListClassPropertyValuesProvider.java, xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-server/src/test/java/org/xwiki/rest/internal/resources/classes/DBListClassPropertyValuesProviderTest.java
https://jira.xwiki.org/browse/XWIKI-15956
* Implement the getValue method for DBList classes.
=> XWIKI-15956: Suggest Fails To Display Current Value Correctly On Edit

xwiki-platform-core/xwiki-platform-index/xwiki-platform-index-ui/src/main/resources/XWiki/DeletedDocuments.xml
* Add a modal and start refactoring the delete all code
=> XWIKI-15921: Refactor DeletedDocuments to get rid of prototypejs

xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-macros/xwiki-platform-rendering-macro-include/src/main/java/org/xwiki/rendering/macro/include/IncludeMacroParameters.java
https://jira.xwiki.org/browse/XWIKI-15825
* Apply the PropertyGroup and PropertyFeature to some include macro
parameters.
=> XWIKI-15825: Use feature and grouping parameters to the Include macro descriptor

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-themes/xwiki-platform-flamingo-theme-ui/src/main/resources/FlamingoThemes/WebPreferences.xml, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/internal/mandatory/XWikiPreferencesDocumentInitializer.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/objects/classes/BaseClass.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/objects/classes/ListClass.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/objects/meta/ListMetaClass.java, xwiki-platform-core/xwiki-platform-panels/xwiki-platform-panels-ui/src/main/resources/PanelsCode/WebPreferences.xml, xwiki-platform-core/xwiki-platform-release/xwiki-platform-release-ui/src/main/resources/ReleaseCode/WebPreferences.xml, xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-server/src/main/java/org/xwiki/rest/internal/resources/classes/AbstractDocumentListClassPropertyValuesProvider.java, xwiki-platform-core/xwiki-platform-sandbox/src/main/resources/Sandbox/WebPreferences.xml, xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/uicomponents/suggest/suggestPropertyValues.js, xwiki-platform-core/xwiki-platform-web/src/main/webapp/templates/macros.vm, xwiki-platform-distribution/xwiki-platform-distribution-ui/xwiki-platform-distribution-ui-admin-user/src/main/resources/XWiki/Admin.xml, xwiki-platform-distribution/xwiki-platform-distribution-ui/xwiki-platform-distribution-ui-base/src/main/resources/XWiki/WebPreferences.xml, xwiki-platform-distribution/xwiki-platform-distribution-ui/xwiki-platform-distribution-ui-base/src/main/resources/XWiki/XWikiPreferences.xml
https://jira.xwiki.org/browse/XWIKI-15980
* Introduce a freeText parameter in the ListClass which indicates that the property can take a simple string as a value.
=> XWIKI-15980: Setting a main wiki or a filesystem skin is much harder with the new picker

pom.xml, xwiki-platform-core/xwiki-platform-query/xwiki-platform-query-manager/src/test/java/org/xwiki/query/internal/EscapeLikeParametersFilterTest.java
https://jira.xwiki.org/browse/XWIKI-16027
* Upgrade the dependency
* Added a test to ensure the behaviour of JSQLParser with "like not"
=> XWIKI-16027: upgrade jsqlparser

xwiki-platform-core/xwiki-platform-legacy/xwiki-platform-legacy-office-importer/src/main/java/org/xwiki/officeimporter/internal/openoffice/DefaultOpenOfficeConverter.java, xwiki-platform-core/xwiki-platform-office/xwiki-platform-office-importer/pom.xml, xwiki-platform-core/xwiki-platform-office/xwiki-platform-office-importer/src/main/java/org/xwiki/officeimporter/converter/OfficeConverter.java, xwiki-platform-core/xwiki-platform-office/xwiki-platform-office-importer/src/main/java/org/xwiki/officeimporter/internal/converter/DefaultOfficeConverter.java, xwiki-platform-core/xwiki-platform-office/xwiki-platform-office-importer/src/main/java/org/xwiki/officeimporter/internal/converter/DefaultOfficeImporterRecognizer.java, xwiki-platform-core/xwiki-platform-office/xwiki-platform-office-importer/src/main/java/org/xwiki/officeimporter/internal/server/DefaultOfficeServer.java, xwiki-platform-core/xwiki-platform-office/xwiki-platform-office-importer/src/main/java/org/xwiki/officeimporter/internal/server/DefaultOfficeServerConfiguration.java, xwiki-platform-core/xwiki-platform-office/xwiki-platform-office-importer/src/main/java/org/xwiki/officeimporter/script/OfficeImporterScriptService.java, xwiki-platform-core/xwiki-platform-office/xwiki-platform-office-importer/src/main/resources/document-formats.js, xwiki-platform-core/xwiki-platform-office/xwiki-platform-office-viewer/src/main/java/org/xwiki/office/viewer/internal/DefaultOfficeResourceViewer.java, xwiki-platform-core/xwiki-platform-office/xwiki-platform-office-viewer/src/main/java/org/xwiki/office/viewer/script/DefaultOfficeViewerScriptService.java, xwiki-platform-core/xwiki-platform-office/xwiki-platform-office-viewer/src/test/java/org/xwiki/office/viewer/internal/DefaultOfficeResourceViewerTest.java, xwiki-platform-core/xwiki-platform-office/xwiki-platform-office-viewer/src/test/java/org/xwiki/office/viewer/script/DefaultOfficeViewerScriptServiceTest.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/internal/export/OfficeExporter.java, xwiki-platform-core/xwiki-platform-wysiwyg/xwiki-platform-wysiwyg-api/src/main/java/org/xwiki/wysiwyg/internal/importer/OfficeAttachmentImporter.java
https://jira.xwiki.org/browse/XWIKI-15031
* Use latest release of jodconverter
* Fix issues to make to code compile
* Add the export properties from the XWiki fork of Jodconverter
All tests are now passing on office module.
=> XWIKI-15031: Move to sbraconnier's JODConverter

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-themes/xwiki-platform-flamingo-theme-ui/src/main/resources/FlamingoThemes/WebPreferences.xml, xwiki-platform-core/xwiki-platform-invitation/xwiki-platform-invitation-ui/src/main/resources/Invitation/WebPreferences.xml, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/internal/mandatory/XWikiPreferencesDocumentInitializer.java, xwiki-platform-core/xwiki-platform-panels/xwiki-platform-panels-ui/src/main/resources/PanelsCode/WebPreferences.xml, xwiki-platform-core/xwiki-platform-release/xwiki-platform-release-ui/src/main/resources/ReleaseCode/WebPreferences.xml, xwiki-platform-core/xwiki-platform-sandbox/src/main/resources/Sandbox/WebPreferences.xml, xwiki-platform-distribution/xwiki-platform-distribution-ui/xwiki-platform-distribution-ui-admin-user/src/main/resources/XWiki/Admin.xml, xwiki-platform-distribution/xwiki-platform-distribution-ui/xwiki-platform-distribution-ui-base/src/main/resources/XWiki/WebPreferences.xml, xwiki-platform-distribution/xwiki-platform-distribution-ui/xwiki-platform-distribution-ui-base/src/main/resources/XWiki/XWikiPreferences.xml
https://jira.xwiki.org/browse/XWIKI-16025
* Use an explicit query to avoid suggested skin pages from being hidden.
=> XWIKI-16025: Skins dropdown doesn't always display the existing Skin pages

xwiki-platform-core/xwiki-platform-resource/xwiki-platform-resource-api/src/main/java/org/xwiki/resource/ResourceType.java, xwiki-platform-core/xwiki-platform-resource/xwiki-platform-resource-default/src/main/java/org/xwiki/resource/resources/ResourcesResourceReference.java, xwiki-platform-core/xwiki-platform-resource/xwiki-platform-resource-default/src/main/java/org/xwiki/resource/skins/SkinsResourceReference.java, xwiki-platform-core/xwiki-platform-resource/xwiki-platform-resource-servlet/pom.xml, xwiki-platform-core/xwiki-platform-resource/xwiki-platform-resource-servlet/src/main/java/org/xwiki/resource/servlet/RoutingFilter.java
* Don't use concrete classes SkinResourceReference and
ResourceResourceReference in RoutingFilter but rely on a new API from
ResourceType.
=> [Misc] Remove dependency between platform-resource-servlet and platform-resource-default

xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/uicomponents/suggest/xwiki.selectize.js
https://jira.xwiki.org/browse/XWIKI-16024
* Preload selectize suggestions earlier.
* Prevent opening the links of the selectize elements.
=> XWIKI-16024: Selecting an option from the drop-down that lists available Skins navigates to the page

xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/js/xwiki/panelwizard/panelWizard.js
https://jira.xwiki.org/browse/XWIKI-16020
* Fix the panels preview when changing the width.
=> XWIKI-16020: Changing the width of the right panel column using "Page Administration : Panels" moves them to the bottom of the page

xwiki-platform-core/xwiki-platform-office/xwiki-platform-office-importer/pom.xml, xwiki-platform-core/xwiki-platform-office/xwiki-platform-office-importer/src/main/java/org/xwiki/officeimporter/server/script/OfficeServerScriptService.java, xwiki-platform-core/xwiki-platform-office/xwiki-platform-office-importer/src/test/java/org/xwiki/officeimporter/server/script/OfficeServerScriptServiceTest.java
=> [Misc] Improve tests in office-importer.

xwiki-platform-core/xwiki-platform-test/pom.xml
https://jira.xwiki.org/browse/XWIKI-15982
* test-upgrade and test-ui to the right profile
=> XWIKI-15982: dependency issue: profile integration-tests required for xwiki-platform-test-upgrade

xwiki-platform-distribution/xwiki-platform-distribution-ui/xwiki-platform-distribution-ui-base/src/main/resources/XWiki/XWikiPreferences.xml
- Modify XWikiPreferences "meta" property to add new extension point.
=> XWIKI-16093: Add extension point to make the HTML head pluggable

xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/uicomponents/job/question/XClassBreakingQuestion.js, xwiki-platform-core/xwiki-platform-web/src/main/webapp/templates/job/question/XClassBreakingQuestion.data.vm
https://jira.xwiki.org/browse/XWIKI-16058
* Remove the checkbox of "objects" instead of just hiding them.
* Remove the links on XClass
=> XWIKI-16058: Cannot "Select all" the pages when deleting AWM apps

xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/web/ExportURLFactory.java
* Override the newly introduce method in ExportURLFactory
=> XWIKI-6073: Browsers usually cache JS/CSS resources even if they have changed

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/docextra.vm, xwiki-platform-core/xwiki-platform-oldcore/src/main/resources/ApplicationResources.properties, xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/js/xwiki/viewers/information.css, xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/js/xwiki/viewers/information.js, xwiki-platform-core/xwiki-platform-web/src/main/webapp/templates/informationinline.vm
https://jira.xwiki.org/browse/XWIKI-13362
=> XWIKI-13362: Display the page reference for a page, for users to be able to copy-paste it

xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-server/pom.xml, xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-server/src/main/java/org/xwiki/rest/internal/ModelFactory.java, xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-server/src/test/java/org/xwiki/rest/internal/ModelFactoryTest.java
as discussed on the mailing list
=> XWIKI-16120: some object properties are not part of the public api

xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/doc/XWikiDocumentTest.java
Refactoring from JUnit 3 (!) to JUnit 5.
=> [Misc] Refactoring of XWikiDocumentTest to use JUnit 5 framework.

xwiki-platform-core/xwiki-platform-annotations/xwiki-platform-annotation-rest/src/main/java/org/xwiki/annotation/rest/internal/AbstractAnnotationRESTResource.java
* block the redirects as they are leading to an unexpected result for the annotations UI
=> XWIKI-11447: Error message when trying to load annotations on search page

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-docker/src/test/it/org/xwiki/flamingo/test/ui/EditTranslationIT.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/api/Document.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/doc/XWikiDocument.java, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/doc/XWikiDocumentRenderingTest.java, xwiki-platform-core/xwiki-platform-web/src/main/webapp/templates/contentvars.vm
https://jira.xwiki.org/browse/XWIKI-16307
* Use the current document if the given locale is ROOT
* Improve integration tests to check this behaviour
=> XWIKI-16307: Unable to view the original document in multilingual wiki

xwiki-platform-core/xwiki-platform-menu/xwiki-platform-menu-ui/src/main/resources/Menu/MenuMacro.xml
Thank you @evalica for all your help! 
https://jira.xwiki.org/browse/XWIKI-16439
=> XWIKI-16439: Improve the menu toggle on mobile to suggest it's open	

xwiki-platform-core/xwiki-platform-web/src/main/webapp/templates/extension.vm
: The placeholder text from Administration > Extensions does not disappear when start typing on Edge
=> XWIKI-14819:  The placeholder text from Administration > Extensions does not disappear when start typing on Edge

xwiki-platform-core/xwiki-platform-dashboard/xwiki-platform-dashboard-ui/src/main/resources/Dashboard/XWikiUserDashboardSheet.xml
=>  XWIKI-12639: Introduce extension point to add custom categories in the user profile

xwiki-platform-core/xwiki-platform-annotation/xwiki-platform-annotation-ui/src/main/resources/AnnotationCode/Script.xml
* Dropped annotation support for older skins (Colibri)
=> XWIKI-17225: Annotation link is visible when More Action menu is removed

xwiki-platform-core/xwiki-platform-oldcore/src/main/resources/ApplicationResources.properties, xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/uicomponents/widgets/locationPicker.js
[Issue link](https://jira.xwiki.org/browse/XWIKI-13662)
After:
=> XWIKI-13662: Improve validation message when trying to create a top level terminal page

xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-ui/src/main/resources/XWiki/Mentions/MentionsMacro.xml
Jira issue: https://jira.xwiki.org/browse/XWIKI-17546
=> XWIKI-17546: User mentions during the update of AWM fields does not produce notifications

xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-ui/src/main/resources/XWiki/Mentions/WebHome.xml
https://jira.xwiki.org/browse/XWIKI-17518
=> XWIKI-17518: There should be no mentions in a clean wiki for the Admin user

xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/pom.xml, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/src/main/java/org/xwiki/mentions/internal/DefaultMentionXDOMService.java, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/src/main/java/org/xwiki/mentions/internal/DefaultMentionsDataConsumer.java, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/src/main/java/org/xwiki/mentions/internal/MentionXDOMService.java, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/src/test/java/org/xwiki/mentions/internal/DefaultMentionXDOMServiceTest.java, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/src/test/java/org/xwiki/mentions/internal/DefaultMentionsDataConsumerTest.java
https://jira.xwiki.org/browse/XWIKI-17529
=> XWIKI-17529: Parsing of content for mentions analysis is wrongly using syntax xwiki/2.1

xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-api/src/main/java/org/xwiki/mentions/script/MentionsScriptService.java, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/pom.xml, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/src/main/java/org/xwiki/mentions/internal/DefaultMentionsEventExecutor.java, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/src/main/java/org/xwiki/mentions/internal/async/MentionsData.java, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/src/main/java/org/xwiki/mentions/internal/jmx/JMXMentions.java, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/src/main/java/org/xwiki/mentions/internal/jmx/JMXMentionsMBean.java, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/src/main/java/org/xwiki/mentions/internal/listeners/MentionsApplicationReadyEventListener.java, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/src/test/java/org/xwiki/mentions/internal/DefaultMentionNotificationParametersServiceTest.java, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/src/test/java/org/xwiki/mentions/internal/DefaultMentionNotificationServiceTest.java, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/src/test/java/org/xwiki/mentions/internal/DefaultMentionsDataConsumerTest.java, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/src/test/java/org/xwiki/mentions/internal/DefaultMentionsEventExecutorTest.java, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/src/test/java/org/xwiki/mentions/internal/async/DefaultMentionsThreadsProviderTest.java, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/src/test/java/org/xwiki/mentions/internal/listeners/MentionsApplicationReadyEventListenerTest.java, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-notifications/src/test/java/org/xwiki/mentions/internal/MentionsNotificationDisplayerTest.java, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-test/xwiki-platform-mentions-test-docker/src/test/it/org/xwiki/mentions/test/ui/MentionsIT.java
- various fixes and defensive code added
- improved internal APIs
=> XWIKI-17524: Replace Jobs with threads to handle mentions asynchronously

xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/pom.xml, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/src/main/java/org/xwiki/mentions/internal/DefaultMentionsEventExecutor.java, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/src/main/java/org/xwiki/mentions/internal/MentionsBlockingQueueProvider.java, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/src/main/java/org/xwiki/mentions/internal/async/DefaultMentionsBlockingQueueProvider.java, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/src/test/java/org/xwiki/mentions/internal/DefaultMentionsEventExecutorTest.java, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/src/test/java/org/xwiki/mentions/internal/async/DefaultMentionsBlockingQueueProviderTest.java
Jira: https://jira.xwiki.org/browse/XWIKI-17619
=> XWIKI-17619: Mention queue locking exception

xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/pom.xml, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/src/main/java/org/xwiki/mentions/internal/DefaultMentionsEventExecutor.java, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/src/main/java/org/xwiki/mentions/internal/MentionsBlockingQueueProvider.java, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/src/main/java/org/xwiki/mentions/internal/async/DefaultMentionsBlockingQueueProvider.java, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/src/test/java/org/xwiki/mentions/internal/DefaultMentionsEventExecutorTest.java, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/src/test/java/org/xwiki/mentions/internal/async/DefaultMentionsBlockingQueueProviderTest.java
(cherry picked from commit 938c1d0cdf8c9e2fc9c1019dbd7a92b158112ad3)
=> XWIKI-17619: Mention queue locking exception (#1351)

xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/src/main/java/org/xwiki/mentions/internal/DefaultMentionsDataConsumer.java, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/src/test/java/org/xwiki/mentions/internal/DefaultMentionsDataConsumerTest.java, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-test/pom.xml, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-test/xwiki-platform-mentions-test-docker/pom.xml, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-test/xwiki-platform-mentions-test-docker/src/test/it/org/xwiki/mentions/test/ui/MentionsIT.java, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-test/xwiki-platform-mentions-test-pageobjects/pom.xml, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-test/xwiki-platform-mentions-test-pageobjects/src/main/java/org/xwiki/mentions/test/po/MentionNotificationPage.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-test/xwiki-platform-notifications-test-pageobjects/src/main/java/org/xwiki/platform/notifications/test/po/GroupedNotificationElementPage.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-test/xwiki-platform-notifications-test-pageobjects/src/main/java/org/xwiki/platform/notifications/test/po/NotificationsTrayPage.java
https://jira.xwiki.org/browse/XWIKI-17648
More elements tested, comments mentions tested too.
Retry on flickering elements introduced.
=> XWIKI-17648: NestedMentionsIT#basic is flickering

xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-ui/src/main/resources/XWiki/Mentions/MentionsTip.xml, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-ui/src/main/resources/XWiki/Mentions/MentionsTranslations.fr.xml, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-ui/src/main/resources/XWiki/Mentions/MentionsTranslations.xml
https://jira.xwiki.org/browse/XWIKI-17579
=> XWIKI-17579: Explaining the use of the mention macro on the tips

xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/uicomponents/container/columns.css
=> XWIKI-14210: container macro doesn't work properly with dynamic layout

xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/po/CommentsTab.java, xwiki-platform-distribution/xwiki-platform-distribution-flavor/xwiki-platform-distribution-flavor-test/xwiki-platform-distribution-flavor-test-ui/src/test/it/org/xwiki/test/ui/CommentAsAdminTest.java
https://jira.xwiki.org/browse/XWIKI-17726
=> XWIKI-17726: CommentAsAdminTest#testReplyToCommentAsAdmin is flickering

xwiki-platform-core/xwiki-platform-autotag/src/main/java/com/xpn/xwiki/plugin/autotag/Tag.java, xwiki-platform-core/xwiki-platform-xml/xwiki-platform-xml-script/pom.xml, xwiki-platform-core/xwiki-platform-xml/xwiki-platform-xml-script/src/main/java/org/xwiki/xml/script/XMLScriptService.java, xwiki-platform-core/xwiki-platform-xml/xwiki-platform-xml-script/src/test/java/org/xwiki/xml/script/XMLScriptServiceTest.java
https://jira.xwiki.org/browse/XWIKI-17766
=> XWIKI-17766: Update deprecated method calls to org.xwiki.xml.XMLUtils

xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/uicomponents/viewers/comments.js
https://jira.xwiki.org/browse/XWIKI-17780
=> XWIKI-17780: Comment 'Reply' button is missing after adding a comment and refreshing the page

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/commentsinline.vm, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/objects/classes/ListClass.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/objects/classes/StringClass.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/objects/classes/TextAreaClass.java, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/objects/classes/StaticListClassTest.java, xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/js/xwiki/xwiki.js
Cherry pick of XWIKI-17371 for 11.10.11.
To be merged after https://github.com/xwiki/xwiki-commons/pull/105
=> XWIKI-17374: Fix escaping in property displayer

xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-ui/src/main/resources/Refactoring/Code/RefactoringConfiguration.xml, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-ui/src/main/resources/Refactoring/Code/RefactoringTranslations.xml
https://jira.xwiki.org/browse/XWIKI-17821
- Hides the "skip the recycle bin" configuration if the recycle bin is not activated.
- Hides the delete section if the recycle bin is not activated as it would currently display an empty page.
=> XWIKI-17821: Hide the recycle bin skipping configuration when the recycle bin is not activated

xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-notifications/src/main/resources/templates/notification/rss/mentions.mention.vm
https://jira.xwiki.org/browse/XWIKI-17924
Hides the change link when no change can be found.
=> XWIKI-17924: The mentions rss template needlessly displays a change link

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-docker/src/test/it/org/xwiki/flamingo/test/docker/AllITs.java, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-docker/src/test/it/org/xwiki/flamingo/test/docker/LoginIT.java
https://jira.xwiki.org/browse/XWIKI-17948
=> XWIKI-17948: LoginIT is not executed

xwiki-platform-core/xwiki-platform-web/src/main/webapp/templates/notification/rss/default.vm
https://jira.xwiki.org/browse/XWIKI-17923
=> XWIKI-17923: The default rss item description template needlessly displays a change link

xwiki-platform-core/pom.xml, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/user/impl/xwiki/MyBasicAuthenticator.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/user/impl/xwiki/MyFormAuthenticator.java, xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-server/src/main/java/org/xwiki/rest/internal/XWikiSecretVerifier.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/pom.xml, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-api/src/main/java/org/xwiki/security/authentication/api/AuthenticationFailureManager.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-api/src/main/java/org/xwiki/security/authentication/api/AuthenticationFailureStrategy.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-default/pom.xml, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-default/src/checkstyle/checkstyle-suppressions.xml, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-default/src/main/java/org/xwiki/security/authentication/internal/CaptchaAuthenticationFailureStrategy.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-default/src/main/java/org/xwiki/security/authentication/internal/DefaultAuthenticationFailureManager.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-default/src/main/java/org/xwiki/security/authentication/internal/DisableAccountFailureStrategy.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-default/src/test/java/org/xwiki/security/authentication/internal/DefaultAuthenticationFailureManagerTest.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-script/src/main/java/org/xwiki/security/authentication/script/AuthenticationScriptService.java
* Also use the session in authentication security to know if the form
should be validated or not.
=> XWIKI-17468: Authentication Captcha is not working when using another login

xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-api/pom.xml
Definition of an extension name for the mentions API.
=> XWIKI-17895: Modularize the mentions data consumers

xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/js/xwiki/table/livetable.js
=> XWIKI-18038: Livetable "html" field parameter doesn't generate HTML code anymore

xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-ui/src/main/resources/XWiki/Mentions/Configuration.xml, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-ui/src/main/resources/XWiki/Mentions/MentionsTranslations.xml
https://jira.xwiki.org/browse/XWIKI-18227
=> XWIKI-18227: Mentions administration title is not translatable

xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/filters/FilterList.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/utilities/BaseSelect.vue
* Modify BaseSelect to use objects instead of strings
=> XWIKI-18272 The list (dropdown) live data filter doesn't include the actual values

xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-macros/xwiki-platform-rendering-macro-code/pom.xml, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-macros/xwiki-platform-rendering-macro-code/src/test/resources/macrocode15.test, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-macros/xwiki-platform-rendering-macro-code/src/test/resources/macrocode16.test
https://jira.xwiki.org/browse/XWIKI-18363
=> XWIKI-18363: Auto-detection of language with the code macro is broken

xwiki-platform-core/xwiki-platform-help/xwiki-platform-help-ui/src/test/java/org/xwiki/help/HelpTest.java, xwiki-platform-core/xwiki-platform-ratings/xwiki-platform-ratings-ui/src/test/java/org/xwiki/ratings/RatingsTest.java, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-page/src/test/java/org/xwiki/test/page/HTML50ComponentList.java, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-page/src/test/java/org/xwiki/test/page/PageTest.java, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-page/src/test/resources/skins/flamingo/skin.properties
- Introduces a component list of html/5.0
- Provides methods to render document and parse them with Jsoup
- Initializes a default skin environment
- Cleanup of the existing page test
=> [Misc] PageTest improvements.

xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-ui/pom.xml, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-ui/src/main/resources/Refactoring/Code/RefactoringConfiguration.xml, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-ui/src/test/java/org/xwiki/refactoring/RefactoringConfigurationTest.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-ui/src/test/resources/skins/flamingo/skin.properties
https://jira.xwiki.org/browse/XWIKI-18447
- Set relative URL to the xredirect field of the RefactoringConfiguration.xml form.
- Introduces a first PageTest for RefactoringConfiguration.xml
=> XWIKI-18447: Invalid authentication information request warning when saving document delete options from Administration

xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-ui/pom.xml, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-ui/src/main/resources/Refactoring/Code/RefactoringConfiguration.xml, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-ui/src/test/java/org/xwiki/refactoring/RefactoringConfigurationTest.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-ui/src/test/resources/skins/flamingo/skin.properties
https://jira.xwiki.org/browse/XWIKI-18447
- Set relative URL to the xredirect field of the RefactoringConfiguration.xml form.
- Introduces a first PageTest for RefactoringConfiguration.xml
=> XWIKI-18447: Invalid authentication information request warning when saving document delete options from Administration (12.10.x)

xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-test/xwiki-platform-appwithinminutes-test-docker/src/test/it/org/xwiki/appwithinminutes/test/ui/AllITs.java, xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-test/xwiki-platform-appwithinminutes-test-docker/src/test/it/org/xwiki/appwithinminutes/test/ui/StaticListClassFieldIT.java, xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-test/xwiki-platform-appwithinminutes-test-pageobjects/src/main/java/org/xwiki/appwithinminutes/test/po/ApplicationClassEditPage.java, xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-test/xwiki-platform-appwithinminutes-test-pageobjects/src/main/java/org/xwiki/appwithinminutes/test/po/StaticListClassFieldEditPane.java
StaticListClassFieldTest replaced with StaticListClassFieldIT on xwiki-platform-appwithinminutes-test-docker
=> [misc] Migrates StaticListClassFieldTest to a docker integration test

xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-test/xwiki-platform-appwithinminutes-test-docker/src/test/it/org/xwiki/appwithinminutes/test/ui/AllITs.java, xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-test/xwiki-platform-appwithinminutes-test-docker/src/test/it/org/xwiki/appwithinminutes/test/ui/LiveTableGeneratorIT.java, xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-test/xwiki-platform-appwithinminutes-test-pageobjects/src/main/java/org/xwiki/appwithinminutes/test/po/ApplicationClassEditPage.java, xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-test/xwiki-platform-appwithinminutes-test-pageobjects/src/main/java/org/xwiki/appwithinminutes/test/po/ApplicationHomePage.java
LiveTableGeneratorTest ported to a docker integration test in xwiki-platform-appwithinminutes-test-docker
=> [Misc] Migrates LiveTableGeneratorTest to a docker integration test

xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-test/xwiki-platform-appwithinminutes-test-docker/pom.xml, xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-test/xwiki-platform-appwithinminutes-test-docker/src/test/it/org/xwiki/appwithinminutes/test/ui/AddEntryIT.java, xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-test/xwiki-platform-appwithinminutes-test-docker/src/test/it/org/xwiki/appwithinminutes/test/ui/AllITs.java, xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-test/xwiki-platform-appwithinminutes-test-pageobjects/src/main/java/org/xwiki/appwithinminutes/test/po/ApplicationHomePage.java, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/po/LiveTableElement.java
https://jira.xwiki.org/browse/XWIKI-18258
- Wait added on ApplicationHomePage#clickAddNewEntry to prevent access to the name field before it is displayed.
- AddEntryTest (in xwiki-platform-distribution-flavor-test-ui) migrated to docker as AddEntryIT (in xwiki-platform-appwithinminutes-test-docker).
=> XWIKI-18258: AddEntryTest#testEntryNameWithURLSpecialCharacters is flickering

xwiki-platform-core/xwiki-platform-resource/xwiki-platform-resource-servlet/src/main/java/org/xwiki/resource/servlet/AbstractServletResourceReferenceHandler.java, xwiki-platform-core/xwiki-platform-webjars/xwiki-platform-webjars-api/pom.xml, xwiki-platform-core/xwiki-platform-webjars/xwiki-platform-webjars-api/src/main/java/org/xwiki/webjars/internal/WebJarsResourceReferenceHandler.java, xwiki-platform-core/xwiki-platform-webjars/xwiki-platform-webjars-api/src/main/java/org/xwiki/webjars/internal/filter/LessWebJarsResourceFilter.java, xwiki-platform-core/xwiki-platform-webjars/xwiki-platform-webjars-api/src/main/java/org/xwiki/webjars/internal/filter/VelocityWebJarsResourceFilter.java, xwiki-platform-core/xwiki-platform-webjars/xwiki-platform-webjars-api/src/main/java/org/xwiki/webjars/internal/filter/WebJarsResourceFilter.java, xwiki-platform-core/xwiki-platform-webjars/xwiki-platform-webjars-api/src/main/resources/META-INF/components.txt, xwiki-platform-core/xwiki-platform-webjars/xwiki-platform-webjars-api/src/test/java/org/xwiki/webjars/internal/WebJarsResourceReferenceHandlerTest.java, xwiki-platform-core/xwiki-platform-webjars/xwiki-platform-webjars-api/src/test/java/org/xwiki/webjars/internal/filter/LessWebJarsResourceFilterTest.java, xwiki-platform-core/xwiki-platform-webjars/xwiki-platform-webjars-api/src/test/java/org/xwiki/webjars/internal/filter/VelocityWebJarsResourceFilterTest.java
https://jira.xwiki.org/browse/XWIKI-18492
- pass the servlet response to filterResource if it exists
- less files are compiled to css when evaluate=true
=> XWIKI-18492: Add support for compiling LESS files from WebJar at runtime in the context of the skin

xwiki-platform-core/xwiki-platform-resource/xwiki-platform-resource-servlet/pom.xml, xwiki-platform-core/xwiki-platform-resource/xwiki-platform-resource-servlet/src/main/java/org/xwiki/resource/servlet/AbstractServletResourceReferenceHandler.java, xwiki-platform-core/xwiki-platform-resource/xwiki-platform-resource-servlet/src/test/java/org/xwiki/resource/servlet/AbstractServletResourceReferenceHandlerTest.java, xwiki-platform-core/xwiki-platform-webjars/xwiki-platform-webjars-api/src/test/java/org/xwiki/webjars/internal/WebJarsResourceReferenceHandlerTest.java, xwiki-platform-core/xwiki-platform-webjars/xwiki-platform-webjars-api/src/test/java/org/xwiki/webjars/internal/filter/LessWebJarsResourceFilterTest.java, xwiki-platform-core/xwiki-platform-webjars/xwiki-platform-webjars-api/src/test/java/org/xwiki/webjars/internal/filter/VelocityWebJarsResourceFilterTest.java
- Resources closed using AbstractServletResourceReferenceHandler
- Resources testing improved in xwiki-platform-resource-servlet and xwiki-platform-webjars-api
=> [Misc] Improves the resource closing of the resource handler

xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/pom.xml, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/config/package.json, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/config/vue.config.js, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/LivedataDropdownMenu.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/LivedataEntrySelectorAll.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/LivedataEntrySelectorInfoBar.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/LivedataPagination.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/LivedataRefreshButton.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/displayers/DisplayerActions.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/displayers/DisplayerLink.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/layouts/cards/LayoutCards.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/layouts/cards/LayoutCardsNewCard.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/layouts/table/LayoutTable.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/layouts/table/LayoutTableNewRow.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/panels/LivedataAdvancedPanelFilter.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/panels/LivedataAdvancedPanelFilterEntry.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/panels/LivedataAdvancedPanelProperties.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/panels/LivedataAdvancedPanelSort.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/webjar/Logic.js
* The date filter has not been translated, as it is related to XWIKI-18535
=> XWIKI-17428 Use translation keys in the live data UI

xwiki-platform-core/xwiki-platform-invitation/xwiki-platform-invitation-ui/pom.xml
- Add dependency on xwiki-platform-administration-ui (needed for configuration purpose)
=> XWIKI-18502: Extension updater propose to upgrade Invitation to 13.1 when 12.10.5 flavor is installed

xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-integration/src/main/java/org/xwiki/test/integration/maven/ArtifactResolver.java
Detected at https://github.com/checkstyle/checkstyle/issues/9967
=> Fixed Checkstyle Violation

xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-ui/pom.xml
- Add dependency on `xwiki-platform-refactoring-api`
=> XWIKI-18501: Extension updater propose to upgrade Refactoring UI to 13.1 when 12.10.5 flavor is installed

xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-test/xwiki-platform-livedata-test-pageobjects/src/main/java/org/xwiki/livedata/test/po/TableLayoutElement.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/filters/LivedataFilter.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/filters/filterMixin.js, xwiki-platform-core/xwiki-platform-panels/xwiki-platform-panels-test/xwiki-platform-panels-test-docker/pom.xml, xwiki-platform-core/xwiki-platform-panels/xwiki-platform-panels-test/xwiki-platform-panels-test-docker/src/test/it/org/xwiki/panels/test/ui/docker/AllITs.java, xwiki-platform-core/xwiki-platform-panels/xwiki-platform-panels-test/xwiki-platform-panels-test-docker/src/test/it/org/xwiki/panels/test/ui/docker/PanelIT.java, xwiki-platform-core/xwiki-platform-panels/xwiki-platform-panels-test/xwiki-platform-panels-test-pageobjects/pom.xml, xwiki-platform-core/xwiki-platform-panels/xwiki-platform-panels-test/xwiki-platform-panels-test-pageobjects/src/main/java/org/xwiki/panels/test/po/PanelsHomePage.java, xwiki-platform-core/xwiki-platform-panels/xwiki-platform-panels-ui/pom.xml, xwiki-platform-core/xwiki-platform-panels/xwiki-platform-panels-ui/src/main/resources/Panels/WebHome.xml
- Livetable replace with a Live Data
- Migrates the panel tests to docker and add a Live Data test
=> XWIKI-18621: Replace the Panels live table with live data

xwiki-platform-core/xwiki-platform-extension/xwiki-platform-extension-test/xwiki-platform-extension-test-pageobjects/src/main/java/org/xwiki/extension/test/po/DependencyPane.java, xwiki-platform-core/xwiki-platform-extension/xwiki-platform-extension-test/xwiki-platform-extension-test-pageobjects/src/main/java/org/xwiki/extension/test/po/ExtensionPane.java, xwiki-platform-core/xwiki-platform-extension/xwiki-platform-extension-test/xwiki-platform-extension-test-pageobjects/src/main/java/org/xwiki/extension/test/po/SearchResultsPane.java
- Adapt tests in xwiki-platform-extension-test to the updated HTML
structure of the extension / extension dependencies panes
=> XWIKI-14811: Bad layout when using a font larger than the default one

xwiki-platform-core/xwiki-platform-wysiwyg/xwiki-platform-wysiwyg-api/src/main/java/org/xwiki/wysiwyg/converter/RequestParameterConverter.java, xwiki-platform-core/xwiki-platform-wysiwyg/xwiki-platform-wysiwyg-api/src/main/java/org/xwiki/wysiwyg/filter/ConversionFilter.java, xwiki-platform-core/xwiki-platform-wysiwyg/xwiki-platform-wysiwyg-api/src/main/java/org/xwiki/wysiwyg/internal/converter/DefaultRequestParameterConverter.java, xwiki-platform-core/xwiki-platform-wysiwyg/xwiki-platform-wysiwyg-api/src/main/resources/META-INF/components.txt
https://jira.xwiki.org/browse/XWIKI-18773
=> XWIKI-18773: Allow to call ConversionFilter in a specific ResourceReferenceHandler

xwiki-platform-core/pom.xml, xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-test/xwiki-platform-administration-test-docker/src/test/it/org/xwiki/administration/test/ui/ResetPasswordIT.java, xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-test/xwiki-platform-administration-test-pageobjects/src/main/java/org/xwiki/administration/test/po/ResetPasswordPage.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/resources/ApplicationResources.properties, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-api/src/main/java/org/xwiki/security/authentication/ResetPasswordRequestResponse.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-default/src/main/java/org/xwiki/security/authentication/internal/DefaultResetPasswordManager.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-default/src/main/java/org/xwiki/security/authentication/internal/DefaultResetPasswordRequestResponse.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-default/src/test/java/org/xwiki/security/authentication/internal/DefaultResetPasswordManagerTest.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-script/src/main/java/org/xwiki/security/authentication/script/AuthenticationScriptService.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-script/src/test/java/org/xwiki/security/authentication/script/AuthenticationScriptServiceTest.java, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/resetpasswordinline.vm
https://jira.xwiki.org/browse/XWIKI-18787
* Refactor a bit the Authentication API to be more sound
* Fix related tests
This PR should only be merged when 13.5 will be released and the revapi ignores are clean to avoid any problems.
=> XWIKI-18787: Authentication API does not return proper results

xwiki-platform-core/xwiki-platform-like/xwiki-platform-like-ui/src/main/resources/XWiki/Like/LikeTranslations.ru.xml
"Нравится" more correct see:
https://ru.wikipedia.org/wiki/%D0%9D%D1%80%D0%B0%D0%B2%D0%B8%D1%82%D1%81%D1%8F
=> fix "Нравиться" to "Нравится"

xwiki-platform-core/xwiki-platform-dashboard/xwiki-platform-dashboard-ui/src/main/resources/Dashboard/XWikiUserDashboardSheet.xml, xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-profile/xwiki-platform-user-profile-ui/src/main/resources/XWiki/XWikiUserPreferencesSheet.xml
* Make profile edit button link text visible on screen-readers only
* Add title attribute to the link
=> XWIKI-18008: User profile edit button missing link purpose

xwiki-platform-core/xwiki-platform-edit/xwiki-platform-edit-ui/src/main/resources/XWiki/InplaceEditing.xml, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/js/xwiki/actionbuttons/actionButtons.js
* Ensure to expose fakeform
* Define in configuration which selector is used for the inplace
editing button
* Send the JSON answer obtained from the request when sending the
saved event
=> XWIKI-19115: Improve extension capability of inplace editing

xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-ui/src/main/resources/XWiki/Notifications/Code/NotificationsDisplayerUIX.xml, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/uicomponents/widgets/notification.js
- XWIKI-18941: role alert for .xnotification-container
- XWIKI-19134: notification labels readable by screenreaders
=> XWIKI-19134: make notification labels readable by screenreader

xwiki-platform-core/xwiki-platform-filter/xwiki-platform-filter-instance/xwiki-platform-filter-instance-api/src/main/java/org/xwiki/filter/instance/input/InstanceInputProperties.java, xwiki-platform-core/xwiki-platform-filter/xwiki-platform-filter-instance/xwiki-platform-filter-instance-api/src/main/java/org/xwiki/filter/instance/output/InstanceOutputProperties.java
With Respect to Issue https://github.com/checkstyle/checkstyle/issues/11015
Pull request - https://github.com/checkstyle/checkstyle/pull/11020
The link to failed build- https://app.circleci.com/pipelines/github/checkstyle/checkstyle/10533/workflows/5e688e70-96af-43e5-b25c-af4b52575ea5/jobs/108026
=> [Misc] Simplify boolean expressions

xwiki-platform-core/xwiki-platform-annotation/xwiki-platform-annotation-ui/src/main/resources/AnnotationCode/Script.xml
* adjust code to be IE compatible
=> XWIKI-19306: Can't add annotations on IE 11

xwiki-platform-core/xwiki-platform-observation/xwiki-platform-observation-remote/src/main/java/org/xwiki/observation/remote/RemoteObservationManagerConfiguration.java, xwiki-platform-core/xwiki-platform-observation/xwiki-platform-observation-remote/src/main/java/org/xwiki/observation/remote/internal/DefaultRemoteObservationManagerConfiguration.java, xwiki-platform-core/xwiki-platform-observation/xwiki-platform-observation-remote/src/test/java/org/xwiki/observation/remote/internal/DefaultRemoteObservationManagerConfigurationTest.java, xwiki-platform-core/xwiki-platform-observation/xwiki-platform-observation-remote/src/test/java/org/xwiki/observation/remote/test/AbstractROMTestCase.java
Jira: https://jira.xwiki.org/browse/XWIKI-19394
=> XWIKI-19394: Introduce the notion of cluster identifier

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-docker/src/test/it/org/xwiki/flamingo/test/docker/InformationIT.java
Caused by https://jira.xwiki.org/browse/XRENDERING-375
=> [Misc] Fix InformationIT for new parsers

xwiki-platform-distribution/xwiki-platform-distribution-flavor/xwiki-platform-distribution-flavor-data/pom.xml, xwiki-platform-tools/xwiki-platform-tool-packager-plugin/pom.xml, xwiki-platform-tools/xwiki-platform-tool-packager-plugin/src/main/java/com/xpn/xwiki/tool/backup/DataMojo.java
Wait for the document analysis tasks to be finished before continuing.
=> XWIKI-19352: Indexing of the attachments usage on the wiki

xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/pom.xml, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/checkstyle/checkstyle-suppressions.xml, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/java/org/xwiki/search/solr/internal/metadata/DocumentSolrMetadataExtractor.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/test/java/org/xwiki/search/solr/internal/metadata/DocumentSolrMetadataExtractorTest.java
* Use the original metadata author in solr metadata extractor
* Refactor the associated test
Note: the changes are currently not passing because of a Fan-Out complexity of 22 against 20 according to our checkstyle.
=> XWIKI-19340: Index original author in Solr

xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-docker/src/main/java/org/xwiki/test/docker/internal/junit5/database/DatabaseContainerExecutor.java
* Set the missing instructions for allowing to use our custom image
* Fix the username since TC does not allow to use sys/system user
=> [Misc] Ensure to be able to use Oracle image for docker test

xwiki-platform-core/xwiki-platform-index/xwiki-platform-index-api/src/main/java/org/xwiki/index/internal/DefaultTasksManager.java, xwiki-platform-core/xwiki-platform-index/xwiki-platform-index-api/src/main/java/org/xwiki/index/internal/TasksStore.java, xwiki-platform-core/xwiki-platform-index/xwiki-platform-index-api/src/test/java/org/xwiki/index/internal/TasksStoreTest.java
https://jira.xwiki.org/browse/XWIKI-19571
=> XWIKI-19571: ORA-01400: cannot insert NULL into ("XWIKI"."XWIKIDOCUMENTINDEXINGQUEUE"."XWT_VERSION") when creating an instance on Oracle

xwiki-platform-core/xwiki-platform-edit/xwiki-platform-edit-ui/src/main/resources/XWiki/InplaceEditing.xml, xwiki-platform-core/xwiki-platform-realtime/xwiki-platform-realtime-wysiwyg/xwiki-platform-realtime-wysiwyg-webjar/src/main/webjar/wysiwygEditor.js, xwiki-platform-core/xwiki-platform-store/xwiki-platform-store-filesystem-oldcore/src/main/java/org/xwiki/store/script/TemporaryAttachmentsScriptService.java
* Disable the temporary upload for realtime editor
=> XWIKI-18810: Save of the document shouldn't be performed each time an upload is done

xwiki-platform-core/xwiki-platform-index/xwiki-platform-index-api/src/main/java/org/xwiki/index/migration/R140300001XWIKI19571DataMigration.java, xwiki-platform-core/xwiki-platform-index/xwiki-platform-index-api/src/test/java/org/xwiki/index/migration/R140300001XWIKI19571DataMigrationTest.java
Explicitly set the wiki id in the hibernate store during the migration to make sure to use the right database schema
Jira: https://jira.xwiki.org/browse/XWIKI-19677
=> XWIKI-19667: R140300001XWIKI19571DataMigration fails on postgres 12 db

xwiki-platform-core/xwiki-platform-eventstream/xwiki-platform-eventstream-api/src/main/java/org/xwiki/eventstream/query/CompareQueryCondition.java, xwiki-platform-core/xwiki-platform-eventstream/xwiki-platform-eventstream-api/src/main/java/org/xwiki/eventstream/query/SimpleEventQuery.java, xwiki-platform-core/xwiki-platform-eventstream/xwiki-platform-eventstream-api/src/test/java/org/xwiki/eventstream/SimpleEventQueryTest.java, xwiki-platform-core/xwiki-platform-eventstream/xwiki-platform-eventstream-stores/xwiki-platform-eventstream-store-solr/src/main/java/org/xwiki/eventstream/store/solr/internal/SolrEventStore.java, xwiki-platform-core/xwiki-platform-eventstream/xwiki-platform-eventstream-stores/xwiki-platform-eventstream-store-solr/src/test/java/org/xwiki/eventstream/store/solr/internal/EventStoreTest.java
* Add a contains query condition
* Add the contains method in SimpleEventQuery
* Handle the contains query condition in the Solr event store
* Add tests
Jira issue: https://jira.xwiki.org/browse/XWIKI-19689
=> XWIKI-19689: Support contains queries in SimpleEventQuery

xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/LivedataDropdownMenu.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/panels/LiveDataAdvancedPanelExtension.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/panels/LivedataAdvancedPanels.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/webjar/Logic.js
* Add an array of extension panel objects to the logic.
* Add a new advanced panel that represents an extension.
* Add menu items for all extension panels.
Jira issue: https://jira.xwiki.org/browse/XWIKI-19707
=> XWIKI-19707: Add JavaScript API for extending Live Data with menu item and panel

xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-rest/src/main/java/org/xwiki/livedata/internal/rest/DefaultLiveDataEntriesResource.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-rest/src/test/java/org/xwiki/livedata/internal/rest/DefaultLiveDataEntriesResourceTest.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/webjar/liveDataSource.js
* Expose the bug in a unit test
=> XWIKI-19718: LiveData is badly parsing the filter values

xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/tests/unit/LivedataDropdownMenu.spec.js, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/tests/unit/panels/LiveDataAdvancedPanelExtension.spec.js, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/tests/unit/panels/LivedataAdvancedPanelFilter.spec.js, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/tests/unit/panels/LivedataAdvancedPanelProperties.spec.js, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/tests/unit/panels/LivedataAdvancedPanelSort.spec.js, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/tests/unit/panels/LivedataAdvancedPanels.spec.js, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/panels/LiveDataAdvancedPanelExtension.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/panels/LivedataAdvancedPanelFilter.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/panels/LivedataAdvancedPanelProperties.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/panels/LivedataAdvancedPanelSort.vue
* Declare the panel property in all panels.
* Use the data from the panel instead of duplicating the information.
Jira issue: https://jira.xwiki.org/browse/XWIKI-19788
=> XWIKI-19788: Live Data panels have invalid attribute "panel"

xwiki-platform-core/xwiki-platform-index/xwiki-platform-index-test/xwiki-platform-index-test-pageobjects/src/main/java/org/xwiki/index/test/po/DeletedDocsPage.java, xwiki-platform-core/xwiki-platform-legacy/xwiki-platform-legacy-oldcore/src/main/aspect/com/xpn/xwiki/web/DeleteActionCompatibilityAspect.aj, xwiki-platform-core/xwiki-platform-oldcore/src/main/resources/ApplicationResources.properties
* update some forgotten 14.4.1 tags
=> XWIKI-19653: Ability to redirect deleted page link to a new page

xwiki-platform-core/xwiki-platform-image/xwiki-platform-image-lightbox/xwiki-platform-image-lightbox-test/xwiki-platform-image-lightbox-test-pageobjects/src/main/java/org/xwiki/image/lightbox/test/po/Lightbox.java, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/po/AttachmentsPane.java
* remove not needed throws Exception
* adjust lightbox page date translation clean up since before `AttachmentsPane#getDateOfLastUpload`returned an additional space before the actual date
=> XWIKI-13454: Add pagination for Attachments

xwiki-platform-distribution/xwiki-platform-distribution-war-dependencies/pom.xml
Jira: https://jira.xwiki.org/browse/XWIKI-20028
=> XWIKI-20028: Cache issue when mention components need to be reloaded

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/js/xwiki/xwiki.js
* move code to plain js, since jquery blocks are executed too late
* recreate the script element to be able to load dynamically added js resources
=> XWIKI-20112: Custom headers are not registered when loaded to soon

xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/src/main/java/org/xwiki/mentions/internal/DefaultMentionsDataConsumer.java, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/src/test/java/org/xwiki/mentions/internal/DefaultMentionsDataConsumerTest.java, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-test/xwiki-platform-mentions-test-docker/src/test/it/org/xwiki/mentions/test/ui/MentionsIT.java
Jira: https://jira.xwiki.org/browse/XWIKI-20114
Note: this PR targets branch `stable-14.4.x` because a punctual issue prevents to execute docker tests on `master`
=> XWIKI-20114: Mention in comments wrongly attributed to the last document content editor

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/macros.vm, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/macros.vm, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/notification/macros.vm
XWIKI-20125: Disable lightbox for livetable
=> XWIKI-19480: Lightbox gallery displays many times the profile picture and additional ones

xwiki-platform-core/xwiki-platform-image/xwiki-platform-image-lightbox/xwiki-platform-image-lightbox-test/xwiki-platform-image-lightbox-test-docker/src/test/it/org/xwiki/image/lightbox/test/ui/LightboxIT.java, xwiki-platform-core/xwiki-platform-image/xwiki-platform-image-lightbox/xwiki-platform-image-lightbox-ui/src/main/resources/XWiki/Lightbox/LightboxConfiguration.xml, xwiki-platform-core/xwiki-platform-image/xwiki-platform-image-lightbox/xwiki-platform-image-lightbox-ui/src/main/resources/XWiki/Lightbox/LightboxConfigurationClass.xml
* enable lightbox by default
This should be merged after https://github.com/xwiki/xwiki-platform/pull/1915
=> XWIKI-20092: Enable the lightbox view for images by default

xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/doc/XWikiDocument.java, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/test/MockitoOldcore.java
Jira: https://jira.xwiki.org/browse/XWIKI-20124
=> XWIKI-20124: Errors on creating subwiki from template

xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-notifications/pom.xml, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-notifications/src/main/java/org/xwiki/mentions/internal/descriptors/NotificationAdministrationDocumentInitializer.java, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-notifications/src/test/java/org/xwiki/mentions/internal/descriptors/NotificationAdministrationDocumentInitializerTest.java
Jira: https://jira.xwiki.org/browse/XWIKI-20132
=> XWIKI-20132: Merge conflict hit during flavor upgrade when upgrading from 8.4 with filestore

xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-default/src/checkstyle/checkstyle-suppressions.xml, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-default/src/main/java/org/xwiki/notifications/filters/migration/R140401000XWIKI15460DataMigration.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-default/src/test/java/org/xwiki/notifications/filters/migration/R140401000XWIKI15460DataMigrationTest.java
* Don't rely on the UserManager if the user doesn't belong to current wiki
Note: still a WIP, need to fix tests.
=> XWIKI-20184: R140401000XWIKI15460 Migration error when migrating from < 14.0 if user belongs to subwiki

xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-api/src/main/java/org/xwiki/security/authentication/RetrieveUsernameException.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-api/src/main/java/org/xwiki/security/authentication/RetrieveUsernameManager.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-default/src/checkstyle/checkstyle-suppressions.xml, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-default/src/main/java/org/xwiki/security/authentication/internal/AuthenticationMailSender.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-default/src/main/java/org/xwiki/security/authentication/internal/DefaultResetPasswordManager.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-default/src/main/java/org/xwiki/security/authentication/internal/DefaultRetrieveUsernameManager.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-default/src/main/java/org/xwiki/security/authentication/internal/R140600000XWIKI19869DataMigrationListener.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-default/src/main/resources/META-INF/components.txt, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-default/src/test/java/org/xwiki/security/authentication/internal/AuthenticationMailSenderTest.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-default/src/test/java/org/xwiki/security/authentication/internal/DefaultResetPasswordManagerTest.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-default/src/test/java/org/xwiki/security/authentication/internal/DefaultRetrieveUsernameManagerTest.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-default/src/test/java/org/xwiki/security/authentication/internal/R140600000XWIKI19869DataMigrationListenerTest.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-script/src/main/java/org/xwiki/security/authentication/script/AuthenticationScriptService.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-script/src/test/java/org/xwiki/security/authentication/script/AuthenticationScriptServiceTest.java, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/forgotusername.vm
* Refactor forgot username feature to use java components with a RetrieveUsernameManager as we did for reset password
=> XWIKI-20138: On private wikis, users cannot recover their username

xwiki-platform-core/xwiki-platform-filter/xwiki-platform-filter-instance/xwiki-platform-filter-instance-document/src/main/java/org/xwiki/filter/instance/output/DocumentInstanceOutputProperties.java
Fixed minor typo in UI: "comming" -> "coming"
=> fixed typo: comming -> coming

xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins/src/main/resources/xwiki-source/plugin.js, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-test/xwiki-platform-ckeditor-test-docker/src/test/it/org/xwiki/ckeditor/test/ui/AllITs.java, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-test/xwiki-platform-ckeditor-test-docker/src/test/it/org/xwiki/ckeditor/test/ui/TextAreaIT.java, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-ui/src/main/resources/CKEditor/VelocityMacros.xml, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/doc/XWikiDocument.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/objects/classes/BaseClass.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/objects/classes/TextAreaClass.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/objects/meta/TextAreaMetaClass.java, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/editors/xdom_macros.vm, xwiki-platform-core/xwiki-platform-wysiwyg/xwiki-platform-wysiwyg-api/src/main/java/org/xwiki/wysiwyg/converter/HTMLConverter.java, xwiki-platform-core/xwiki-platform-wysiwyg/xwiki-platform-wysiwyg-api/src/main/java/org/xwiki/wysiwyg/internal/converter/DefaultHTMLConverter.java, xwiki-platform-core/xwiki-platform-wysiwyg/xwiki-platform-wysiwyg-api/src/main/java/org/xwiki/wysiwyg/script/WysiwygEditorScriptService.java
* add the field "restricted" to textarea properties
* take it into account in the textarea displayer
* take it into account in the WYSIWYG
TODO:
* tests
=> XWIKI-20366: Introduce a "restricted" switch to TextArea object properties

xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/tests/unit/LivedataDropdownMenu.spec.js, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/LivedataDropdownMenu.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/LivedataEntrySelectorAll.vue
Jira: https://jira.xwiki.org/browse/XWIKI-20205
This might require Vue tests (said @manuelleduc)
=> XWIKI-20205: Clicking the Global Search button also activates the Live Data actions button

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/delete.vm, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/refactoring_macros.vm, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-docker/src/test/it/org/xwiki/flamingo/test/docker/DeletePageIT.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/resources/ApplicationResources.properties, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/po/DeletePageConfirmationPage.java, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/js/xwiki/delete.js
* cherry-pick of the https://github.com/xwiki/xwiki-platform/pull/1997 changes
=> XWIKI-20426: The backlinks section of the delete UI no longer displayed backlink documents

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/misc.less
* cherry-pick from https://github.com/xwiki/xwiki-platform/pull/2022
=> XWIKI-20472: Results drop-down box is not properly displayed in document Delete view

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/js/xwiki/viewers/attachments.js
Jira: https://jira.xwiki.org/browse/XWIKI-20475
=> XWIKI-20475: "Attach" and "Cancel" buttons  are displayed in Attachment Tab when in-place edit mode is cancelled

xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins/src/main/resources/xwiki-macro/macroEditor.js
The same code changes made in this PR for the CKEditor on contrib: https://github.com/xwiki-contrib/application-ckeditor/pull/71
=> XWIKI-20492: Editing a macro that has a picker allowing multiple options merges the selected options instead of displaying them separately.

xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins/src/main/resources/xwiki-macro/macroEditor.js, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins/src/main/resources/xwiki-macro/plugin.js
Same changes as this PR for the CKEditor on contrib: https://github.com/xwiki-contrib/application-ckeditor/pull/72
=> XWIKI-20491: Provide the source document to the html displayers of the macro parameters

xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins/src/main/resources/xwiki-upload/plugin.js, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-ui/src/main/resources/CKEditor/FileUploader.xml, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-ui/src/test/java/org/xwiki/ckeditor/FileUploaderPageTest.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/web/XWikiServletRequestStub.java
Jira: https://jira.xwiki.org/browse/XWIKI-20314
=> XWIKI-20314: Uploading image.png using image dialog creates badly named attachments

xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/store/migration/DataMigration.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/java/org/xwiki/search/solr/internal/migration/R141004000XWIKI20575DataMigration.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/java/org/xwiki/search/solr/internal/migration/R150000000XWIKI20575DataMigration.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/resources/META-INF/components.txt, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/test/java/org/xwiki/search/solr/internal/DefaultSolrTest.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/test/java/org/xwiki/search/solr/internal/api/FieldUtilsTest.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-server/xwiki-platform-search-solr-server-core/src/main/resources/conf/managed-schema
* Add the missing dynamic field in managed-schema to handle fields with root locale
* Provide a migration to empty the solr core in order to trigger a reindex
* Add a new very simple unit test for FieldUtils
=> XWIKI-20575: Impossible to search pages created without locale

xwiki-platform-core/xwiki-platform-image/xwiki-platform-image-lightbox/xwiki-platform-image-lightbox-test/xwiki-platform-image-lightbox-test-docker/src/test/it/org/xwiki/image/lightbox/test/ui/LightboxIT.java, xwiki-platform-core/xwiki-platform-image/xwiki-platform-image-lightbox/xwiki-platform-image-lightbox-test/xwiki-platform-image-lightbox-test-pageobjects/src/main/java/org/xwiki/image/lightbox/test/po/ImagePopover.java, xwiki-platform-core/xwiki-platform-image/xwiki-platform-image-lightbox/xwiki-platform-image-lightbox-test/xwiki-platform-image-lightbox-test-pageobjects/src/main/java/org/xwiki/image/lightbox/test/po/LightboxPage.java
PR to be able to merge it either if needed before the release of 14.10.4, or right after.
=> [Misc] Improve exceptions handling of LightboxIT

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/macros.vm, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/test/java/org/xwiki/web/MacrosTest.java
* Add the new macro in macros.vm
* Provide a new test in MacrosTest for covering it
=> XWIKI-20583: Provide a macro for sanitizing URLs in templates

xwiki-platform-core/xwiki-platform-image/xwiki-platform-image-processing/xwiki-platform-image-processing-plugin/src/main/java/com/xpn/xwiki/plugin/image/ImagePlugin.java, xwiki-platform-core/xwiki-platform-image/xwiki-platform-image-processing/xwiki-platform-image-processing-plugin/src/test/java/com/xpn/xwiki/plugin/image/ImagePluginTest.java
Jira: https://jira.xwiki.org/browse/XWIKI-20602
=> XWIKI-20602: Server-side image resizing does not preserver image ratio in case of outscaling

README.md
=> Grammatically updated the readme file.

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/changesinline.vm
* inject required skin extensions
=> XWIKI-20722: JSX Objects are not loaded in the Rendered Diff view

xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/WCAGContext.java
**Jira:** https://jira.xwiki.org/browse/XWIKI-20541
**PR Changes: **
*Fixed the default parameter that failed non-docker tests unexpectedly
See https://ci.xwiki.org/job/XWiki/job/xwiki-platform/job/master/6565 for such fails
=> XWIKI-20541-2: Integrate a WCAG 2.1 validation tool in XWiki build/CI

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/uicomponents/tools/pageReady.js
* Make sure all URLs are absolute
* Handle fetch requests with Request parameter
=> [Misc] Fix URL handling pageReady.js

xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-test/xwiki-platform-administration-test-pageobjects/src/main/java/org/xwiki/administration/test/po/TemplatesAdministrationSectionPage.java
**Jira:** https://jira.xwiki.org/browse/XWIKI-20767
* Workaround to fix the form submission button click.
=> XWIKI-20767: TemplatesAdministrationSectionPage#createPagesFromTemplate is flickering

xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/store/XWikiHibernateStore.java
* Add a soft reference map of locks to XWikiHibernateStore to synchronize document saves.
While writing an integration test, I encountered https://jira.xwiki.org/browse/XWIKI-13473 so I decided to give it a quick try. The locks are stored in a `ReferenceMap` (with soft references for values) to ensure that they can be cleared under memory pressure but that under no circumstances a lock that is currently in use is removed from the map (as this would endanger the purpose of the lock).
Unfortunately, this only fixes the saving itself and not other issues like that when adding several comments, object ids might not be correctly incremented. However, I can confirm that this avoids the exceptions that were reported in the Jira issue.
=> XWIKI-13473: Exception when the same document is saved at the same time in 2 different threads

xwiki-platform-core/xwiki-platform-oldcore/src/main/resources/ApplicationResources.properties, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/js/xwiki/table/livetable.js
**Jira:** https://jira.xwiki.org/browse/XWIKI-20693
* Added an aria-label to the livetable pagesizeselect Element
=> XWIKI-20693: Livetable page size select doesn't have a name

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/figure.less
Jira: https://jira.xwiki.org/browse/XWIKI-20823
=> XWIKI-20823: Standalone Figures are displayed next to each other

xwiki-platform-core/xwiki-platform-component/xwiki-platform-component-wiki/src/main/java/org/xwiki/component/wiki/WikiComponent.java, xwiki-platform-core/xwiki-platform-component/xwiki-platform-component-wiki/src/main/java/org/xwiki/component/wiki/internal/ComponentClassInitializer.java, xwiki-platform-core/xwiki-platform-component/xwiki-platform-component-wiki/src/main/java/org/xwiki/component/wiki/internal/DefaultWikiComponent.java, xwiki-platform-core/xwiki-platform-component/xwiki-platform-component-wiki/src/main/java/org/xwiki/component/wiki/internal/DefaultWikiComponentBuilder.java, xwiki-platform-core/xwiki-platform-component/xwiki-platform-component-wiki/src/main/java/org/xwiki/component/wiki/internal/WikiComponentConstants.java, xwiki-platform-core/xwiki-platform-component/xwiki-platform-component-wiki/src/main/java/org/xwiki/component/wiki/internal/bridge/DefaultWikiComponentBridge.java, xwiki-platform-core/xwiki-platform-component/xwiki-platform-component-wiki/src/main/java/org/xwiki/component/wiki/internal/bridge/WikiComponentBridge.java, xwiki-platform-core/xwiki-platform-component/xwiki-platform-component-wiki/src/test/java/org/xwiki/component/wiki/DefaultWikiComponentBuilderTest.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/XWiki.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/doc/MandatoryDocumentInitializer.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/objects/classes/NumberClass.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/java/org/xwiki/search/solr/internal/IndexingUserConfigurationInitializer.java
* add priority support to wiki components
Depends on https://github.com/xwiki/xwiki-commons/pull/265.
=> XCOMMONS-2507: Add a priority concept in components

xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-default/src/main/java/org/xwiki/user/internal/converter/AbstractUserReferenceConverter.java, xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-default/src/test/java/org/xwiki/user/internal/converter/UserReferenceConverterTest.java
* Add support for converting UserReference to DocumentReference
* Add a unit test
Jira issue: https://jira.xwiki.org/browse/XWIKI-20868
=> XWIKI-20868: UserReference cannot be converted to DocumentReference in Velocity

xwiki-platform-core/xwiki-platform-export/xwiki-platform-export-pdf/xwiki-platform-export-pdf-test/xwiki-platform-export-pdf-test-docker/src/test/it/org/xwiki/export/pdf/test/ui/PDFExportIT.java
Fixing regression introduced with https://github.com/xwiki/xwiki-platform/pull/2151
Testing logs (after PR): https://up1.xwikisas.com/#LGC2mQlGjQ5xIGzu9cUj8w
=> [Misc]: Fixing export PDF functional test

xwiki-platform-core/xwiki-platform-resource/xwiki-platform-resource-default/src/main/java/org/xwiki/resource/entity/EntityResourceReference.java, xwiki-platform-core/xwiki-platform-resource/xwiki-platform-resource-default/src/test/java/org/xwiki/resource/entity/EntityResourceReferenceTest.java, xwiki-platform-core/xwiki-platform-url/xwiki-platform-url-schemes/xwiki-platform-url-scheme-reference/src/main/java/org/xwiki/url/internal/reference/EntityResourceReferenceResolver.java, xwiki-platform-core/xwiki-platform-url/xwiki-platform-url-schemes/xwiki-platform-url-scheme-standard/src/main/java/org/xwiki/url/internal/standard/entity/AbstractEntityResourceReferenceResolver.java, xwiki-platform-core/xwiki-platform-url/xwiki-platform-url-schemes/xwiki-platform-url-scheme-standard/src/test/java/org/xwiki/url/internal/standard/entity/BinEntityResourceReferenceResolverTest.java, xwiki-platform-core/xwiki-platform-vfs/xwiki-platform-vfs-api/src/main/java/org/xwiki/vfs/VfsResourceReference.java
* add the concept of anchor to EntityResourceReference
* add the support for extracting the anchor in EntityResourceReference resolvers
=> XWIKI-20870: Add support for the anchor in EntityResourceReference and EntityResourceReference resolvers

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/children.vm, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/siblings.vm
Jira: https://jira.xwiki.org/browse/XWIKI-20902
=> XWIKI-20902: Shortcuts are not working on the children and sibling pages

xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-macro/src/main/resources/ApplicationResources.properties, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/tests/unit/LivedataPagination.spec.js, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/LivedataPagination.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/webjar/Logic.js
**Jira:** https://jira.xwiki.org/browse/XWIKI-20756
* Added a translated title to the select
* Updated unit tests
=> XWIKI-20756: Livedata page size select does not have an accessible name

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/edit.less, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/js/xwiki/editors/autosave.js
**Jira:** https://jira.xwiki.org/browse/XWIKI-20825
* Removed the use of opacity
* Added a new class to the parent element instead.
* Updated style using theme for the new class.
**View:** 
**Video demo:** https://up1.xwikisas.com/#31sM6F-oM1I2dW67EIaV3g
=> XWIKI-20825: Edit autosave frequency contrast issue

xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/po/BasePage.java, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/po/ViewPage.java
**Jira:** https://jira.xwiki.org/browse/XWIKI-20842
* Updated the PO selectors
Passed both:
* `mvn clean install -Pquality,integration-tests,docker -f xwiki-platform-core/xwiki-platform-dashboard/xwiki-platform-dashboard-test/xwiki-platform-dashboard-test-docker/ -Dxwiki.test.ui.wcag=true`
* `mvn clean install -Pquality,integration-tests,docker -f xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-test/xwiki-platform-ckeditor-test-docker/ -Dxwiki.test.ui.wcag=true`
Those two modules failed the build on #6703 , see the jira ticket for more details.
=> XWIKI-20842: More actions button is an anchor

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-docker/src/test/it/org/xwiki/flamingo/test/docker/AttachmentIT.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-test/xwiki-platform-livedata-test-pageobjects/src/main/java/org/xwiki/livedata/test/po/TableLayoutElement.java, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/po/DateRangePicker.java
* treat the filter-date case
* rename test since it's actually using a live data
=> XWIKI-20231: AttachmentIT#filterAttachmentsLivetable is flickering

xwiki-platform-core/xwiki-platform-panels/xwiki-platform-panels-ui/src/main/resources/Panels/Applications.xml
**Jira:** https://jira.xwiki.org/browse/XWIKI-10752
* Reduced scope of the media query selectors in charge for this presentation bug
* Added extra style to display the inner elements nicely whatever the size of the column
https://up1.xwikisas.com/#mpc2g5T1yZzarhjFXvLGDw
BFD
=> XWIKI-10752: "More applications" content is not readable in condensed display

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/uicomponents/widgets/buttonGroup.css
Jira: https://jira.xwiki.org/browse/XWIKI-21075
Target: 15.6-rc-1, 15.5.1, 14.10.14
=> XWIKI-21075: buttonGroup.css applies to Live Data "more actions" button

xwiki-platform-core/xwiki-platform-attachment/xwiki-platform-attachment-picker/xwiki-platform-attachment-picker-ui/src/main/resources/Attachment/Picker/Code/AttachmentGalleryPicker.xml, xwiki-platform-core/xwiki-platform-attachment/xwiki-platform-attachment-picker/xwiki-platform-attachment-picker-webjar/src/main/webjar/attachmentGalleryPicker.js, xwiki-platform-core/xwiki-platform-attachment/xwiki-platform-attachment-picker/xwiki-platform-attachment-picker-webjar/src/main/webjar/solrSearch.js, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins/src/main/webjar/xwiki-image/attachmentService.js, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins/src/main/webjar/xwiki-image/imageWizard.js, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins/src/main/webjar/xwiki-image/plugin.js, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins/src/main/webjar/xwiki-slash/plugin.js, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-test/xwiki-platform-ckeditor-test-docker/src/test/it/org/xwiki/ckeditor/test/ui/QuickActionsIT.java, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-test/xwiki-platform-ckeditor-test-docker/src/test/it/org/xwiki/ckeditor/test/ui/UndoRedoIT.java, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-ui/src/main/resources/CKEditor/EditSheet.xml, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-ui/src/main/resources/CKEditor/Translations.xml, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-ui/src/main/resources/XWiki/SuggestSolrMacros.xml
Jira: https://jira.xwiki.org/browse/XWIKI-20938
This pull request adds a new Quick Action to quickly upload or search for and insert an image into the WYSIWYG editor.
Here's a preview of the feature:
=> XWIKI-20938: Add ability to insert an image using the keyboard

xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-test/xwiki-platform-ckeditor-test-docker/src/test/it/org/xwiki/ckeditor/test/ui/ImagePluginIT.java
JIRA: https://jira.xwiki.org/browse/XWIKI-21159
This is a cherry pick.
=> XWIKI-21159: ImagePluginIT#updateExternalImageSize is flickering

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/editactions.vm, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/buttons.less
Jira: https://jira.xwiki.org/browse/XWIKI-18579
=> XWIKI-18579: Inconsistent rounding of save buttons at the bottom of the edit forms (in-place or not)

xwiki-platform-core/xwiki-platform-image/xwiki-platform-image-lightbox/xwiki-platform-image-lightbox-webjar/src/main/webjar/lightbox.js
https://jira.xwiki.org/browse/XWIKI-21096
* Fixed an inconsistency in a translation key introduced in https://github.com/xwiki/xwiki-platform/pull/2281
=> XWIKI-21096: Add keyboard navigation to the Lightbox feature

xwiki-platform-core/xwiki-platform-eventstream/xwiki-platform-eventstream-api/src/main/java/org/xwiki/eventstream/query/MailEntityQueryCondition.java, xwiki-platform-core/xwiki-platform-eventstream/xwiki-platform-eventstream-api/src/test/java/org/xwiki/eventstream/EqualEventQueryTest.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-notifiers/xwiki-platform-notifications-notifiers-default/pom.xml, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-notifiers/xwiki-platform-notifications-notifiers-default/src/main/java/org/xwiki/notifications/notifiers/internal/UserEventDispatcher.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-notifiers/xwiki-platform-notifications-notifiers-default/src/main/java/org/xwiki/notifications/notifiers/internal/UserEventDispatcherListener.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-notifiers/xwiki-platform-notifications-notifiers-default/src/main/java/org/xwiki/notifications/notifiers/internal/UserEventDispatcherScheduler.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-notifiers/xwiki-platform-notifications-notifiers-default/src/main/resources/META-INF/components.txt, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-notifiers/xwiki-platform-notifications-notifiers-default/src/test/java/org/xwiki/notifications/notifiers/internal/UserEventDispatcherTest.java
* UserEventDispatcher should take care of not querying twice the same events
=> XWIKI-21299: Multiple mail received with live email notifications

xwiki-platform-core/pom.xml, xwiki-platform-core/xwiki-platform-attachment/xwiki-platform-attachment-api/src/main/java/org/xwiki/attachment/script/AttachmentScriptService.java, xwiki-platform-core/xwiki-platform-attachment/xwiki-platform-attachment-validation/xwiki-platform-attachment-validation-api/pom.xml, xwiki-platform-core/xwiki-platform-attachment/xwiki-platform-attachment-validation/xwiki-platform-attachment-validation-api/src/main/java/org/xwiki/attachment/validation/AttachmentValidationScriptService.java, xwiki-platform-core/xwiki-platform-attachment/xwiki-platform-attachment-validation/xwiki-platform-attachment-validation-ui/src/main/resources/XWiki/Attachment/Validation/Code/FileSizeValidation.xml, xwiki-platform-core/xwiki-platform-attachment/xwiki-platform-attachment-validation/xwiki-platform-attachment-validation-ui/src/main/resources/XWiki/Attachment/Validation/Code/MimetypeValidation.xml
https://jira.xwiki.org/browse/XWIKI-21321
=> XWIKI-21321: Rename attachmentValidation script service to attachment.validation

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/uicomponents/dashboard/dashboard.js
Jira: https://jira.xwiki.org/browse/XWIKI-21290
=> XWIKI-21290: Dashboard edit title can be wrong if the content contains an element with a title class

Jenkinsfile, xwiki-platform-core/xwiki-platform-extension/xwiki-platform-extension-security/xwiki-platform-extension-security-test/xwiki-platform-extension-security-test-pageobjects/src/main/java/org/xwiki/extension/security/test/po/ExtensionVulnerabilitiesAdminPage.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-test/xwiki-platform-livedata-test-pageobjects/src/main/java/org/xwiki/livedata/test/po/LiveDataElement.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-test/xwiki-platform-livedata-test-pageobjects/src/main/java/org/xwiki/livedata/test/po/TableLayoutElement.java, xwiki-platform-distribution/xwiki-platform-distribution-flavor/xwiki-platform-distribution-flavor-test/pom.xml, xwiki-platform-distribution/xwiki-platform-distribution-flavor/xwiki-platform-distribution-flavor-test/xwiki-platform-distribution-flavor-test-security/pom.xml, xwiki-platform-distribution/xwiki-platform-distribution-flavor/xwiki-platform-distribution-flavor-test/xwiki-platform-distribution-flavor-test-security/src/test/it/org/xwiki/test/security/AllTests.java, xwiki-platform-distribution/xwiki-platform-distribution-flavor/xwiki-platform-distribution-flavor-test/xwiki-platform-distribution-flavor-test-security/src/test/it/org/xwiki/test/security/ExtensionSecurityTest.java
Jira: https://jira.xwiki.org/browse/XWIKI-21264
**TODO**
=> XWIKI-21264: Implement a security list functional test without mocking the sources

xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/store/XWikiHibernateStore.java
JIRA: https://jira.xwiki.org/browse/XWIKI-21385
I basically re-applied the same mechanism @michitux put in place for xwiki documents to xwiki space saving.
=> XWIKI-21385: Possible SQL error in case of concurrent save of space

xwiki-platform-core/xwiki-platform-dashboard/xwiki-platform-dashboard-test/xwiki-platform-dashboard-test-docker/src/test/it/org/xwiki/dashboard/test/ui/DashboardIT.java
https://jira.xwiki.org/browse/XWIKI-20827
* Fixed an outdated functional test
The [changes merged here](https://github.com/xwiki/xwiki-platform/pull/2329) created [a test fail on the CI](https://ci.xwiki.org/job/XWiki/job/xwiki-platform/job/master/lastCompletedBuild/testReport/org.xwiki.dashboard.test.ui/AllIT$NestedDashboardIT/Platform_Builds___main___integration_tests___IT_for_xwiki_platform_core_xwiki_platform_dashboard_xwiki_platform_dashboard_test_xwiki_platform_dashboard_test_docker___Build_for_IT_for_xwiki_platform_core_xwiki_platform_dashboard_xwiki_platform_dashboard_test_xwiki_platform_dashboard_test_docker___editDashboard_TestUtils_/).
=> XWIKI-20827: Inline links must be distinguishable without relying on color

xwiki-platform-core/pom.xml, xwiki-platform-core/xwiki-platform-extension/xwiki-platform-extension-index/pom.xml, xwiki-platform-core/xwiki-platform-extension/xwiki-platform-extension-index/src/main/java/org/xwiki/extension/index/internal/ExtensionIndexSolrCoreInitializer.java, xwiki-platform-core/xwiki-platform-extension/xwiki-platform-extension-index/src/main/java/org/xwiki/extension/index/internal/ExtensionIndexStore.java, xwiki-platform-core/xwiki-platform-extension/xwiki-platform-extension-index/src/main/java/org/xwiki/extension/index/internal/listener/ExtensionIndexApplicationStartedListener.java, xwiki-platform-core/xwiki-platform-extension/xwiki-platform-extension-index/src/main/java/org/xwiki/extension/index/internal/listener/ExtensionIndexCleanupListener.java, xwiki-platform-core/xwiki-platform-extension/xwiki-platform-extension-index/src/main/java/org/xwiki/extension/index/security/ExtensionSecurityAnalysisResult.java, xwiki-platform-core/xwiki-platform-extension/xwiki-platform-extension-index/src/main/resources/META-INF/components.txt, xwiki-platform-core/xwiki-platform-extension/xwiki-platform-extension-index/src/test/java/org/xwiki/extension/index/internal/listener/ExtensionIndexCleanupListenerTest.java, xwiki-platform-core/xwiki-platform-extension/xwiki-platform-extension-security/xwiki-platform-extension-security-api/src/main/java/org/xwiki/extension/security/internal/ExtensionSecuritySolrClient.java, xwiki-platform-core/xwiki-platform-extension/xwiki-platform-extension-security/xwiki-platform-extension-security-api/src/test/java/org/xwiki/extension/security/internal/ExtensionSecuritySolrClientTest.java, xwiki-platform-core/xwiki-platform-extension/xwiki-platform-extension-security/xwiki-platform-extension-security-index/src/main/java/org/xwiki/extension/security/internal/analyzer/VulnerabilityIndexer.java, xwiki-platform-core/xwiki-platform-extension/xwiki-platform-extension-security/xwiki-platform-extension-security-index/src/test/java/org/xwiki/extension/security/internal/analyzer/VulnerabilityIndexerTest.java
Jira: https://jira.xwiki.org/browse/XWIKI-21360
**TODO**
=> XWIKI-21360: Core extensions vulnerabilities are not updated after an upgrade of XWiki

xwiki-platform-core/xwiki-platform-index/xwiki-platform-index-default/src/main/java/org/xwiki/index/internal/migration/R140300000XWIKI19614DataMigration.java, xwiki-platform-core/xwiki-platform-index/xwiki-platform-index-default/src/test/java/org/xwiki/index/internal/migration/R140300000XWIKI19614DataMigrationTest.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/org/xwiki/internal/migration/R150000000XWIKI20285DataMigration.java
Jira: https://jira.xwiki.org/browse/XWIKI-21463
=> XWIKI-21463: Many "Failed to resolve document reference" warnings when upgrading XWiki on Oracle

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/extension.vm
https://jira.xwiki.org/browse/XWIKI-21344
* Updated the class of the label to make it visible to assistive techs
=> XWIKI-21344: extensionSearchRepositoryList select has a hidden label

xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/webjar/liveDataSource.js
This PR is somewhat difficult to test, but you can "feel" the code by setting a breakpoint on the abort line and setting network throttling to GPRS or something badly slow.
Convenient test link: http://localhost:8080/xwiki/bin/view/Main/AllDocs?minify=false&useLiveData=true#|t=alldocs&p=1&l=15&s=doc.location&d=asc&doc.title=f
=> XWIKI-21447: Incorrect results when typing slowly in filter fields

xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-requiredrights/xwiki-platform-security-requiredrights-default/src/main/java/org/xwiki/platform/security/requiredrights/internal/RequiredRightsChangedFilter.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-requiredrights/xwiki-platform-security-requiredrights-default/src/main/java/org/xwiki/platform/security/requiredrights/internal/RequiredRightsChangedResult.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-requiredrights/xwiki-platform-security-requiredrights-default/src/main/java/org/xwiki/platform/security/requiredrights/internal/RequiredRightsEditConfirmationChecker.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-requiredrights/xwiki-platform-security-requiredrights-default/src/main/resources/ApplicationResources.properties, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-requiredrights/xwiki-platform-security-requiredrights-default/src/main/resources/css/security/requiredrights/requiredRightsEditConfirmationChecker.css, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-requiredrights/xwiki-platform-security-requiredrights-default/src/main/resources/js/security/requiredrights/requiredRightsEditConfirmationChecker.js, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-requiredrights/xwiki-platform-security-requiredrights-default/src/main/resources/templates/security/requiredrights/requiredRightsEditConfirmationChecker.vm, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-requiredrights/xwiki-platform-security-requiredrights-default/src/test/java/org/xwiki/platform/security/requiredrights/internal/RequiredRightsChangedFilterTest.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-requiredrights/xwiki-platform-security-requiredrights-default/src/test/java/org/xwiki/platform/security/requiredrights/internal/RequiredRightsEditConfirmationCheckerTest.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-requiredrights/xwiki-platform-security-requiredrights-test/xwiki-platform-security-requiredrights-test-docker/src/test/it/org/xwiki/security/requiredrights/test/ui/RequiredRightsIT.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-requiredrights/xwiki-platform-security-requiredrights-test/xwiki-platform-security-requiredrights-test-pageobjects/src/main/java/org/xwiki/security/requiredrights/test/po/RequiredRightsPreEditCheckElement.java
Jira: https://jira.xwiki.org/browse/XWIKI-21477
* Provide shorter sentence and a summary of the added/removed rights
* The details are hidden by default
**Folded**
**Expanded**
=> XWIKI-21477: Improve the required rights result reporting

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/type.less, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/variablesInit.vm, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-theme/xwiki-platform-flamingo-theme-bootswatch/src/main/resources/FlamingoThemes/Simplex.xml, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-theme/xwiki-platform-flamingo-theme-bootswatch/src/main/resources/FlamingoThemes/Spacelab.xml, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-theme/xwiki-platform-flamingo-theme-bootswatch/src/main/resources/FlamingoThemes/Yeti.xml, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-theme/xwiki-platform-flamingo-theme-ui/pom.xml, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-theme/xwiki-platform-flamingo-theme-ui/src/main/resources/FlamingoThemes/Iceberg.xml
Jira
* https://jira.xwiki.org/browse/XWIKI-21582
* https://jira.xwiki.org/browse/XWIKI-21333
=> XWIKI-21582: It's hard to distinguish between "i" and small caps "l" in Extension Manager with the new implemented font

xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-test/xwiki-platform-search-solr-test-docker/src/test/it/org/xwiki/search/solr/test/ui/SolrSearchIT.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-test/xwiki-platform-search-solr-test-pageobjects/src/main/java/org/xwiki/search/solr/test/po/SolrSearchPage.java
Edit some XPaths to support branches 14.10.x and 15.5.x.
=> [Misc] Fix SolrSearchIT failing test

.mvn/gradle-enterprise.xml
Set remote build cache to push only if authenticated
=> Update gradle enterprise 

xwiki-platform-core/pom.xml, xwiki-platform-core/xwiki-platform-extension/xwiki-platform-extension-security/xwiki-platform-extension-security-index/pom.xml, xwiki-platform-core/xwiki-platform-extension/xwiki-platform-extension-security/xwiki-platform-extension-security-index/src/main/java/org/xwiki/extension/security/analyzer/ReviewsFetcher.java, xwiki-platform-core/xwiki-platform-extension/xwiki-platform-extension-security/xwiki-platform-extension-security-index/src/main/java/org/xwiki/extension/security/internal/DefaultReviewsFetcher.java, xwiki-platform-core/xwiki-platform-extension/xwiki-platform-extension-security/xwiki-platform-extension-security-index/src/main/java/org/xwiki/extension/security/internal/ExtensionSecurityException.java, xwiki-platform-core/xwiki-platform-extension/xwiki-platform-extension-security/xwiki-platform-extension-security-index/src/main/java/org/xwiki/extension/security/internal/ExtensionSecurityJob.java
Jira: https://jira.xwiki.org/browse/XWIKI-21725
=> XWIKI-21725: Cloudflare reject review requests without a user agent

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/uicomponents/search/searchSuggest.js
* Prevents the search suggest to be broken in case of missing evaluator
=> XWIKI-21744: Errors related to ObjectEvaluator after upgrading to 15.10.2

xwiki-platform-core/xwiki-platform-bridge/src/main/java/org/xwiki/bridge/DocumentAccessBridge.java, xwiki-platform-core/xwiki-platform-lesscss/xwiki-platform-lesscss-default/src/main/java/org/xwiki/lesscss/internal/resources/LESSSkinFileResourceReference.java, xwiki-platform-core/xwiki-platform-lesscss/xwiki-platform-lesscss-default/src/test/java/org/xwiki/lesscss/internal/resources/LESSSkinFileResourceReferenceTest.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/webjar/Logic.js, xwiki-platform-core/xwiki-platform-localization/xwiki-platform-localization-api/src/main/java/org/xwiki/localization/TranslationBundleDoesNotExistsException.java, xwiki-platform-core/xwiki-platform-localization/xwiki-platform-localization-api/src/main/java/org/xwiki/localization/TranslationBundleFactoryDoesNotExistsException.java, xwiki-platform-core/xwiki-platform-localization/xwiki-platform-localization-sources/xwiki-platform-localization-source-wiki/src/main/java/org/xwiki/localization/wiki/internal/DocumentTranslationBundleFactory.java, xwiki-platform-core/xwiki-platform-office/xwiki-platform-office-importer/src/main/java/org/xwiki/officeimporter/internal/converter/DefaultOfficeConverterResult.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/doc/XWikiDocument.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/objects/BaseCollection.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/plugin/packaging/Package.java, xwiki-platform-core/xwiki-platform-oldcore/src/test/resources/hibernate.cfg.xml, xwiki-platform-core/xwiki-platform-repository/xwiki-platform-repository-server-api/src/main/java/org/xwiki/repository/internal/RepositoryManager.java, xwiki-platform-core/xwiki-platform-repository/xwiki-platform-repository-server-ui/src/main/resources/ExtensionCode/RepositoryAdmin.xml, xwiki-platform-core/xwiki-platform-scheduler/xwiki-platform-scheduler-api/src/main/java/com/xpn/xwiki/plugin/scheduler/SchedulerPlugin.java, xwiki-platform-core/xwiki-platform-scheduler/xwiki-platform-scheduler-api/src/main/java/com/xpn/xwiki/plugin/scheduler/SchedulerPluginApi.java, xwiki-platform-core/xwiki-platform-store/xwiki-platform-store-merge/xwiki-platform-store-merge-default/src/main/java/org/xwiki/store/merge/internal/DefaultMergeManager.java, xwiki-platform-core/xwiki-platform-wiki/xwiki-platform-wiki-default/src/test/java/org/xwiki/wiki/internal/descriptor/DefaultWikiDescriptorManagerTest.java, xwiki-platform-core/xwiki-platform-wiki/xwiki-platform-wiki-ui/xwiki-platform-wiki-ui-mainwiki/src/main/resources/WikiManager/Translations.ca.xml, xwiki-platform-core/xwiki-platform-wiki/xwiki-platform-wiki-ui/xwiki-platform-wiki-ui-mainwiki/src/main/resources/WikiManager/Translations.da.xml, xwiki-platform-core/xwiki-platform-wiki/xwiki-platform-wiki-ui/xwiki-platform-wiki-ui-mainwiki/src/main/resources/WikiManager/Translations.it.xml, xwiki-platform-core/xwiki-platform-wiki/xwiki-platform-wiki-ui/xwiki-platform-wiki-ui-mainwiki/src/main/resources/WikiManager/Translations.mr.xml, xwiki-platform-core/xwiki-platform-wiki/xwiki-platform-wiki-ui/xwiki-platform-wiki-ui-mainwiki/src/main/resources/WikiManager/Translations.ro.xml, xwiki-platform-core/xwiki-platform-wiki/xwiki-platform-wiki-ui/xwiki-platform-wiki-ui-mainwiki/src/main/resources/WikiManager/Translations.sv.xml, xwiki-platform-core/xwiki-platform-wiki/xwiki-platform-wiki-ui/xwiki-platform-wiki-ui-mainwiki/src/main/resources/WikiManager/Translations.xml, xwiki-platform-core/xwiki-platform-wiki/xwiki-platform-wiki-ui/xwiki-platform-wiki-ui-mainwiki/src/main/resources/WikiManager/Translations.zh.xml, xwiki-platform-tools/xwiki-platform-tool-configuration-resources/src/main/resources/hibernate.cfg.xml.vm
I ran:
```
git grep -l  "does not exists"  | xargs sed -i 's/does not exists/does not exist/g'
```
=> [Misc] Change 'does not exists' to 'does not exist'

xwiki-platform-core/xwiki-platform-like/xwiki-platform-like-api/pom.xml, xwiki-platform-core/xwiki-platform-like/xwiki-platform-like-api/src/main/resources/templates/likers.vm, xwiki-platform-core/xwiki-platform-like/xwiki-platform-like-api/src/test/java/org/xwiki/like/LikersPageTest.java, xwiki-platform-core/xwiki-platform-like/xwiki-platform-like-test/xwiki-platform-like-test-docker/src/test/it/org/xwiki/like/test/ui/LikeIT.java, xwiki-platform-core/xwiki-platform-like/xwiki-platform-like-test/xwiki-platform-like-test-pageobjects/src/main/java/org/xwiki/like/test/po/LikersPage.java
Jira: https://jira.xwiki.org/browse/XWIKI-18992
**Before**
**After**
=> XWIKI-18992: Replace the Livetable of likers of a page with a Live Data macro

xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-ui/src/main/resources/XWiki/Notifications/Code/NotificationsDisplayerUIX.xml
Jira: https://jira.xwiki.org/browse/XWIKI-21550
=> XWIKI-21550: Remove the border and increase the shadown of the header dropdowns

xwiki-platform-core/xwiki-platform-repository/xwiki-platform-repository-server-ui/src/test/java/org/xwiki/repository/server/ui/ExtensionSheetPageTest.java
* Fix missing assert in ExtensionSheetPageTest
N/A
N/A
N/A
=> [Misc] Fix missing assert in test

xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-ui/src/main/resources/IconThemesCode/IconPicker.xml
https://jira.xwiki.org/browse/XWIKI-12013
* Replaced the hard coded icon selection with a call to the appropriate velocity API
* Sorted the result of this call
* Added event handlers to filter the available icons based on the text in the input field.
* The filtering is done directly in the JS that creates the icons instead of via the json query. Even though the initial results transferred will be larger than the amount of icons displayed, this is more efficient when searching through icons, because a new filter does not need a new request.
Demo with the changes proposed in this PR applied.
https://github.com/user-attachments/assets/8bfc2524-10c4-4104-a545-1634fcbc12ea
Only manual tests such as the ones seen in the demo above.
From what I can see, there's no pageObject for integration …
=> XWIKI-12013: Sort the icons alphabetically in the icon picker

xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-ui/src/main/resources/XWiki/AdminPageUIX.xml, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/menus_content.vm, xwiki-platform-core/xwiki-platform-like/xwiki-platform-like-ui/src/main/resources/XWiki/Like/LikeViewersMenuUIX.xml
=> XWIKI-12629: Page Right is shown when administering inexistent WebHome

xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-ui/src/main/resources/XWiki/AdminPageUIX.xml, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/menus_content.vm, xwiki-platform-core/xwiki-platform-like/xwiki-platform-like-ui/src/main/resources/XWiki/Like/LikeViewersMenuUIX.xml
=> XWIKI-12629: Page Right is shown when administering inexistent WebHome page

xwiki-platform-core/xwiki-platform-help/xwiki-platform-help-ui/src/main/resources/Help/Applications/WebHome.xml, xwiki-platform-core/xwiki-platform-help/xwiki-platform-help-ui/src/main/resources/Help/Code/VelocityMacros.xml, xwiki-platform-core/xwiki-platform-help/xwiki-platform-help-ui/src/main/resources/Help/Macros/WebHome.xml, xwiki-platform-core/xwiki-platform-help/xwiki-platform-help-ui/src/main/resources/Help/Templates/WebHome.xml, xwiki-platform-core/xwiki-platform-help/xwiki-platform-help-ui/src/main/resources/Help/WebHome.xml
**Jira:** https://jira.xwiki.org/browse/XWIKI-19406
* Removed the bootstrap grid from the card on the Help Home page
* Added style to the new card elements
* Added a couple classes to force the number of columns in a card list
* Updated structure on other pages of the help section.
https://up1.xwikisas.com/#XCvEXu2KSZCe4wDKI1s4-g
Successfully passed `mvn clean install -Pquality,integration-tests,docker -f xwiki-platform-core/xwiki-platform-help/ -Dxwiki.test.ui.wcag=true`
Done during BFD on June the 8th
=> XWIKI-19406: Layout alignment issue

.github/renovate.json5
N/A
* add an exclusion for all the deprecated dependencies of bootstrap that are currently difficult to upgrade
*
*
=> [Misc] Ignore boostrap in renovate

pom.xml
=> [Misc] Upgrade to latest LO LTS

xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-ui/src/main/resources/XWiki/ForgotUsernameMailContent.xml
- Add XWiki.Mail object with French content to page XWiki.ForgotUsernameMailContent
=> XWIKI-22943: Make username reminder mail available in French

xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins/src/main/webjar/xwiki-resource/entityResourceSuggester.js, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-ui/src/main/resources/CKEditor/LinkNameStrategyHelper.xml
To be merged once 17.4.2 is released.
*  Ensure to check if the input reference exists and return it as exact match if it does
(cherry picked from commit 27c16af66d6dcd81e8c95aacb3ba8f9bf518108b)
*
*
=> XWIKI-23229: The link dialog doesn't suggest creating a link to a pasted reference

xwiki-platform-core/xwiki-platform-websocket/src/main/java/org/xwiki/websocket/internal/DynamicEchoEndpoint.java, xwiki-platform-core/xwiki-platform-websocket/src/test/java/org/xwiki/websocket/internal/DynamicEchoEndpointTest.java
https://jira.xwiki.org/browse/XWIKI-23350
*
*
* stable-17.4.x
=> XWIKI-23350: Unable to find Decoder for type: jakarta.websocket.MessageHandler$Whole on DynamicEchoEndpoint

xwiki-platform-core/xwiki-platform-skin/xwiki-platform-skin-test/xwiki-platform-skin-test-pageobjects/src/main/java/org/xwiki/skin/test/po/SkinInlinePage.java, xwiki-platform-core/xwiki-platform-skin/xwiki-platform-skin-test/xwiki-platform-skin-test-pageobjects/src/main/java/org/xwiki/skin/test/po/SkinTemplateElement.java, xwiki-platform-core/xwiki-platform-skin/xwiki-platform-skin-ui/src/main/resources/SkinsCode/XWikiSkinsSheet.xml
N/A
* Put a propertySlided CSS class whenever properties are displayed through a slide animation in the theme editor
* Use that CSS class in the PO to know what to wait for before accessing the form
*
*
=> [Misc] Fix WikiSkinIT test

xwiki-platform-core/xwiki-platform-oldcore/src/main/resources/ApplicationResources.properties
https://jira.xwiki.org/browse/XWIKI-23518
* Fixed the typos and wording problems raised in the issue description.
None
None, minor changes to the default translation value only, it should be pretty safe still.
* None.
=> XWIKI-23518: Distribution Wizard typos and some wording issue
