xwiki-platform-core/xwiki-platform-ratings/xwiki-platform-ratings-api/src/main/java/org/xwiki/ratings/internal/DefaultRatingsManager.java, xwiki-platform-core/xwiki-platform-ratings/xwiki-platform-ratings-api/src/main/java/org/xwiki/ratings/internal/SeparatePageRatingsManager.java
The bug consisted in the fact that all users were serialized to their local representation (spage.page) and this proved to be an issue when serializing a global user acting on a subwiki due to the fact that the serialized user document would not contain the main wiki prefix (space.page instead of mainWikiID:space.page)
=> XWIKI-11917 : Remove debugging modal when rating an extension, on a sub-wiki

xwiki-platform-core/xwiki-platform-wiki/xwiki-platform-wiki-rest/xwiki-platform-wiki-rest-default/src/main/java/org/xwiki/wiki/rest/internal/DefaultWikiManagerREST.java
Just remove a redundancy in the declaration of API paths (REST service `xwiki-platform-wiki` module)  since it's already defined in the [`xwiki-platform-wiki-rest-api`](https://github.com/xwiki/xwiki-platform/blob/master/xwiki-platform-core/xwiki-platform-wiki/xwiki-platform-wiki-rest/xwiki-platform-wiki-rest-api/src/main/java/org/xwiki/wiki/rest/WikiManagerREST.java#L35) module
=> Remove redondancy in the API

xwiki-platform-core/xwiki-platform-lesscss/xwiki-platform-lesscss-default/src/main/java/org/xwiki/lesscss/internal/LESSConfiguration.java, xwiki-platform-core/xwiki-platform-lesscss/xwiki-platform-lesscss-default/src/main/java/org/xwiki/lesscss/internal/compiler/CachedLESSCompiler.java, xwiki-platform-core/xwiki-platform-lesscss/xwiki-platform-lesscss-default/src/main/java/org/xwiki/lesscss/internal/compiler/DefaultLESSCompiler.java, xwiki-platform-core/xwiki-platform-lesscss/xwiki-platform-lesscss-default/src/main/java/org/xwiki/lesscss/internal/compiler/less4j/Less4jCompiler.java, xwiki-platform-core/xwiki-platform-lesscss/xwiki-platform-lesscss-default/src/test/java/org/xwiki/lesscss/internal/LESSConfigurationTest.java, xwiki-platform-core/xwiki-platform-lesscss/xwiki-platform-lesscss-default/src/test/java/org/xwiki/lesscss/internal/compiler/CachedLESSCompilerTest.java, xwiki-platform-core/xwiki-platform-lesscss/xwiki-platform-lesscss-default/src/test/java/org/xwiki/lesscss/internal/compiler/less4j/Less4jCompilerTest.java, xwiki-platform-tools/xwiki-platform-tool-configuration-resources/src/main/resources/xwiki.properties.vm
Let the LESS compiler output sourcemaps inline in the CSS files.
=> XWIKI-13128: LESS compiler can output sourcemaps

xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-test/xwiki-platform-administration-test-pageobjects/src/main/java/org/xwiki/administration/test/po/TemplateProviderInlinePage.java
* called waitForIt() method, due to the fact that the test failed on the firefox 35
=> [Misc] improve functional test

xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-default/src/main/java/org/xwiki/refactoring/internal/DefaultModelBridge.java
* I replaced the use of the compact serializer with the local serializer in order to get the full name of the new reference instead of 'WebHome'.
=> XWIKI-13483  After page rename, the old page redirects wrongly to Main.WebHome

xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-ui/src/main/resources/XWiki/Registration.xml
* Form.disable(window.lb.form) was performing an unusual action by redirecting to another page displaying the same form, while its own purpose was to close the pop-up window just like the "x" button is doing
=> XWIKI-12314 : Improper redirect when you cancel the request for adding a new user

xwiki-platform-core/xwiki-platform-blog/xwiki-platform-blog-ui/src/main/resources/Blog/BlogPostClass.xml, xwiki-platform-core/xwiki-platform-blog/xwiki-platform-blog-ui/src/main/resources/Blog/Categories.xml
* the `name` field of the `Blog.CategoryClass` class has no reason to be translation key since it's not rendered
* added `hql` statement in order to exclude `Blog.CategoryTemplate` from the list of displayed `Categories` in object mode.
* `Blog.Categories` should be also excluded from here since it's not displayed in inline mode nor in panels.
=> XWIKI-13560 : Translation key xe.blog.code.blogcategories displayed when editing a blog post in the object editor

xwiki-platform-core/xwiki-platform-ratings/xwiki-platform-ratings-api/src/main/java/org/xwiki/ratings/internal/AbstractRatingsManager.java, xwiki-platform-core/xwiki-platform-ratings/xwiki-platform-ratings-api/src/main/java/org/xwiki/ratings/internal/SeparatePageRatingsManager.java
* Fixed the NPE : RatingsConfiguration component was injected in both SeparatePageRatingsManager and it's superclass AbstractRatingsManager.
=> XWIKI-13274 : Subpages don't inherit properly space rating configuration

xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-macros/xwiki-platform-rendering-macro-container/src/main/java/org/xwiki/rendering/internal/macro/container/ColumnsLayoutManager.java, xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/uicomponents/container/columns.css
Sets different class to every container which represents column numbers. By default limit is 50 columns (can be increased/decreased by explicitly specifying number of max columns as ssfx parameter).
Fixed by Tieto Czech s.r.o., Lukas Raska, lukas.raska@tieto.com
=> XWIKI-10118: Allow multiple column layouts on single page

xwiki-platform-core/xwiki-platform-ratings/xwiki-platform-ratings-ui/src/main/resources/XWiki/Ratings.xml
* this commit is to fix the same issue for XWiki 8.3
* this could be applied also for XWiki 7.4.5 only if the fix for http://jira.xwiki.org/browse/XWIKI-13274 will be also applied
=> XWIKI-13727 : Ratings app is unusable on XWiki 7.4.5

xwiki-platform-core/xwiki-platform-web/src/main/webapp/templates/pdfheader.vm
Fix bug by displaying the title only once if it’s the same as the space
When a PDF is exported from a page which has the same title as its space name, this code prevents the document title and the document space (which are, in this case, the same) to be printed twice.
=> XWIKI-14260: Exporting as PDF Level 1 pages, with Header option selected, displays the title of the page 2 times

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/layout.less, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/misc.less, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/print.css
- Moved background color from .main to content containing containers
- Tested on editors, viewers, actions and print preview
Result:
=> XWIKI-14304: Visually separate document tabs from content

xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/XWiki.java
* Add XWiki#getExternalURL(DocumentReference, String, String, String,
XWikiContext)
=> XWIKI-14376: Add support to DocumentReference in XWiki#getExternalURL()

xwiki-platform-core/xwiki-platform-eventstream/xwiki-platform-eventstream-api/pom.xml, xwiki-platform-core/xwiki-platform-eventstream/xwiki-platform-eventstream-default/src/main/java/org/xwiki/eventstream/internal/UntypedRecordableEventDescriptorComponentBuilder.java, xwiki-platform-core/xwiki-platform-eventstream/xwiki-platform-eventstream-default/src/test/java/org/xwiki/eventstream/internal/UntypedRecordableEventDescriptorComponentBuilderTest.java
This pull request fixes two bugs : 
* The first one (9c515fc) was due to a missing dependency in `xwiki-platform-eventstream-api` which triggered the errors available here : http://ci.xwiki.org/job/xwiki-platform_Quality/4226/console (_Failed to lookup component [role = [interface org.xwiki.observation.EventListener] hint = [Untyped Event Listener]]_).
My guess is that the maven build has been able to succeed because the dependency added here (`xwiki-commons-observation-api`) is also a dependency of `xwiki-commons-tool-test-component`, which is present of the `pom.xml` of `xwiki-platform-eventstream-api`, but with the scope `test`.
* The second commit (b45c588) fixes a bug that provoked in-page events to not be registered at application startup time.
=> XWIKI-14348: Allow registration of custom events in wiki pages

xwiki-platform-core/xwiki-platform-activitystream/xwiki-platform-activitystream-api/src/main/java/com/xpn/xwiki/plugin/activitystream/eventstreambridge/BridgeEventStream.java, xwiki-platform-core/xwiki-platform-eventstream/xwiki-platform-eventstream-api/src/main/java/org/xwiki/eventstream/events/AbstractEventStreamEvent.java, xwiki-platform-core/xwiki-platform-eventstream/xwiki-platform-eventstream-api/src/main/java/org/xwiki/eventstream/events/EventStreamAddedEvent.java, xwiki-platform-core/xwiki-platform-eventstream/xwiki-platform-eventstream-api/src/main/java/org/xwiki/eventstream/events/EventStreamDeletedEvent.java
* Add EventStreamAddedEvent and EventStreamDeletedEvent
* Update the BridgeEventStream to trigger those events when needed
* Update BridgeEventStream in order to avoid loops between observation events and event stream events
=> XWIKI-14507: Allow actions in the event stream to be observed

xwiki-platform-core/xwiki-platform-oldcore/src/main/resources/xhtml2fo.xsl
- Replaced 'kp' with 'ko' since the 'kp' language code does not exist (according to https://www.loc.gov/standards/iso639-2/php/code_list.php) and 'ko' is the correct code for Korean language
=> XWIKI-14524: Korean PDF export broken

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/shortcuts.vm, xwiki-platform-core/xwiki-platform-oldcore/src/main/resources/ApplicationResources.properties
* Add developer shortcuts to flamingo shortcuts
=> XWIKI-11162: Allow quickly switching the type of user (simple / advanced) without moving away from the current page

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/macros.vm
When we display lists that are too big, it causes a loop to run for hours. Instead, we can use a text filter as a fallback if there are too many items (proposed solution 2).
JIRA: https://jira.xwiki.org/browse/XWIKI-12990
=> XWIKI-12990: Displaying a livetable list filter for a non-static list field is not scalable

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/delete.js
Changed the condition for operation finished in delete.js, to check the actual state of the job and not its progress
=> XWIKI-14649: Delete UI announces success immediately regardless of the actual result (for big terminal pages)

xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-rest/src/main/java/org/xwiki/search/solr/internal/rest/SOLRSearchSource.java
The search result's title field is empty because it's multi-lingual field.
This causes the title in solr search results to be null. So use the locale
field to look up the correct title field to populate the search result with.
Jira: https://jira.xwiki.org/browse/XWIKI-14763
=> XWIKI-14763: Use the document's locale to find the title

pom.xml, xwiki-platform-core/xwiki-platform-annotations/xwiki-platform-annotation-ui/src/main/resources/AnnotationCode/Script.xml, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/pom.xml, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/docextra.vm, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/menus_content.vm, xwiki-platform-core/xwiki-platform-oldcore/src/main/resources/ApplicationResources.properties, xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/js/xwiki/actionbuttons/actionButtons.js, xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/js/xwiki/xwiki.js
* Add (again) the Keypress JS library
* Fix regression that was overriding browser shortcuts
* Allow sequence shortcuts to be triggered without triggering combo shortcuts
=> XWIKI-14808: Replace OpenJS Keyboard JS with Keypress JS for handling keyboard shortcuts

xwiki-platform-tools/xwiki-platform-tool-configuration-resources/src/main/resources/xwiki.cfg.vm
XWIKI-14839 : xwiki.authentication.useip should be mentioned in xwiki.cfg
=> Add xwiki.authentication.useip property

xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/uicomponents/job/job.css
Resolves XWIKI-13640. Pushes text onto new line, removing need for any scrollbars. Tested on both extension manager and distribution wizard.
=> XWIKI-13640: Overflow issue in the UI of the Distribution Wizard

xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/java/org/xwiki/search/solr/internal/metadata/AbstractSolrMetadataExtractor.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-ui/src/main/resources/Main/SolrSearchConfig.xml, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-ui/src/main/resources/Main/SolrSearchMacros.xml
I find this works well in my XWiki instance however I think I should set the "locale" rather than hard code the language to English. Wasn't sure how to achieve this so open to comment.
Also tried to boost by tag object independently of others but couldn't get this to work. Does the database schema need updating to allow this?
=> Added Solr sloppy phrase matching capability and config

xwiki-platform-tools/xwiki-platform-tool-jetty/xwiki-platform-tool-jetty-resources/src/main/resources/start_xwiki.bat, xwiki-platform-tools/xwiki-platform-tool-jetty/xwiki-platform-tool-jetty-resources/src/main/resources/start_xwiki.sh, xwiki-platform-tools/xwiki-platform-tool-jetty/xwiki-platform-tool-jetty-resources/src/main/resources/start_xwiki_debug.bat, xwiki-platform-tools/xwiki-platform-tool-jetty/xwiki-platform-tool-jetty-resources/src/main/resources/start_xwiki_debug.sh
I suggest updating the documentation link.
The link now sends a 404 error.
XWIKI-14983 issue. obsolescence of the supplied documentation
=> XWIKI-14983 issue. obsolescence of the supplied documentation

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/headers.less
See https://jira.xwiki.org/browse/XWIKI-15283
*Before:*
*After:*
Note that the section titles (h1 and h2) now appear with the h1 height.
=> XWIKI-15283: Vertical scroll bar randomly appears

xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-profile/xwiki-platform-user-profile-ui/src/main/resources/XWiki/XWikiUserSheet.xml, xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/js/xwiki/actionbuttons/actionButtons.js, xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/js/xwiki/editors/dataeditors.js
See https://jira.xwiki.org/browse/XWIKI-15366
*Before:*
*After:*
**Other issue:**
The issue has already been solved for the following screenshot but there was other pages where it happened.
*Before:*
*After:*
=> XWIKI-15366: Make the sticky save bar have a smoother transition

xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-wikimacro/xwiki-platform-rendering-wikimacro-api/src/main/java/org/xwiki/rendering/internal/macro/wikibridge/DefaultWikiMacro.java, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-wikimacro/xwiki-platform-rendering-wikimacro-api/src/main/java/org/xwiki/rendering/macro/wikibridge/WikiMacroBindingInitializer.java, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-wikimacro/xwiki-platform-rendering-wikimacro-store/src/main/java/org/xwiki/rendering/wikimacro/internal/CoreWikiMacroBindingInitializer.java
* Move the WikiMacroBindingInitializer class out of the internal package.
* Change the related imports.
* Use the WikiMacro as parameter of the initialize method instead
of its DocumentReference.
See https://jira.xwiki.org/browse/XWIKI-15398
=> XWIKI-15398: Move WikiMacroBindingInitializer as a public interface

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/historyinline.vm, xwiki-platform-core/xwiki-platform-oldcore/src/main/resources/ApplicationResources.properties
* add the "Action" title for the column name
* simplified the condition on the title display because the administration rights imply the edit rights
=> XWIKI-11283 : Missing "Actions" column name on the History table

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/editobject.vm, xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-api/src/main/java/org/xwiki/icon/IconManager.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/internal/objects/classes/DefaultPageQueryBuilder.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/internal/objects/classes/ImplicitlyAllowedValuesPageQueryBuilder.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/resources/META-INF/components.txt, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/internal/objects/classes/DefaultPageQueryBuilderTest.java, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/internal/objects/classes/ImplicitlyAllowedValuesPageQueryBuilderTest.java, xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-model/pom.xml, xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-model/src/main/java/org/xwiki/rest/model/jaxb/MapAdapter.java, xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-model/src/test/java/org/xwiki/rest/model/jaxb/MapAdapterTest.java, xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-server/pom.xml, xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-server/src/main/java/org/xwiki/rest/internal/resources/classes/AbstractClassPropertyValuesProvider.java, xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-server/src/main/java/org/xwiki/rest/internal/resources/classes/AbstractDocumentListClassPropertyValuesProvider.java, xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-server/src/main/java/org/xwiki/rest/internal/resources/classes/AbstractUsersAndGroupsClassPropertyValuesProvider.java, xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-server/src/main/java/org/xwiki/rest/internal/resources/classes/GroupsClassPropertyValuesProvider.java, xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-server/src/main/java/org/xwiki/rest/internal/resources/classes/PageClassPropertyValuesProvider.java, xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-server/src/main/java/org/xwiki/rest/internal/resources/classes/UsersClassPropertyValuesProvider.java, xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-server/src/main/resources/META-INF/components.txt, xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-server/src/test/java/org/xwiki/rest/internal/resources/classes/AbstractListClassPropertyValuesProviderTest.java, xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-server/src/test/java/org/xwiki/rest/internal/resources/classes/GroupsClassPropertyValuesProviderTest.java, xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-server/src/test/java/org/xwiki/rest/internal/resources/classes/PageClassPropertyValuesProviderTest.java, xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-server/src/test/java/org/xwiki/rest/internal/resources/classes/UsersClassPropertyValuesProviderTest.java, xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/uicomponents/suggest/suggestPropertyValues.js, xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/uicomponents/suggest/xwiki.selectize.css, xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/uicomponents/suggest/xwiki.selectize.js, xwiki-platform-core/xwiki-platform-web/src/main/webapp/templates/displayer_page.vm
* DefaultPageQueryBuilder, ImplicitlyAllowedValuesPageQueryBuilder
* Add support to nested maps serialization in MapAdapter.
* Improve AbstractDocumentListClassPropertyValuesProvider
* Add icon and hint metadata to the property values.
* Make the getIcon method return a map with icon related information.
* Replace the document name with the parent space name when the
document is WebHome in the getLabel method.
* Create a Page class property values provider.
* Display icons in the selectize when an icon metadata is passed.
* Create a displayer for the Page class.
* Add related tests
* Increase jacoco threshold
https://jira.xwiki.org/browse/XWIKI-15434
* Search pages with the shown label name (e.g. "Sandbox Test Page 1").
* Support for the `wiki:` prefix / search through sub-wikis.
* Show …
=> XWIKI-15434: Create a displayer for the Page field that supports autocomplete

xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-test-pageobjects/src/main/java/org/xwiki/appwithinminutes/test/po/SuggestClassFieldEditPane.java, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/po/SuggestInputElement.java, xwiki-platform-distribution/xwiki-platform-distribution-flavor/xwiki-platform-distribution-flavor-test/xwiki-platform-distribution-flavor-test-ui/src/test/it/org/xwiki/test/ui/appwithinminutes/PageClassFieldTest.java, xwiki-platform-distribution/xwiki-platform-distribution-flavor/xwiki-platform-distribution-flavor-test/xwiki-platform-distribution-flavor-test-ui/src/test/it/org/xwiki/test/ui/appwithinminutes/UserClassFieldTest.java
* Add functional tests for the AWM Page class field.
* Add documentation on some public methods.
* Rename the UserClassFieldEditPane class to SuggestClassFieldEditPane as it could be generalized.
* It seems that inserting text in the selectize element, before having the initial values added to the suggestions, doesn't update the suggestion list but keeps the initial list.
*Workaround*: `pagePicker.click().waitForSuggestions();` this makes sure the initial values have been loaded.
* The `SuggestInputElement#click` method didn't worked as expected on multiselect inputs having selected suggestions as a click was made on one of those selected suggestions.
*Workaround*: perform the click on the text input. Had to also click on the suggest input before to make sure it also works for single …
=> XWIKI-8587: Add a Document field type that has a picker associated which suggests document names

xwiki-platform-core/xwiki-platform-sharepage/xwiki-platform-sharepage-ui/src/main/resources/XWiki/SharePage.xml
https://jira.xwiki.org/browse/XWIKI-15467
* Remove the loading icon of the share page modal after status init.
=> XWIKI-15467: Loading icon remains stuck when you Share a page by email using an email address

xwiki-platform-core/xwiki-platform-messagestream/xwiki-platform-messagestream-ui/src/main/resources/Main/MessageSenderMacro.xml
https://jira.xwiki.org/browse/XWIKI-15462
* Set the user and group pickers of the Message Sender Macro back to single-select inputs.
=> XWIKI-15462: Messages sent to multiple users are received only by the first added user

xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/js/xwiki/table/livetable.js
https://jira.xwiki.org/browse/XWIKI-15474
* Cache livetable row elements.
*Before:*
*After:*
=> XWIKI-15474: Toggles aren't saved in the UI when changing the page of the Filters

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/editclass.vm, xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/js/xwiki/editors/dataeditors.css
https://jira.xwiki.org/browse/XWIKI-15454
* Use the xform and skin css rules for the editor inputs.
*Before:*
*After:*
=> XWIKI-15454: Wrong suggest input size in object edition

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/commentsinline.vm, xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/uicomponents/viewers/comments.js
XWIKI-15494:The number of comments is not updated in More actions menu
* added back the functionalities that shouldn't been deleted
* fixed the update of comments in More actions menu
* moved modals in commentscontent tab
=> XWIKI-15422:Make comments modals consistent

xwiki-platform-core/xwiki-platform-xclass/xwiki-platform-xclass-ui/src/main/resources/XWiki/ClassSheet.xml
https://jira.xwiki.org/browse/XWIKI-15492
* Avoid escaping html entities twice.
=> XWIKI-15492: XWiki.ClassSheet generates sheets which double escape the special characters in the document titles upon usage of the sheet

xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-ui/src/main/resources/XWiki/SearchSuggestSourceClass.xml
https://jira.xwiki.org/browse/XWIKI-15452
* Use a Page field on the Service property of the Search Suggest class.
This change was taken from #803.
The page picker used is the default one and does not include hidden pages (even though the user enabled it, since https://github.com/xwiki/xwiki-platform/commit/be171e02c8d60025a652307f116bdbb0c65d77c3#diff-6f2ffb743b760b87c60b2a806239c4ffR72).
There is also no sql filters regarding the suggested page list (which means all pages of the wiki are suggested).
=> XWIKI-15452: Use auto-suggestion on xproperties that can support it

xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-rest/src/main/java/org/xwiki/search/solr/internal/rest/SOLRSearchSource.java
https://jira.xwiki.org/browse/XWIKI-15536
* Add missing path element (wiki) when creating the URI of a translated page in the rest Solr Search.
=> XWIKI-15536: Error while performing certain requests on the Search resources REST API

xwiki-platform-tools/xwiki-platform-tool-jetty/xwiki-platform-tool-jetty-resources/src/main/resources/stop_xwiki.sh
https://jira.xwiki.org/browse/XWIKI-15493
* Add an optional argument to the stop_xwiki.sh script to define the number of second to wait for the XWiki lock before exiting.
* Set the default wait time to 30sec.
=> XWIKI-15493: stop_xwiki.sh does not wait long enough for clean exit

xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-ui/src/main/resources/XWiki/Notifications/Code/NotificationsFiltersPreferencesMacro.xml, xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/js/xwiki/table/livetable.js
https://jira.xwiki.org/browse/XWIKI-15544
* Revert 0f26476 which adds cache to the rendered rows of the livetable.
* Make the notifications filters livetable update the fetchedRows when
clicking a switch.
=> XWIKI-15544: Improper behavior when permanently deleting pages

xwiki-platform-core/xwiki-platform-url/xwiki-platform-url-api/pom.xml, xwiki-platform-core/xwiki-platform-url/xwiki-platform-url-api/src/main/java/org/xwiki/url/ExtendedURL.java, xwiki-platform-core/xwiki-platform-url/xwiki-platform-url-api/src/test/java/org/xwiki/url/ExtendedURLTest.java
* Make `extractParameters` protected to be tested
* Add a new test for extractParameters
* Add new assertion for equality test
* Fix thresholds
* Refactor to JUnit5
=> misc: Fix pseudo-tested method in xwiki-platform-url-api

xwiki-platform-core/xwiki-platform-resource/xwiki-platform-resource-default/pom.xml, xwiki-platform-core/xwiki-platform-resource/xwiki-platform-resource-default/src/main/java/org/xwiki/resource/internal/entity/DefaultEntityResourceActionLister.java, xwiki-platform-core/xwiki-platform-resource/xwiki-platform-resource-default/src/test/java/org/xwiki/resource/internal/MainResourceReferenceHandlerManagerTest.java, xwiki-platform-core/xwiki-platform-resource/xwiki-platform-resource-default/src/test/java/org/xwiki/resource/internal/entity/DefaultEntityResourceActionListerTest.java
* Refactor one test to use JUnit 5
* Add a more exhaustive test on MainResourceReferenceHandlerManager
* Extract a method and add a test for DefaultEntityResourceActionLister
=> misc: Fix pseudo-tested method in xwiki-platform-resource-default

xwiki-platform-distribution/xwiki-platform-distribution-debian/pom.xml
* Add missing dependency to xwiki-platform-distribution-debian
=> Fix build failure on Debian distribution

xwiki-platform-core/xwiki-platform-menu/xwiki-platform-menu-ui/src/main/resources/Menu/WebHome.xml
Bring back the changes from: https://github.com/xwiki/xwiki-platform/commit/17b8b60c1b6d9b3a6cf8385165b76fd88b261040#diff-ae8a5758f70d31be40578af6c17189b5
=> XWIKI-15604: All Menu entries have Page name "WebHome" in the LiveTable

xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-docker/src/main/java/org/xwiki/test/docker/junit5/XWikiDockerExtension.java
@vmassol so VNC is now working with this change on my machine. Now we can also wait a new release of testcontainer.
=> [Misc] Specify the VNC container to use in order to avoid segfault

xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-ui/src/main/resources/XWiki/AdminThemesSheet.xml
https://jira.xwiki.org/browse/XWIKI-15671
* Fix Javascript issue in AdminThemesSheet to avoid JS race condition
=> XWIKI-15671: Navigation tree not showing after theme change

xwiki-platform-core/xwiki-platform-annotations/xwiki-platform-annotation-io/src/main/java/org/xwiki/annotation/internal/AnnotationClassDocumentInitializer.java
https://jira.xwiki.org/browse/XWIKI-15715
* Use a User field on the Author property of the AnnotationClass class.
=> XWIKI-15715: XWiki.XWikiComments document is saved twice at during each startup

xwiki-platform-core/pom.xml, xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-api/src/main/java/org/xwiki/rest/resources/classes/ClassPropertyValuesProvider.java, xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-api/src/main/java/org/xwiki/rest/resources/classes/ClassPropertyValuesResource.java, xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-server/src/main/java/org/xwiki/rest/internal/resources/classes/AbstractClassPropertyValuesProvider.java, xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-server/src/main/java/org/xwiki/rest/internal/resources/classes/AbstractDocumentListClassPropertyValuesProvider.java, xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-server/src/main/java/org/xwiki/rest/internal/resources/classes/ClassPropertyValuesResourceImpl.java, xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-server/src/main/java/org/xwiki/rest/internal/resources/classes/DefaultClassPropertyValuesProvider.java, xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-server/src/test/java/org/xwiki/rest/internal/resources/classes/ClassPropertyValuesResourceImplTest.java, xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/uicomponents/suggest/suggestPropertyValues.js, xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/uicomponents/suggest/suggestUsersAndGroups.js, xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/uicomponents/suggest/xwiki.selectize.js, xwiki-platform-core/xwiki-platform-web/src/main/webapp/templates/uorgsuggest.vm
https://jira.xwiki.org/browse/XWIKI-15605
* Add an optional parameter to the ClassPropertyValuesResource API to get the exact match value.
* Add a getValue method to the ClassPropertyValuesProvider to get the exact match value.
* Use the exact match parameter when fetching selected items in the property suggest picker.
* Use the exact match query for selected values in users or groups suggest picker.
=> XWIKI-15605: Auto-suggest control doesn't display correctly hidden pages

xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-ui/src/main/resources/XWiki/QuickSearchUIX.xml
https://jira.xwiki.org/browse/XWIKI-15718
* Add missing label to an input for accessibility purpose.
=> XWIKI-15718 #headerglobalsearchinput is missing the label

xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-ui/src/main/resources/XWiki/AdminGroupsSheet.xml, xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-ui/src/main/resources/XWiki/AdminUsersSheet.xml, xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-ui/src/main/resources/XWiki/TemplateProviderMacros.xml, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/attachment_macros.vm, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/commentsinline.vm, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/export_modal.vm, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/modals.less, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/style.less.vm, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/macros.vm, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-ui/src/main/resources/XWiki/Notifications/Code/NotificationsFiltersPreferencesMacro.xml, xwiki-platform-core/xwiki-platform-panels/xwiki-platform-panels-ui/src/main/resources/PanelsCode/NavigationConfigurationSheet.xml, xwiki-platform-core/xwiki-platform-sharepage/xwiki-platform-sharepage-ui/src/main/resources/XWiki/SharePage.xml, xwiki-platform-core/xwiki-platform-web/src/main/webapp/templates/job/question/OverwriteQuestion.vm, xwiki-platform-core/xwiki-platform-web/src/main/webapp/templates/locationPicker_macros.vm, xwiki-platform-tools/xwiki-platform-tool-standards-validator/src/test/resources/xwiki-invalid.html, xwiki-platform-tools/xwiki-platform-tool-standards-validator/src/test/resources/xwiki-valid.html
- Adding styling for .modal-title for the font-size property
- Replace headings usage for .modal-title and .panel-title in order to comply with WCAG rules
=> XWIKI-15726: Headings hierarchy is broken when using Bootstrap .modal-title and .panel-title

xwiki-platform-core/xwiki-platform-query/xwiki-platform-query-manager/src/main/java/org/xwiki/query/internal/EscapeLikeParametersQuery.java, xwiki-platform-core/xwiki-platform-query/xwiki-platform-query-manager/src/test/java/org/xwiki/query/internal/EscapeLikeParametersFilterTest.java
https://jira.xwiki.org/browse/XWIKI-15724
The expression should always be visited in `EscapeLikeParametersQuery` in order to be converted later.
Unit tests added in EscapeLikeParametersFilterTest
=> XWIKI-15724: ClassCastException when specifying the escape character and using like

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/export_modal.vm, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-pageobjects/src/main/java/org/xwiki/flamingo/sking/test/po/ExportModal.java, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-pageobjects/src/main/java/org/xwiki/flamingo/sking/test/po/OtherFormatPane.java, xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/uicomponents/exporter/exporter.js
https://jira.xwiki.org/browse/XWIKI-15444
* Form is now created on the fly to avoid nested form
All dedicated tests running.
=> XWIKI-15444: Export UI does not export child pages if there are many (and tree has pagination)

xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/export/html/HtmlPackager.java
https://jira.xwiki.org/browse/XWIKI-14334
* Stub the request response when rendering page for html, to avoid the
response to be closed.
=> XWIKI-14334: Sometimes HTML exporting fails and redirects to xwiki/pages/xwiki/Main/Search.html

xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-ui/src/main/resources/XWiki/ForgotUsername.xml, xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-ui/src/main/resources/XWiki/ResetPassword.xml
[XWIKI-15682: Global users can't recover their password from a subwiki](https://jira.xwiki.org/browse/XWIKI-15682)
[XWIKI-15681: Global users can't recover their login from a subwiki](https://jira.xwiki.org/browse/XWIKI-15681)
- pull request for both issues since they are related and should behave similarly
- fix aims to mimic the behaviour of the login action (first local user then global, if local does not exist)
=> Recover username and pasword for global users from subwikis

xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/uicomponents/flavor/picker.css, xwiki-platform-core/xwiki-platform-web/src/main/webapp/templates/flavor/macros.vm
https://jira.xwiki.org/browse/XWIKI-15693
* Remove inline style from macros.vm and put it in picker.css
=> XWIKI-15693: Remove inline styling from WikiManager.CreateWiki

xwiki-platform-distribution/xwiki-platform-distribution-flavor/xwiki-platform-distribution-flavor-test/xwiki-platform-distribution-flavor-test-webstandards/src/test/it/org/xwiki/test/webstandards/CustomDutchWebGuidelinesValidator.java
https://jira.xwiki.org/browse/XWIKI-15691
* Add XWiki.XWikiSyntaxGroups in the list of exceptions
=> XWIKI-15691: Inline styling is not allowed in XWiki.XWikiSyntaxGroups

xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/web/ExportAction.java
https://jira.xwiki.org/browse/XWIKI-15794
* Fix the name of the xar package when no name is given.
=> XWIKI-15794: The default exported wiki XAR package name is 'XWiki.XWikiPreferences' instead of 'backup'

xwiki-platform-core/xwiki-platform-oldcore/src/main/resources/xhtml2fo.xsl, xwiki-platform-core/xwiki-platform-web/src/main/webapp/templates/pdfcover.vm, xwiki-platform-core/xwiki-platform-web/src/main/webapp/templates/pdffooter.vm, xwiki-platform-core/xwiki-platform-web/src/main/webapp/templates/pdfheader.vm
* Changed default font to sans fonts
* Added thin lines between doc header, doc footer and page content text
* Fixed the document pdfheader to display document titles instead of document space name
* Polished the document cover to display title and document metadata to the left and repeat the thin separator lines to preserve the same look and feel as the pages
=> XWIKI-15761: Improve look and feel of default pdf export

xwiki-platform-core/xwiki-platform-wiki/xwiki-platform-wiki-ui/xwiki-platform-wiki-ui-mainwiki/src/main/resources/WikiManager/UserWikiSheet.xml
* Use the documentUser instead of the currentUser
=> XWIKI-15885: When visiting a user profile page with a different user, the list of joined wikis is wrong

xwiki-platform-core/xwiki-platform-oldcore/src/main/resources/ApplicationResources.properties, xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/uicomponents/viewers/tags.js
* Add missing translation keys and use them in tags.js
=> XWIKI-15843: Missing use of translation key in tags.js

xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/po/HistoryPane.java, xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/uicomponents/viewers/history.js, xwiki-platform-distribution/xwiki-platform-distribution-flavor/xwiki-platform-distribution-flavor-test/xwiki-platform-distribution-flavor-test-ui/src/test/it/org/xwiki/test/ui/CompareVersionsTest.java
https://jira.xwiki.org/browse/XWIKI-15883
* Add a missing "s" to identify properly the input
Add new integration-test to identify properly the behaviour of delete range version
=>  XWIKI-15883: Selected page versions range cannot be deleted anymore from History tab

xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/main/java/org/xwiki/refactoring/internal/job/AbstractEntityJobWithChecks.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/main/java/org/xwiki/refactoring/internal/job/MoveJob.java
https://jira.xwiki.org/browse/XWIKI-15870
* Allow a job to skip the check for page deletion
=> XWIKI-15870: Warning message when copying a page

xwiki-platform-core/xwiki-platform-index/xwiki-platform-index-ui/src/main/resources/Index/Translations.xml, xwiki-platform-core/xwiki-platform-index/xwiki-platform-index-ui/src/main/resources/XWiki/DeletedDocuments.xml
https://jira.xwiki.org/browse/XWIKI-15880
* Add the button inside the livetable
* Wait for user confirmation
* Refresh the livetable once it's done
* I only supported the button for the livetable, not for the "noscript" part of the view
* For now the confirmation message displayed is the same as for single document deletion
=> XWIKI-15880: Create a button to delete all from the recycle bin

xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-ui/src/main/resources/XWiki/ResetPassword.xml, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/objects/classes/PasswordClass.java
https://jira.xwiki.org/browse/XWIKI-15899
* Generate the password recovery URL by serializing the user document.
* Avoid NPE.
=> XWIKI-15899: Global users cannot recover their password from a subwiki due to macro errors

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/historyinline.vm, xwiki-platform-core/xwiki-platform-oldcore/src/main/resources/ApplicationResources.properties
https://jira.xwiki.org/browse/XWIKI-15713
* Change the warning message of an empty history of a page.
I'm making a PR because I haven't tested the change and maybe the new key should have another name.
=> XWIKI-15713: History tab indicate that the page does not exist when the history is empty

xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-docker/src/main/java/org/xwiki/test/docker/junit5/AbstractContainerExecutor.java, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-docker/src/main/java/org/xwiki/test/docker/junit5/TestConfiguration.java, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-docker/src/main/java/org/xwiki/test/docker/junit5/XWikiDockerExtension.java, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-docker/src/main/java/org/xwiki/test/docker/junit5/browser/Browser.java, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-docker/src/main/java/org/xwiki/test/docker/junit5/browser/BrowserContainerExecutor.java, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-docker/src/main/java/org/xwiki/test/docker/junit5/servletEngine/ServletContainerExecutor.java, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-docker/src/main/java/org/xwiki/test/docker/junit5/servletEngine/ServletEngine.java
* Fix places of the test resources: they should be mounted in browser
container, not in servlet container
=> XWIKI-15944: Add ability to pass test resources to Docker-based tests

xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-docker/src/main/java/org/xwiki/test/docker/junit5/TestConfiguration.java
https://jira.xwiki.org/browse/XWIKI-15971
* Factorize the code to get values from annotation or properties
* Define a new strategy for the value overriding.
This one has been tested by fixing some parameter values in the annotation of MenuTest and by using some parameters in command line to override those values. The new strategy is well applied.
=> XWIKI-15971: docker test: allow to select another default servletEngine (or browser) value

xwiki-platform-core/xwiki-platform-panels/xwiki-platform-panels-ui/src/main/resources/Panels/MyRecentModifications.xml
https://jira.xwiki.org/browse/XWIKI-15961
* Specify the document language when duplicates are shown.
Maybe a better solution would be to always show the document title using the user language (as it was already the case) and keep the language hint when duplicates are shown.
=> XWIKI-15961: A page appears more then once in the "My Recent Modifications" when it has more then one translation

xwiki-platform-core/xwiki-platform-web/src/main/webapp/templates/rightpanels.vm
https://jira.xwiki.org/browse/XWIKI-15979
When checking the rights of the menu in the subwiki we are currently checking them against `Menu.Menu1.WebHome`: the reference to the wiki is lost.
I proposed to fix it by getting the proper reference to the page (like we already do in https://github.com/xwiki/xwiki-platform/blob/master/xwiki-platform-core/xwiki-platform-panels/xwiki-platform-panels-api/src/main/java/org/xwiki/panels/internal/AbstractPanelsUIExtensionManager.java#L124-L129) and check the rights against it.
Tested locally against the scenario of the issue. I get the menu displayed with Admin and hidden with the local user of the subwiki. With a guest user I get it displayed too: I don't know if it's expected.
=> XWIKI-15979: Global Menu is displayed (with error) in subwiki for a local user

xwiki-platform-distribution/xwiki-platform-distribution-flavor/xwiki-platform-distribution-flavor-test/xwiki-platform-distribution-flavor-test-webstandards/pom.xml, xwiki-platform-distribution/xwiki-platform-distribution-flavor/xwiki-platform-distribution-flavor-test/xwiki-platform-distribution-flavor-test-webstandards/src/test/it/org/xwiki/test/webstandards/CustomDutchWebGuidelinesValidationTest.java, xwiki-platform-distribution/xwiki-platform-distribution-flavor/xwiki-platform-distribution-flavor-test/xwiki-platform-distribution-flavor-test-webstandards/src/test/it/org/xwiki/test/webstandards/framework/AbstractValidationTest.java
https://jira.xwiki.org/browse/XWIKI-15666
As discussed in https://markmail.org/message/okihfnpkavhnbkib the proposed solution for now is to skip technical pages from WCAG validator.
This has been done by checking a boolean `skipTechnicalPages` in the validator classes: if set to true, then the pages are parsed to get the value of the `hidden` attribute.
=> XWIKI-15666: Validation check broken for 2 consecutive line breaks on translation pages

xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/web/EditAction.java
https://jira.xwiki.org/browse/XWIKI-15199
* Add a supplementary condition when previewing a deleted section.
tested locally.
=> XWIKI-15199: Uncaught exception when previewing deleted section

xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/store/hibernate/query/HqlQueryExecutor.java
* query#getPositionalParameters might involve some transformation (see
EscapeLikeParametersQuery), so it might be good to avoid calling it too
many times in #populateParameters
=> [Misc] Refactor HqlQueryExecutor to improve perf a little bit

xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/uicomponents/suggest/suggestPages.js
https://jira.xwiki.org/browse/XWIKI-16022
* Add a way to limit the page picker search under a certain space.
```
{{velocity}}
{{html}}
#set ($param = {'data-suggest-space': 'XWiki'})
#pagePicker($param)
{{/html}}
{{/velocity}}
```
=> XWIKI-16022: Limit the generic page picker search to a space

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/editobject.vm, xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/js/xwiki/editors/dataeditors.js, xwiki-platform-distribution/xwiki-platform-distribution-flavor/xwiki-platform-distribution-flavor-test/xwiki-platform-distribution-flavor-test-escaping/src/test/it/org/xwiki/test/escaping/ObjectAndClassEditorTest.java
https://jira.xwiki.org/browse/XWIKI-16044
* Use 'classname' instead of 'className' as this is the one use everywhere else.
=> XWIKI-16044: className vs classname inconsistency in "objectremove" and "objectadd" actions

xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/main/resources/ApplicationResources.properties, xwiki-platform-core/xwiki-platform-web/src/main/webapp/templates/job_macros.vm
https://jira.xwiki.org/browse/XWIKI-15641
* Add a simple info box when a job is waiting to start
=> XWIKI-15641: Display information to user when a job is waiting another to finish/timeout

xwiki-platform-core/xwiki-platform-extension/xwiki-platform-extension-script/src/test/java/org/xwiki/extension/script/ExtensionManagerScriptServiceTest.java, xwiki-platform-core/xwiki-platform-localization/xwiki-platform-localization-sources/xwiki-platform-localization-source-wiki/src/test/java/org/xwiki/localization/wiki/internal/DocumentTranslationBundleFactoryTest.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-bridge/src/test/java/org/xwiki/security/authorization/AbstractWikiTestCase.java
* Unregister new listener components in some module tests to avoid
missing dependencies.
=> XWIKI-6732: Introduce DocumentRenamingEvent and DocumentRenamedEvent events

xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/test/MockitoOldcore.java
* Make sure that testss using MockitoOldCore loads a URLConfiguration
component
=> XWIKI-6073: Browsers usually cache JS/CSS resources even if they have changed

xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/XWiki.java, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/XWikiTest.java, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/test/AbstractBridgedXWikiComponentTestCase.java
https://jira.xwiki.org/browse/XWIKI-15991
* Take into account the xwiki.language.forceSupported xwiki parameter.
* Move the logic of XWiki#getLanguagePreference to XWiki#getLocalePreference.
To actually see the benefits of the improvement, the `xwiki.language.forceSupported` parameter should be set to `1`.
=> XWIKI-15991: Wrong locale used in multilingual wiki

xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/store/XWikiHibernateStore.java, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/store/AbstractXWikiHibernateStoreTest.java, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/store/XWikiHibernateStoreTest.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-default/src/main/java/org/xwiki/refactoring/internal/DefaultLinkRefactoring.java
https://jira.xwiki.org/browse/XWIKI-8346
* Check two schemes when executing load backlinks request: with and
without the wiki id.
This fix itself is not enough for fixing completely XWIKI-8346: the `updateLinksOnFarm` needs to be set to true in the move/rename request too. Which is by default not the case.
=> XWIKI-8346: Broken cross-wiki links on page rename

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/htmlheader.vm, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/doc/XWikiDocument.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/web/SaveAction.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/web/SaveAndContinueAction.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/web/XWikiAction.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/resources/ApplicationResources.properties, xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/js/xwiki/actionbuttons/actionButtons.js, xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/js/xwiki/editors/dataeditors.js, xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/js/xwiki/meta.js
https://jira.xwiki.org/browse/XWIKI-6665
The proposed solution is to record in a field of the editor the last version of the working document and to send it to the server when saving.
The server will compare this version number against the latest version of the document: if the latest version is different than the one sent on the request it means someone certainly save the document in the meantime. We also compare the edition dates: in some edge cases we could have the same revision numbers that are not the same revisions (e.g. a deleted and recreated document).
We then compute a content and an object diff to remove the false positive: the doc could have been saved in the meantime because of an attachment added.
Finally in case of conflict we send a 409 status with a JSON containing both …
=>  XWIKI-6665: Saving edits after lock expiration doesn't warn the user that the page may be stale

xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-ui/src/main/resources/AppWithinMinutes/LiveTableViewSheet.xml
https://jira.xwiki.org/browse/XWIKI-16220
* Check if the AWM page is part of an extension: if it's the case, do not hijack the rename button.
=> XWIKI-16220: AWM applications located in extensions are not protected against move/rename anymore

xwiki-platform-distribution/xwiki-platform-distribution-debian/xwiki-platform-distribution-debian-tomcat/xwiki-platform-distribution-debian-tomcat8-common/src/deb/resources/etc/xwiki/xwiki-tomcat8.xml
As discussed in XWIKI-16236 , I am creating this PR to resolve the issues raised. See also XWIKI-15756 and XWIKI-16235 . See https://jira.xwiki.org/browse/XWIKI-16236 for details.
=> Fix XWIKI-16236 by enabling & increasing tomcat8 cache; use correct syntax for JarScanner, JarScanFilter.

xwiki-platform-distribution/xwiki-platform-distribution-debian/xwiki-platform-distribution-debian-tomcat/xwiki-platform-distribution-debian-tomcat8-common/src/deb/resources/etc/xwiki/xwiki-tomcat8.xml
The changes to this file are detailed in https://jira.xwiki.org/browse/XWIKI-16257
Summary: Update to XWIKI-16236 to adjust cache size & disable unneeded
tomcat8 features. Update documentation, etc to be consistent with
https://github.com/xwiki/xwiki-platform/blob/master/xwiki-platform-core/xwiki-platform-web/src/main/webapp/META-INF/context.xml
per Vincent Massol's comments on PR associated with XWIKI-16236:
https://github.com/xwiki/xwiki-platform/pull/1083
=> XWIKI-16257: adjust cache size & disable unneeded tomcat8 features for debian xwiki-tomcat8-* packages

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/editinline.vm, xwiki-platform-core/xwiki-platform-panels/xwiki-platform-panels-ui/src/main/resources/Panels/PanelSheet.xml
This standardizes the Panels inline editing to follow the xform styling convention.
**Panel Editing Page Before Class Addition**:
**Panel Editing Page After Class Addition**:
=> XWIKI-15916: Use .xform style standard in Panels

xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-ui/src/main/resources/XWiki/AdminSheet.xml, xwiki-platform-core/xwiki-platform-menu/xwiki-platform-menu-ui/src/main/resources/Menu/MenuConfigurationSection.xml, xwiki-platform-core/xwiki-platform-menu/xwiki-platform-menu-ui/src/main/resources/Menu/MenuTranslations.xml
https://jira.xwiki.org/browse/XWIKI-15630
This improves the order of items in the "Look & Feel" category of Administration.
The P1 proposal for the order is implemented. This orders the items by their usage type.
If something is not right, please let me know. :)
=> XWIKI-15630: Improve the items order in the Administration's "Look&Feel"

xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/XWiki.java, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/po/editor/EditPage.java, xwiki-platform-distribution/xwiki-platform-distribution-flavor/xwiki-platform-distribution-flavor-test/xwiki-platform-distribution-flavor-test-ui/src/test/it/org/xwiki/test/ui/LanguageTest.java
https://jira.xwiki.org/browse/XWIKI-14165
* Add a check in XWiki#preparedDocument to use doc instead of tdoc if
an empty language parameter is used.
* Refactor LanguageTest#translateDocument to check with one original
document and 2 translations.
=> XWIKI-14165: Unable to edit the original document if it has default language blank and en (configured default translation) translation exists

xwiki-platform-core/xwiki-platform-panels/xwiki-platform-panels-ui/src/main/resources/Panels/PanelSheet.xml, xwiki-platform-distribution/xwiki-platform-distribution-flavor/xwiki-platform-distribution-flavor-test/xwiki-platform-distribution-flavor-test-ui/src/test/it/org/xwiki/test/ui/LanguageTest.java
https://jira.xwiki.org/browse/XWIKI-14166
* Add a new test to show the problem
* Edit PanelSheet to use tdoc instead of doc: the object are shared
but only the  translation is invalidated in the cache when the
translation is edited, so we need to retrieve their values from the
translation to avoid display inconsistencies.
The root problem of XWIKI-14166 is that objects are shared among documents and their translations, and our cache mechanism does not handle the changes on the objects properly. 
IMO we should invalidate the document and all their translations if the original document or one of its translations has a change on one of its objects. Else we could have inconsistencies such as the one described in XWIKI-14166.
So right now my fix only handle changes made on panels, but any …
=> XWIKI-14166: Inline edit not saving documents with default language blank and existing translation in the configured default language

xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/web/XWikiServletURLFactory.java
https://jira.xwiki.org/browse/XWIKI-15450
Fallback on `createAttachmentRevisionURL` when creating an attachment URL for download. This is an easy solution which use the already existing mechanism to add the revision number at the end of the URL. It should both prevents the cache mechanism in case of a new version has been updated, and use the cache mechanism when downloading several times the same attachment.
I only ran oldcore unit tests for it, but perform manual validation by running an instance and downloading/uploading attachments.
@Enygma2002 suggested that we could also use the browser cache mechanism with the right header, but I find it more complicated, especially since apparently the example shown by @mflorea on it use a ResourceHandler that we currently only have for webjars. …
=> XWIKI-15450: Browser cache for attachments is never invalidated (needs browser clear cache)

xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-ui/src/main/resources/IconThemesCode/IconPicker.xml
https://jira.xwiki.org/projects/XWIKI/issues/XWIKI-16295
Hi,
This issue does exist in edge. I have confirmed it.
After analyzing, what I noticed was that the `.xwikiIconPickerContainer div` was outside the `body` tag and directly inside the `html` tag. I do not know if this was intended but it was causing Microsoft Edge to behave inaccurately.
So, what I essentially did was put the `.xwikiIconPickerContainer div` inside the `body` tag rather than outside which fixed the issue.
**HTML Before:**
**HTML After:**
=> XWIKI-16295: All page is selected when selecting an Icon for a AWM

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-docker/src/test/it/org/xwiki/flamingo/test/ui/EditIT.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/XWiki.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/XWikiException.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/api/Document.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/doc/XWikiDocument.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/store/XWikiCacheStore.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/store/XWikiHibernateStore.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/store/XWikiStoreInterface.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/web/CreateAction.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/web/CreateActionRequestHandler.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/resources/ApplicationResources.properties, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/XWikiMockitoTest.java, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/XWikiTest.java, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/api/XWikiTest.java, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/plugin/packaging/ImportTest.java, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/web/CreateActionTest.java, xwiki-platform-core/xwiki-platform-web/src/main/webapp/templates/createinline.vm
https://jira.xwiki.org/browse/XWIKI-16314
* Add new store methods to check the limit size of a property
* Add new cache store methods to cache the property limits. 
* Add new checks in CreateAction and in save to check the length of a
page path
* Edit createinline.vm to handle new exception in case of path too
long
* Add new unit test to check new behaviours
* Add new integration test to ensure UI changes
Tested with the 4 database supported in docker test:
* mysql
* postgresql
* HSQLDB
* Oracle DB
HSQLDB showed that we might have exceptions to retrieve the limit based on the DB type, so I don't really know if this code would work on Oracle DB or other DB that are not supported in Docker tests.
=> XWIKI-16314: Force users to respect the DB limit when creating a page

xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-wikimacro/xwiki-platform-rendering-wikimacro-macros/pom.xml, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-wikimacro/xwiki-platform-rendering-wikimacro-macros/xwiki-platform-rendering-wikimacro-macro-wikimacrocontent/pom.xml, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-wikimacro/xwiki-platform-rendering-wikimacro-macros/xwiki-platform-rendering-wikimacro-macro-wikimacrocontent/src/main/java/org/xwiki/rendering/wikimacro/macro/wikimacrocontent/WikiMacroContentMacro.java, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-wikimacro/xwiki-platform-rendering-wikimacro-macros/xwiki-platform-rendering-wikimacro-macro-wikimacrocontent/src/main/resources/META-INF/components.txt, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-wikimacro/xwiki-platform-rendering-wikimacro-macros/xwiki-platform-rendering-wikimacro-macro-wikimacrocontent/src/test/java/org/xwiki/rendering/wikimacro/macro/wikimacrocontent/WikiMacroContentMacroTest.java, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-wikimacro/xwiki-platform-rendering-wikimacro-store/pom.xml, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-wikimacro/xwiki-platform-rendering-wikimacro-store/src/main/java/org/xwiki/rendering/wikimacro/internal/DefaultWikiMacroRenderer.java, xwiki-platform-core/xwiki-platform-wysiwyg/xwiki-platform-wysiwyg-api/src/main/java/org/xwiki/wysiwyg/internal/converter/DefaultHTMLConverter.java, xwiki-platform-distribution/xwiki-platform-distribution-war-dependencies/pom.xml
https://jira.xwiki.org/browse/XWIKI-16389
* Create a dedicated macro for wikimacro content that insert the content of a wikimacro and put a dedicated metadata around it for inline editing
* Process in DefaultWikiMacroRenderer the rendered wikimacro to remove the macro markers that could prevent from inline editing.
Unit tests has been added to the new module and some manual tests have been performed.
I mostly use this macro for testing manually my changes:
```
{{velocity}}
{{box}}
{{wikimacrocontent/}}
{{/box}}
This content is $xcontext.macro.content.length() characters length.
{{/velocity}}
```
I needed the fix provided for https://jira.xwiki.org/browse/XRENDERING-562 (see https://github.com/xwiki/xwiki-rendering/pull/174) to avoid some issues with the two consecutive metadatablocks …
=> XWIKI-16389: Dedicated macro for inline editing of wikimacro content

xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/pdf/impl/PdfExportImpl.java
When dom4j's SAXReader.read(InputSource) is called (as PdfExportImpl.java does), in the end SAXHelper.createXMLReader(boolean) is called, which in dom4j 2.1.1 sets the "http://apache.org/xml/features/nonvalidating/load-external-dtd" feature to false.
This PR sets the feature to true as a workaround. Perhaps this is going to be fixed upstream, in which case this PR could be reverted.
=> XCOMMONS-1503: workaround to use dom4j 2.1.1

xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-ui/src/main/resources/AppWithinMinutes/ClassEditSheet.xml, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/objects/classes/BaseClass.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/objects/classes/ListClass.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/objects/meta/ListMetaClass.java, xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-model/pom.xml, xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-model/src/main/java/org/xwiki/rest/model/jaxb/PropertyValue.java, xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-model/src/test/java/org/xwiki/rest/model/jaxb/PropertyValueTest.java, xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-server/src/main/java/org/xwiki/rest/internal/resources/classes/StaticListClassPropertyValuesProvider.java, xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-server/src/main/resources/META-INF/components.txt, xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-server/src/test/java/org/xwiki/rest/internal/resources/classes/StaticListClassPropertyValuesProviderTest.java, xwiki-platform-core/xwiki-platform-web/src/main/webapp/templates/displayer_staticlist.vm
https://jira.xwiki.org/browse/XWIKI-16412
It also fixes
https://jira.xwiki.org/browse/XWIKI-16411
* Create the dedicated PropertyValuesProvider in rest-server to reuse
the mechanism already existing for picking a value
* Create the dedicated displayer_staticlist.vm for it.
=> XWIKI-16412: Allow to type a custom value in a StaticListClass

xwiki-platform-distribution/xwiki-platform-distribution-ui/xwiki-platform-distribution-ui-base/src/main/resources/XWiki/XWikiPreferences.xml
This request aims at changing the identifier of the HTML head extension point.
=> XWIKI-16457: Update the identifier of the extension point used to make the HTML head plugable

xwiki-platform-distribution/xwiki-platform-distribution-debian/xwiki-platform-distribution-debian-tomcat/xwiki-platform-distribution-debian-tomcat9-common/src/deb/control/postinst
* Update the user used when giving permissions in /var/lib/xwiki/data
=> XWIKI-16607 : The package xwiki-tomcat9-common fails to install on Debian Bullseye

xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/uicomponents/suggest/xwiki.selectize.js
* the way $control_input was accessed caused problems in velocity parsing, leading to test errors
=> XWIKI-16147: Livetable suggest input field has no title

xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/objects/classes/ComputedFieldClass.java, xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-server/src/main/java/org/xwiki/rest/internal/ModelFactory.java
- Add method ComputedFieldClass:getComputedValue() performing an evaluation of the ComputedFieldClass script.
- Introduce method ModelFactor:serializePropertyValue(PropertyInterface, PropertyClass, XWikiContext context) so that the ComputedFieldClass properties get their value evaluated when represented in REST.
(or should we create a distinct issue focusing on the introduction of ComputedFieldClass:getComputedValue?)
=> XWIKI-16663: Computed field values should be available in REST representations

xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/java/org/xwiki/search/solr/internal/AbstractSolrInstance.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/java/org/xwiki/search/solr/internal/api/SolrInstance.java
- Add method "SolrDocument get(String id)" in SolrInstance
- Add implementation of the method in AbstractSolrInstance
=> XWIKI-16719: Add ability to retrieve a SolrDocument by its identifier

xwiki-platform-core/xwiki-platform-xclass/xwiki-platform-xclass-ui/src/main/resources/XWiki/ClassSheet.xml, xwiki-platform-core/xwiki-platform-xclass/xwiki-platform-xclass-ui/src/main/resources/XWiki/XClassTranslations.xml
* provide a way to create a template provider from a class
* the template must be created first, in order to be used in the template provider
* by default, the template provider is available only in the root space of the class (for XWiki.Code.MyClass -> XWiki)
=> XWIKI-16725: Add action to create Template Provider from the Class UI

xwiki-platform-core/xwiki-platform-xclass/xwiki-platform-xclass-ui/src/main/resources/XWiki/ObjectSheet.xml
Edited ObjectSheet to follow .xform style standard when code for a new sheet is generated.
Added standard label and support for hint for each class property.
=> XWIKI-16727: Use .xform style standard for Class Sheet

xwiki-platform-core/xwiki-platform-annotation/xwiki-platform-annotation-ui/src/main/resources/AnnotationCode/Macros.xml, xwiki-platform-core/xwiki-platform-annotation/xwiki-platform-annotation-ui/src/main/resources/AnnotationCode/Style.xml
* reply class is required from js for the functionality to work
* overridden padding added by 'reply' class
=> XWIKI-16794: Reply doesn't work properly

xwiki-platform-core/xwiki-platform-extension/xwiki-platform-extension-handlers/xwiki-platform-extension-handler-xar/src/main/java/org/xwiki/extension/xar/internal/security/XarSecurityRule.java, xwiki-platform-core/xwiki-platform-extension/xwiki-platform-extension-handlers/xwiki-platform-extension-handler-xar/src/test/java/org/xwiki/extension/xar/internal/XarSecurityRuleTest.java
* Define XarSecurityRule#hashCode() and XarSecurityRule#equals(Object)
=> XWIKI-16899: Adding a user to a group provided by an extension crashes the security cache

xwiki-platform-core/xwiki-platform-oldcore/pom.xml, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/pdf/impl/PdfExportImpl.java
[Css4j 2.0.0](https://github.com/css4j/css4j-dist/releases/tag/css4j-2.0.0) is the latest available version of the library, but is not totally backwards-compatible with 1.0. This pull request makes the necessary changes, plus a small addition (commit 3e45129).
Unfortunately I was unable to verify that `xwiki-platform` builds after the change, due to this:
`[ERROR] Failed to execute goal on project xwiki-platform-rendering-macro-script: Could not resolve dependencies for project org.xwiki.platform:xwiki-platform-rendering-macro-script:jar:12.0-SNAPSHOT: Could not find artifact org.xwiki.rendering:xwiki-rendering-transformation-macro:jar:tests:12.0-20191129.175630-16 in xwiki-snapshots (http://nexus.xwiki.org/nexus/content/groups/public-snapshots) -> [Help 1]`
=> XWIKI-16905: Upgrade to CSS4J 2.0.0

xwiki-platform-core/xwiki-platform-office/xwiki-platform-office-ui/src/main/resources/XWiki/OfficeImporter.xml, xwiki-platform-core/xwiki-platform-office/xwiki-platform-office-ui/src/main/resources/XWiki/OfficeImporterResults.xml
XWIKI-16498: Remove docextra from OfficeImporter action-result pages
Link : https://jira.xwiki.org/browse/XWIKI-16498
Before: 
After: 
(Let me know my mistakes, thanks!) - Haxsen
=> XWIKI-16498: Remove docextra from OfficeImporter action-result pages

xwiki-platform-core/xwiki-platform-index/xwiki-platform-index-tree/xwiki-platform-index-tree-macro/src/main/resources/XWiki/ChildrenMacro.xml
Escape double quotes before calling documentTree.
=> XWIKI-15490: Children macro not working for a document with a double quote in its name

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/edit.vm
Fixes XWIKI-16345.
Link: https://jira.xwiki.org/browse/XWIKI-16345
Before:
After:
=> XWIKI-16345: Use .xform style standard for the edit panels

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/menus_content.vm
Issue link: https://jira.xwiki.org/browse/XWIKI-15708
Before:
After:
=> XWIKI-15708: Consistent #tmEditObject and #tmEditClass menu entries icons

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/shortcuts.vm
Issue link: https://jira.xwiki.org/browse/XWIKI-15477
Before:
After:
=> XWIKI-15477: Missing Annotations icon in the More Actions menu when Annotation tab is displayed

xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/js/xwiki/actionbuttons/actionButtons.css
**Issue link:** https://jira.xwiki.org/browse/XWIKI-16341
**Issue Description:** The input is aligned with the button ONLY on the 'editor=wiki' mode. If you switch to WYSIWYG, object, class editors, the alignment is lost. There is a 1px difference.
**Before:**
After:
**Solution:** 
Input box "Add Summary" was a little bit above the line of actions-buttons. So 1px from the top is added to keep align it with other action buttons.
=> Issue XWIKI-16341 " 'Add summary' input not aligned with 'Save' buttons "

xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/js/xwiki/editors/dataeditors.css
**Issue:**  XWIKI-16342 Unaligned buttons for class and object editors
**Issue link:**  https://jira.xwiki.org/browse/XWIKI-16342
**Before:** 
**After:**
=> XWIKI-16342 "Unaligned buttons for class and object editors"

xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-profile/xwiki-platform-user-profile-ui/src/main/resources/XWiki/XWikiUserProfileSheet.xml, xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-profile/xwiki-platform-user-profile-ui/src/main/resources/XWiki/XWikiUserSheet.xml
Issue XWIKI-7716 has been solved.
Issue-Link: https://jira.xwiki.org/browse/XWIKI-7716
Replacing h1 tags with h2 tags. As there should be only one h1 tag in the document.
Added a title to a link `<a>`  tag.
**Result:** 
**Inspect**
=> XWIKI-7716: Use .xform style standard in the User Profile

xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/js/xwiki/actionbuttons/actionButtons.js
Clear the comment content after a successful save and continue action.
=> XWIKI-17077: Pre-filled text from Summary field should be cleared automatically when the page is saved after uploading a logo

xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-ui/src/main/resources/XWiki/QuickSearchUIX.xml
**Issue**: XWIKI-15364
**Issue link:** https://jira.xwiki.org/browse/XWIKI-15364
**Description:** This is done in the form of the Main Search page, but we should also do it for the global/quick search form, on the navbar-menu.
**Before:** 
**After:**
=> XWIKI-15364: Add role="search" to the global / quicksearch form

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/editmeta.vm, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/edit.less
Issue link: https://jira.xwiki.org/browse/XWIKI-16344
Tested.
Before:
After:
Any problems, let me know. Thanks!
=> XWIKI-16344: Use .xform style standard in the wiki and wysiwyg edit modes

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/forms.less, xwiki-platform-core/xwiki-platform-panels/xwiki-platform-panels-ui/src/main/resources/Panels/CreatePanel.xml, xwiki-platform-core/xwiki-platform-scheduler/xwiki-platform-scheduler-ui/src/main/resources/Scheduler/WebHome.xml
**Issue**: XWIKI-10954 
**Issue link**: https://jira.xwiki.org/browse/XWIKI-10954
**Description:** Text Field and button input elements are aligned. I tested my changes on multiple browsers (Edge, Firefox, Chrome). I have solved both `Create a Job` and `Create a Panel` with a single line of code. `vertical-align: middle`.
**Before:**  
**After:**
=> XWIKI-10954: "Panel Title" field is not aligned with "Create" button

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/xlist.less, xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/js/xwiki/importer/import.css
**Issue**: XWIKI-10952
**Issue link:**  https://jira.xwiki.org/browse/XWIKI-10952
**Description:**  Aligned the title and the description rows having only the icon on the left side. Tested on multiple Browsers (IE, Edge, Firefox, and chrome). Responsive across all devices. Responsiveness can be seen in the screenshots.
**Before:** 
Desktop:
Tablet : 
Mobile:
**After:**
Desktop:
Tablet:
Mobile:
=> XWIKI-10952: The "Available package" information is not aligned

xwiki-platform-core/xwiki-platform-panels/xwiki-platform-panels-ui/src/main/resources/Panels/DocumentInformation.xml
Issue link: https://jira.xwiki.org/browse/XWIKI-17127
The checkbox was loading wrong styles after `form` class was replaced by `xform`.
Before:
After:
Thanks to Marius for telling me the right solution.
=> XWIKI-17127: Page Information "xhidden" checkbox is misaligned

xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-ui/src/main/resources/XWiki/SolrSearchAdmin.xml
Issue Link: https://jira.xwiki.org/browse/XWIKI-17128
Line `109` has 118 characters so it doesn't exceed the limit.
Before:
After:
Let me know any mistakes, thanks!
=> XWIKI-17128: "Queue size" in Solr Search Administration is not using xform standards

xwiki-platform-distribution/xwiki-platform-distribution-debian/xwiki-platform-distribution-debian-mysql-common/src/deb/control/postinst, xwiki-platform-tools/xwiki-platform-tool-configuration-resources/src/main/resources/hibernate.cfg.xml.vm
I'm asking a review because these new settings are the ones that I have tested with success on a virtual machine, but I have not tried to build the debian package nor to upgrade an existing installation with the new packages. You could see it as a WIP with a request to point me where I should improve my proposition.
Thank you!
Guillaume
=> XWIKI-16303: Make utf8mb4 the default in XWiki Debian packages.

xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-server/src/main/java/org/xwiki/rest/internal/Utils.java, xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-server/src/main/java/org/xwiki/rest/internal/url/resources/JobStatusRestURLGenerator.java, xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-server/src/test/java/org/xwiki/rest/internal/url/resources/JobStatusRestURLGeneratorTest.java
JIRA: https://jira.xwiki.org/browse/XWIKI-16967
* Don't use AbstractJobRestURLGenerator#getIdStringElement anymore but
rely on the full list and handle it in Utils#createURI same as we do
for space names
* Add a unit test for JobStatusRestURLGenerator
=> XWIKI-16967: Failed to get the list of flavors on Distribution Wizard on Tomcat

xwiki-platform-core/xwiki-platform-vfs/xwiki-platform-vfs-api/src/main/java/org/xwiki/vfs/VfsResourceReference.java, xwiki-platform-core/xwiki-platform-vfs/xwiki-platform-vfs-api/src/main/java/org/xwiki/vfs/internal/AbstractVfsResourceReferenceSerializer.java, xwiki-platform-core/xwiki-platform-vfs/xwiki-platform-vfs-api/src/main/java/org/xwiki/vfs/internal/CascadingVfsPermissionChecker.java, xwiki-platform-core/xwiki-platform-vfs/xwiki-platform-vfs-api/src/main/java/org/xwiki/vfs/internal/DefaultVfsPermissionChecker.java, xwiki-platform-core/xwiki-platform-vfs/xwiki-platform-vfs-api/src/main/java/org/xwiki/vfs/internal/URIVfsResourceReferenceSerializer.java, xwiki-platform-core/xwiki-platform-vfs/xwiki-platform-vfs-api/src/main/java/org/xwiki/vfs/internal/VfsResourceReferenceResolver.java, xwiki-platform-core/xwiki-platform-vfs/xwiki-platform-vfs-api/src/main/java/org/xwiki/vfs/internal/VfsResourceReferenceSerializer.java, xwiki-platform-core/xwiki-platform-vfs/xwiki-platform-vfs-api/src/main/java/org/xwiki/vfs/internal/attach/AttachURIVfsResourceReferenceSerializer.java, xwiki-platform-core/xwiki-platform-vfs/xwiki-platform-vfs-api/src/main/java/org/xwiki/vfs/internal/attach/AttachVfsPermissionChecker.java, xwiki-platform-core/xwiki-platform-vfs/xwiki-platform-vfs-api/src/main/java/org/xwiki/vfs/internal/attach/AttachVfsResourceReferenceSerializer.java, xwiki-platform-core/xwiki-platform-vfs/xwiki-platform-vfs-api/src/main/java/org/xwiki/vfs/internal/attach/XWikiModelNode.java, xwiki-platform-core/xwiki-platform-vfs/xwiki-platform-vfs-api/src/main/java/org/xwiki/vfs/internal/script/PathConverter.java, xwiki-platform-core/xwiki-platform-vfs/xwiki-platform-vfs-api/src/main/java/org/xwiki/vfs/internal/script/VfsResourceReferenceConverter.java, xwiki-platform-core/xwiki-platform-vfs/xwiki-platform-vfs-api/src/test/java/org/xwiki/vfs/internal/DefaultVfsManagerTest.java, xwiki-platform-core/xwiki-platform-vfs/xwiki-platform-vfs-api/src/test/java/org/xwiki/vfs/internal/VfsResourceReferenceSerializerTest.java, xwiki-platform-core/xwiki-platform-vfs/xwiki-platform-vfs-api/src/test/java/org/xwiki/vfs/internal/VfsResourceReferenceTest.java, xwiki-platform-core/xwiki-platform-vfs/xwiki-platform-vfs-api/src/test/java/org/xwiki/vfs/internal/attach/AttachURIVfsResourceReferenceSerializerTest.java, xwiki-platform-core/xwiki-platform-vfs/xwiki-platform-vfs-api/src/test/java/org/xwiki/vfs/internal/script/VfsResourceReferenceConverterTest.java
JIRA: 
* https://jira.xwiki.org/browse/XWIKI-16793
* https://jira.xwiki.org/browse/XWIKI-17244
This PR fixes two issues related to VFS macro:
* the fact that we couldn't have a file with a space in a name in an archive (XWIKI-16973)
* the fact that we couldn't rely on an archive with a space in its name (XWIKI-17244)
The provided fix consists mainly in not relying anymore on URI in VfsResourceReference, but on a new String reference attribute. For the problem of the space name in attachment name, it also needed some work to encode the name and decode it in VFS.
=> XWIKI-16973: Spaces in file names in Zip files cause VFS Tree macro break

xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-api/pom.xml, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-api/src/checkstyle/checkstyle-suppressions.xml, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-api/src/main/java/org/xwiki/security/authorization/AuthorizationManager.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-api/src/main/java/org/xwiki/security/authorization/DefaultAuthorizationManager.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-api/src/main/java/org/xwiki/security/authorization/Right.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-api/src/main/java/org/xwiki/security/authorization/cache/internal/DefaultSecurityCache.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-api/src/test/java/org/xwiki/security/authorization/RightTest.java
Jira issue: https://jira.xwiki.org/browse/XWIKI-17559
* Add a new API to register a right with a set of existing Rights that
should imply it
* Refactor existing register method so that by default Admin Right
automatically imply the newly registered right
* Refactor Right impliedRight to make it mutable internally
* Add a new disabled test to check changes: disabled because Rights
are static and it currently breaks integrations tests
* Add more fine-grained checkstyle ignore and refactor checkstyle
problems on DefaultSecurityCache based on that
=> XWIKI-17559: Allow to register a right as an implied right of an already existing right

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/action-menus.less
- Replace the custom embedded display by having the dropdown outside the nav.
- Reset overwritten properties with Bootstrap variables.
=> XWIKI-17628: Dropdowns are displayed inside #xwikimainmenu

xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/pom.xml, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/src/main/java/org/xwiki/mentions/internal/async/DefaultMentionsBlockingQueueProvider.java, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/src/main/java/org/xwiki/mentions/internal/async/MapBasedLinkedBlockingQueue.java, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/src/main/java/org/xwiki/mentions/internal/async/MentionsData.java, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/src/test/java/org/xwiki/mentions/internal/async/DefaultMentionsBlockingQueueProviderTest.java, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/src/test/java/org/xwiki/mentions/internal/async/MapBasedLinkedBlockingQueueTest.java
* Provide a dedicated Map-based implementation of LinkedBlockingQueue
* Use H2 MVStore as the underlying lib to persist the map of data on
disk
(marking as draft since it's still missing the unit tests)
=> XWIKI-17636: Use a lighter library to perform disk-persistent blocking queue in mention

xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-script/src/main/java/org/xwiki/user/script/GroupScriptService.java
- Fixes the use of invalid tags in the javadoc.
https://jira.xwiki.org/browse/XWIKI-15833
=> XWIKI-15833: Users shouldn't be able to pick a group as a subgroup of itself

xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/src/main/java/org/xwiki/mentions/internal/DefaultMentionXDOMService.java, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/src/main/java/org/xwiki/mentions/internal/DefaultMentionsDataConsumer.java, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/src/main/java/org/xwiki/mentions/internal/MentionXDOMService.java, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/src/test/java/org/xwiki/mentions/internal/DefaultMentionXDOMServiceTest.java, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/src/test/java/org/xwiki/mentions/internal/DefaultMentionsDataConsumerTest.java, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-ui/src/main/resources/XWiki/Mentions/MentionsMacro.xml
https://jira.xwiki.org/browse/XWIKI-17718
Currently the mention is fully qualified identifier (eg, "xwiki:XWiki.U1") to reference the mentioned user, even when the user is local to the wiki.
The user picker is expecting to see local users identified by their short qualifier (eg, "XWiki.U1").
Consequently,  when the user picker is displayed twice, once for the short form and once for the fully qualified one.
The solution is to use the short for the mention's identifier.
As a consequence, the wiki in which the mention occurred is now needed for the resolution of the user.
=> XWIKI-17718: Duplicate user when editing the mentions macro in WYSIWYG

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/commentfield.vm, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/commentsinline.vm, xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/uicomponents/viewers/comments.js
https://jira.xwiki.org/browse/XWIKI-17811
Stores the submitted comment in a hidden field in case of error during the comment form submission (eg, invalid captcha).
The content is then retrieved and the form redisplayed with its previous content when the form is not validated.
=> XWIKI-17811: Comment text not displayed after being submited with an invalid captcha

xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/uicomponents/viewers/comments.js
* Clarify variable name in comments.js
* Move when the success notification message is sent when a comment is
posted, to ensure the comment is already displayed before, since
tests are waiting for it.
=> XWIKI-17726: CommentAsAdminTest#testReplyToCommentAsAdmin is flickering

xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-test/xwiki-platform-mentions-test-docker/src/test/it/org/xwiki/mentions/test/ui/MentionsIT.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-test/xwiki-platform-notifications-test-pageobjects/src/main/java/org/xwiki/platform/notifications/test/po/NotificationsTrayPage.java
https://jira.xwiki.org/browse/XWIKI-17827
The asynchronous tasks of the mentions and the notifications take longer than the default timeout of `waitOnNotificationCount`.
Consequently the test fails before the expected notification is received.
The notification is then received by `Mentions#comment` which fails too because it reads an unexpected mentions.
- Increases the timeout of the mention docker tests to 15 seconds.
- `NotificationsTrayPage#waitOnNotificationCount(String userId, String wiki, int expectedUnread, int timeout)` allowing to choose the timeout before stopping to wait for the notification count to reach the expected number.
=> XWIKI-17827: MentionsIT#documentBody is flickering

pom.xml, xwiki-platform-core/xwiki-platform-edit/xwiki-platform-edit-ui/src/main/resources/XWiki/InplaceEditing.xml, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/edit.vm, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/editactions.vm, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-docker/src/test/it/org/xwiki/flamingo/test/docker/EditIT.java, xwiki-platform-core/xwiki-platform-minimaldependencies/pom.xml, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/web/SaveAction.java, xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/js/xwiki/actionbuttons/actionButtons.js
JIRA: https://jira.xwiki.org/browse/XWIKI-17658 and https://jira.xwiki.org/browse/XWIKI-17871
The idea of this fix is to rely on the cached data of previousVersion field in case of using the back button to ensure
1. that the content is sent with the right version info to avoid a conflict
2. that the user will not send data with wrong previous information which could override existing data (situation before the check conflict mechanism)
In order to do that, I had to inject the needed fields for the check conflict mechanism in the edit template, since they need to be in the original DOM to be properly cached by the browser: fields injected with Javascript are not cached. 
I also had to change the way we reload the editor in actionButtons.js to ensure to force the reload without the cached …
=> XWIKI-17658: Unsaved content changes are not preserved anymore when using the browser's Back button to return to edit mode

xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-default/src/main/java/org/xwiki/refactoring/internal/AbstractRefactoringConfigurationSource.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-default/src/main/java/org/xwiki/refactoring/internal/DefaultRefactoringConfiguration.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-default/src/main/java/org/xwiki/refactoring/internal/MainWikiRefactoringConfigurationSource.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-default/src/main/resources/META-INF/components.txt, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-default/src/test/java/org/xwiki/refactoring/internal/DefaultLinkRefactoringTest.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-default/src/test/java/org/xwiki/refactoring/internal/DefaultRefactoringConfigurationTest.java, xwiki-platform-tools/xwiki-platform-tool-configuration-resources/src/main/resources/xwiki.properties.vm
https://jira.xwiki.org/browse/XWIKI-17820
- Introduces the main wiki refactoring configuration source that always look at the main wiki documents
- The configuration is now resolved by looking for a value:
- In the current wiki
- Then in the main wiki
- Then in xwiki.properties
If no value is found, returns the default value.
=> XWIKI-17820: Make the refactoring configuration more fine grained

xwiki-platform-core/xwiki-platform-messagestream/xwiki-platform-messagestream-api/pom.xml, xwiki-platform-core/xwiki-platform-messagestream/xwiki-platform-messagestream-api/src/main/java/org/xwiki/messagestream/internal/DefaultMessageStream.java, xwiki-platform-core/xwiki-platform-messagestream/xwiki-platform-messagestream-api/src/main/resources/ApplicationResources.properties, xwiki-platform-core/xwiki-platform-messagestream/xwiki-platform-messagestream-api/src/main/resources/templates/notification/rss/directMessage.vm, xwiki-platform-core/xwiki-platform-messagestream/xwiki-platform-messagestream-api/src/main/resources/templates/notification/rss/groupMessage.vm, xwiki-platform-core/xwiki-platform-messagestream/xwiki-platform-messagestream-api/src/main/resources/templates/notification/rss/messages_macros.vm, xwiki-platform-core/xwiki-platform-messagestream/xwiki-platform-messagestream-api/src/main/resources/templates/notification/rss/personalMessage.vm, xwiki-platform-core/xwiki-platform-messagestream/xwiki-platform-messagestream-api/src/main/resources/templates/notification/rss/publicMessage.vm, xwiki-platform-core/xwiki-platform-messagestream/xwiki-platform-messagestream-api/src/test/java/org/xwiki/messagestream/internal/DefaultMessageStreamConfigurationTest.java, xwiki-platform-core/xwiki-platform-messagestream/xwiki-platform-messagestream-api/src/test/java/org/xwiki/messagestream/internal/DefaultMessageStreamTest.java
https://jira.xwiki.org/browse/XWIKI-17915
- Defines dedicated templates to display the message in RSS feeds
- Defines dedicated titles for the event, used as the titles of the message in the RSS feeds
- Hides the changes when no version is provided
=> XWIKI-17915: Message stream messages are not displayed correctly in the rss feeds

xwiki-platform-core/xwiki-platform-messagestream/xwiki-platform-messagestream-api/pom.xml, xwiki-platform-core/xwiki-platform-messagestream/xwiki-platform-messagestream-api/src/main/java/org/xwiki/messagestream/GroupMessageDescriptor.java, xwiki-platform-core/xwiki-platform-messagestream/xwiki-platform-messagestream-api/src/main/java/org/xwiki/messagestream/internal/AbstractMessageStreamNotificationFilter.java, xwiki-platform-core/xwiki-platform-messagestream/xwiki-platform-messagestream-api/src/main/java/org/xwiki/messagestream/internal/DirectMessageStreamNotificationFilter.java, xwiki-platform-core/xwiki-platform-messagestream/xwiki-platform-messagestream-api/src/main/java/org/xwiki/messagestream/internal/GroupMessageStreamNotificationFilter.java, xwiki-platform-core/xwiki-platform-messagestream/xwiki-platform-messagestream-api/src/main/java/org/xwiki/messagestream/internal/PersonalMessageStreamNotificationFilter.java, xwiki-platform-core/xwiki-platform-messagestream/xwiki-platform-messagestream-api/src/main/resources/META-INF/components.txt, xwiki-platform-core/xwiki-platform-messagestream/xwiki-platform-messagestream-api/src/test/java/org/xwiki/messagestream/internal/DirectMessageStreamNotificationFilterTest.java, xwiki-platform-core/xwiki-platform-messagestream/xwiki-platform-messagestream-api/src/test/java/org/xwiki/messagestream/internal/GroupMessageStreamNotificationFilterTest.java, xwiki-platform-core/xwiki-platform-messagestream/xwiki-platform-messagestream-api/src/test/java/org/xwiki/messagestream/internal/PersonalMessageStreamNotificationFilterTest.java, xwiki-platform-core/xwiki-platform-messagestream/xwiki-platform-messagestream-api/src/test/java/org/xwiki/messagestream/script/MessageStreamScriptServiceTest.java, xwiki-platform-core/xwiki-platform-messagestream/xwiki-platform-messagestream-ui/src/main/resources/Main/MessageSenderMacro.xml, xwiki-platform-core/xwiki-platform-web/src/main/webapp/templates/notification/groupMessage.vm, xwiki-platform-core/xwiki-platform-web/src/main/webapp/templates/notification/macros.vm
https://jira.xwiki.org/browse/XWIKI-15815
- Enables the group message descriptor
- Defines the group messages filter
- Introduces a group message notification template, and update of the common message macros to support more than one translation parameter.
- Introduces a common AbstractMessageStreamNotificationFilter for all the messages
- Migration of the remaining JUnit 4 tests to JUnit 5
=> XWIKI-15815: The visible to Group option doesn't send any message to any user from the selected group

xwiki-platform-core/xwiki-platform-index/xwiki-platform-index-tree/xwiki-platform-index-tree-api/src/main/resources/org/xwiki/index/tree/internal/nestedpages/query/queries.hbm.xml
Added a condition for `doc.XWD_LANGUAGE is null` beside of `doc.XWD_LANGUAGE = ''` to handle cases where the DB stores a null in the language field instead of an empty string.
Oracle does that; see also comment at https://github.com/xwiki/xwiki-platform/blob/master/xwiki-platform-core/xwiki-platform-oldcore/src/main/resources/xwiki.oracle.hbm.xml#L37
As I am not fully comfortable with the document tree part of the code it would be nice if someone else could double check the two changes, small as they are.
=> XWIKI-17699 Page tree is not sorted by title when using Oracle DB

xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/web/DownloadAction.java, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/web/DownloadActionTest.java, xwiki-platform-tools/xwiki-platform-tool-configuration-resources/src/main/resources/xwiki.properties.vm
JIRA: https://jira.xwiki.org/browse/XWIKI-17754
The fix consists in adding a new property to always force-download some attachments based on their mimetype. The following changes have been made:
* introduce a new property to list the mimetypes to force-download
* improve a bit the documentation about whitelist/blacklist properties
to explain the limitations for PR users
* Refactor the check in DownloadAction to decide if the file should be
served inline or as attachment
* Refactor DownloadActionTest and provide some more tests to check the
various conditions
=> XWIKI-17754: Allow to force-download attachments with a given mimetype even if they are added by a PR user

xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/pdf/impl/PdfExportImpl.java, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/pdf/impl/PdfExportImplTest.java
Creates a `XMLReader` and sets it to dom4j's `SAXReader`. It sets the `http://xml.org/sax/features/namespaces` feature which is generally a good idea (and compatible with what _dom4j_ did to its default reader).
The new reader uses a _Xerces-j_ fixed configuration which causes whitespace to be different to the previous test output, so the text in the test is now compared after doing a `replaceAll` that removes whitespace between tags. This also prevents a bogus test fail depending on which XML parser is used.
This pull request depends on xwiki/xwiki-commons#103.
=> XWIKI-17796: Use ComponentManager to set the XMLReader used by PDF export

xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/js/xwiki/table/livetable.js
https://jira.xwiki.org/browse/XWIKI-18038
Retrieve the unescaped "colname"_value field when available during the livetable client side generation.
=> XWIKI-18038: Livetable "html" field parameter doesn't generate HTML code anymore

xwiki-platform-core/xwiki-platform-ratings/xwiki-platform-ratings-ui/pom.xml, xwiki-platform-core/xwiki-platform-ratings/xwiki-platform-ratings-ui/src/main/resources/XWiki/Ratings/RatingsMacros.xml, xwiki-platform-core/xwiki-platform-ratings/xwiki-platform-ratings-ui/src/test/java/org/xwiki/ratings/RatingsTest.java
Escapes the page name when displaying the displayFullRating macro.
https://jira.xwiki.org/browse/XWIKI-17037
=> XWIKI-17037: Vote isn't saved when the Page or it parent Space has a double quote in its name

xwiki-platform-core/xwiki-platform-ratings/xwiki-platform-ratings-api/pom.xml, xwiki-platform-core/xwiki-platform-ratings/xwiki-platform-ratings-api/src/main/java/org/xwiki/ratings/events/UpdateAverageRatingFailedEvent.java, xwiki-platform-core/xwiki-platform-ratings/xwiki-platform-ratings-api/src/main/java/org/xwiki/ratings/events/UpdatedAverageRatingEvent.java, xwiki-platform-core/xwiki-platform-ratings/xwiki-platform-ratings-api/src/main/java/org/xwiki/ratings/events/UpdatingAverageRatingEvent.java, xwiki-platform-core/xwiki-platform-ratings/xwiki-platform-ratings-api/src/main/java/org/xwiki/ratings/internal/averagerating/AbstractAverageRatingManager.java, xwiki-platform-core/xwiki-platform-ratings/xwiki-platform-ratings-api/src/main/java/org/xwiki/ratings/internal/averagerating/XObjectAverageRatingManager.java, xwiki-platform-core/xwiki-platform-ratings/xwiki-platform-ratings-api/src/main/resources/ApplicationResources.properties, xwiki-platform-core/xwiki-platform-ratings/xwiki-platform-ratings-api/src/test/java/org/xwiki/ratings/internal/averagerating/AbstractAverageRatingManagerTest.java, xwiki-platform-core/xwiki-platform-ratings/xwiki-platform-ratings-api/src/test/java/org/xwiki/ratings/internal/averagerating/XObjectAverageRatingManagerTest.java
Implements XObjectAverageRatingManager#moveAverageRatings and update the AverageRatings XObject entityReference field to reflect the new reference of the moved entities (the move Page as well as sub-entities).
As a consequence, empty constructor added to  UpdateAverageRatingFailedEvent and UpdatedAverageRatingEvent, and the data accompanying the avarage ratings event is now a list of AverageRatings to reflect the fact that multiple ratings can be modified on a single "transaction".
https://jira.xwiki.org/browse/XWIKI-17038
=> XWIKI-17038: The votes are lost after renaming the page

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/commentsinline.vm
We are working our way through our XWiki instance with the [WAVE plugin](https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh) at the moment to increase accessibility, that is resolve all errors thrown by their standards.We found one very minor issue is a missing label or title attribute in a modal dialogue to copy a comments permalink. This PR is meant to fix this. It is my very first contribution to XWiki and I would be glad if there are any standards I missed, if you could advice me on where to look and what to fix.
=> Introduce title attribute into "Go to permalink" modal dialogue

xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-profile/xwiki-platform-user-profile-test/xwiki-platform-user-profile-test-docker/src/test/it/org/xwiki/user/test/ui/UserChangePasswordIT.java, xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-profile/xwiki-platform-user-profile-test/xwiki-platform-user-profile-test-pageobjects/src/main/java/org/xwiki/user/test/po/ChangePasswordPage.java
https://jira.xwiki.org/browse/XWIKI-17158
- Improves the way we detect if the password update messages are displayed, to make it faster (avoiding timeouts that makes the test flicker).
- Code style and documentation improvements
=> XWIKI-17158: UserChangePasswordIT#changePasswordWhenPolicyIsLength8AndNumberMandatory is flaky

xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-macros/xwiki-platform-rendering-macro-code/pom.xml, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-macros/xwiki-platform-rendering-macro-code/src/test/resources/macrocode15.test, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-macros/xwiki-platform-rendering-macro-code/src/test/resources/macrocode16.test
https://jira.xwiki.org/browse/XWIKI-18363
- Downgrade Pygments from 2.5.1 to 2.4.2 because of regressions in the way Pygment guesses the language of the code.
- Introduction of two non regression tests for future upgrades.
=> XWIKI-18363: Auto-detection of language with the code macro is broken

xwiki-platform-distribution/xwiki-platform-distribution-flavor/xwiki-platform-distribution-flavor-test/xwiki-platform-distribution-flavor-test-ui/src/test/it/org/xwiki/test/ui/RegisterTest.java
https://jira.xwiki.org/browse/XWIKI-18255
Sets explicitly all the registration form fields to be independent of the state of the form before the beginning of the test.
=> XWIKI-18255: RegisterFromAdministrationTest#testRegisterExistingUser is flickering

xwiki-platform-distribution/xwiki-platform-distribution-flavor/xwiki-platform-distribution-flavor-test/xwiki-platform-distribution-flavor-test-ui/src/test/it/org/xwiki/test/ui/appwithinminutes/StaticListClassFieldTest.java
Reordering items with large label when configuring a static list can be difficult when the item labels are long and the screen width small.
This was making StaticListClassFieldTest#testItemsEditor fail.
We are shortening label of the reordered item to make the test pass, until the items UI component is fixed (see XWIKI-18343).
=> [Misc] Fixes StaticListClassFieldTest#testItemsEditor for the current integration tests resolution

xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-api/src/main/java/org/xwiki/notifications/filters/script/NotificationFiltersScriptService.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-watch/src/main/java/org/xwiki/notifications/filters/watch/script/NotificationWatchScriptService.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-preferences/xwiki-platform-notifications-preferences-api/pom.xml, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-preferences/xwiki-platform-notifications-preferences-api/src/checkstyle/checkstyle-suppressions.xml, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-preferences/xwiki-platform-notifications-preferences-api/src/main/java/org/xwiki/notifications/preferences/script/NotificationPreferenceScriptService.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-preferences/xwiki-platform-notifications-preferences-api/src/test/java/org/xwiki/notifications/preferences/script/NotificationPreferenceScriptServiceTest.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-test/xwiki-platform-notifications-test-docker/pom.xml, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-test/xwiki-platform-notifications-test-docker/src/test/it/org/xwiki/platform/notifications/test/ui/NotificationsSettingsIT.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-test/xwiki-platform-notifications-test-pageobjects/src/main/java/org/xwiki/platform/notifications/test/po/AbstractNotificationsSettingsPage.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-test/xwiki-platform-notifications-test-pageobjects/src/main/java/org/xwiki/platform/notifications/test/po/NotificationsAdministrationPage.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-test/xwiki-platform-notifications-test-pageobjects/src/main/java/org/xwiki/platform/notifications/test/po/NotificationsUserProfilePage.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-test/xwiki-platform-notifications-test-pageobjects/src/main/java/org/xwiki/platform/notifications/test/po/preferences/filters/NotificationFilterPreference.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-ui/src/main/resources/XWiki/Notifications/Code/NotificationFilterPreferenceLivetableResults.xml, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-ui/src/main/resources/XWiki/Notifications/Code/NotificationPreferenceService.xml, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-ui/src/main/resources/XWiki/Notifications/Code/NotificationsApplicationsPreferencesMacro.xml, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-ui/src/main/resources/XWiki/Notifications/Code/NotificationsAutoWatchPreferencesMacro.xml, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-ui/src/main/resources/XWiki/Notifications/Code/NotificationsEmailPreferencesMacro.xml, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-ui/src/main/resources/XWiki/Notifications/Code/NotificationsFiltersPreferencesMacro.xml, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-ui/src/main/resources/XWiki/Notifications/Code/Translations.xml, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-ui/src/main/resources/XWiki/Notifications/Code/XWikiUserNotificationsSheet.xml, xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-profile/xwiki-platform-user-profile-test/xwiki-platform-user-profile-test-pageobjects/src/main/java/org/xwiki/user/test/po/AbstractUserProfilePage.java
JIRA: https://jira.xwiki.org/browse/XWIKI-16158
* Improve various Notification script service to allow using them with
a given UserReference instead of the context user reference
* Change the different Notification Preferences Macros to add a user
parameter which is the reference of the user for which to display
the preferences
* Change the code of those macros to be able to handle the given user
and not only the context user
* Change XWikiUserNotificationsSheet to allow displaying the
notifications tab in user profile for any user for which current
user has admin rights
=> XWIKI-16158: Allow admin to access the notification preferences of other users

xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/uicomponents/viewers/diff.css, xwiki-platform-core/xwiki-platform-web/src/main/webapp/templates/diff_macros.vm
https://jira.xwiki.org/browse/XWIKI-18304
- Introduction of a new diff-line-decision class to help the css selection
- Prevent the white-space pre-wrap on the diff decision td and apply it on the proposed decisions instead
- Uniformize the padding to keep an uniform view when switching between the proposed decisions.
=> XWIKI-18304: Misalignment issue and unneeded scroll bar on the Version conflict box

xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/uicomponents/viewers/diff.css, xwiki-platform-core/xwiki-platform-web/src/main/webapp/templates/diff_macros.vm
- Introduction of a new diff-line-decision class to help the css selection
- Fixes the comment formatting
- defining the containing table as width lower than 100 (e.g., 99.99%) prevents the display of an horizontal scrollbar when a td has a border.
=> XWIKI-18304: Misalignment issue and unneeded scroll bar on the Version conflict box (#1517)

xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-test/xwiki-platform-appwithinminutes-test-docker/pom.xml, xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-test/xwiki-platform-appwithinminutes-test-docker/src/test/it/org/xwiki/appwithinminutes/test/ui/AddEntryIT.java, xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-test/xwiki-platform-appwithinminutes-test-docker/src/test/it/org/xwiki/appwithinminutes/test/ui/AllITs.java, xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-test/xwiki-platform-appwithinminutes-test-pageobjects/src/main/java/org/xwiki/appwithinminutes/test/po/ApplicationHomePage.java, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/po/LiveTableElement.java
- Wait added on ApplicationHomePage#clickAddNewEntry to prevent access to the name field before it is displayed.
- AddEntryTest (in xwiki-platform-distribution-flavor-test-ui) migrated to docker as AddEntryIT (in xwiki-platform-appwithinminutes-test-docker).
- Adding the missing nested test in AllITs
- Improves the sorting page objects
=> XWIKI-18258: AddEntryTest#testEntryNameWithURLSpecialCharacters is flickering

xwiki-platform-core/xwiki-platform-panels/xwiki-platform-panels-ui/src/main/resources/Panels/Applications.xml
Issue: https://jira.xwiki.org/browse/XWIKI-15119
I know it is an old issue but it is still relevant.
Old vs new
In the old, the text after an icon is a set amount of pixels after the icon, and this is not aligned with the other titles when the icons are not the same size
In the new, the width property of the icon is a set amount of pixels so the text always starts at the same position.
I set it at 20px since this was also already the height of the box so the icon is in a square now.
Since there is already some space left now as icons are smaller than 20px, the left margin of the following text can be reduced (to .1em).
=> XWIKI-15119: The Applications panel entries are not properly aligned

xwiki-platform-core/xwiki-platform-extension/xwiki-platform-extension-handlers/xwiki-platform-extension-handler-xar/src/test/java/org/xwiki/extension/xar/internal/question/CleanPagesQuestionRecorderTest.java, xwiki-platform-core/xwiki-platform-extension/xwiki-platform-extension-handlers/xwiki-platform-extension-handler-xar/src/test/java/org/xwiki/extension/xar/internal/question/ConflictQuestionRecorderTest.java, xwiki-platform-core/xwiki-platform-lesscss/xwiki-platform-lesscss-default/src/test/java/org/xwiki/lesscss/internal/resources/LESSObjectPropertyResourceReferenceTest.java, xwiki-platform-core/xwiki-platform-lesscss/xwiki-platform-lesscss-default/src/test/java/org/xwiki/lesscss/internal/resources/LESSSkinFileResourceReferenceTest.java, xwiki-platform-core/xwiki-platform-lesscss/xwiki-platform-lesscss-default/src/test/java/org/xwiki/lesscss/internal/skin/DocumentSkinReferenceTest.java, xwiki-platform-core/xwiki-platform-lesscss/xwiki-platform-lesscss-default/src/test/java/org/xwiki/lesscss/internal/skin/FSSkinReferenceTest.java, xwiki-platform-core/xwiki-platform-mail/xwiki-platform-mail-send/xwiki-platform-mail-send-api/src/test/java/org/xwiki/mail/MailStatusResultSerializerTest.java, xwiki-platform-core/xwiki-platform-mail/xwiki-platform-mail-send/xwiki-platform-mail-send-api/src/test/java/org/xwiki/mail/MailStatusTest.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-api/src/test/java/org/xwiki/security/authorization/internal/SecurityAccessTest.java, xwiki-platform-core/xwiki-platform-wysiwyg/xwiki-platform-wysiwyg-api/src/test/java/org/xwiki/wysiwyg/internal/cleaner/HTMLCleanerTest.java
As a part of generally desirable migration to JUnit5, I've searched for JUnit4 imports and replaced 10 first occurrences (of course, the are many more left).
Changes:
- org.junit.Test -> org.junit.jupiter.api.Test
- org.junit.Assert -> org.junit.jupiter.api.Assertions
- org.junit.Before -> org.junit.jupiter.api.BeforeEach
=> Replaced some JUnit4 imports with JUnit5

xwiki-platform-core/xwiki-platform-like/xwiki-platform-like-api/src/main/java/org/xwiki/like/internal/LikeRight.java, xwiki-platform-core/xwiki-platform-like/xwiki-platform-like-api/src/test/java/org/xwiki/like/internal/LikeRightTest.java
As it is exposed in https://jira.xwiki.org/browse/XWIKI-18510, there is an inconsistency of naming the Like right with the rest of the rights from the platform (those are with lowercase).
The changing of the name with lowercase will not impact the checking of access (since for those cases we're working with the object itself).
Note that the current PR is only a draft, it was not extensively tested, even if the unit testing are passing.
=> XWIKI-18510: A right object with like level will not be displayed in page administration

xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/config/vue.config.js
Export style as less files instead of css
For now, every style file (even only css ones) is built as less file, because the configuration of the MiniCssExtractPlugin plugin only allow to specify the filename globally, and not according to a specific rule. This is not really an issue, as less is a superset of css, but his could lower performance as every css files will have to be parsed through the less compiler.
Also strangely, the `"[name]"` template string of webpack resolves to `xwiki-livedata-vue.umd.min` for the main less filename, instead of `xwiki-livedata-vue`. But this is just a cosmetic issue.
=> XWIKI-18270 Live Data macro styles don't use the color theme

xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-test/xwiki-platform-appwithinminutes-test-pageobjects/src/main/java/org/xwiki/appwithinminutes/test/po/ApplicationClassEditPage.java, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/XWikiWebDriver.java, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/po/ViewPage.java
Moving to the top of the screen is required for the drag and drop action to work, but using sendKey(HOME) wasn't working on Chrome (the drag and drop action was performed while the scroll up is still moving). sendKey replaced with executeScript("window.scrollTo(0, 0)")
=> XWIKI-18542: AWM tests failing on chrome

xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-test/xwiki-platform-appwithinminutes-test-pageobjects/src/main/java/org/xwiki/appwithinminutes/test/po/ApplicationClassEditPage.java, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/XWikiWebDriver.java, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/po/ViewPage.java
Moving to the top of the screen is required for the drag and drop action to work, but using sendKey(HOME) wasn't working on Chrome (the drag and drop action was performed while the scroll up is still moving). sendKey replaced with executeScript("window.scrollTo(0, 0)")
- scrollTo(int,int) moved to a dedicated method in XWikiWebDriver.
- Introducing a `scrollToTop` method in `ViewPage`.
=> XWIKI-18542: AWM tests failing on chrome (#1598)

xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-notifications/src/main/resources/templates/mentions/mention.vm, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-test/xwiki-platform-mentions-test-docker/src/test/it/org/xwiki/mentions/test/ui/MentionsIT.java
Uses the translated document to access the rendered title. This has to advantages:
- the name of the document is used if the title is empty
- the title is displayed in the current locale of the user
=> XWIKI-18560: Mentions notification can display a link to the mention with an empty text

xwiki-platform-core/xwiki-platform-extension/xwiki-platform-extension-ui/src/main/resources/XWiki/ExtensionUpdater.xml
- When an extension id is present in the request, display extension info in the updater context (same approach as in extensionHistory.vm)
=> XWIKI-18461: Extension version links are not working from Extension updater

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/js/xwiki/usersandgroups/usersandgroups.js
- In the UI JavaScript, convert the rights to lowercase before comparing them with the
reference rights ('admin', 'view', etc.)
=> XWIKI-18556: Rights UI only display rights with the proper case

xwiki-platform-core/xwiki-platform-tree/xwiki-platform-tree-webjar/src/main/webjar/tree.js
- When ctrl key is pressed, open link in new window / tab in tree.js  event listener
=> XWIKI-15495: Enable CTRL+CLICK on document tree to open links in new tabs

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/extension.vm, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/uicomponents/extension/extension.css
- Use span instead of paragraph for extension-status element since paragraphs are not authorized in headings
=> XWIKI-14811: Bad layout when using a font larger than the default one

xwiki-platform-core/xwiki-platform-sandbox/pom.xml
- Add dependency on `xwiki-platform-uiextension-ui`, which is needed by the Sandbox application to get listed in the Applications panel via a `UserExtensionClass` object.
=> XWIKI-18500: Extension updater propose to upgrade Sandbox to 13.1 when 12.10.5 flavor is installed

xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-api/src/main/java/org/xwiki/icon/IconManager.java, xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-api/src/main/java/org/xwiki/icon/IconSet.java, xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-default/src/main/java/org/xwiki/icon/internal/DefaultIconManager.java, xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-default/src/test/java/org/xwiki/icon/internal/DefaultIconManagerTest.java, xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-rest/pom.xml, xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-rest/xwiki-platform-icon-rest-api/pom.xml, xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-rest/xwiki-platform-icon-rest-api/src/main/java/org/xwiki/icon/rest/IconThemesResource.java, xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-rest/xwiki-platform-icon-rest-api/src/main/resources/simple.xjb, xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-rest/xwiki-platform-icon-rest-api/src/main/resources/xwiki.rest.icon.model.xsd, xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-rest/xwiki-platform-icon-rest-default/pom.xml, xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-rest/xwiki-platform-icon-rest-default/src/main/java/org/xwiki/icon/internal/DefaultIconThemesResource.java, xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-rest/xwiki-platform-icon-rest-default/src/main/resources/META-INF/components.txt, xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-rest/xwiki-platform-icon-rest-default/src/test/java/org/xwiki/icon/internal/DefaultIconThemesResourceTest.java, xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-test/pom.xml, xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-test/xwiki-platform-icon-test-docker/pom.xml, xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-test/xwiki-platform-icon-test-docker/src/test/it/org/xwiki/icon/test/ui/AllITs.java, xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-test/xwiki-platform-icon-test-docker/src/test/it/org/xwiki/icon/test/ui/IconThemesRestIT.java, xwiki-platform-core/xwiki-platform-minimaldependencies/pom.xml
- Introduces the icon extension rest api and default implementation modules
- Introduces the icon extension docker tests module
=> XWIKI-18604: Expose the Icon Theme through the REST API

xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-livetable/src/main/java/org/xwiki/livedata/internal/livetable/DefaultLiveDataConfigurationResolver.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-livetable/src/test/java/org/xwiki/livedata/internal/livetable/DefaultLiveDataConfigurationResolverTest.java, xwiki-platform-core/xwiki-platform-panels/xwiki-platform-panels-test/xwiki-platform-panels-test-docker/src/test/it/org/xwiki/panels/test/ui/docker/PanelIT.java, xwiki-platform-core/xwiki-platform-wiki/xwiki-platform-wiki-test/xwiki-platform-wiki-test-docker/src/test/it/org/xwiki/wiki/test/ui/WikiTemplateIT.java, xwiki-platform-core/xwiki-platform-wiki/xwiki-platform-wiki-test/xwiki-platform-wiki-test-pageobjects/src/main/java/org/xwiki/wiki/test/po/WikiIndexPage.java
Update the livetable data configuration resolver to apply the following precedence for the property names:
- name defined in the Live Data macro
- name defined in the translations
- pretty name of the property
- identifier of the property
=> XWIKI-18628: Field pretty name should not take precedence over the specified translation prefix

xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-test/xwiki-platform-appwithinminutes-test-pageobjects/src/main/java/org/xwiki/appwithinminutes/test/po/ApplicationClassEditPage.java, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/XWikiWebDriver.java, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/po/ViewPage.java
- Explains why a call to the javascript window.scrollTo method is the best way to scroll
- Documents why using XWikiWebDriver#scrollTo(int, int) is the best way to move to the top of the page
- Documents why we stopped using a home page key press action to move the view to the top of the page in ApplicationClassEditPage
=> [Misc] Page object documentation improvements

xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-api/src/main/resources/ApplicationResources.properties, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-api/src/main/resources/liveDataConfiguration.json, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-api/src/test/resources/DefaultLiveDataConfigurationResolver.test, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-livetable/src/main/java/org/xwiki/livedata/internal/livetable/LiveTableLiveDataPropertyStore.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-livetable/src/main/java/org/xwiki/livedata/internal/livetable/LiveTableRequestHandler.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-livetable/src/test/java/org/xwiki/livedata/internal/livetable/LiveTableLiveDataPropertyStoreTest.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-livetable/src/test/java/org/xwiki/livedata/internal/livetable/LiveTableRequestHandlerTest.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-macro/src/main/resources/ApplicationResources.properties, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-test/xwiki-platform-livedata-test-pageobjects/src/main/java/org/xwiki/livedata/test/po/TableLayoutElement.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/tests/mocks/xwiki-selectize.js, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/tests/unit/filters/FilterList.spec.js, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/filters/FilterList.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/filters/LivedataFilter.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/filters/filterMixin.js, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/panels/LivedataAdvancedPanelFilterEntry.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/webjar/Logic.js, xwiki-platform-core/xwiki-platform-livetable/xwiki-platform-livetable-ui/src/main/resources/XWiki/LiveTableResultsMacros.xml, xwiki-platform-core/xwiki-platform-livetable/xwiki-platform-livetable-ui/src/test/java/org/xwiki/livetable/LiveTableResultsTest.java
https://jira.xwiki.org/browse/XWIKI-18661
- Introduce a new 'empty' filter on Live Data
- Introduce a new 'empty' matcher on Livetable
- Make the conversion for the new filter on Live Data - Live Table Connector
- Hides the select field in the advanced panel when the filter type is 'empty'
=> XWIKI-18661: Impossible to filter panel type or category with empty value

xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-ui/src/main/resources/XWiki/AdminCustomRightsSheet.xml, xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-ui/src/main/resources/XWiki/AdminExtensionRightsSheet.xml, xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-ui/src/main/resources/XWiki/AdminTranslations.xml, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/rightsUI.vm, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-script/src/main/java/org/xwiki/security/authorization/script/SecurityAuthorizationScriptService.java
https://jira.xwiki.org/browse/XWIKI-17533
This PR is an experiment to find a trade-off for allowing to set custom rights, without having to rewrite entirely the whole rights UI, and without breaking the existing one. 
Here's what I said about it on the chat:
>  guys I'm thinking about a trade-off solution for the custom right UI problem we currently have. To sum up, right now when a custom right is injected it's not possible to configure it through the Rights UI and there's no extension point to inject it. So currently the only solution is to code a dedicated UI for the custom right. In my case, I'm currently writing an extension that will need at least 2 custom rights and I'm thinking how do I deal with that issue. So far I was seeing 3 options:
> 1. to re-write entirely the rights UI …
=> XWIKI-17533: Allow to set custom rights in administration

xwiki-platform-core/xwiki-platform-like/xwiki-platform-like-api/src/main/java/org/xwiki/like/internal/DefaultLikeManager.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-api/src/main/java/org/xwiki/security/authorization/AuthorizationManager.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-api/src/main/java/org/xwiki/security/authorization/DefaultAuthorizationManager.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-api/src/main/java/org/xwiki/security/authorization/Right.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-api/src/test/java/org/xwiki/security/authorization/AbstractAuthorizationTestCase.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-api/src/test/java/org/xwiki/security/authorization/DefaultAuthorizationManagerIntegrationTest.java
https://jira.xwiki.org/browse/XWIKI-17571
* Add a new API in AuthorizationManager to unregister a right
* Provide some new package private method in Right to unregister it
* Refactor tests to use junit5 and provide new tests for
register/unregister
* Use the new API when the DefaultLikeManager is disposed to
unregister the right.
Unit tests provided, also tested manually by uninstalling Like API and checking the UI for Extension Rights.
=> XWIKI-17571: Allow to unregister a right

xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-api/src/main/resources/liveDataConfiguration.json, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-api/src/test/resources/DefaultLiveDataConfigurationResolver.test, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-livetable/src/main/resources/liveTableLiveDataConfiguration.json, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-macro/src/main/resources/ApplicationResources.properties, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-test/xwiki-platform-livedata-test-docker/pom.xml, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-test/xwiki-platform-livedata-test-docker/src/test/it/org/xwiki/livedata/test/ui/LiveDataIT.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-test/xwiki-platform-livedata-test-pageobjects/src/main/java/org/xwiki/livedata/test/po/LiveDataElement.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/tests/unit/displayers/BaseDisplayer.spec.js, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/tests/unit/displayers/DisplayerActions.spec.js, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/tests/unit/displayers/DisplayerDocTitle.spec.js, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/tests/unit/displayers/DisplayerLink.spec.js, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/tests/unit/displayers/displayerTestsHelper.js, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/tests/unit/footnotes/LivedataFootnotes.spec.js, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/XWikiLivedata.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/displayers/BaseDisplayer.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/displayers/DisplayerActions.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/displayers/DisplayerDocTitle.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/displayers/DisplayerLink.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/displayers/displayerLinkMixin.js, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/footnotes/LivedataFootnotes.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/webjar/Logic.js
Introduce a DocTitle component dedicated to displaying the doc.title property.
Introduce a Footnotes component to display footnotes
Introduce the logic to check if an entry is empty because the current user does not have the right to view it
=> XWIKI-18732: Live Data source should be able to display contextual error/warning messages

xwiki-platform-core/xwiki-platform-ratings/xwiki-platform-ratings-api/src/main/java/org/xwiki/ratings/RatingsManager.java
The enum `RatingQueryField` is public, so all fields should be documented.
Related checkstyle issue https://github.com/checkstyle/checkstyle/issues/9876
The link to the failed build: https://github.com/checkstyle/checkstyle/pull/10200/checks?check_run_id=2928353421#step:6:8170
=> [Misc] Javadoc fixes

xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-rest/pom.xml, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-rest/src/main/java/org/xwiki/livedata/internal/rest/DefaultLiveDataEntriesResource.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-rest/src/main/java/org/xwiki/livedata/internal/rest/LiveDataResourceContextInitializer.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-rest/src/main/resources/META-INF/components.txt, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-rest/src/test/java/org/xwiki/livedata/internal/rest/DefaultLiveDataEntriesResourceTest.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-rest/src/test/java/org/xwiki/livedata/internal/rest/LiveDataResourceContextInitializerTest.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/webjar/liveDataSource.js
https://jira.xwiki.org/browse/XWIKI-18722
- If the namespace if not null and of type wiki, the context is updated with the namespace's wiki.
- The namespace parameter is now sent when when creating Live Data requests
=> XWIKI-18722: Current wiki not passed to the context when calling a Livetable result template or page

xwiki-platform-core/xwiki-platform-sharepage/xwiki-platform-sharepage-ui/src/main/resources/XWiki/SharePage.xml
[XWIKI-18897](https://jira.xwiki.org/browse/XWIKI-18897)
The picker did work properly but it was affected by two conflicting CSS selectors. One in the SharePage ssx and one in the EditSheet ssx.
The solution was to have the SharePage selector have the same value as the EditSheet one.
=> XWIKI-18897 - User Picker doesn't appear when inserting a macro that uses it

xwiki-platform-core/xwiki-platform-wiki/xwiki-platform-wiki-ui/xwiki-platform-wiki-ui-mainwiki/src/main/resources/WikiManager/WebHome.xml, xwiki-platform-core/xwiki-platform-wiki/xwiki-platform-wiki-ui/xwiki-platform-wiki-ui-mainwiki/src/test/java/org/xwiki/wiki/WikiManagerTest.java
Make the properties that are requested by the LD macro but do not correspond to a document or XClass property not-editable by default.
=> XWIKI-18892: Properties that does not correspond to XClass properties should not be editable

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/layoutvars.vm
JIRA: https://jira.xwiki.org/browse/XWIKI-18910
Proposed solution:
* Ensure to display the language menu only if $doc is defined in the
current context.
=> XWIKI-18910: Errors appear in the wiki console after selecting the "Forgot your username or password option", on a Multilingual wiki

xwiki-platform-core/pom.xml, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-test/xwiki-platform-livedata-test-docker/src/test/it/org/xwiki/livedata/test/ui/LiveDataIT.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-test/xwiki-platform-livedata-test-pageobjects/src/main/java/org/xwiki/livedata/test/po/TableLayoutElement.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/objects/classes/ListClass.java, xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-server/src/main/java/org/xwiki/rest/internal/resources/classes/StaticListClassPropertyValuesProvider.java, xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-server/src/test/java/org/xwiki/rest/internal/resources/classes/StaticListClassPropertyValuesProviderTest.java
This uses the view displayer to populate the metadata that is returned by the REST service.
Jira issue: https://jira.xwiki.org/browse/XWIKI-19048
I would like to get feedback on two questions here:
* The unit test (`StaticListClassPropertyValuesProviderTest`) is not just testing `StaticListClassPropertyValuesProvider` but also its interaction with `ListClass` using an actual `ListClass` object and not a mock. This really helped me during the development to ensure that I'm correctly using the interface and, e.g., handling the XML-encoded result value correctly. However, this is kind of against the idea of an isolated unit test. What do you think, is this kind of test okay or should I change it to, e.g., mock the results of the `ListClass`-methods?
* The implementation of …
=> XWIKI-19048: Live data list filter should display and filter by (translated) labels for static list properties

xwiki-platform-core/xwiki-platform-annotation/xwiki-platform-annotation-ui/src/main/resources/AnnotationCode/Script.xml
* fix AnnotationsIT: the js condition to check if an annotation exists was failing when an anotation started at the beginning of the text since `!plainTextStartOffset.value` returns true for `0`
=> XWIKI-11169: Annotations can not be displayed on content generated by the HTML macro

xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/doc/XWikiDocument.java, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/doc/XWikiDocumentMockitoTest.java
* Use the provided number for getting the object
* Add a unit test to check the desired behavior and avoid a regression
Jira issue: https://jira.xwiki.org/browse/XWIKI-19201
=> XWIKI-19201: XWikiDocument.getXObject(EntityReference, int, boolean, XWikiContext) ignores the given number when checking for an existing object

xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/doc/XWikiDocument.java, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/doc/XWikiDocumentMockitoTest.java
* Create objects directly with the correct number
* Add an assertion in the test that no duplicate object is created
* Change the JavaDoc comment to match the implementation
Jira issue: https://jira.xwiki.org/browse/XWIKI-19202
Note: this depends on #1722 as the used `getXObject` variant is buggy without it.
=> XWIKI-19202: XWikiDocument.readObjectsFromFormUpdateOrCreate() creates duplicate objects when ids are non-continuous

xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/doc/XWikiDocument.java, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/doc/XWikiDocumentMockitoTest.java
* Create objects with the correct number
* Add a test case to test adding, updating and removing objects
Jira issue: https://jira.xwiki.org/browse/XWIKI-19203
Note: this depends on #1722 as `getXObject` has been buggy before.
=> XWIKI-19203: The xobjectNumbers from the addedObjects parameter are ignored

xwiki-platform-core/xwiki-platform-legacy/xwiki-platform-legacy-oldcore/src/main/aspect/com/xpn/xwiki/web/XWikiActionCompatibilityAspect.aj, xwiki-platform-core/xwiki-platform-legacy/xwiki-platform-legacy-oldcore/src/main/java/com/xpn/xwiki/web/ViewrevAction.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/internal/redirection/RedirectClassRedirectionFilter.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/redirection/RedirectionFilter.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/web/DownloadAction.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/web/GetAction.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/web/ViewAction.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/web/ViewAttachRevAction.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/web/XWikiAction.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/resources/META-INF/components.txt, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/internal/redirection/RedirectClassRedirectionFilterTest.java
- Introduce RedirectionFilter role
- Move the existing redirection logic in a new RedirectClassRedirectionFilter component
- XWikiAction#execute loads and execute the RedirectionFilter components by order of priority
- Make RedirectClassRedirectionFilter with a 500 priority to make it executed early
=> XWIKI-19308: Modularize the redirection logic in XWikiAction

xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/doc/XWikiDocument.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/web/EditAction.java, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/doc/XWikiDocumentMockitoTest.java
* Extract a new method `XWikiDocument.readAddedUpdatedAndRemovedObjectsFromForm()` from `readFromForm()`
* Change the existing unit test of `readFromForm()` to test this method instead (as it only tested the extracted code, anyways)
* Use this new method during preview/edit actions instead of `XWikiDocument.readObjectsFromForm()`
Jira issue: https://jira.xwiki.org/browse/XWIKI-19193
=> XWIKI-19193: Objects are not created or removed during preview

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/js/xwiki/importer/import.css
* Prefix all styles that might be generic with `#import` (id defined here: [importinline.vm#L57](https://github.com/michitux/xwiki-platform/blob/bd419a583691c1156a38e44022781ae876932da0/xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/importinline.vm#L57)).
Jira issue: https://jira.xwiki.org/browse/XWIKI-19079
=> XWIKI-19079: Styling of search suggestions is broken when the importer is open

xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-test/xwiki-platform-administration-test-pageobjects/src/main/java/org/xwiki/administration/test/po/LocalizationAdministrationSectionPage.java, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/po/BootstrapSelect.java
* Adapt BootstrapSelect page object to no longer rely on removed attribute.
* Make selectors in LocalizationAdministrationSectionPage more robust.
* Improve performance of BootstrapSelect.
This fixes test failures introduced in https://jira.xwiki.org/browse/XWIKI-19323 and improves the performance of the BootstrapSelect page object by reducing the number of calls to the web driver.
=> XWIKI-19323: Upgrade to Bootstrap Select 1.13.18

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/locationPicker_macros.vm
* Add 'exclusions': "$!options.exclusions" to the map of options passed to the documentTree macro
=> XWIKI-19343: Add ability to exclude some locations when using the location picker

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/menus_macros.vm
* Escape title and content in #submenuitem - they are always unescaped from a localization.
Jira issue: https://jira.xwiki.org/browse/XWIKI-19149
=> XWIKI-19149: id likers: invalid attributes in german localization

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/javascript.vm, xwiki-platform-core/xwiki-platform-skin/xwiki-platform-skin-skinx/src/main/java/com/xpn/xwiki/plugin/skinx/AbstractDocumentSkinExtensionPlugin.java, xwiki-platform-core/xwiki-platform-skin/xwiki-platform-skin-skinx/src/main/java/com/xpn/xwiki/plugin/skinx/AbstractSkinExtensionPlugin.java, xwiki-platform-core/xwiki-platform-skin/xwiki-platform-skin-skinx/src/main/java/com/xpn/xwiki/plugin/skinx/CssResourceSkinExtensionPlugin.java, xwiki-platform-core/xwiki-platform-skin/xwiki-platform-skin-skinx/src/main/java/com/xpn/xwiki/plugin/skinx/CssSkinExtensionPlugin.java, xwiki-platform-core/xwiki-platform-skin/xwiki-platform-skin-skinx/src/main/java/com/xpn/xwiki/plugin/skinx/CssSkinFileExtensionPlugin.java, xwiki-platform-core/xwiki-platform-skin/xwiki-platform-skin-skinx/src/main/java/com/xpn/xwiki/plugin/skinx/JsResourceSkinExtensionPlugin.java, xwiki-platform-core/xwiki-platform-skin/xwiki-platform-skin-skinx/src/main/java/com/xpn/xwiki/plugin/skinx/JsSkinExtensionPlugin.java, xwiki-platform-core/xwiki-platform-skin/xwiki-platform-skin-skinx/src/main/java/com/xpn/xwiki/plugin/skinx/JsSkinFileExtensionPlugin.java, xwiki-platform-core/xwiki-platform-skin/xwiki-platform-skin-skinx/src/main/java/com/xpn/xwiki/plugin/skinx/LinkExtensionPlugin.java, xwiki-platform-core/xwiki-platform-skin/xwiki-platform-skin-skinx/src/test/java/com/xpn/xwiki/plugin/skinx/CssSkinExtensionPluginTest.java, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/stylesheets.vm
* XML-escape all URLs in script/link-tags.
* Do not escape URLs during assembly as helper methods add parameters with & as separator.
* Ensure that "\n" is printed after every link/script.
* Cleanup duplicate code.
I have introduced some new helper methods for code deduplication in the parent class which is only relevant for some child classes. I'm wondering if it would be better to move them into separate helper classes. What do you think?
In this code I'm following the principle to XML-escape text the moment it is inserted into an XML tag and not earlier. In my opinion this is the best approach and necessary here as some other methods that are called just add additional parameters using `&` as separator and thus escaping the `&` early just creates the mess we previously had.
Jira issue: …
=> XWIKI-19026: The <head> is full of invalid HTML <link> and <script> elements

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/misc.less, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/localePicker.js, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/po/BootstrapSelect.java
* Remove invalid child tag.
* Escape the language in both translations.
* Remove now unused CSS rule.
* Remove workaround in BootstrapSelect object.
Jira issue: https://jira.xwiki.org/browse/XWIKI-19342
=> XWIKI-19342: The locale picker generates invalid child tag in option-element

xwiki-platform-core/xwiki-platform-realtime/xwiki-platform-realtime-webjar/src/main/webjar/loader.js, xwiki-platform-core/xwiki-platform-realtime/xwiki-platform-realtime-webjar/src/main/webjar/toolbar.js, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/uicomponents/suggest/xwiki.selectize.js
* Fix invalid self-closing HTML tags, see https://jquery.com/upgrade-guide/3.5/. Note that apart from xwiki.selectize.js, this leaves single tags as-is as they should be okay.
Jira issue: https://jira.xwiki.org/browse/XWIKI-14928
=> Fixes for XWIKI-14928: Upgrade to jQuery 3.6.0

xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-wikimacro/xwiki-platform-rendering-wikimacro-store/src/test/java/org/xwiki/rendering/wikimacro/internal/DefaultWikiMacroTest.java
* Fix DefaultWikiMacroTest that still expected xhtml/1.0.
Original Jira issue: https://jira.xwiki.org/browse/XRENDERING-509
=> XRENDERING-509: Add support for HTML5 in the {{html}} Macro

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-docker/src/test/it/org/xwiki/flamingo/test/docker/EditIT.java
* Fix EditIT for additional available parsers.
Jira issue for the original issue: https://jira.xwiki.org/browse/XRENDERING-375
=> XRENDERING-375: Add a parser for HTML 5/XHTML 5

xwiki-platform-core/xwiki-platform-edit/xwiki-platform-edit-ui/src/main/resources/XWiki/InplaceEditing.xml, xwiki-platform-core/xwiki-platform-wysiwyg/xwiki-platform-wysiwyg-api/src/main/java/org/xwiki/wysiwyg/internal/cleaner/DefaultHTMLCleaner.java, xwiki-platform-core/xwiki-platform-wysiwyg/xwiki-platform-wysiwyg-api/src/main/java/org/xwiki/wysiwyg/internal/converter/DefaultHTMLConverter.java, xwiki-platform-core/xwiki-platform-wysiwyg/xwiki-platform-wysiwyg-api/src/main/java/org/xwiki/wysiwyg/script/WysiwygEditorScriptService.java, xwiki-platform-core/xwiki-platform-wysiwyg/xwiki-platform-wysiwyg-api/src/test/java/org/xwiki/wysiwyg/internal/cleaner/HTMLCleanerTest.java, xwiki-platform-core/xwiki-platform-wysiwyg/xwiki-platform-wysiwyg-api/src/test/java/org/xwiki/wysiwyg/internal/converter/DefaultHTMLConverterTest.java
* Use HTML5 for inplace editing
* Use HTML in DefaultHTMLConverter
* Configure HTMLCleaner to accept HTML5
Jira issue: https://jira.xwiki.org/browse/XWIKI-19271
This depends on xwiki/xwiki-rendering#195 (XRENDERING-375: Add a parser for HTML 5/XHTML 5).
Further, this also depends on xwiki-contrib/application-ckeditor#46 as without the changes in CKEditor this will break the editing experience.
=> XWIKI-19271: Change HTMLConverter to parse and render HTML5

xwiki-platform-core/xwiki-platform-image/xwiki-platform-image-lightbox/xwiki-platform-image-lightbox-test/xwiki-platform-image-lightbox-test-pageobjects/src/main/java/org/xwiki/image/lightbox/test/po/Lightbox.java
* fix lightboxIT#navigateThroughImages test that was failing on chrome browse
=> XWIKI-19172: Display rendered images in view mode inside a lightbox

xwiki-platform-core/xwiki-platform-index/xwiki-platform-index-api/src/main/java/org/xwiki/index/migration/R140200001XWIKI19352DataMigration.java, xwiki-platform-core/xwiki-platform-index/xwiki-platform-index-api/src/main/resources/META-INF/components.txt, xwiki-platform-core/xwiki-platform-index/xwiki-platform-index-api/src/test/java/org/xwiki/index/migration/R140200001XWIKI19352DataMigrationTest.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/store/migration/hibernate/R140200000XWIKI19352DataMigration.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/resources/META-INF/components.txt
Split the migration in two distinct steps:
- remove the xwikilink table in oldcore
- repopulate it with up to date entries in index-api
=> XWIKI-19352: Indexing of the attachments usage on the wiki

xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/objects/classes/GroupsClass.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/objects/classes/LevelsClass.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/objects/classes/ListClass.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/objects/classes/UsersClass.java, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/objects/classes/GroupsClassTest.java, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/objects/classes/LevelsClassTest.java, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/objects/classes/ListClassTest.java, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/objects/classes/UsersClassTest.java, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/web/EditFormTest.java
* Refactor ListClass#fromList to take into account multiselect
* Provide a new ListClass#fromList API with a parameter to filter out
empty values
* Provide a new ListClass#getListFromString API with a parameter to
filter out empty values
* Use those new APIS in UsersClass/GroupsClass/LevelsClass
* Add some new tests
=> XWIKI-15776: The groups displayer store values with a coma at the end

xwiki-platform-core/xwiki-platform-display/xwiki-platform-display-api/src/main/java/org/xwiki/display/internal/DocumentContentAsyncExecutor.java, xwiki-platform-core/xwiki-platform-display/xwiki-platform-display-api/src/main/java/org/xwiki/display/internal/DocumentDisplayerParameters.java, xwiki-platform-core/xwiki-platform-display/xwiki-platform-display-macro/src/main/java/org/xwiki/rendering/internal/macro/display/DisplayMacro.java, xwiki-platform-core/xwiki-platform-display/xwiki-platform-display-macro/src/test/java/org/xwiki/rendering/internal/macro/DisplayMacroTest.java, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-macros/xwiki-platform-rendering-macro-include/src/main/java/org/xwiki/rendering/internal/macro/include/IncludeMacro.java, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-macros/xwiki-platform-rendering-macro-include/src/test/java/org/xwiki/rendering/internal/macro/include/IncludeMacroTest.java
* Add the id generator as document displayer parameter.
* Adapt heading and image ids when loading the XDOM in the DocumentContentAsyncExecutor and set it on the XDOM.
* Set the id generator in the include and display macro.
Jira issue: https://jira.xwiki.org/browse/XRENDERING-6
=> XRENDERING-6: Id are not unique when included document or macro content has the same headers as the top document

xwiki-platform-core/xwiki-platform-office/xwiki-platform-office-importer/src/main/java/org/xwiki/officeimporter/internal/builder/DefaultPresentationBuilder.java, xwiki-platform-core/xwiki-platform-office/xwiki-platform-office-importer/src/test/java/org/xwiki/officeimporter/internal/builder/DefaultPresentationBuilderTest.java
* Sort slides by numeric id and not by file name.
* Extend the test to validate the bug fix.
Jira issue: https://jira.xwiki.org/browse/XWIKI-19565
=> XWIKI-19565: PowerPoint slides aren't ordered as the file imported

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/getdocuments.vm
if the "sort" parameter does not look like a property name or any other accepted value then just scrap it.
Note: this also removes the `sort` parameter if it is a comma separated list of values, like `doc.fullName, doc.date`. As the `dir` parameter to define the sort direction would only applied to the last value (I think), this is unlikely to be a use case which has been supported. Should I take this into account, anyway? (It will make the regexp to check the parameter somewhat more complicated, however.)
=> XWIKI-17568: clean sort parameter value

xwiki-platform-core/pom.xml, xwiki-platform-core/xwiki-platform-index/xwiki-platform-index-api/src/main/java/org/xwiki/index/internal/TaskExecutor.java, xwiki-platform-core/xwiki-platform-index/xwiki-platform-index-api/src/main/java/org/xwiki/index/migration/R140300000XWIKI19614DataMigration.java, xwiki-platform-core/xwiki-platform-index/xwiki-platform-index-api/src/main/resources/META-INF/components.txt, xwiki-platform-core/xwiki-platform-index/xwiki-platform-index-api/src/test/java/org/xwiki/index/internal/TaskExecutorTest.java, xwiki-platform-core/xwiki-platform-index/xwiki-platform-index-api/src/test/java/org/xwiki/index/migration/R140300000XWIKI19614DataMigrationTest.java, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/src/main/java/org/xwiki/mentions/internal/DefaultMentionsDataConsumer.java, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/src/test/java/org/xwiki/mentions/internal/DefaultMentionsDataConsumerTest.java
- Use getDocumentReferenceWithLocale instead of getDocumentReference when:
- passing the DocumentReference to the task consumers.
- resolving the previous version of a documentation during mentions analysis
- Reindex the links and attachments they are missing for localized pages
=> XWIKI-19614: The locale is ignored when indexing documents

xwiki-platform-core/xwiki-platform-image/xwiki-platform-image-lightbox/xwiki-platform-image-lightbox-test/xwiki-platform-image-lightbox-test-docker/src/test/it/org/xwiki/image/lightbox/test/ui/LightboxIT.java, xwiki-platform-core/xwiki-platform-image/xwiki-platform-image-lightbox/xwiki-platform-image-lightbox-test/xwiki-platform-image-lightbox-test-pageobjects/src/main/java/org/xwiki/image/lightbox/test/po/ImagePopover.java, xwiki-platform-core/xwiki-platform-image/xwiki-platform-image-lightbox/xwiki-platform-image-lightbox-test/xwiki-platform-image-lightbox-test-pageobjects/src/main/java/org/xwiki/image/lightbox/test/po/Lightbox.java, xwiki-platform-core/xwiki-platform-image/xwiki-platform-image-lightbox/xwiki-platform-image-lightbox-ui/src/main/resources/XWiki/Lightbox/LightboxTranslations.xml, xwiki-platform-core/xwiki-platform-image/xwiki-platform-image-lightbox/xwiki-platform-image-lightbox-ui/src/main/resources/XWiki/Lightbox/WebHome.xml, xwiki-platform-core/xwiki-platform-image/xwiki-platform-image-lightbox/xwiki-platform-image-lightbox-webjar/src/main/webjar/less/lightbox.less, xwiki-platform-core/xwiki-platform-image/xwiki-platform-image-lightbox/xwiki-platform-image-lightbox-webjar/src/main/webjar/lightbox.js
* extracted the image id, prioritizing the manually added one, and display it as part of the lightbox description
* provide a button to copy the displayed image id to clipboard
=> XWIKI-19463: Display image ids in the Lightbox

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/uicomponents/widgets/notification.css
https://jira.xwiki.org/browse/XWIKI-19637
=> XWIKI-19637: XWiki.widgets.Notification messages are hidden when a modal is opened

xwiki-platform-core/xwiki-platform-image/xwiki-platform-image-lightbox/xwiki-platform-image-lightbox-test/xwiki-platform-image-lightbox-test-pageobjects/src/main/java/org/xwiki/image/lightbox/test/po/LightboxPage.java, xwiki-platform-core/xwiki-platform-image/xwiki-platform-image-lightbox/xwiki-platform-image-lightbox-ui/src/main/resources/XWiki/Lightbox/WebHome.xml, xwiki-platform-core/xwiki-platform-image/xwiki-platform-image-lightbox/xwiki-platform-image-lightbox-webjar/src/main/webjar/less/lightbox.less, xwiki-platform-core/xwiki-platform-image/xwiki-platform-image-lightbox/xwiki-platform-image-lightbox-webjar/src/main/webjar/lightbox.js
* open the popover close to the mouse location by adding it to a container that changes position based on mouse events
Small demo:
https://user-images.githubusercontent.com/22794181/163386780-150a0b66-69a8-4579-82a2-efe82c730e23.mp4
=> XWIKI-19636: The image popup can be hard to follow on large images

xwiki-platform-core/xwiki-platform-image/xwiki-platform-image-lightbox/xwiki-platform-image-lightbox-test/xwiki-platform-image-lightbox-test-pageobjects/src/main/java/org/xwiki/image/lightbox/test/po/ImagePopover.java
XWIKI-19659: LightboxIT#navigateThroughImages is flickering
* the download attribute is no longer added on popover show event, so wait instead for the actual popover, which is now added as child to the #imagePopoverContainer element
=> XWIKI-19660: LightboxIT#playSlideshow is flickering

xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/XWikiLivedata.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/webjar/Logic.js
* Do not replace the original container but instead update it accordingly once Vue.js has been loaded.
* Remove the id from the root component as it is now on the wrapping container.
Jira issue: https://jira.xwiki.org/browse/XWIKI-19634
=> XWIKI-19634: Live Data triggers JavaScript events on a detached DOM element

xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/webjar/Logic.js
* Add the xwiki:livedata:instanceCreated event.
Jira issue: https://jira.xwiki.org/browse/XWIKI-19724
=> XWIKI-19724: LiveData should trigger an event when an instance has been created

xwiki-platform-core/xwiki-platform-store/xwiki-platform-store-filesystem-oldcore/pom.xml, xwiki-platform-core/xwiki-platform-store/xwiki-platform-store-filesystem-oldcore/src/main/java/org/xwiki/store/filesystem/internal/DefaultTemporaryAttachmentSessionsManager.java, xwiki-platform-core/xwiki-platform-store/xwiki-platform-store-filesystem-oldcore/src/test/java/org/xwiki/store/filesystem/internal/DefaultTemporaryAttachmentSessionsManagerTest.java
Jira: https://jira.xwiki.org/browse/XWIKI-19719
=> XWIKI-19719: Attachments added via copy & paste state that they've been by admin instead of the user editing the page

xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-api/pom.xml, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-api/src/main/java/org/xwiki/notifications/filters/internal/CachedModelBridge.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-api/src/main/java/org/xwiki/notifications/filters/internal/ModelBridge.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-api/src/main/java/org/xwiki/notifications/filters/internal/listener/DeleteUserEventListener.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-api/src/main/java/org/xwiki/notifications/filters/internal/listener/DeletedWikiEventListener.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-api/src/main/resources/META-INF/components.txt, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-api/src/test/java/org/xwiki/notifications/filters/internal/CachedModelBridgeTest.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-api/src/test/java/org/xwiki/notifications/filters/internal/listener/DeleteUserEventListenerTest.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-api/src/test/java/org/xwiki/notifications/filters/internal/listener/DeletedWikiEventListenerTest.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-default/pom.xml, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-default/src/main/java/org/xwiki/notifications/filters/internal/DefaultModelBridge.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-default/src/main/java/org/xwiki/notifications/filters/internal/NotificationFilterPreferenceStore.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-default/src/main/java/org/xwiki/notifications/filters/migration/R140500000XWIKI15460DataMigration.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-default/src/test/java/org/xwiki/notifications/filters/internal/DefaultModelBridgeTest.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-default/src/test/java/org/xwiki/notifications/filters/internal/NotificationFilterPreferenceStoreTest.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-default/src/test/java/org/xwiki/notifications/filters/migration/R140500000XWIKI15460DataMigrationTest.java
- Listen for deleted users and remove the corresponding notification filter preferences from the store and from the cache
- Update R140500000XWIKI15460DataMigration to also cleanup remaining notification filter preferences for previously removed users
Jira: https://jira.xwiki.org/browse/XWIKI-18397
=> XWIKI-18397: Notification filter preferences are never cleaned for deleted users

xwiki-platform-core/xwiki-platform-eventstream/xwiki-platform-eventstream-stores/xwiki-platform-eventstream-store-solr/src/main/java/org/xwiki/eventstream/store/solr/internal/SolrEventStore.java, xwiki-platform-core/xwiki-platform-eventstream/xwiki-platform-eventstream-stores/xwiki-platform-eventstream-store-solr/src/main/java/org/xwiki/eventstream/store/solr/internal/WikiDeletedListener.java, xwiki-platform-core/xwiki-platform-eventstream/xwiki-platform-eventstream-stores/xwiki-platform-eventstream-store-solr/src/test/java/org/xwiki/eventstream/store/solr/internal/EventStoreTest.java, xwiki-platform-core/xwiki-platform-extension/xwiki-platform-extension-index/src/main/java/org/xwiki/extension/index/internal/ExtensionIndexStore.java, xwiki-platform-core/xwiki-platform-extension/xwiki-platform-extension-index/src/main/java/org/xwiki/extension/index/internal/job/ExtensionIndexJob.java, xwiki-platform-core/xwiki-platform-ratings/xwiki-platform-ratings-api/src/main/java/org/xwiki/ratings/internal/SolrRatingsManager.java, xwiki-platform-core/xwiki-platform-ratings/xwiki-platform-ratings-api/src/main/java/org/xwiki/ratings/internal/averagerating/SolrAverageRatingManager.java, xwiki-platform-core/xwiki-platform-ratings/xwiki-platform-ratings-api/src/test/java/org/xwiki/ratings/internal/SolrRatingsManagerTest.java, xwiki-platform-core/xwiki-platform-ratings/xwiki-platform-ratings-api/src/test/java/org/xwiki/ratings/internal/averagerating/SolrAverageRatingManagerTest.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/java/org/xwiki/search/solr/SolrUtils.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/java/org/xwiki/search/solr/internal/DefaultSolrUtils.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/test/java/org/xwiki/search/solr/internal/DefaultSolrUtilsTest.java
* Escape empty strings as "" for equality queries
* Match missing values when the value is `null` (previously, it matched the string "null")
Jira issue: https://jira.xwiki.org/browse/XWIKI-19682
=> XWIKI-19682: Solr ParseException from SimpleEventQuery when comparing with equality to empty string

xwiki-platform-core/xwiki-platform-image/xwiki-platform-image-lightbox/xwiki-platform-image-lightbox-webjar/src/main/webjar/lightbox.js
• don't hide the popover immediately on image mousemove since popover('show') will close it anyway
• on popover mouseleave hide it with a delay, since it's easy to go out without wanting to
=> XWIKI-19745: Going diagonally towards the image popover closes it

xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authorization/xwiki-platform-security-authorization-bridge/src/main/java/org/xwiki/security/authorization/internal/DefaultSecurityEntryReader.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authorization/xwiki-platform-security-authorization-bridge/src/test/java/org/xwiki/security/authorization/internal/DefaultSecurityEntryReaderTest.java
* Prevent the DefaultSecurityEntryReader to throw an exception if the
wiki does not exist anymore: just handle the exception as if the
returned owner is null, as it seems to have been planned for
=> XWIKI-19806: BridgeAuthorizationManager errors when deleting a subwiki  which cause errors when creating another subwiki

xwiki-platform-core/xwiki-platform-bridge/src/main/java/org/xwiki/bridge/event/AbstractDocumentEvent.java, xwiki-platform-core/xwiki-platform-bridge/src/main/java/org/xwiki/bridge/event/DocumentDeletedEvent.java, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/delete.vm, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/refactoring_macros.vm, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/renameStep1.vm, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-docker/src/test/it/org/xwiki/flamingo/test/docker/DeletePageIT.java, xwiki-platform-core/xwiki-platform-index/xwiki-platform-index-test/xwiki-platform-index-test-docker/src/test/it/org/xwiki/index/test/ui/docker/DeletedDocsIT.java, xwiki-platform-core/xwiki-platform-index/xwiki-platform-index-test/xwiki-platform-index-test-pageobjects/src/main/java/org/xwiki/index/test/po/DeletedDocsPage.java, xwiki-platform-core/xwiki-platform-index/xwiki-platform-index-test/xwiki-platform-index-test-pageobjects/src/main/java/org/xwiki/index/test/po/RestoreDocumentConfirmationModal.java, xwiki-platform-core/xwiki-platform-index/xwiki-platform-index-ui/src/main/resources/XWiki/DeletedDocuments.xml, xwiki-platform-core/xwiki-platform-index/xwiki-platform-index-ui/src/main/resources/XWiki/DeletedDocumentsJSON.xml, xwiki-platform-core/xwiki-platform-legacy/xwiki-platform-legacy-oldcore/src/main/aspect/com/xpn/xwiki/web/DeleteActionCompatibilityAspect.aj, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/web/DeleteAction.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/web/DeleteSpaceAction.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/resources/ApplicationResources.properties, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/main/java/org/xwiki/refactoring/internal/job/DeleteJob.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/main/java/org/xwiki/refactoring/internal/listener/AutomaticRedirectCreatorListener.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/main/java/org/xwiki/refactoring/internal/listener/BackLinkUpdaterListener.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/main/java/org/xwiki/refactoring/internal/script/DefaultRequestFactory.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/main/java/org/xwiki/refactoring/job/DeleteRequest.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/test/java/org/xwiki/refactoring/internal/listener/AutomaticRedirectCreatorListenerTest.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/test/java/org/xwiki/refactoring/internal/listener/BackLinkUpdaterListenerTest.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/test/java/org/xwiki/refactoring/script/RefactoringScriptServiceTest.java, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/po/DeletePageConfirmationPage.java, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/po/LiveTableElement.java, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/js/xwiki/delete.js
Cherry-pick of commits from https://github.com/xwiki/xwiki-platform/pull/1843
* added option in the UI to select a new target document and to enable for it the update backlinks and/or the create of an automatic redirect
* set the selected options on the delete request and update AutomaticRedirectCreatorListener and BackLinkUpdaterListener to consider also the DocumentDeletedEvent
* add the possibility to restore a document which was recreated at the original location to include the usecase when a user wants to restore a document after a redirect was added (delete the recreated document and restore the original version)
* add unit tests and functional tests
=> XWIKI-19653: Ability to redirect deleted page link to a new page

xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-default/src/main/java/org/xwiki/notifications/filters/migration/R140401000XWIKI15460DataMigration.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-default/src/test/java/org/xwiki/notifications/filters/migration/R140401000XWIKI15460DataMigrationTest.java
Move the check of whether the execution should be continued based on the configuration and if it is the main wiki that is updated in hibernateMigrate because the missing columns are not yet updated in shouldExecute.
=> XWIKI-19855: SQL errors when upgrading XWiki from pre 14.x to 14.4.1

xwiki-platform-distribution/xwiki-platform-distribution-war-legacydependencies/pom.xml
Replace xwiki-rendering-transformation-macro with xwiki-rendering-legacy-transformation-macro in xwiki-platform-distribution-war-legacydependencies.
See https://github.com/xwiki/xwiki-rendering/pull/216 for the xwiki-rendering part of this work.
=> XRENDERING-664: Allow macros to have several categories

xwiki-platform-core/xwiki-platform-office/xwiki-platform-office-importer/src/main/resources/document-formats.js
https://jira.xwiki.org/browse/XWIKI-19818
* Use the appropriate filter for odt documents
=> XWIKI-19818: ODT export doesn't produce 'real' odt documents but 'office html' (?) documents

xwiki-platform-core/xwiki-platform-oldcore/src/main/java/org/xwiki/doc/tasks/XWikiDocumentIndexingTask.java
Jira: https://jira.xwiki.org/browse/XWIKI-19875
=> XWIKI-19875: TaskData.type values are duplicated in memory

xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-default/src/main/java/org/xwiki/notifications/filters/migration/R140401000XWIKI15460DataMigration.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-default/src/test/java/org/xwiki/notifications/filters/migration/R140401000XWIKI15460DataMigrationTest.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-notifiers/xwiki-platform-notifications-notifiers-default/pom.xml, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-notifiers/xwiki-platform-notifications-notifiers-default/src/main/java/org/xwiki/notifications/notifiers/internal/UserEventDispatcher.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-notifiers/xwiki-platform-notifications-notifiers-default/src/test/java/org/xwiki/notifications/notifiers/internal/UserEventDispatcherTest.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-default/src/main/java/org/xwiki/security/authentication/internal/DefaultResetPasswordManager.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-default/src/test/java/org/xwiki/security/authentication/internal/DefaultResetPasswordManagerTest.java, xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-api/pom.xml, xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-api/src/main/java/org/xwiki/user/UserException.java, xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-default/pom.xml, xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-default/src/main/java/org/xwiki/user/internal/DefaultUserManager.java, xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-default/src/main/java/org/xwiki/user/internal/document/CurrentUserManager.java, xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-default/src/main/java/org/xwiki/user/internal/document/DocumentUserManager.java, xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-default/src/test/java/org/xwiki/user/internal/DefaultUserManagerTest.java, xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-default/src/test/java/org/xwiki/user/internal/document/CurrentUserManagerTest.java, xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-default/src/test/java/org/xwiki/user/internal/document/DocumentUserManagerTest.java, xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-script/src/main/java/org/xwiki/user/script/UserScriptService.java
- Add a control for the existence of the user's wiki on org.xwiki.user.internal.document.DocumentUserManager.exists(org.xwiki.user.UserReference)
- When removing user's notifications in R140401000XWIKI15460DataMigration, verify if their is still notifications to remove before removing unknown user's notifications
Jira: https://jira.xwiki.org/browse/XWIKI-19902
=> XWIKI-19902: Potential error log caused by not existing user during R140401000XWIKI15460 migration

xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/po/AttachmentsPane.java
* add fix for [org.xwiki.test.ui.CompareVersionsTest](https://github.com/xwiki/xwiki-platform/blob/master/xwiki-platform-distribution/xwiki-platform-distribution-flavor/xwiki-platform-distribution-flavor-test/xwiki-platform-distribution-flavor-test-ui/src/test/it/org/xwiki/test/ui/CompareVersionsTest.java#L160), since the test was failing with ElementNotInteractableException even if the element was clickable (visible and enabled)
The failure is not reproducible on docker tests that use the `AttachmentsPane#deleteAttachmentByFileByName` so moving this test to docker should remove the need of `JavascriptExecutor` in the future
=> XWIKI-13454: Add pagination for Attachments

xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-test/xwiki-platform-administration-test-pageobjects/src/main/java/org/xwiki/administration/test/po/ForgotUsernamePage.java, xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-test/xwiki-platform-administration-test-pageobjects/src/main/java/org/xwiki/administration/test/po/ResetPasswordPage.java, xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-ui/src/main/resources/XWiki/ForgotUsername.xml, xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-ui/src/main/resources/XWiki/ResetPassword.xml, xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-ui/src/main/resources/XWiki/ResetPasswordComplete.xml, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/login.vm, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-api/src/main/java/org/xwiki/security/authentication/AuthenticationAction.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-api/src/main/java/org/xwiki/security/authentication/AuthenticationResourceReference.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-default/src/main/java/org/xwiki/security/authentication/internal/DefaultResetPasswordManager.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-default/src/main/java/org/xwiki/security/authentication/internal/resource/AuthenticationResourceReferenceHandler.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-default/src/main/java/org/xwiki/security/authentication/internal/resource/AuthenticationResourceReferenceResolver.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-default/src/main/java/org/xwiki/security/authentication/internal/resource/AuthenticationResourceReferenceSerializer.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-default/src/test/java/org/xwiki/security/authentication/internal/DefaultResetPasswordManagerTest.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-default/src/test/java/org/xwiki/security/authentication/internal/resource/AuthenticationResourceReferenceHandlerTest.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-default/src/test/java/org/xwiki/security/authentication/internal/resource/AuthenticationResourceReferenceResolverTest.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-default/src/test/java/org/xwiki/security/authentication/internal/resource/AuthenticationResourceReferenceSerializerTest.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-script/src/main/java/org/xwiki/security/authentication/script/AuthenticationScriptService.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-script/src/test/java/org/xwiki/security/authentication/script/AuthenticationScriptServiceTest.java, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/forgotusername.vm, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/resetpasswordinline.vm, xwiki-platform-distribution/xwiki-platform-distribution-flavor/xwiki-platform-distribution-flavor-test/xwiki-platform-distribution-flavor-test-webstandards/src/test/it/org/xwiki/test/webstandards/framework/DefaultValidationTest.java
This provides two things: the fix of the bug by handling a wiki part in
the URLs for authentication resource, and a rename of the authentication
resource action (forgot becomes retrieveusername and reset becomes
resetpassword).
Note that the latter changes are not backward compatible, but they were
still unstable (since 13.1RC1).
=> XWIKI-19591: Local users of subwikis can't recover password or username

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/uorgsuggest.vm
- When controlling access, resolve the user page reference relatively to the wiki reference it belongs to instead of the current wiki reference
=> XWIKI-20007: When sharing a page from a subwiki, even non viewable users get suggested

xwiki-platform-core/xwiki-platform-dashboard/xwiki-platform-dashboard-ui/src/main/resources/Dashboard/XWikiUserDashboardSheet.xml, xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-profile/xwiki-platform-user-profile-ui/src/main/resources/XWiki/XWikiUserPreferencesSheet.xml, xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-profile/xwiki-platform-user-profile-ui/src/main/resources/XWiki/XWikiUserProfileSheet.xml, xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-profile/xwiki-platform-user-profile-ui/src/main/resources/XWiki/XWikiUserSheet.xml
This pull request:
* Adds a pencil icon in profile edit link
* Updates the profile edit link style with btn btn-xs classes and dedicated CSS rules
The contrast has been checked with Firefox accessibility tools (7.29 : 1)
=> XWIKI-18003: Pencil buttons on profile page are not consistent with the used icon theme and missing contrast

xwiki-platform-core/xwiki-platform-lesscss/xwiki-platform-lesscss-default/src/main/java/org/xwiki/lesscss/internal/cache/CacheKeyFactory.java
This is an attempt to implement XWIKI-19832. Not sure this is the right approach nor if the list of excluded parameters is correct but a review and a recommendation on how to implement the feature is welcome.
Remarks:
* The list of excluded parameters was obtained empirically by observing the existing request parameters when computing the cache key of a LESS resource, there might be other parameters to exclude from the list but I don't know how to get the exhaustive list.
* A possible downside of this approach is that the request parameters are in this case always taken into account when `withContext` is `true`. However a LESS resource is not meant to receive request parameters others than the ones already used for computing the cache key and the excluded ones, is it?
=> XWIKI-19832: Take into account the request parameters when caching a LESS SSX

xwiki-platform-core/xwiki-platform-tree/xwiki-platform-tree-war/src/main/webapp/resources/uicomponents/widgets/tree.js, xwiki-platform-core/xwiki-platform-tree/xwiki-platform-tree-webjar/src/main/webjar/tree.js, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/treeview.vm
* move the inline js code to and external file so the dataeditors.js will append it in HTML head
* make sure the moved code is active only when it necessary (when data.instance.settings.xwiki.fieldName is defined)
=> XWIKI-20060: Database Tree property changes are not saved anymore in object mode

xwiki-platform-tools/xwiki-platform-tool-jetty/xwiki-platform-tool-jetty-resources/src/main/resources/start_xwiki_debug.sh
Jira: https://jira.xwiki.org/browse/XWIKI-20086
=> XWIKI-20086: Jetty debug address does not allow debug from a different host on Java 11

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/layoutvars.vm, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/api/XWiki.java
* use the getSpacePreferenceFor API that takes a spaceReference as a parameter to correctly read preferences for a space of any level
=> XWIKI-20078: Wrong panels preferences displayed and edited in the administration of a page when it's not a top level page

xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-ui/src/main/resources/CKEditor/InlineEditor.xml
This fixes the overlap we see between the two toolbars when editing inline, hopefully in all cases.
This needs manual testing.
=> CKEDITOR-470: Fix the CKEditor and XWiki's save toolbars overlap for inline editing

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/js/xwiki/xwiki.js
* move code to plain js, since jquery blocks are executed too late
* use createContextualFragment to preserve the script tag attributes
=> XWIKI-20112: Custom headers are not registered when loaded to soon

xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/webjar/Logic.js
Trigger an event whenever entries are displayed in a live data. 
This code needs to be better tested, right now I only tested on attachments live data with a JSX containing:
```
require(['jquery'], function ($) {
var initialize = function () {
console.log('initialize called');
$('#docAttachments').find('a.move-attachment').on('click', function (event) {
event.preventDefault();
console.log("Property attached!");
});
}
$(document).on('xwiki:livedata:entriesUpdated', initialize);
});
```
=> [Misc] Trigger an event when an entry is updated on LD

xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-ui/src/main/resources/CKEditor/MacroService.xml, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-transformations/xwiki-platform-rendering-transformation-macro/pom.xml, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-transformations/xwiki-platform-rendering-transformation-macro/src/main/java/org/xwiki/rendering/internal/transformation/macro/XWikiMacroTransformationConfiguration.java, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-transformations/xwiki-platform-rendering-transformation-macro/src/test/java/org/xwiki/rendering/internal/transformation/macro/XWikiMacroTransformationConfigurationTest.java, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-xwiki/src/main/java/org/xwiki/rendering/script/RenderingScriptService.java, xwiki-platform-tools/xwiki-platform-tool-configuration-resources/src/main/resources/xwiki.properties.vm
- Introduce getHiddenMacroCategories in RenderingScriptService
- Use getHiddenMacroCategories in the CKEditor macro dialog implementation
- Document rendering.transformation.macro.hiddenCategories in xwiki.properties.vm
Jira: https://jira.xwiki.org/browse/XWIKI-19993
=> XWIKI-19993: Allow admins to configure the macros

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/js/xwiki/xwiki.js
* make sure that scripts are executes in the order they are added
* don't override the async attribute if defined
* use hasAttribute to verify if the async attribute is defined
=> XWIKI-20112: Custom headers are not registered when loaded to soon (#1917)

.github/dependabot.yml
Fixed a typing error by changing `hep` to `helps` in dependabot.yml
=> Fix typo in a comment in dependabot.yml

xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-ui/src/main/resources/CKEditor/ImageEditorService.xml
Jira: https://jira.xwiki.org/browse/XWIKI-20123
*Before*
*After*
=> XWIKI-20123: XWiki image editor modal radio buttons are badly spaced

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/javascript.vm, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/js/xwiki/prototypeJSPatches.js
* save and restore the native Array.from implementation
=> XWIKI-20183: Prototype.js breaks the standard Array.from method

xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins/src/main/resources/xwiki-macro/plugin.js
Jira: https://jira.xwiki.org/browse/XWIKI-20167
Result on Chrome:
PS: Working as well on Firefox and Edge.
=> XWIKI-20167: The cursor is not visible after a macro that supports inline is added standalone on chrome

xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/doc/XWikiDocument.java, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/doc/XWikiDocumentTest.java, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/test/MockitoOldcore.java
* Set the archive to null value instead of setting it to an empty archive in case of clone
* Add some more comment to explain why
* Add a unit test to ensure that getXWikiDocumentArchive(context) behave as expected even after a clone
=> XWIKI-20208: XWikiDocument#getDocumentArchive(context) always return an empty archive

xwiki-platform-core/pom.xml, xwiki-platform-core/xwiki-platform-attachment/xwiki-platform-attachment-ui/pom.xml, xwiki-platform-core/xwiki-platform-attachment/xwiki-platform-attachment-ui/src/main/resources/XWiki/AttachmentSelector.xml, xwiki-platform-core/xwiki-platform-attachment/xwiki-platform-attachment-ui/src/main/resources/XWiki/AttachmentSelectorTranslations.xml, xwiki-platform-core/xwiki-platform-attachment/xwiki-platform-attachment-ui/src/test/java/org/xwiki/attachment/AttachmentSelectorPageTest.java, xwiki-platform-core/xwiki-platform-attachment/xwiki-platform-attachment-ui/src/test/resources/icons.properties, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-ui/src/main/resources/CKEditor/FileUploader.xml, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/org/xwiki/store/TemporaryAttachmentSessionsManager.java, xwiki-platform-core/xwiki-platform-store/xwiki-platform-store-filesystem-oldcore/pom.xml, xwiki-platform-core/xwiki-platform-store/xwiki-platform-store-filesystem-oldcore/src/main/java/org/xwiki/store/filesystem/StoreFilesystemOldcoreException.java, xwiki-platform-core/xwiki-platform-store/xwiki-platform-store-filesystem-oldcore/src/main/java/org/xwiki/store/filesystem/internal/DefaultTemporaryAttachmentSessionsManager.java, xwiki-platform-core/xwiki-platform-store/xwiki-platform-store-filesystem-oldcore/src/main/java/org/xwiki/store/filesystem/internal/StoreFilesystemOldcoreException.java, xwiki-platform-core/xwiki-platform-store/xwiki-platform-store-filesystem-oldcore/src/main/java/org/xwiki/store/script/TemporaryAttachmentsScriptService.java, xwiki-platform-core/xwiki-platform-store/xwiki-platform-store-filesystem-oldcore/src/test/java/org/xwiki/store/filesystem/internal/DefaultTemporaryAttachmentSessionsManagerTest.java, xwiki-platform-core/xwiki-platform-store/xwiki-platform-store-filesystem-oldcore/src/test/java/org/xwiki/store/script/TemporaryAttachmentsScriptServiceTest.java
Jira: https://jira.xwiki.org/browse/XWIKI-19702
- Use the temporary attachment store to save newly uploaded attachments
- Allow users with view right to access the upload button
- List temporary attachments from the current document in the attachment selection modal
TODO:
Related bug:
- https://jira.xwiki.org/browse/XWIKI-20181
=> XWIKI-19702: Attachment selector upload should not save immediately the page

xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-api/src/main/java/org/xwiki/security/authentication/RetrieveUsernameException.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-api/src/main/java/org/xwiki/security/authentication/RetrieveUsernameManager.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-default/src/checkstyle/checkstyle-suppressions.xml, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-default/src/main/java/org/xwiki/security/authentication/internal/AuthenticationMailSender.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-default/src/main/java/org/xwiki/security/authentication/internal/DefaultResetPasswordManager.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-default/src/main/java/org/xwiki/security/authentication/internal/DefaultRetrieveUsernameManager.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-default/src/main/java/org/xwiki/security/authentication/internal/R140600000XWIKI19869DataMigrationListener.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-default/src/main/resources/META-INF/components.txt, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-default/src/test/java/org/xwiki/security/authentication/internal/AuthenticationMailSenderTest.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-default/src/test/java/org/xwiki/security/authentication/internal/DefaultResetPasswordManagerTest.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-default/src/test/java/org/xwiki/security/authentication/internal/DefaultRetrieveUsernameManagerTest.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-default/src/test/java/org/xwiki/security/authentication/internal/R140600000XWIKI19869DataMigrationListenerTest.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-script/src/main/java/org/xwiki/security/authentication/script/AuthenticationScriptService.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-script/src/test/java/org/xwiki/security/authentication/script/AuthenticationScriptServiceTest.java, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/forgotusername.vm
Note this is the same PR as #1939 but for branch 14.4.x. 
Creating it since it could be merged before #1939 as we're about to release 14.9RC1 and we shouldn't commit unstable things on master.
=> XWIKI-20138: On private wikis, users cannot recover their username

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/copy.vm, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/delete.vm, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/rename.vm
Added breadcrumbs to `copy.vm`, `delete.vm` and `rename.vm` templates.
For now, the page location displayed in the breadcrumbs is always the original page. This makes sense, because the url always stays to the original page too, as the action is bound to this page.
However, this can be a bit misleading in some situations, like after a rename / move operation, where the breadcrumb is now associated with the old path of the page. Maybe in that case it would be better to modify the breadcrumbs path to the renamed / moved page (even if the template is still bound to the original page location). wdyt?
=> XWIKI-13399 delete UI does not have breadcrumbs, so going back to top level is not intuitive

xwiki-platform-core/pom.xml, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/org/xwiki/store/TemporaryAttachmentSessionsManager.java, xwiki-platform-core/xwiki-platform-store/xwiki-platform-store-filesystem-oldcore/src/main/java/org/xwiki/store/filesystem/internal/DefaultTemporaryAttachmentSessionsManager.java, xwiki-platform-core/xwiki-platform-store/xwiki-platform-store-filesystem-oldcore/src/test/java/org/xwiki/store/filesystem/internal/DefaultTemporaryAttachmentSessionsManagerTest.java
Example usage of this new API: https://github.com/xwiki-contrib/application-changerequest/pull/74/commits/0a116bc826dd61649d0a429a0816672466b0f15f
=> XWIKI-20282: Provide an API allowing to attach an XWikiAttachment as temporary attachment

xwiki-platform-core/xwiki-platform-csrf/pom.xml, xwiki-platform-core/xwiki-platform-csrf/src/main/java/org/xwiki/csrf/internal/DefaultCSRFToken.java
- Replace several lines of synchronized code by a call to computeIfAbsent on a ConcurrentHashMap
- Code coverage ratio lowered because we do as much with less code
Note: applicable on master/14.4.x/13.10.x
=> [misc] Simplify token generation in DefaultCSRFToken

xwiki-platform-core/xwiki-platform-annotation/xwiki-platform-annotation-core/src/main/java/org/xwiki/annotation/rights/AnnotationRightService.java, xwiki-platform-core/xwiki-platform-annotation/xwiki-platform-annotation-io/src/main/java/org/xwiki/annotation/rights/internal/XWikiAnnotationRightService.java, xwiki-platform-core/xwiki-platform-annotation/xwiki-platform-annotation-rest/src/main/java/org/xwiki/annotation/rest/internal/AbstractAnnotationRESTResource.java, xwiki-platform-core/xwiki-platform-annotation/xwiki-platform-annotation-rest/src/main/java/org/xwiki/annotation/rest/internal/AnnotationsRESTResource.java, xwiki-platform-core/xwiki-platform-annotation/xwiki-platform-annotation-rest/src/main/java/org/xwiki/annotation/rest/internal/SingleAnnotationRESTResource.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/doc/XWikiDocument.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/org/xwiki/store/TemporaryAttachmentSessionsManager.java, xwiki-platform-core/xwiki-platform-store/xwiki-platform-store-filesystem-oldcore/src/main/java/org/xwiki/store/filesystem/internal/DefaultTemporaryAttachmentSessionsManager.java, xwiki-platform-core/xwiki-platform-store/xwiki-platform-store-filesystem-oldcore/src/test/java/org/xwiki/store/filesystem/internal/DefaultTemporaryAttachmentSessionsManagerTest.java
* Implement attaching the temporary attachments to document in TemporaryAttachmentSessionManager
* Use the new method in AnnotationRestResource after parsing the parameter
=> XWIKI-18989: Cannot upload attachments in annotation

xwiki-platform-core/xwiki-platform-edit/xwiki-platform-edit-ui/src/main/resources/XWiki/InplaceEditing.xml
This allows respecting the standard for query serialization when fields have several values, as is the case for the xaction parameter, and to do this serialization using a browser-provided feature. the field name is repeated for each value instead of having comma-separated
values: key=val1,val2 becomes key=val1&key=val2.
:warning: Some caveats:
- instead of erasing existing fields, the code now cumulates values. I don't know if there can be unintented consequences
- I don't know what to test to verify if the code does not break anything. The nominal case of editing a page works okay on my end
=> XWIKI-20338: Serialize form data using FormData when in-place editing

xwiki-platform-core/pom.xml, xwiki-platform-core/xwiki-platform-wysiwyg/xwiki-platform-wysiwyg-api/src/main/java/org/xwiki/wysiwyg/converter/RequestParameterConversionResult.java, xwiki-platform-core/xwiki-platform-wysiwyg/xwiki-platform-wysiwyg-api/src/main/java/org/xwiki/wysiwyg/converter/RequestParameterConverter.java, xwiki-platform-core/xwiki-platform-wysiwyg/xwiki-platform-wysiwyg-api/src/main/java/org/xwiki/wysiwyg/internal/converter/DefaultRequestParameterConverter.java
* Provide an API to allow use RequestParameterConverter and let consumer of the API decides how to handle errors
=> XWIKI-20399: RequestParameterConverter should not always handle errors with ServletResponse

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/delete.vm, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/refactoring_macros.vm, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/renameStep1.vm, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-docker/src/test/it/org/xwiki/flamingo/test/docker/DeletePageIT.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/resources/ApplicationResources.properties, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/po/DeletePageConfirmationPage.java, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/js/xwiki/delete.js
* display the backlinks URL at the beginning of the panel, not after the new target is selected
* deprecate translation key
* delete declaration of $message since it wasn't used anymore
Note that I kept that idea of having a link that redirects the user to a backlinks page rather than displaying the full list on the current panel, which is also consistent with the rename operation https://www.xwiki.org/xwiki/bin/download/Documentation/UserGuide/Features/DocumentLifecycle/WebHome/RenameConfirmFlamingoAdvanced.png?rev=1.2
The backlinks panel when no target is selected:
The backlinks panel with a selected target:
=> XWIKI-20426: The backlinks section of the delete UI no longer displayed backlink documents

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/misc.less
* make sure that livetable pagesize has the right width value, since in this case the xform class was altering the desired value
=> XWIKI-20472: Results drop-down box is not properly displayed in document Delete view

xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-ui/src/main/resources/XWiki/Mentions/MentionsMacro.xml
* using `##` is a common practice to handle possible spacing breakage in Velocity code
=> XWIKI-20500: Whitespace to the right of a mention is not properly displayed when the mention is inside a text, in view mode: appears stuck to the text

xwiki-platform-core/xwiki-platform-image/xwiki-platform-image-processing/xwiki-platform-image-processing-api/pom.xml, xwiki-platform-core/xwiki-platform-image/xwiki-platform-image-processing/xwiki-platform-image-processing-api/src/main/java/com/xpn/xwiki/internal/plugin/image/ThumbnailatorImageProcessor.java, xwiki-platform-core/xwiki-platform-image/xwiki-platform-image-processing/xwiki-platform-image-processing-api/src/test/java/com/xpn/xwiki/internal/plugin/image/ThumbnailatorImageProcessorTest.java, xwiki-platform-core/xwiki-platform-image/xwiki-platform-image-processing/xwiki-platform-image-processing-plugin/pom.xml, xwiki-platform-core/xwiki-platform-image/xwiki-platform-image-processing/xwiki-platform-image-processing-plugin/src/main/java/com/xpn/xwiki/plugin/image/ImagePlugin.java, xwiki-platform-core/xwiki-platform-image/xwiki-platform-image-processing/xwiki-platform-image-processing-plugin/src/test/java/com/xpn/xwiki/plugin/image/ImagePluginTest.java
* Force the image size in ThumbnailatorImageProcessor
* Only preserve the aspect ratio when one of the sizes is missing, or it is requested, not also when one of the sizes is larger than the original.
* Add tests.
Jira issue: https://jira.xwiki.org/browse/XWIKI-20532
=> XWIKI-20532: Server-side image resizing always preserves the aspect ratio

xwiki-platform-core/xwiki-platform-office/xwiki-platform-office-importer/pom.xml, xwiki-platform-core/xwiki-platform-office/xwiki-platform-office-importer/src/main/java/org/xwiki/officeimporter/internal/converter/DefaultOfficeConverter.java, xwiki-platform-core/xwiki-platform-office/xwiki-platform-office-importer/src/main/resources/document-formats.js, xwiki-platform-core/xwiki-platform-office/xwiki-platform-office-importer/src/test/java/org/xwiki/officeimporter/internal/converter/DefaultOfficeConverterTest.java
* Upgrade dependency
* Use interface DocumentConverter instead of now final class LocalConverter in DefaultOfficeConverter to allow mocking
* Refactoring of document-formats.js based on official file to ease future upgrades and integrate changes
=> XWIKI-20137: Upgrade to jodconverter 4.4.5

xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-page/src/main/java/org/xwiki/test/page/LocalizationSetup.java
* Fix LocalizationSetup to properly match method with varargs following changes in Mockito 5
Note: to be merged once the upgrade of Mockito 5 is performed on xwiki-commons
=> XCOMMONS-2610: Upgrade to Mockito 5

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/js/xwiki/table/livetable.js
* Undo encoding of "|" in certain cases to recover the parameters.
Jira issue: https://jira.xwiki.org/browse/XWIKI-20571
=> XWIKI-20571: Livetable parameters cannot be recovered with URI encoding

xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/internal/skin/InternalSkinManager.java, xwiki-platform-tools/xwiki-platform-tool-packager-plugin/src/main/java/org/xwiki/tool/packager/internal/PackagerComponentManagerInitializer.java, xwiki-platform-tools/xwiki-platform-tool-packager-plugin/src/main/resources/META-INF/components.txt
* Use a Provider<URLConfiguration> in InternalSkinManager to avoid dependency issues with tool packager plugin
* Add a new ComponentManagerInitializer in the tool packager plugin to handle unregistering the stuff we don't need for packaging
Note that I only tested this by building  `xwiki-platform-distribution-flavor-data-hsqldb` so I might miss impacts on the other mojo than packager.
=> XWIKI-20578: tool packager plugin ouputs lots of errors related to missing URLConfiguration component

xwiki-platform-core/xwiki-platform-url/xwiki-platform-url-api/src/main/java/org/xwiki/url/URLSecurityManager.java, xwiki-platform-core/xwiki-platform-url/xwiki-platform-url-default/src/main/java/org/xwiki/url/internal/DefaultURLSecurityManager.java, xwiki-platform-core/xwiki-platform-url/xwiki-platform-url-default/src/test/java/org/xwiki/url/internal/DefaultURLSecurityManagerTest.java
* Avoid double-encoding when trying to repair a URI by escaping % that belongs to percent encoded byte and replacing them afterwards
* Add new various test cases related to reparation of URI with %
=> XWIKI-20615: $response.sendRedirect repair too much

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/breadcrumbs.less, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/locationPicker_macros.vm, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/uicomponents/widgets/locationPicker.css
Jira: https://jira.xwiki.org/browse/XWIKI-19140
- Changes to the locationpicker template: moving the block for the location actions after the breadcrumbs (same as visual) , which allows for the focus to go in the expected order when tabbing.
- The style changes in the .css are there to put the objects back at their original position.
=> XWIKI-19140: Fix order location actions and breadcrumbs while creating new page

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/rendercontent.vm, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/test/java/org/xwiki/web/DisplaycontentPageTest.java
* Set the content type to text/plain when the output syntax is not HTML
* Add a page test
It would be possible to move the code to `contentvars.vm`, it just seemed strange to set the content type in this template (on the other hand, the rendered document could do the same). Any opinions?
Jira issue: https://jira.xwiki.org/browse/XWIKI-20290
=> XWIKI-20290: Set correct content type in rendercontent.vm

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/documentTags.vm, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/test/java/org/xwiki/web/DocumentTagsTest.java
Summary:
When there are no tags:
When user **has edit rights**, ```Tags [+]``` is displayed.
When user **does NOT have edit rights**, nothing is displayed at all.
When there are tags, it is displayed to all type of users irrespective of their edit rights.
(But user with edit rights can see the ```+``` sign as well :)
=> XWIKI-17588: Display some text when there's no tag for a page

xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-ui/src/main/resources/AppWithinMinutes/Title.xml, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/editmeta.vm
* we should check first if the current space is expecting the title to be mandatory
* using #getSpacePreference(String) will eventually fallback on a #getXWikiPreference() method
=> XWIKI-17325  The page title field cannot be made mandatory at space level

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/breadcrumbs.less, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/uicomponents/widgets/locationPicker.css
**Jira:** https://jira.xwiki.org/browse/XWIKI-20670
Fixed a regression introduced in 
https://github.com/xwiki/xwiki-platform/pull/2049/commits/3580ea9292c002b5166a07212b7d102efb8bfc8a
The css selectors were not valid.
=> XWIKI-20670: Location icons are displayed smaller and without grey background in Create Page view

xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins/src/main/resources/xwiki-source/plugin.js
Jira: https://jira.xwiki.org/browse/XWIKI-20724
Required for https://jira.xwiki.org/browse/NCAPP-68
Example of use by an extension:
```javascript
$(document).on('xwiki:ckeditor:convertHTML', function(event, data) {
data.example = 1;
});
```
=> XWIKI-20724: Allow extensions to add parameters to the html conversion request

xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-macros/xwiki-platform-rendering-macro-toc/pom.xml, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-macros/xwiki-platform-rendering-macro-toc/src/main/java/org/xwiki/rendering/internal/macro/toc/XWikiTocMacro.java, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-macros/xwiki-platform-rendering-macro-toc/src/main/resources/toc.css
Jira: https://jira.xwiki.org/browse/XRENDERING-708
Depends on https://github.com/xwiki/xwiki-rendering/pull/254
Apply a css style on toc item with no direct children of the level right below (e.g., an h3 following an h1), based on the `nodirectchild` css class.
Related forum post: https://forum.xwiki.org/t/annotating-table-of-content-entries-skipped-level/12070
=> XRENDERING-708: Table of content does not support level skipping

xwiki-platform-core/pom.xml, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/objects/BaseCollection.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/objects/BaseElement.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/objects/BaseProperty.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/objects/ElementInterface.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/objects/LargeStringProperty.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/objects/ListProperty.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/objects/classes/BaseClass.java, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/objects/BaseObjectTest.java, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/objects/classes/BaseClassTest.java, xwiki-platform-core/xwiki-platform-store/xwiki-platform-store-merge/xwiki-platform-store-merge-api/pom.xml, xwiki-platform-core/xwiki-platform-store/xwiki-platform-store-merge/xwiki-platform-store-merge-api/src/main/java/com/xpn/xwiki/doc/merge/MergeConfiguration.java, xwiki-platform-core/xwiki-platform-store/xwiki-platform-store-merge/xwiki-platform-store-merge-api/src/main/java/org/xwiki/store/merge/MergeManagerResult.java, xwiki-platform-core/xwiki-platform-store/xwiki-platform-store-merge/xwiki-platform-store-merge-default/src/main/java/org/xwiki/store/merge/internal/DefaultMergeManager.java, xwiki-platform-core/xwiki-platform-store/xwiki-platform-store-merge/xwiki-platform-store-merge-default/src/test/java/org/xwiki/store/merge/internal/DefaultMergeManagerTest.java
* Provide a new configuration option for allowing to fallback on another version
* Use that new configuration in all merge operations
* Change the signature of the BaseProperty#merge method to be able to reference the configuration instance
=> XWIKI-20702: Allow to chose the fallback version in case of conflict when performing merge

xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-ui/src/main/resources/XWiki/Notifications/Code/NotificationsDisplayerUIX.xml
**Jira:** https://jira.xwiki.org/browse/XWIKI-20745
* Changed the css containing presentation to a less and used a color theme variable
* Removed the .9 opacity that reduced contrast on most themes.
Now this notification count is a `badge` with the color pattern of a `danger button`.
**View: **
*Before*
*After*
**Note:** The solution chosen depends on the compliance of the active color theme danger buttons to WCAG 2.1 AA contrast minimums. If the buttons pass it, this badge will pass too. This makes this solution dependant of https://github.com/xwiki/xwiki-platform/pull/2101
=> XWIKI-20745: Notification count color lacks contrast

xwiki-platform-core/xwiki-platform-extension/xwiki-platform-extension-handlers/xwiki-platform-extension-handler-xar/src/test/java/org/xwiki/extension/xar/internal/handler/WikiEventListenerTest.java, xwiki-platform-core/xwiki-platform-oldcore/pom.xml, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/XWiki.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/org/xwiki/security/authservice/AbstractXWikiAuthServiceWrapper.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/org/xwiki/security/authservice/XWikiAuthServiceComponent.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/org/xwiki/security/authservice/internal/AuthServiceConfiguration.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/org/xwiki/security/authservice/internal/AuthServiceConfigurationClassInitializer.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/org/xwiki/security/authservice/internal/AuthServiceConfigurationInvalidator.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/org/xwiki/security/authservice/internal/AuthServiceManager.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/org/xwiki/security/authservice/internal/StandardXWikiAuthServiceComponent.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/org/xwiki/security/authservice/script/AuthServiceScriptService.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/resources/ApplicationResources.properties, xwiki-platform-core/xwiki-platform-oldcore/src/main/resources/META-INF/components.txt, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-ui/pom.xml, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authentication/xwiki-platform-security-authentication-ui/src/main/resources/XWiki/Authentication/Administration.xml
* introduce a role to expose an authenticator as component
* refactor XWiki#getAuthService() to rely on components by default
* add a section in the authentication administration to
* show information about the current authenticator
* allow changing it (when it's not an authenticator set through xwiki.cfg or injected dynamically)
* as a bonus of being configured at wiki level: it's possible to use different auth services on different wikis (unconfigured subwiki inherit main wiki configuration which inherit xwiki.properties configuration)
A backport of the API is provided through https://github.com/xwiki-contrib/authservice-backport because existing authenticators needs to implement this new role, and they are obviously not going to upgrade to 15.3 anytime soon.
Before someone ask: the …
=> XWIKI-20548: Allow choosing the authenticator at runtime

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-theme/xwiki-platform-flamingo-theme-ui/src/main/resources/FlamingoThemes/Iceberg.xml
**Jira:** https://jira.xwiki.org/browse/XWIKI-20680
**PR changes:**
Colors on the flamingo colorTheme `Iceberg`:
*  \@navbar-default-bg : #3E7CBC → #3E79BC  (slightly darker blue)
*  \@link-color : #3173B5 → #2F6FAF (slightly darker blue)
* \@gray-light:#777777 → #727272 (slightly darker gray)
* \@breadcrumb-color:#777777 → #727272 (slightly darker gray)
* \@btn-primary-bg: #3e7cbc→ #386da7 (darker blue)
* \@text-muted: \@light-gray → \@gray
*  \@btn-success-bg: \@brand-success (#56b881) → #31754f (much darker green)
*  \@brand-danger: #d9534f  → #ca302c (darker red)
See https://forum.xwiki.org/t/fixing-a11y-contrast-issues-on-the-main-view/11917 for more details.
=> XWIKI-20680: Contrast issues on the default theme

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/variablesInit.vm, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-ui/src/main/resources/XWiki/Notifications/Code/NotificationsDisplayerUIX.xml
**Jira:** https://jira.xwiki.org/browse/XWIKI-20736
* Added redefinition of some bootstrap variables when initializing a wiki without a theme.
**View:**
=> XWIKI-20736: Contrast issues on a themeless wiki 

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/menus_macros.vm, xwiki-platform-core/xwiki-platform-oldcore/src/main/resources/ApplicationResources.properties
**Jira:** https://jira.xwiki.org/browse/XWIKI-20707
* Removed the separator at the start of the navbar left.
This doesn't change any display, and has little to no sense, since there is no element before (and none after). 
The use of separators should be avoided, since it's in most cases a sign that 2 distinct lists could be created.
This separator was first introduced in https://github.com/xwiki/xwiki-platform/commit/0681b42fd3ac050aebd9777bacbe5c3ffcc17d9b .
=> XWIKI-20707: Remove <ul> separator in navbar

xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/LivedataDropdownMenu.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/LivedataEntrySelectorInfoBar.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/LivedataPagination.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/displayers/DisplayerActions.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/layouts/LayoutLoader.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/layouts/cards/LayoutCards.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/layouts/table/LayoutTable.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/panels/LivedataAdvancedPanelFilterEntry.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/panels/LivedataAdvancedPanelSort.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/utilities/XWikiLoader.vue
**Jira:** https://jira.xwiki.org/browse/XWIKI-20781
* Replaced hard coded values with color theme values, trying to match the closest: value-wise (considering the Iceberg color theme) and then semantically-wise.
* Replaced some semi-transparent elements with full colors (from the theme), some uses of transparency seemed superfluous
**View:**
**Note:**
Those changes will only change code quality and not accessibility of the interface as long as https://jira.xwiki.org/browse/XWIKI-20680 is not closed.
=> XWIKI-20781: Livedata colors are hard coded

xwiki-platform-core/xwiki-platform-image/xwiki-platform-image-lightbox/xwiki-platform-image-lightbox-webjar/src/main/webjar/less/lightbox.less
**Jira:** https://jira.xwiki.org/browse/XWIKI-19469
* Reduced margins and increased size of elements up to 44*44
See jira for details about the choice of solution.
**View:**
With tabbing order displayed by Firefox accessibility tool, we can see that the interactive elments cover most of the popup:
=> XWIKI-19469: The size of the image download and open Lightbox links is too small

xwiki-platform-core/xwiki-platform-like/xwiki-platform-like-test/xwiki-platform-like-test-pageobjects/src/main/java/org/xwiki/like/test/po/LikeButton.java, xwiki-platform-core/xwiki-platform-like/xwiki-platform-like-ui/src/main/resources/XWiki/Like/LikeUIX.xml
**Jira:** https://jira.xwiki.org/browse/XWIKI-19139
* Changed the `like-button`element nature from `div` to `button`.
___
Accessibility works properly now: accessible through keyboard and activable with keyboard using standard button interactions.
=> XWIKI-19139: Like button can't be focused by tabulator

xwiki-platform-core/xwiki-platform-export/xwiki-platform-export-pdf/xwiki-platform-export-pdf-test/xwiki-platform-export-pdf-test-content/src/main/resources/PDFExportIT/FormFields.xml
* The HTML wasn't valid. The region was opened with \<dd> and closed with \<dl>.
**WCAG report that highlights this typo in tests:** 
> WCAG warnings in the test class [org.xwiki.export.pdf.test.ui.AllITs]:
> Validation in the test method [formFields]
> Check for [org.xwiki.test.ui.po.ViewPage] at [http://xwikiweb:8080/xwiki/bin/view/PDFExportIT/FormFields].
> \<dt> and \<dd> elements must be contained by a \<dl>
> Description: Ensures \<dt> and \<dd> elements are contained by a \<dl>
> Help URL: https://dequeuniversity.com/rules/axe/4.6/dlitem?application=axeAPI
> Impact: serious
> Tags: cat.structure, wcag2a, wcag131
> HTML element: 
> 	\<dd>
> 	\</dd>
> Selector: [dd:nth-child(1)]
> Fix any of the following:
>   Description list item does not have a \<dl> parent element
=> [Misc] Fixed formFields structure in functional tests

xwiki-platform-core/xwiki-platform-attachment/xwiki-platform-attachment-ui/src/main/resources/XWiki/AttachmentSelector.xml
https://jira.xwiki.org/browse/XWIKI-20884
=> XWIKI 20884: Pass a file in AttachmentSelector instead of a file input to fix file size and mimetype verification

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/menus_macros.vm, xwiki-platform-core/xwiki-platform-oldcore/src/main/resources/ApplicationResources.properties
The HTML validator returned warnings such as:
```
Validating HTML5 validity for [http://127.0.0.1:8080/xwiki/bin/view/WikiManager/Translations] executed with credentials Admin:admin
Warning at 209:49 Possible misuse of “aria-label”. (If you disagree with this warning, file an issue report or send e-mail to www-validator@w3.org.)
```
[The warning on the CI](https://ci.xwiki.org/job/XWiki/job/xwiki-platform/job/master/6680/testReport//org.xwiki.test.webstandards.framework/DefaultValidationTest/Platform_Builds___main___distribution___flavor_test_webstandards___Build_for_Flavor_Test___Webstandards______/)
This was caused by the PR https://github.com/xwiki/xwiki-platform/pull/2120 merged in 15.3.
I tested out a screen reader to see how it would react in regards to this list. NVDA on Windows …
=> [Misc] Remove list label in navbar

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/attachment_macros.vm, xwiki-platform-core/xwiki-platform-like/xwiki-platform-like-api/src/main/resources/templates/likers.vm, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-ui/src/main/resources/Main/SolrUserFacet.xml, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/getusers.vm, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/macros.vm
https://jira.xwiki.org/browse/XWIKI-20824
* Added an alt text to user avatars.
* The change to solve the PR is in **`getusers.vm`**, but other files were changed too to solve the same problem in other parts of the UI. The solution is the same since the structure around those images is the same.
* All values are changed to `""` because this `img` in this context is purely decorative: it only helps the user to understand faster what account the anchor next to the picture is pointing to. For a non sighted user, adding a label would only "repeat" the name twice (once for the image, and another for the anchor content). See the jira ticket comments for more details.
=> XWIKI-20824: Administration user images must have an alternate text

xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-ui/src/main/resources/XWiki/QuickSearchUIX.xml
* Updated the implementation of the button 'disabled' state to fix webstandards issues raised previously at https://ci.xwiki.org/job/XWiki/job/xwiki-platform/job/master/6701/testReport/junit/org.xwiki.test.webstandards.framework/DefaultValidationTest/Platform_Builds___main___distribution___flavor_test_webstandards___Build_for_Flavor_Test___Webstandards______/ This failure was caused by https://github.com/xwiki/xwiki-platform/pull/2163.
=> XWIKI-20733: Top navigation search section has two tab indexes

xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/XWiki.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/doc/XWikiDocumentArchive.java, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/doc/XWikiDocumentArchiveTest.java
JIRA: https://jira.xwiki.org/browse/XWIKI-20919
Note that it targets LTS. 
* Add checks in XWiki#deleteDocumentVersions and XWikiDocumentArchive#removeVersions to perform removal is the range of version is not empty and to avoid reseting the entire archive in such case
* Perform some refactoring in XWikiDocumentArchive to document properly getNodes and make it more clear on the meaning of its arguments. Rename #getNearestFullVersion also since the name is wrong: that method does not return the nearest full version, it returns the next one
=> XWIKI-20919: The document is deleted when it has only one version if a revision deletion action is triggered with a non-existing version

xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins/src/main/webjar/xwiki-upload/plugin.js, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-ui/src/main/resources/CKEditor/FileUploader.xml
Jira: https://jira.xwiki.org/browse/XWIKI-20932
Currently, we decide if we are in the presence of a pasted image based on its name (i.e., `image.png`) which proved to be inaccurate and locale dependent.
Instead, I propose to toggle a `duringPaste` flag based on two listeners, `beforePaste` and `afterPaste`, respectively turning setting the flag `true` and `false`.
We append a timestamp and a random integer to the filename when  `duringPaste` is `true`.
Note: Not fully cleaned up, I'd like to have some opinion of the approach before.
=> XWIKI-20932: Images pasted from clipboard are attached with 'grafik.png' name on Firefox with German language

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/js/xwiki/table/livetable.js
**Jira:** https://jira.xwiki.org/browse/XWIKI-19142
* Removed the `text` attribute generated in the options for the livetable select element.
No changes to UI, only some in the generated HTML.
=> XWIKI-19142: Livetable select options have invalid attribute "text"

xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-api/src/main/java/org/xwiki/notifications/GroupingEventManager.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-api/src/main/java/org/xwiki/notifications/NotificationConfiguration.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-api/src/main/java/org/xwiki/notifications/internal/DefaultNotificationConfiguration.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-notifiers/xwiki-platform-notifications-notifiers-api/pom.xml, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-notifiers/xwiki-platform-notifications-notifiers-api/src/main/java/org/xwiki/notifications/notifiers/email/NotificationEmailGroupingStrategy.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-notifiers/xwiki-platform-notifications-notifiers-api/src/main/java/org/xwiki/notifications/notifiers/internal/email/grouping/DefaultNotificationEmailGroupingStrategy.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-notifiers/xwiki-platform-notifications-notifiers-api/src/main/java/org/xwiki/notifications/notifiers/internal/email/grouping/OneMailPerCompositeEmailGroupingStrategy.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-notifiers/xwiki-platform-notifications-notifiers-api/src/main/java/org/xwiki/notifications/notifiers/internal/email/grouping/SeparatedMentionEmailGroupingStrategy.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-notifiers/xwiki-platform-notifications-notifiers-api/src/main/java/org/xwiki/notifications/notifiers/internal/email/live/LiveNotificationEmailListener.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-notifiers/xwiki-platform-notifications-notifiers-api/src/main/java/org/xwiki/notifications/notifiers/internal/email/live/LiveNotificationEmailManager.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-notifiers/xwiki-platform-notifications-notifiers-api/src/main/java/org/xwiki/notifications/notifiers/internal/email/live/LiveNotificationEmailSender.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-notifiers/xwiki-platform-notifications-notifiers-api/src/main/java/org/xwiki/notifications/notifiers/internal/email/live/PrefilteringLiveNotificationEmailDispatcher.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-notifiers/xwiki-platform-notifications-notifiers-api/src/main/resources/META-INF/components.txt, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-notifiers/xwiki-platform-notifications-notifiers-api/src/test/java/org/xwiki/notifications/notifiers/internal/email/grouping/DefaultNotificationEmailGroupingStrategyTest.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-notifiers/xwiki-platform-notifications-notifiers-api/src/test/java/org/xwiki/notifications/notifiers/internal/email/grouping/OneMailPerCompositeEmailGroupingStrategyTest.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-notifiers/xwiki-platform-notifications-notifiers-api/src/test/java/org/xwiki/notifications/notifiers/internal/email/grouping/SeparatedMentionEmailGroupingStrategyTest.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-notifiers/xwiki-platform-notifications-notifiers-default/pom.xml, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-notifiers/xwiki-platform-notifications-notifiers-default/src/main/java/org/xwiki/notifications/notifiers/internal/email/AbstractMimeMessageIterator.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-notifiers/xwiki-platform-notifications-notifiers-default/src/main/java/org/xwiki/notifications/notifiers/internal/email/DefaultPeriodicMimeMessageIterator.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-notifiers/xwiki-platform-notifications-notifiers-default/src/main/java/org/xwiki/notifications/notifiers/internal/email/live/DefaultLiveMimeMessageIterator.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-notifiers/xwiki-platform-notifications-notifiers-default/src/test/java/org/xwiki/notifications/notifiers/internal/email/DefaultPeriodicMimeMessageIteratorTest.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-sources/src/main/java/org/xwiki/notifications/sources/internal/DefaultGroupingEventManager.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-sources/src/main/java/org/xwiki/notifications/sources/internal/DefaultParametrizedNotificationManager.java, xwiki-platform-tools/xwiki-platform-tool-configuration-resources/src/main/resources/xwiki.properties.vm
JIRA: https://jira.xwiki.org/browse/XWIKI-17034
Previous work was about introducing strategies to group events for creating composite events. This work is about strategies for chosing how many mails should be sent for each composite event to notify by email. Historically the strategy was hardcoded and consisted in putting all composite events in the same email. Here we provide different strategies: the previous one, but also a strategy allowing to send one email per composite event, and another one allowing to send a separate email specifically for mentions.
That work also improves previous API to use a clear UserReference instead of a String which is vague.
=> XWIKI-17034: Allow to define different grouping strategy for notifications

xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-test/xwiki-platform-ckeditor-test-docker/src/test/it/org/xwiki/ckeditor/test/ui/ImagePluginIT.java, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-test/xwiki-platform-ckeditor-test-pageobjects/src/main/java/org/xwiki/ckeditor/test/po/LinkSelectorModal.java, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-test/xwiki-platform-ckeditor-test-pageobjects/src/main/java/org/xwiki/ckeditor/test/po/image/ImageDialogEditModal.java, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-test/xwiki-platform-ckeditor-test-pageobjects/src/main/java/org/xwiki/ckeditor/test/po/image/edit/ImageDialogAdvancedEditForm.java, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-test/xwiki-platform-ckeditor-test-pageobjects/src/main/java/org/xwiki/ckeditor/test/po/image/edit/ImageDialogStandardEditForm.java, xwiki-platform-core/xwiki-platform-image/xwiki-platform-image-style/xwiki-platform-image-style-api/src/main/java/org/xwiki/image/style/internal/rendering/AbstractCaptionedImageChainingListener.java, xwiki-platform-core/xwiki-platform-image/xwiki-platform-image-style/xwiki-platform-image-style-api/src/main/java/org/xwiki/image/style/internal/rendering/CaptionedImageParseChainingListener.java, xwiki-platform-core/xwiki-platform-image/xwiki-platform-image-style/xwiki-platform-image-style-api/src/main/java/org/xwiki/image/style/internal/rendering/CaptionedImageParseListenerProvider.java, xwiki-platform-core/xwiki-platform-image/xwiki-platform-image-style/xwiki-platform-image-style-api/src/main/java/org/xwiki/image/style/internal/rendering/CaptionedImageRenderChainingListener.java, xwiki-platform-core/xwiki-platform-image/xwiki-platform-image-style/xwiki-platform-image-style-api/src/main/java/org/xwiki/image/style/internal/rendering/CaptionedImageRenderListenerProvider.java, xwiki-platform-core/xwiki-platform-image/xwiki-platform-image-style/xwiki-platform-image-style-api/src/test/resources/figure/linkedImage.test
* Handle images that are wrapped inside links for figure styles.
* Refactor the code to move common code inside the chaining listeners to a base class.
* Add a functional test to verify that image captions and links can actually be used together via CKEditor.
Jira issue: https://jira.xwiki.org/browse/XRENDERING-670
=> XRENDERING-670: Image captions cannot be used in combination with links on images

xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/WCAGContext.java
Changes to the status of the WCAG rules that are currently not violated. From this point on, all rules set to true will make the build fail when they are violated. The build will only fail on an accessibility regression. See the [XWiki WCAG testing page](https://dev.xwiki.org/xwiki/bin/view/Community/WCAGTesting#HTesting) for more details about the consequences of these changes.
Because of https://jira.xwiki.org/browse/XWIKI-20909, in order to pass tests, we temporarily deactivate the `scrollable-region-focusable` fails.
As of https://ci.xwiki.org/job/XWiki%20Environment%20Tests/job/xwiki-platform/job/master/255/, there are only a few rules that fail through tests:
- aria-allowed-attr 5 violations
- aria-required-children 65 violations
- label 79 violations
- duplicate-id 8 violations
- …
=> [Misc] Accessibility rules update

xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins/src/main/webjar/xwiki-macro/macroEditor.js, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins/src/main/webjar/xwiki-macro/macroSelector.js, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins/src/main/webjar/xwiki-macro/macroService.js, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins/src/main/webjar/xwiki-macro/macroWizard.css, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins/src/main/webjar/xwiki-macro/plugin.js, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins/src/main/webjar/xwiki-slash/plugin.js, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-ui/src/main/resources/CKEditor/EditSheet.xml, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-ui/src/main/resources/CKEditor/Translations.xml
Jira: https://jira.xwiki.org/browse/XWIKI-19982
This PR introduces a "{" shortcut to quickly insert Macros from the WYSIWYG editor.
It also skips the macro parameters dialog when no mandatory fields are present to reduce interactions (The user can still edit them afterwards).
Here's a preview of the feature:
=> XWIKI-19982: Add ability to add a macro by using the keyboard

xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/layouts/table/LayoutTableHeaderNames.vue
**Jira:** https://jira.xwiki.org/browse/XWIKI-21008
* Added `role=presentation` on both of the buttons that trigger the dragging behaviour.
Successfully passed:
* `mvn clean install -f xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/ -Pdocker,integration-tests,quality -Dxwiki.test.ui.wcag=true`
* `mvn clean install -f xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-test/ -Pdocker,integration-tests,quality -Dxwiki.test.ui.wcag=true`
=> XWIKI-21008: Livedata table headers buttons should not be read out

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-theme/xwiki-platform-flamingo-theme-ui/src/main/resources/FlamingoThemesCode/ThemeSheet.xml, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-theme/xwiki-platform-flamingo-theme-ui/src/main/resources/FlamingoThemesCode/Translations.xml
**Jira:** https://jira.xwiki.org/browse/XWIKI-20973
* Added a localized label to the iframe
In the document shown above, an Axe-core analysis with Axe devtool doesn't report any WCAG violation from the iframe.
I could not find many references to this element in tests. The only one is a pageobject that's generated using the id of the element (`iframe`) that I left unchanged, so no test should be failed because of this PR.
This label is generated in javascript, so we create a new l10n javascript module. It might have been possible to generate it in velocity and not have one extra HTTP request to avoid loading this very small module.
=> XWIKI-20973: Color theme edit frame must have an accessible name

xwiki-platform-core/xwiki-platform-scheduler/xwiki-platform-scheduler-ui/src/main/resources/Scheduler/WebHome.xml
**Jira:** https://jira.xwiki.org/browse/XWIKI-21001
* Changed the class of the label in order to make it visible to screen readers and not just unusable.
* Replaced the input default value with a placeholder
Passed successfully: 
* `mvn clean install -f xwiki-platform-core/xwiki-platform-scheduler/xwiki-platform-scheduler-ui/ -Pdocker,integration-tests,quality -Dxwiki.test.ui.wcag=true`
* `mvn clean install -f xwiki-platform-core/xwiki-platform-scheduler/xwiki-platform-scheduler-test/ -Pdocker,integration-tests,quality -Dxwiki.test.ui.wcag=true`
=> XWIKI-21001: Job scheduler creation form name field is not labelled

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/attachmentsinline.vm, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-sources/src/main/java/org/xwiki/notifications/sources/internal/DefaultParametrizedNotificationManager.java, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/importinline.vm
**Jira:** https://jira.xwiki.org/browse/XWIKI-21000
* Updated the class of the labels so they can be seen by screen reader users
Passed successfully:
* `mvn clean install -f xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/ -Pdocker,integration-tests,quality`
* `mvn clean install -f xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/ -Pdocker,integration-tests,quality  `
* `mvn clean install -f xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/ -Pdocker,integration-tests`
=> XWIKI-21000: Administration Import upload input field is not labelled

xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/pom.xml
We currently have [issues with WCAG tests on the CI environment tests](https://ci.xwiki.org/job/XWiki%20Environment%20Tests/job/xwiki-platform/job/master/261/), and I found that it was caused by a dependency not being up-to-date. I noticed there's dependabot on xwiki-platform, but I don't know why it wouldn't bump https://mvnrepository.com/artifact/com.deque.html.axe-core/selenium that we depend on in xwiki-platform-test-ui . 
It would be great if it could start PRs for bumping this dependency's versions, is there something to fix in [the POM](https://github.com/xwiki/xwiki-platform/blob/0414805d43c29a72a31fca1fb075fdafd0c1a133/xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/pom.xml#L78) ?
=> [Misc] Bump axe-core for selenium from 4.6.0 to 4.7.0

xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authorization/xwiki-platform-security-authorization-api/src/main/java/org/xwiki/security/authorization/cache/internal/DefaultSecurityCache.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authorization/xwiki-platform-security-authorization-api/src/main/java/org/xwiki/security/authorization/cache/internal/DefaultSecurityCacheLoader.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authorization/xwiki-platform-security-authorization-api/src/test/java/org/xwiki/security/authorization/DefaultAuthorizationManagerIntegrationTest.java
* Load the full group hierarchy for shadow entries.
* Refactor the group loading code.
* Add a test for this scenario.
* Refactor group listing in the security cache to be safe from concurrent modifications.
=> XWIKI-21013: Access rights aren't applied after nested group member changes in subwiki

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/macros.vm
**Jira:** https://jira.xwiki.org/browse/XWIKI-16150
Yesterday, a PR was merged: https://github.com/xwiki/xwiki-platform/pull/2149.
However, it brought in some webstandard fails: https://ci.xwiki.org/job/XWiki/job/xwiki-platform/job/master/6746/testReport/org.xwiki.test.webstandards.framework/DefaultValidationTest/Platform_Builds___main___distribution___flavor_test_webstandards___Build_for_Flavor_Test___Webstandards______/
Here is a fix to those fails.
* Replaced the `aria-description` with `aria-describedby`
* `aria-description` is not yet in the aria standards (in the draft for ARIA 1.3 though), so we fall back onto the very similar solution that is `aria-describedby`.
=> XWIKI-16150: Make livetable suggest filters accessible

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/delete.vm, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/restore.vm, xwiki-platform-core/xwiki-platform-oldcore/src/main/resources/ApplicationResources.properties
**Jira:** https://jira.xwiki.org/browse/XWIKI-20972
EDIT: A commit message https://github.com/xwiki/xwiki-platform/pull/2215/commits/bb81586d9c450d8dae3644557c480331c3370fe5 does not follow best practices, please squash this PR when merging.
* Added labels for the dropdowns, with an escaped translation.
No view changes.
This hsould also fix https://jira.xwiki.org/browse/XWIKI-20991. 
The issues are very similar but were reported differently.
Didn't trigger the reported WCAG warnings when running:
* `mvn clean install -f xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-docker/ -Pdocker,integration-tests -Dxwiki.test.ui.wcag=true -Dit.test=DeletePageIT#deletePageWithUsedClass`
* `mvn clean install -f …
=> XWIKI-20972: Delete page children tab dropdown toggler has no accessible name

xwiki-platform-core/pom.xml, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/documentTags.vm, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/uicomponents/suggest/suggest.js, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/uicomponents/viewers/tags.css, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/uicomponents/viewers/tags.js
**Jira:** https://jira.xwiki.org/browse/XWIKI-21083
* Now using  `javascript:void(0)` instead of `null` for an empty URL
* (extra Accessibility) Updated the DOM to properly generate the suggest element
* (extra Accessibility) Updated style to avoid visual changes related to the DOM changes
Used keyboard only to choose tags. It'd be similar with a mouse.
https://up1.xwikisas.com/#0ig--RpKFzgBJ3ES2Yd6Ew
It's not a good thing to have an anchor with an empty URL, so there is no perfectly clean solution to make those and I chose to go with the `javascript:void(0)` which has some impact on performance, very minimal but still here.
The better technical solution would have been to replace the anchor with a button in the case there's no URL, however it would have brought a lot of changes in the …
=> XWIKI-21083: Tag suggest feature is broken

xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authorization/xwiki-platform-security-authorization-api/src/main/java/org/xwiki/security/authorization/cache/internal/DefaultSecurityCache.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authorization/xwiki-platform-security-authorization-api/src/main/java/org/xwiki/security/authorization/cache/internal/IllegalCacheStateException.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authorization/xwiki-platform-security-authorization-api/src/test/java/org/xwiki/security/authorization/cache/internal/DefaultSecurityCacheTest.java
* Add a reference map to store entries that are needed for the hierarchy but that are no longer in the cache.
* Use weak references for children to allow children to just disappear and to allow the GC to remove the parts of the hierarchy that are no longer referenced by the cache.
* Don't trigger hierarchical cache invalidation when an entry is removed from the cache.
* Fix adding shadow parents in the security cache test.
* Modify the tests to expect the new behavior of not triggering hierarchical removal when entries are removed from the cache.
Jira issue: https://jira.xwiki.org/browse/XWIKI-21039
=> XWIKI-21039: Don't dispose security cache entries hierarchically when the cache is full

xwiki-platform-core/xwiki-platform-panels/xwiki-platform-panels-ui/src/main/resources/Panels/Applications.xml
**Jira:** https://jira.xwiki.org/browse/XWIKI-20843
* Replaced the anchor for _more applications_ in the Applications panel with a button.
* Updated style
* Added semantics to the disclosure
**View:**
Before PR:
After PR:
The button has the same style when the disclosure is closed.
**Demo:** (made before the last changes on style, but still very similar even on style)
https://up1.xwikisas.com/#NdrhBiSPlXXJNnwWHWfPtA
**Notes:**
* This section is visible only by admins and not regular users.
* For regular users, the section appears and then gets hidden. It was not very noticeable but with a blue button it's way easier to notice this behavior. I couldn't find the code responsible for hiding the section so I didn't fix this. 
https://up1.xwikisas.com/#504lX2oFtkkPm8M9w-L7XQ
=> XWIKI-20843: Application Panel "More Applications" dropdown is not accessible

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/editactions.vm
**Jira:** https://jira.xwiki.org/browse/XWIKI-21019
## PR Changes
* Changed the class of the label from `hidden` to `sr-only`
No visual change
=> XWIKI-21019: Inplace edit summary form lacks a visible accessible name

xwiki-platform-core/xwiki-platform-menu/xwiki-platform-menu-ui/src/main/resources/Menu/MenuMacro.xml, xwiki-platform-core/xwiki-platform-menu/xwiki-platform-menu-ui/src/main/resources/Menu/MenuTranslations.xml
**Jira:** https://jira.xwiki.org/browse/XWIKI-19128
* Added an escaped and translated textual content to the menu.
* Added an aria-controls attribute for improved semantics
We can just add this content to an already existing element that was empty (for no reason? probably forgot to fill it up after https://github.com/xwiki/xwiki-platform/commit/b22c0a82bf65f9e4d2d84fadad4e7d5bada37b25 ).
No visual change
=> XWIKI-19128: burger menu does not have a description

xwiki-platform-core/xwiki-platform-invitation/xwiki-platform-invitation-ui/src/main/resources/Invitation/InvitationConfig.xml
**Jira:** https://jira.xwiki.org/browse/XWIKI-20984
* Updated decline message color to follow color theme (danger color)
It was a hardcoded color, which is against the code style. However we could argue that the color theme should not influence the style of the invitation sent. It's part of the UI here, so it's important to change, and I don't think it'd have nefarious consequences to follow codestyle here.
=> XWIKI-20984: Invitation decline link lacks contrast

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/variablesInit.vm, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-theme/xwiki-platform-flamingo-theme-ui/src/main/resources/FlamingoThemes/Iceberg.xml
**Jira:** https://jira.xwiki.org/browse/XWIKI-20987
* Fixed the 'None' block text color
Updated on Iceberg color theme, and for the absence of color theme (triggered on accessibility tests) The change in value is from `#999999` to  `#727272`.
=> XWIKI-20987: Admin Navigation Panel excluded page 'None' lacks contrast

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/macros.vm
**Jira:** https://jira.xwiki.org/browse/XWIKI-21104
* Added a space between the classes for large panels
We can see that the edit mode (right) panels now follow the proper style for panels, just like view mode (left).
The classes are now properly space separated.
=> XWIKI-21104: Panel background color from the color theme is not kept for the edit mode panels, which can break contrast

xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-profile/xwiki-platform-user-profile-ui/src/main/resources/XWiki/XWikiUserPreferencesSheet.xml
**Jira:** https://jira.xwiki.org/browse/XWIKI-20990
* Fixed web standard error on view mode
The 'for' attribute of the label did not point to any id in view mode.
Edit mode (unchanged):
View mode: no `for` attribute on the label
=> XWIKI-20990: User profile select for showing hidden elements lacks an accessible name

xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/WCAGContext.java
EDIT: <s>**Merge after the 15.6 release, this is not an urgent matter and can wait 15.7RC1** :slightly_smiling_face: </s>
**Do not cherrypick for 15.6 or backport. :)**
Changes to the status of the WCAG rules that are currently not violated. From this point on, all rules set to true will make the build fail when they are violated. The build will only fail on an accessibility regression. See the [XWiki WCAG testing page](https://dev.xwiki.org/xwiki/bin/view/Community/Testing/WCAGTesting#HTesting) for more details about the consequences of these changes.
As of https://ci.xwiki.org/job/XWiki%20Environment%20Tests/job/xwiki-platform/job/master/299/, there are only a few rules that fail through tests:
- aria-allowed-attr 5 violations
- aria-required-children 65 violations
- label 63 violations …
=> Misc: Accessibility rules update

xwiki-platform-core/xwiki-platform-invitation/xwiki-platform-invitation-ui/src/main/resources/Invitation/InvitationCommon.xml, xwiki-platform-core/xwiki-platform-invitation/xwiki-platform-invitation-ui/src/main/resources/Invitation/InvitationMembersCommon.xml, xwiki-platform-core/xwiki-platform-oldcore/src/main/resources/ApplicationResources.properties
**Jira:** https://jira.xwiki.org/browse/XWIKI-20997
* Added a label to the checkbox input field
* Added an id to the memo field, in order for its label to be paired properly
Passed the build: 
* `mvn clean install -f xwiki-platform-core/xwiki-platform-invitation/xwiki-platform-invitation-ui -Pdocker,integration-tests,quality -Dxwiki.test.ui.wcag=true`
=> XWIKI-20997: Invitation displayActionConfirmationForm displays unlabelled form elements

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-theme/xwiki-platform-flamingo-theme-test/xwiki-platform-flamingo-theme-test-docker/src/test/it/org/xwiki/flamingo/test/ui/FlamingoThemeIT.java, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-theme/xwiki-platform-flamingo-theme-ui/src/main/resources/FlamingoThemes/Charcoal.xml
https://jira.xwiki.org/browse/XWIKI-20982
* Made the Charcoal.xml link color a bit darker for contrast
* Updated the custom values used in the test suite to avoid breaking contrast needs.
* This PR also fixes  [XWIKI-20983](https://jira.xwiki.org/browse/XWIKI-20983)
* The charcoal change was made to pass **all** contrast checks in this test suite. It wasn't mentioned in the test, but this fix would have been needed at one point anyways. This change just increases the contrast between backgrounds and the Charcoal link color:
_Previous (left) and new (right) Charcoal colortheme link color_ 
Passed:
* mvn clean install -f xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-theme/xwiki-platform-flamingo-theme-ui/ -Pdocker,integration-tests,quality
* mvn clean install -f …
=> XWIKI-20982: Drawer elements in the color theme editor lack contrast

xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-ui/src/main/resources/AppWithinMinutes/LiveTableEditSheet.xml
https://jira.xwiki.org/browse/XWIKI-20988
* Changed the `for` attribute of the label.
* Linked the \<select> element with its description
***No visual change***
Before the PR vvv
After the PR vvv
The label used to be linked to the input that stays hidden no matter what AFAICS in the code and in tests. A hidden input doesn't need any label: 
> Inputs with the type attribute value of hidden (e.g., type="hidden"). These inputs are hidden and unavailable for user input. They therefore need no label. 
from [Axe documentation](https://dequeuniversity.com/rules/axe/4.4/label)
I decided to go a bit further than fix the error reported on Jira and link the description to the select too since it's already there.
An axe core check on the page screenshoted above didn't return any WCAG violation …
=> XWIKI-20988: Livetable edit sheet available column select lacks a name

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/uicomponents/wizard/wizard.css
https://jira.xwiki.org/browse/XWIKI-20974
* Removed the opacity from wizard 'done' steps.
* This PR is incomplete, it relies on the *currently unmerged* fixes in https://github.com/xwiki/xwiki-platform/pull/2261. It will stay as a draft until this fix for XWIKI-20867 is merged (if the fix for XWIKI-20867 is closed, close this PR).
vvv Before fixes in this PR and https://github.com/xwiki/xwiki-platform/pull/2261
vvv After fixes in this PR and https://github.com/xwiki/xwiki-platform/pull/2261
=> XWIKI-20974: AWM create application wizard steps lack contrast

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/macros.vm
https://jira.xwiki.org/browse/XWIKI-20891
This is a PR to fix a UI regression introduced in https://github.com/xwiki/xwiki-platform/pull/2182 . More precisely, the regression changes were introduced in https://github.com/xwiki/xwiki-platform/commit/bcd341777cc54503603a51be015dfd329085ae57 .
* Removed the label from the list, for UI purpose.
Before this PR (regression on the UI)
After this PR
Passes axe core page tests without triggering a violation.
=> XWIKI-20891: Rich select input is not accessible

xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins/src/main/webjar/xwiki-slash/plugin.js, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-test/xwiki-platform-ckeditor-test-docker/src/test/it/org/xwiki/ckeditor/test/ui/QuickActionsIT.java, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-test/xwiki-platform-ckeditor-test-pageobjects/src/main/java/org/xwiki/ckeditor/test/po/AutocompleteDropdown.java
JIRA: https://jira.xwiki.org/browse/XWIKI-21062
This PR fixes a bug where clicking (rather than pressing enter) on a drop-down triggering Quick Action would
only show the triggering text without opening the new drop-down.
Preview of the fix:
Thanks.
=> XWIKI-21062: Pickers are not displayed properly on some Quick Actions on Windows

xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins/src/main/config/bundleConfiguration.json, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins/src/main/webjar/xwiki-icon/iconService.js, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins/src/main/webjar/xwiki-icon/plugin.js, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins/src/main/webjar/xwiki-slash/plugin.js, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-test/xwiki-platform-ckeditor-test-docker/src/test/it/org/xwiki/ckeditor/test/ui/AllIT.java, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-test/xwiki-platform-ckeditor-test-docker/src/test/it/org/xwiki/ckeditor/test/ui/QuickActionsIT.java, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-ui/src/main/resources/CKEditor/Translations.xml, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-webjar/src/main/webjar/config.js, xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-ui/src/main/resources/IconThemesCode/IconPicker.xml
Jira: https://jira.xwiki.org/browse/XWIKI-20979
This pull request adds a new Quick Action to quickly search for and insert an icon in the WYSIWYG editor.
Here's a preview of the feature:
=> XWIKI-20979: Add a quick action for inserting an icon

xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins/src/main/webjar/xwiki-link/plugin.js, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-test/xwiki-platform-ckeditor-test-docker/src/test/it/org/xwiki/ckeditor/test/ui/QuickActionsIT.java, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-ui/src/main/resources/CKEditor/EditSheet.xml, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-ui/src/main/resources/CKEditor/Translations.xml
Jira: https://jira.xwiki.org/browse/XWIKI-21191
This pull request adds an attachment upload entry in the link autocomplete/quick action.
Here's a preview of the feature:
Thanks.
=> XWIKI-21191: Add support for uploading an attachment from the link quick action

xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins/src/main/webjar/xwiki-image/plugin.js, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-test/xwiki-platform-ckeditor-test-docker/src/test/it/org/xwiki/ckeditor/test/ui/ImagePluginIT.java
Jira: https://jira.xwiki.org/browse/XWIKI-21182
This PR fixes a bug where the image insertion Quick Action always inserted absolute references.
Now the references are relative.
=> XWIKI-21182: The Image Quick Action doesn't use a relative reference for attachments from the current page

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/menus_content.vm
https://jira.xwiki.org/browse/XWIKI-20913
* Fixed a regression on UI for non advanced users introduced in https://github.com/xwiki/xwiki-platform/commit/4904519d476fbda4873bf8c5a4b3d706e4cc44d5
The regression allowed the toggler button to display even when the user was not advanced, and when toggled it displayed an empty dropdown.
=> XWIKI-20913: More actions dropdown structure is not accessible

xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins/src/main/webjar/xwiki-icon/iconService.js
Jira: https://jira.xwiki.org/browse/XWIKI-21237
This PR fixes a caching issue in the Icon Quick Action.
Thanks.
=> XWIKI-21237: The icon list isn't cached in Icon Quick Action.

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-theme/xwiki-platform-flamingo-theme-ui/src/main/resources/FlamingoThemes/Iceberg.xml
Jira: https://jira.xwiki.org/browse/XWIKI-21274
Same approach as for https://github.com/xwiki/xwiki-platform/pull/2101, discussed in https://forum.xwiki.org/t/fixing-a11y-contrast-issues-on-the-main-view/11917/7?u=mleduc.
Change the test color for the info buttons from white to black.
**before**
**after**
=> XWIKI-21274: Info buttons lack contrast

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/buttons.less
Jira: https://jira.xwiki.org/browse/XWIKI-21253
Forum discussion: https://forum.xwiki.org/t/gradient-on-buttons-minimalist-skin-design-1/12618/
Follow up work on image borders: https://github.com/xwiki/xwiki-platform/pull/2319
**Draft PR**
I will document below some before/after screenshot of some elements of XWiki Standard with and without gradients on buttons.
**before**
**after**
**before**
**after**
**before**
**after**
**after**
The state change are on `Save & View`.
**before**
**after**
**before**
**after**
**before**
**after**
**after**
=> XWIKI-21253: Improve the Gradient of buttons

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/buttons.less
Jira: https://jira.xwiki.org/browse/XWIKI-21254
Forum discussion: https://forum.xwiki.org/t/borders-on-buttons-minimalist-skin-design-2/12619
Build on top of https://github.com/xwiki/xwiki-platform/pull/2316, please do not merge first.
All the buttons are borderless, except the default one (i.e., white) which has a border to distinguish it from the background.
Note: the screenshots below contains the changes on gradient on addition to the change on borders.
**before**
**after**
**before**
**after**
**before**
**after**
**before**
**after**
https://github.com/xwiki/xwiki-platform/assets/327856/f6355ac4-3175-4448-8244-a926959bce3a
=> XWIKI-21254: Improve the border on buttons

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/buttons.less
https://jira.xwiki.org/browse/XWIKI-21204
* Added a minimum size for xs-btn from bootstrap in order to match our code style about target size
Before and after the PR being applied, example of the action button in notification, that were slightly changed visually because of this PR. Most xs-btn were already big enough and the added style doesn't change their display.
=> XWIKI-21204: Btn-xs style results in buttons that are too small

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/createinline.vm
https://jira.xwiki.org/browse/XWIKI-19143
* Removed the label semantics from elements that did not need this semantics and were not fit to fulfill all requirements of labels (namely, have a target designated by the 'for' attribute)
* This fix extends a bit beyond what was reported in XWIKI-19143, to fix a similar shortcoming with a similar change.
* There is no change in style caused by this PR, because of [forms.less](https://github.com/xwiki/xwiki-platform/blob/6006c3c4ae08e592d12de3230a7cc5cb06dd1f1a/xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/forms.less#L117)
N/A
Passed:
mvn clean install -f xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/ -Pquality …
=> XWIKI-19143: Label "Type" is not connected to input while creating article

xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-api/src/main/java/org/xwiki/notifications/CompositeEvent.java
* Bulletproofing of composite events, only needed in 14.10.x
Note that this commit alone is not enough for fixing XWIKI-21299.
=> XWIKI-21299: Multiple mail received with live email notifications

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/pom.xml, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/restore.vm, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-docker/src/test/it/org/xwiki/flamingo/test/docker/DeletePageIT.java, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-pageobjects/src/main/java/org/xwiki/flamingo/skin/test/po/RestoreStatusPage.java, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-pageobjects/src/main/java/org/xwiki/flamingo/skin/test/po/UndeletePage.java, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/po/DeletePageOutcomePage.java, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/po/RefactoringStatusPage.java, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/getdeleteddocuments.vm
* Change `restore.vm` to use wiki syntax and add the live data macro
* Add an integration test for the undelete action
* Introduce a new page object class `RefactoringStatusPage` class that takes parts of `CopyOrRenameOrDeleteStatusPage`
* Introduce a new page object class `RestoreStatusPage` inheriting from `RefactoringStatusPage`
* Introduce a new page object class `UndeletePage`
JIRA issue: https://jira.xwiki.org/browse/XWIKI-18752
Before:
After:
=> XWIKI-18752: Replace the livetable from the restore deleted page form with a Live Data

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/notification/email/macros.vm, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/notification/macros.vm
JIRA: https://jira.xwiki.org/browse/XWIKI-20904
This work provides a new macro in the notifications macro to compute the description to display for a composite event. The computation is done as before, based on the number of users concerned by the event. The main change is that the macro performs several fallbacks to try to always display something.
=> XWIKI-20904: The generated translation key for standard notification message is too strict

xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-macro/xwiki-platform-notifications-macro-ui/src/main/resources/XWiki/Notifications/Code/Macro/NotificationsMacro.xml, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/notification/macros.vm
JIRA: https://jira.xwiki.org/browse/XWIKI-18880
* Insert the read button in the template
* Enable it in the notification macros if needed
Note that right now these change might have an impact on backward compatibility if an extension uses a customized template for macro and more specifically if they override `displayNotificationEventSkeleton`: they would lose the "Mark as read" button since it was injected dynamically. Now I really doubt we have much extensions overriding it: at least I don't find any occurrence of such override in xwiki-contrib.
Also note that the provided changes have no impact at all on the UI look&feel.
=> XWIKI-18880: Allow to decide where the Mark as read button is put in notifications template

xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-ui/src/main/resources/XWiki/AdminSheet.xml, xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-ui/src/main/resources/XWiki/AdminTranslations.xml
https://jira.xwiki.org/browse/XWIKI-20758
* Removed the inappropriate roles from the accordion
* Removed the 'aria-multiselectable' attribute that conveyed wrong information to assistive technology users.
See the comments on the jira ticket for explanations on why this solution was chosen.
There is no longer 'role does not contain children' error reported by axe-core.
=> XWIKI-20758: Administration menu violates tablist structure

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/layout.less
https://jira.xwiki.org/browse/XWIKI-18838
After we merged https://github.com/xwiki/xwiki-platform/pull/2166 yesterday, @manuelleduc noticed a regression in the WYSIWYG UI:
This regression is caused by assumptions I had on the '.main' class in XWiki. I did not realize it could be used in a context different than the 'page content container' one. I changed style and this broke the presentation on the WYSIWYG main.
This PR adds an additionnal rule overriding those changes on the WYSIWYG main.
* Patched a grey line appearing in the WYSIWIG editor
=> XWIKI-18838: Use ARIA landmarks for main page regions

xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-api/pom.xml, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-api/src/main/java/org/xwiki/notifications/internal/DefaultCompositeEventStatusManager.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-api/src/test/java/org/xwiki/notifications/internal/DefaultCompositeEventStatusManagerTest.java
JIRA: https://jira.xwiki.org/browse/XWIKI-21097
* Change the algorithm to gather statuses in DefaultCompositeEventStatusManager to request per batch instead of requesting everything at once
* Provide a unit test to cover the changes
=> XWIKI-21097: Request URI too long error when using opening the notification area

xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/layouts/table/LayoutTableHeaderNames.vue
* Resize both column and name to properly resize columns.
* Remove the forced width of 100% on the table to make sure column width
are actually respected and also set all other column width to prevent
weird resizing effects.
* Resize only the column left of the resizer to make it easier to resize
single columns. This is also more consistent with other applications
where you can resize columns like LibreOffice.
Jira issue: https://jira.xwiki.org/browse/XWIKI-19490
This is quite a big UX change, would be nice to get some feedback if we want to change it that much or only a little. We could, e.g., also just resize both column and name which would already be a big improvement and basically prevent the actually reported issue. When I tested it, though, the behavior just felt wrong, still, and …
=> XWIKI-19490: Resizing columns in Live Data makes the column title too small

xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-api/src/main/java/org/xwiki/notifications/filters/internal/event/NotificationFilterPreferenceDeletedEvent.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-default/src/main/java/org/xwiki/notifications/filters/internal/CachedModelBridgeInvalidatorListener.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-default/src/main/java/org/xwiki/notifications/filters/internal/NotificationFilterPreferenceStore.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-default/src/main/java/org/xwiki/notifications/filters/internal/event/NotificationFilterPreferenceEventConverter.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-default/src/test/java/org/xwiki/notifications/filters/internal/NotificationFilterPreferenceStoreTest.java
JIRA: https://jira.xwiki.org/browse/XWIKI-21209
* Refactor NotificationFilterPreferenceStore to ensure to use the right wiki in context when the local store is used
* Use a query based on the filter internal identifier to perform single deletion, to prevent having to load it
* Refactor the way NotificationFilterPreferenceDeletedEvent is used to not send the entire filter instance when it's triggered
* Improve unit tests
=> XWIKI-21209: Delete filter is slow (seems to load all filters)

xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/layouts/table/LayoutTableHeaderNames.vue
* Remove margin between column title and sort icon
* Put the drag handle on top of the column title with an opacity of 0.8
Jira issue: https://jira.xwiki.org/browse/XWIKI-19449 (with screenshots of the before state)
Here is a screenshot of the new version:
And here another one to demonstrate how the handle for dragging columns is displayed (in the "Release Date" column):
Live Data still needs more space, but the difference should be much smaller now. I think the main differences are:
1. Livetable has a smaller padding in the title cells, 8px (default of XWiki) vs. 3px.
2. The sort icon has still less padding (I already reduced it with this commit)
I'm not sure that it is worth giving up this extra space as this space is consistent with other parts of the UI.
=> XWIKI-19449: Livedata table overflows horizontally for container sizes in which livetable fits perfectly fine

xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/layouts/table/LayoutTableHeaderNames.vue
* Set the size of all columns when resizing starts.
* Reset all sizes when resetting column sizes.
Jira issue: https://jira.xwiki.org/browse/XWIKI-21329
Here a video demonstrating both the issue and the solution (note the text at the top):
https://github.com/xwiki/xwiki-platform/assets/198317/20b3aeca-d84a-4d54-ae15-537eccaf985f
This is basically a less drastic version of what I proposed in #2350, taking the feedback from there into account - it still resizes both columns now, and you cannot resize below 100% width.
=> XWIKI-21329: Dragging the resize handle of a Live Data column leads to a jump in size

xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/user/impl/xwiki/XWikiGroupServiceImpl.java, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/getusersandgroups.vm, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/macros.vm, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/js/xwiki/usersandgroups/usersandgroups.js
Related JIRA issues : 
* [XWIKI-21305](https://jira.xwiki.org/browse/XWIKI-21305) - Use user first name or last name when filtering in the rights livetable
* [XWIKI-21306](https://jira.xwiki.org/browse/XWIKI-21306) - In the user rights UI, display the user first name and last name
* [XWIKI-21349](https://jira.xwiki.org/browse/XWIKI-21349) - Provide parameters to enable or disable linking to user profiles in the user displayer
This PR aims at improving the experience of administrators when administering rights for instances with users who have usernames that do not correspond to their actual first name and last name.
=> Improvements to user listing in the rights UI

xwiki-platform-core/xwiki-platform-attachment/xwiki-platform-attachment-picker/xwiki-platform-attachment-picker-webjar/src/main/webjar/attachmentGalleryPicker.js
Jira: https://jira.xwiki.org/browse/XWIKI-21341
=> XWIKI-21341: The attachment gallery picker is not preserving image ratio when downscaling

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/layout.less, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/type.less, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/variables.less
Jira: https://jira.xwiki.org/browse/XWIKI-21333
- Replace the headings sizes with a size scale
- Make the headings size proportional to the viewport width, the size is still bounded and won't get smaller below 768px, or larger above 1200px.
- The size scale is based on two headings size scale (1.250 for the larger screens, and 1.125 for the smaller screens)
I agree the code is complex, I'm looking for ways to simply.
Also, if we drop the viewport scale improvement, the code gets muuuch simpler.
Inspired from https://www.smashingmagazine.com/2016/05/fluid-typography/#controlling-the-rate-of-scale
You can find below the actual `font-size` used for `h1` headings with the default values.
- given a screen size between 768px and 1200px;
- `23px` = the minimal font size a `h1` heading can have …
=> XWIKI-21333: Update the weight and font size of headings

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/macros.vm
https://jira.xwiki.org/browse/XWIKI-20696
* Fixed a space related error in the velocity macro definition
This is fix for a regression reported by @michitux. This regression was introduced in https://github.com/xwiki/xwiki-platform/pull/2133 which added an empty \<p> block above some panels.
After the changes proposed in this PR, we can see that the unintened \<p> node is no longer here:
=> XWIKI-20696: Accessibility best-practice: use landmarks in view pages

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/forms.less
https://jira.xwiki.org/browse/XWIKI-21384
* Overrode color of the placeholder in bootstrap select with color theme defined color.
[Here is a video demo featuring the updated color and highlighting how it passes WCAG contrast standards.](https://up1.xwikisas.com/#wMVQkPXiFwIDjgU6zicPew)
=> XWIKI-21384: Lack of contrast on empty option of localization preferences

xwiki-platform-core/xwiki-platform-tour/xwiki-platform-tour-ui/src/main/resources/TourCode/TourJS.xml
**EDIT:** See https://github.com/xwiki/xwiki-platform/pull/2453#issuecomment-1755663113 for an updated PR starting message
______
______
Fix for https://ge.xwiki.org/scans/tests?search.relativeStartTime=P28D&search.tags=master&search.timeZoneId=Europe%2FBerlin&tests.container=org.xwiki.tour.test.ui.TourApplicationIT&tests.test=verifyTourFeatures
This is a regression caused by the merge for [TOUR-81](https://jira.xwiki.org/browse/TOUR-81).
* Updated the 'hidden' attribute of the button when opening/closing the tour modal
* Overrode the .btn 'display' property when this button is hidden.
[Demo video](https://up1.xwikisas.com/#hxyRVwzGJ_h_172P8wWT-w)
We can see on this video that with the changes brought in this PR, the tour button disappears when the tour is opened, as expected by the …
=> XWIKI-21412: Move the Tour Application to xwiki-platform

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/hierarchy_macros.vm, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/test/java/org/xwiki/web/HierarchyMacrosPageTest.java
Jira: https://jira.xwiki.org/browse/XWIKI-21410
**TODO**
=> XWIKI-21410: Hierarchy macro does not generate correct links for object_property references

xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/doc/XWikiDocument.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/objects/BaseObject.java
* Ensure to retrieve the xclass even when the xobject has been deleted
=> XWIKI-19948: Bad diff information when xobject is deleted

xwiki-platform-core/xwiki-platform-extension/xwiki-platform-extension-index/src/main/java/org/xwiki/extension/index/security/SecurityVulnerabilityDescriptor.java, xwiki-platform-core/xwiki-platform-extension/xwiki-platform-extension-security/xwiki-platform-extension-security-index/src/main/java/org/xwiki/extension/security/internal/analyzer/VulnerabilityIndexer.java, xwiki-platform-core/xwiki-platform-extension/xwiki-platform-extension-security/xwiki-platform-extension-security-index/src/main/java/org/xwiki/extension/security/internal/analyzer/osv/OsvResponseAnalyzer.java, xwiki-platform-core/xwiki-platform-extension/xwiki-platform-extension-security/xwiki-platform-extension-security-index/src/main/java/org/xwiki/extension/security/internal/analyzer/osv/model/response/VulnObject.java, xwiki-platform-core/xwiki-platform-extension/xwiki-platform-extension-security/xwiki-platform-extension-security-index/src/test/java/org/xwiki/extension/security/internal/analyzer/osv/OsvResponseAnalyzerTest.java, xwiki-platform-core/xwiki-platform-extension/xwiki-platform-extension-security/xwiki-platform-extension-security-index/src/test/resources/analyzeOsvResponse.json, xwiki-platform-core/xwiki-platform-extension/xwiki-platform-extension-security/xwiki-platform-extension-security-test/xwiki-platform-extension-security-test-docker/src/test/it/org/xwiki/extension/security/test/ui/ExtensionSecurityIT.java, xwiki-platform-core/xwiki-platform-extension/xwiki-platform-extension-security/xwiki-platform-extension-security-test/xwiki-platform-extension-security-test-docker/src/test/resources/reviews_source.vm
Jira: https://jira.xwiki.org/browse/XWIKI-21322
**Main changes**
- OSV source now returned CVEs as IDs (and so should any other source)
- Results without CVE are ignored
- Nothing of aliases introduced to prevent re-notifying previously stored vulnerabilities with an outdated id
=> XWIKI-21322: CVE IDs column of the security list does not contain CVE IDs

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/uicomponents/viewers/diff.css
https://jira.xwiki.org/browse/XWIKI-21386
* Replaced the half opacity colors with their full opacity alternatives from the color themes (the same as the ones used in .text-muted)
With the Iceberg color theme:
With the Darkly color theme (the text colors are hard coded, which make them look off, however I can't see an easy solution to get all of these colors from the color theme, and it's not the focus of this PR)
We can see that with both color themes, the text passes contrast checks, and is overall more readable. However, it's also less subtle and the eye gets caught on it more easily.
## Note
AFAIK this style rule was created by @mflorea in [this commit](https://github.com/xwiki/xwiki-platform/commit/4ec10a623ed99d887340ddb719d395ebe945dddc#diff-cba9da1f0167da707d85622373578942fbb16bed22 …
=> XWIKI-21386: Change viewer meta data lacks contrast

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/js/xwiki/widgets/modalPopup.css, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/js/xwiki/widgets/modalPopup.js
https://jira.xwiki.org/browse/XWIKI-21437
* Updated style and semantic on the close button
Successfully passed [this error in CI](https://ci.xwiki.org/job/XWiki/job/xwiki-platform/job/master/6926/testReport/org.xwiki.tour.test.ui/TourApplicationIT/Platform_Builds___main___integration_tests___IT_for_xwiki_platform_core_xwiki_platform_tour_xwiki_platform_tour_test_xwiki_platform_tour_test_tests___Build_for_IT_for_xwiki_platform_core_xwiki_platform_tour_xwiki_platform_tour_test_xwiki_platform_tour_test_tests___verifyTourFeatures/).
=> XWIKI-21437: The XModal close button is not accessible

xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/po/ChangesPane.java, xwiki-platform-distribution/xwiki-platform-distribution-flavor/xwiki-platform-distribution-flavor-test/xwiki-platform-distribution-flavor-test-ui/src/test/it/org/xwiki/test/ui/CompareVersionsTest.java
https://jira.xwiki.org/browse/XWIKI-21272
* Fixed outdated functional tests
The [changes merged here](https://github.com/xwiki/xwiki-platform/pull/2323) created [a test fail on the CI](https://ci.xwiki.org/job/XWiki/job/xwiki-platform/job/master/lastCompletedBuild/testReport/org.xwiki.test.ui/CompareVersionsTest/Platform_Builds___main___distribution___flavor_test_ui___Build_for_Flavor_Test___UI___testCompareVersionScenario/).
Successfully passed `mvn clean install -f xwiki-platform-distribution/xwiki-platform-distribution-flavor/xwiki-platform-distribution-flavor-test/xwiki-platform-distribution-flavor-test-ui -Pdocker -Dxwiki.test.ui.wcag=true -Dgradle.cache.local.enabled=false -Dgradle.cache.remote.enabled=false ` (the failing test suite).
=> XWIKI-21272: History navigation arrows are not perceived as links and lacking contrast

xwiki-platform-core/xwiki-platform-help/xwiki-platform-help-ui/src/main/resources/Help/Code/Translations.xml, xwiki-platform-core/xwiki-platform-help/xwiki-platform-help-ui/src/main/resources/Help/Videos/WebHome.xml
https://jira.xwiki.org/browse/XWIKI-21375
[Handle videos in the help page](https://forum.xwiki.org/t/handle-videos-in-the-help-page/13220)
* Changed the list items to anchors sending to different documentation pages
* Added a hint to explicitly set the text alternative of the videos
We can see that now all list items under the videos are anchors that redirect to various sections of the documentation. 
The way I implemented the solution we converged to in the discussion is based upon [this example in a proposal of atomic rule for ACT](https://www.w3.org/WAI/standards-guidelines/act/rules/fd26cf/proposed/#test-cases). There is no designated role for alternative to videos in aria, we rely on the user's understanding.
I decided to add a non-visual hint to highlight the bond between the video …
=> XWIKI-21375: Videos on the help page don't have alternatives

xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/WCAGContext.java
https://jira.xwiki.org/browse/XWIKI-21163
* Bulletproofed the numberOfChecks function
There was [a failure of the WCAG validator on CI](https://ci.xwiki.org/job/XWiki%20Environment%20Tests/job/xwiki-platform/job/master/359/testReport/junit/org.xwiki.export.pdf.test.ui/AllIT$NestedPDFExportIT/MySQL_8_1__Tomcat_9_jdk17__Chrome___Docker_tests_for_xwiki_platform_export_pdf___Build_for_MySQL_8_1__Tomcat_9_jdk17__Chrome___Docker_tests_for_xwiki_platform_export_pdf___largeTable_TestUtils__TestConfiguration_/). This PR fixes this fail and successfully passes `mvn clean install -f xwiki-platform-core/xwiki-platform-export/xwiki-platform-export-pdf/xwiki-platform-export-pdf-test/xwiki-platform-export-pdf-test-docker/ -Pdocker -Dxwiki.test.ui.wcag=true`
=> XWIKI-21163: WCAG reporting: include a summary of the tests for statistics

xwiki-platform-distribution/xwiki-platform-distribution-debian/pom.xml, xwiki-platform-distribution/xwiki-platform-distribution-debian/xwiki-platform-distribution-debian-common/pom.xml, xwiki-platform-distribution/xwiki-platform-distribution-debian/xwiki-platform-distribution-debian-xjetty/pom.xml, xwiki-platform-distribution/xwiki-platform-distribution-debian/xwiki-platform-distribution-debian-xjetty/xwiki-platform-distribution-debian-xjetty-common/pom.xml, xwiki-platform-distribution/xwiki-platform-distribution-debian/xwiki-platform-distribution-debian-xjetty/xwiki-platform-distribution-debian-xjetty-common/src/deb/control/control, xwiki-platform-distribution/xwiki-platform-distribution-debian/xwiki-platform-distribution-debian-xjetty/xwiki-platform-distribution-debian-xjetty-common/src/deb/control/postinst, xwiki-platform-distribution/xwiki-platform-distribution-debian/xwiki-platform-distribution-debian-xjetty/xwiki-platform-distribution-debian-xjetty-common/src/deb/control/postrm, xwiki-platform-distribution/xwiki-platform-distribution-debian/xwiki-platform-distribution-debian-xjetty/xwiki-platform-distribution-debian-xjetty-common/src/deb/resources/lib/systemd/system/xwiki.service, xwiki-platform-distribution/xwiki-platform-distribution-debian/xwiki-platform-distribution-debian-xjetty/xwiki-platform-distribution-debian-xjetty-common/src/deb/resources/usr/lib/sysusers.d/xwiki.conf, xwiki-platform-distribution/xwiki-platform-distribution-debian/xwiki-platform-distribution-debian-xjetty/xwiki-platform-distribution-debian-xjetty-mariadb/pom.xml, xwiki-platform-distribution/xwiki-platform-distribution-debian/xwiki-platform-distribution-debian-xjetty/xwiki-platform-distribution-debian-xjetty-mariadb/src/deb/control/config, xwiki-platform-distribution/xwiki-platform-distribution-debian/xwiki-platform-distribution-debian-xjetty/xwiki-platform-distribution-debian-xjetty-mariadb/src/deb/control/control, xwiki-platform-distribution/xwiki-platform-distribution-debian/xwiki-platform-distribution-debian-xjetty/xwiki-platform-distribution-debian-xjetty-mariadb/src/deb/control/postinst, xwiki-platform-distribution/xwiki-platform-distribution-debian/xwiki-platform-distribution-debian-xjetty/xwiki-platform-distribution-debian-xjetty-mariadb/src/deb/control/postrm, xwiki-platform-distribution/xwiki-platform-distribution-debian/xwiki-platform-distribution-debian-xjetty/xwiki-platform-distribution-debian-xjetty-mysql/pom.xml, xwiki-platform-distribution/xwiki-platform-distribution-debian/xwiki-platform-distribution-debian-xjetty/xwiki-platform-distribution-debian-xjetty-mysql/src/deb/control/config, xwiki-platform-distribution/xwiki-platform-distribution-debian/xwiki-platform-distribution-debian-xjetty/xwiki-platform-distribution-debian-xjetty-mysql/src/deb/control/control, xwiki-platform-distribution/xwiki-platform-distribution-debian/xwiki-platform-distribution-debian-xjetty/xwiki-platform-distribution-debian-xjetty-mysql/src/deb/control/postinst, xwiki-platform-distribution/xwiki-platform-distribution-debian/xwiki-platform-distribution-debian-xjetty/xwiki-platform-distribution-debian-xjetty-mysql/src/deb/control/postrm, xwiki-platform-distribution/xwiki-platform-distribution-debian/xwiki-platform-distribution-debian-xjetty/xwiki-platform-distribution-debian-xjetty-pgsql/pom.xml, xwiki-platform-distribution/xwiki-platform-distribution-debian/xwiki-platform-distribution-debian-xjetty/xwiki-platform-distribution-debian-xjetty-pgsql/src/deb/control/config, xwiki-platform-distribution/xwiki-platform-distribution-debian/xwiki-platform-distribution-debian-xjetty/xwiki-platform-distribution-debian-xjetty-pgsql/src/deb/control/control, xwiki-platform-distribution/xwiki-platform-distribution-debian/xwiki-platform-distribution-debian-xjetty/xwiki-platform-distribution-debian-xjetty-pgsql/src/deb/control/postinst, xwiki-platform-distribution/xwiki-platform-distribution-debian/xwiki-platform-distribution-debian-xjetty/xwiki-platform-distribution-debian-xjetty-pgsql/src/deb/control/postrm
issue: https://jira.xwiki.org/browse/XWIKI-21458
I also added a little change regarding the version of Java installed by default as dependency since:
* we now recommend Java 17 at runtime
* looks like Debian 12+ does not have any Java 11 package anymore
=> XWIKI-21458: Provide a XJetty based Debian package

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/panels.less
Jira: https://jira.xwiki.org/browse/XWIKI-21451
- Technically a (very old) regression between 7.1 and 7.2, by https://github.com/xwiki/xwiki-platform/commit/8b065192c4f26e13f9d4bbbdf34090055c18e218
**Before**
**After**
=> XWIKI-21451: The logging form bottom rounded corners have a blank gap

xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-ui/src/main/resources/AppWithinMinutes/CreateApplication.xml, xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-ui/src/main/resources/AppWithinMinutes/WizardStep.xml, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/uicomponents/wizard/wizard.css, xwiki-platform-core/xwiki-platform-wiki/xwiki-platform-wiki-ui/xwiki-platform-wiki-ui-mainwiki/src/main/resources/WikiManager/CreateWiki.xml
https://jira.xwiki.org/browse/XWIKI-21479
* Updated style for the wizard step
* Updated the class names to avoid unwanted collision with .btn.active
^^^ Before the PR ^^^                 vvv After the PR vvv
Part of the BFD :)
=> XWIKI-21479: Wizard step icons are not in line with the button style

xwiki-platform-core/xwiki-platform-edit/xwiki-platform-edit-ui/src/main/resources/XWiki/InplaceEditing.xml
https://jira.xwiki.org/browse/XWIKI-21005
* Removed the incorrect attribute after loading the CKeditor inplace editor.
This attribute is added by default in the CKEditor > wysiwygarea plugin. We make sure to remove it after the initialization of the editor.
=> XWIKI-21005: CKEditor content on inplace edit uses incorrectly aria-expanded

xwiki-platform-core/xwiki-platform-edit/xwiki-platform-edit-ui/src/main/resources/XWiki/InplaceEditing.xml
https://jira.xwiki.org/browse/XWIKI-21507
* Updated background color
## View
The green border on the input is just a browser extension I use to highlight focus. It's not a change proposed in this PR :)
=> XWIKI-21507: Inplace Editing title does not respect color expectations and does not have enough contrast on some themes

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/drawer.less
https://jira.xwiki.org/browse/XWIKI-21037
* Fixed style
[Here is a video demo of the change.](https://up1.xwikisas.com/#NWgNqdWNv4QRJJz_0xky_w) We can see that with this change, the vertical overflow is visible when scrolling on the dialog. Scrolling outside of the dialog still scroll the body of the document.
Improvement of the drawer following the changes in https://github.com/xwiki/xwiki-platform/pull/2282.
=> XWIKI-21037: Not all items of Drawer are visible and drawer itself don't allow scrolling

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/flamingo.js
https://jira.xwiki.org/browse/XWIKI-18007
* Fixed code style for JSHint
* This is a fix for the regression found in CI:
```
00:21:02,330 [INFO] --- jshint-maven-plugin:1.7.2:lint (default) @ xwiki-platform-flamingo-skin-resources ---
00:21:02,332 [INFO] using jshint version 2.13.6
00:21:02,558 [INFO]   /root/workspace/XWiki_xwiki-platform_master/xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/dateTimePicker.js
00:21:02,762 [INFO]   /root/workspace/XWiki_xwiki-platform_master/xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/localePicker.js
00:21:03,019 [INFO] …
```
=> XWIKI-18007: Drawer menu improvements for accessibility

xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-docker/src/main/java/org/xwiki/test/docker/internal/junit5/servletengine/JettyStandaloneExecutor.java
Jira: https://jira.xwiki.org/browse/XWIKI-21518
This PR removes a reference to a unused Jetty context file in the docker test module.
It is necessary to remove the reference here because it causes the Docker Integration tests to fail at setup time with the following traceback:
```
[INFO] Running org.xwiki.ckeditor.test.ui.AllIT                                                                                                                                                                                              
12:30:11.900 [main] INFO  o.x.t.d.i.j.XWikiDockerExtension - (*) Starting database [HSQLDB_EMBEDDED]...                                                                                                                                      
12:30:11.905 [main] INFO …
```
=> XWIKI-21518: Remove unused Jetty context files

xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/po/AbstractRegistrationPage.java
* Fix AbstractRegistrationPage page object which is now broken since the introduction of a new CSS class in live validation elements
=> XWIKI-21376: Live validation prompts should be presented to users without obtaining focus

xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-test/xwiki-platform-ckeditor-test-docker/src/test/it/org/xwiki/ckeditor/test/ui/AllIT.java, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-test/xwiki-platform-ckeditor-test-docker/src/test/it/org/xwiki/ckeditor/test/ui/LocalizationIT.java, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-ui/src/main/resources/CKEditor/Translations.xml
Jira: https://jira.xwiki.org/browse/XWIKI-21491
This pull request provides a fix for a bug where the translations in the CKEditor integration would break when using the `de_DE` locale.
This PR also includes an integration test to detect the bug.
=> XWIKI-21491: Translation keys are displayed instead of translations when the "German (Germany)" locale is set.

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/historyinline.vm
https://jira.xwiki.org/browse/XWIKI-21533
* Modified ALL the labels generated in the history table from `hidden` to `sr-only`
=> XWIKI-21533: Page History tab Radio buttons are missing a label

xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-macros/xwiki-platform-rendering-macro-cache/pom.xml, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-macros/xwiki-platform-rendering-macro-cache/src/main/java/org/xwiki/rendering/internal/macro/cache/CacheMacroRequiredRightsAnalyzer.java, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-macros/xwiki-platform-rendering-macro-cache/src/main/resources/META-INF/components.txt, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-macros/xwiki-platform-rendering-macro-cache/src/test/java/org/xwiki/rendering/internal/macro/cache/CacheMacroRequiredRightsAnalyzerTest.java, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-xwiki/pom.xml, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-xwiki/src/main/java/org/xwiki/rendering/internal/macro/RawMacroRequiredRightsAnalyzer.java, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-xwiki/src/main/resources/ApplicationResources.properties, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-xwiki/src/main/resources/META-INF/components.txt, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-xwiki/src/test/java/org/xwiki/rendering/internal/macro/RawMacroRequiredRightsAnalyzerTest.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-requiredrights/xwiki-platform-security-requiredrights-default/pom.xml, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-requiredrights/xwiki-platform-security-requiredrights-default/src/main/java/org/xwiki/platform/security/requiredrights/internal/analyzer/AbstractMacroBlockRequiredRightAnalyzer.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-requiredrights/xwiki-platform-security-requiredrights-default/src/main/java/org/xwiki/platform/security/requiredrights/internal/analyzer/DefaultMacroBlockRequiredRightAnalyzer.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-requiredrights/xwiki-platform-security-requiredrights-default/src/main/java/org/xwiki/platform/security/requiredrights/internal/analyzer/DefaultMacroRequiredRightReporter.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-requiredrights/xwiki-platform-security-requiredrights-default/src/main/java/org/xwiki/platform/security/requiredrights/internal/analyzer/ScriptMacroAnalyzer.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-requiredrights/xwiki-platform-security-requiredrights-default/src/main/resources/ApplicationResources.properties, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-requiredrights/xwiki-platform-security-requiredrights-default/src/main/resources/META-INF/components.txt, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-requiredrights/xwiki-platform-security-requiredrights-default/src/test/java/org/xwiki/platform/security/requiredrights/internal/analyzer/DefaultMacroBlockRequiredRightAnalyzerTest.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-requiredrights/xwiki-platform-security-requiredrights-default/src/test/java/org/xwiki/platform/security/requiredrights/internal/analyzer/ScriptMacroAnalyzerTest.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-requiredrights/xwiki-platform-security-requiredrights-macro/pom.xml, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-requiredrights/xwiki-platform-security-requiredrights-macro/src/main/java/org/xwiki/platform/security/requiredrights/MacroRequiredRight.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-requiredrights/xwiki-platform-security-requiredrights-macro/src/main/java/org/xwiki/platform/security/requiredrights/MacroRequiredRightReporter.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-requiredrights/xwiki-platform-security-requiredrights-macro/src/main/java/org/xwiki/platform/security/requiredrights/MacroRequiredRightsAnalyzer.java
This PR introduces a new API for macros to report required rights:
* Add a new API for macros to report required rights.
* Add support for calling these new analyzers in the default macro analyzer.
* Improve error reporting for macro analyzers by displaying an analysis result with the error when the macro analyzer produces an error.
Further, I have included commits that introduce analyzers for the cache and the raw macro to demonstrate the usage of the new API.
Jira issue: https://jira.xwiki.org/browse/XWIKI-21528 and for the analyzers https://jira.xwiki.org/browse/XWIKI-21484 and https://jira.xwiki.org/browse/XWIKI-21485
=> XWIKI-21528: Add a dedicated required rights analyzer API for macros without dependencies

xwiki-platform-core/xwiki-platform-filter/xwiki-platform-filter-instance/xwiki-platform-filter-instance-document/src/main/java/org/xwiki/filter/instance/output/DocumentInstanceOutputProperties.java
The typo is also in the variable/method names, but changing this would probably be a breaking change.
=> [Misc] Fix typo 'save fail' -> 'save fails'

xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-requiredrights/xwiki-platform-security-requiredrights-api/src/main/java/org/xwiki/platform/security/requiredrights/RequiredRightAnalysisResult.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-requiredrights/xwiki-platform-security-requiredrights-default/src/main/java/org/xwiki/platform/security/requiredrights/internal/RequiredRightsChangedResult.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-requiredrights/xwiki-platform-security-requiredrights-default/src/main/java/org/xwiki/platform/security/requiredrights/internal/RequiredRightsEditConfirmationChecker.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-requiredrights/xwiki-platform-security-requiredrights-default/src/main/java/org/xwiki/platform/security/requiredrights/internal/editconfirmationchecker/RequiredRightAnalysisResultSkipValue.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-requiredrights/xwiki-platform-security-requiredrights-default/src/main/java/org/xwiki/platform/security/requiredrights/internal/editconfirmationchecker/RequiredRightsChangedResultSkipValue.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-requiredrights/xwiki-platform-security-requiredrights-default/src/test/java/org/xwiki/platform/security/requiredrights/internal/RequiredRightsEditConfirmationCheckerTest.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-requiredrights/xwiki-platform-security-requiredrights-test/xwiki-platform-security-requiredrights-test-docker/src/test/it/org/xwiki/security/requiredrights/test/ui/RequiredRightsIT.java
Jira: https://jira.xwiki.org/browse/XWIKI-21477
* Fix a regression where results involving the same rights are wrongfully considered equals.
Follow up of https://github.com/xwiki/xwiki-platform/pull/2598 and https://github.com/xwiki/xwiki-platform/pull/2595
=> XWIKI-21477: Improve the required rights result reporting

xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/po/FormContainerElement.java
* Forced scrolling on selection
* Fix for the CI fail: https://ci.xwiki.org/job/XWiki/job/xwiki-platform/job/master/6982/testReport/junit/org.xwiki.test.ui/SkinxTest/Platform_Builds___main___distribution___flavor_test_ui___Build_for_Flavor_Test___UI___testJavascriptExtension/
* I'm not sure of how the scrollTo function works, it's supposed to be called when doing `getFormElement().findElement(by)`, but it did not work properly from here. If I had to guess, it's because the context is limited to the formElement, so it does not try to scroll the whole page but just the form, which does not work. In any case, I added a scrollTo call from the driver, so it works properly here.
After re building with ` mvn clean install -f xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui …
=> Misc: Select does not scroll

xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-xwiki/pom.xml, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-xwiki/src/main/java/org/xwiki/rendering/internal/macro/HTMLMacroRequiredRightsAnalyzer.java, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-xwiki/src/main/resources/ApplicationResources.properties, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-xwiki/src/main/resources/META-INF/components.txt, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-xwiki/src/test/java/org/xwiki/rendering/internal/macro/HTMLMacroRequiredRightsAnalyzerTest.java
* Add a required rights analyzer for the HTML macro.
* Add a unit test that is almost an integration test as it tests with a real HTML cleaner.
Jira issue: https://jira.xwiki.org/browse/XWIKI-21482
This depends on xwiki/xwiki-commons#651.
=> XWIKI-21482: Introduce a required rights analyzer for the HTML macro

xwiki-platform-core/xwiki-platform-realtime/xwiki-platform-realtime-wiki/xwiki-platform-realtime-wiki-test/pom.xml, xwiki-platform-core/xwiki-platform-realtime/xwiki-platform-realtime-wiki/xwiki-platform-realtime-wiki-test/xwiki-platform-realtime-wiki-test-docker/pom.xml, xwiki-platform-core/xwiki-platform-realtime/xwiki-platform-realtime-wiki/xwiki-platform-realtime-wiki-test/xwiki-platform-realtime-wiki-test-docker/src/test/it/org/xwiki/realtime/wiki/test/ui/AllIT.java, xwiki-platform-core/xwiki-platform-realtime/xwiki-platform-realtime-wiki/xwiki-platform-realtime-wiki-test/xwiki-platform-realtime-wiki-test-docker/src/test/it/org/xwiki/realtime/wiki/test/ui/RealtimeWikiEditorIT.java, xwiki-platform-core/xwiki-platform-realtime/xwiki-platform-realtime-wiki/xwiki-platform-realtime-wiki-test/xwiki-platform-realtime-wiki-test-pageobjects/pom.xml, xwiki-platform-core/xwiki-platform-realtime/xwiki-platform-realtime-wiki/xwiki-platform-realtime-wiki-test/xwiki-platform-realtime-wiki-test-pageobjects/src/main/java/org/xwiki/realtime/wiki/test/po/RealtimeWikiEditor.java, xwiki-platform-core/xwiki-platform-realtime/xwiki-platform-realtime-wiki/xwiki-platform-realtime-wiki-webjar/src/main/webjar/wikiEditor.js
Jira: https://jira.xwiki.org/browse/XWIKI-19175
This PR fixes a bug where leaving and joining a Realtime **wiki** editing session again would show "Synchronizing" in the tool bar instead of the coeditors list.
This PR also brings a functional test for this bug.
Thanks.
=> XWIKI-19175: Leaving and rejoining the realtime editing session using  the checkbox doesn't work properly

xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-ui/src/main/resources/XWiki/Notifications/Code/NotificationsDisplayerUIX.xml
https://jira.xwiki.org/browse/XWIKI-21574
* Removed the use of the variable interpreted to ""
Before the PR
After the PR
There is a slight change in the style of the toggle label, however this is barely noticeable even when flashing from one version to the other.
When running the HTML export on a page without the changes, I was able to reproduce the issue described (16.0-snapshot local distrib). With the changes, no error happened in the xwiki console, and the export ended successfully. :)
This PR should be cherry picked for 14.10.20 and 15.5.4
=> XWIKI-21574: Errors in the wiki console when exporting a page as HTML

xwiki-platform-core/xwiki-platform-model/xwiki-platform-model-api/src/main/java/org/xwiki/model/reference/EntityReference.java, xwiki-platform-core/xwiki-platform-model/xwiki-platform-model-api/src/test/java/org/xwiki/model/reference/EntityReferenceTest.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authorization/xwiki-platform-security-authorization-api/src/main/java/org/xwiki/security/internal/XWikiBridge.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authorization/xwiki-platform-security-authorization-bridge/src/main/java/org/xwiki/security/internal/DefaultXWikiBridge.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authorization/xwiki-platform-security-authorization-bridge/src/test/java/org/xwiki/security/internal/DefaultXWikiBridgeTest.java
* Remove parameters from entity references when constructing a security reference.
Jira issue: https://jira.xwiki.org/browse/XWIKI-21439
=> XWIKI-21439: Security Cache ConflictingInsertionException

xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/tests/unit/layouts/cards/LayoutCards.spec.js, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/tests/unit/layouts/cards/LayoutCardsCard.spec.js, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/tests/unit/layouts/table/LayoutTable.spec.js, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/tests/unit/layouts/table/LayoutTableRow.spec.js, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/layouts/cards/LayoutCards.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/layouts/cards/LayoutCardsCard.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/layouts/table/LayoutTable.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/layouts/table/LayoutTableRow.vue
* Add `data-livedata-entry-index` and `data-livedata-entry-id` attributes on the parent DOM node of the entries, for both cards and table layouts
See:
=> XWIKI-21659: Provide entry index in data attribute of LiveData

xwiki-platform-core/xwiki-platform-legacy/xwiki-platform-legacy-oldcore/src/main/aspect/com/xpn/xwiki/XWikiCompatibilityAspect.aj, xwiki-platform-core/xwiki-platform-legacy/xwiki-platform-legacy-oldcore/src/main/aspect/com/xpn/xwiki/api/DocumentCompatibilityAspect.aj, xwiki-platform-core/xwiki-platform-legacy/xwiki-platform-legacy-oldcore/src/main/aspect/com/xpn/xwiki/api/XWikiCompatibilityAspect.aj, xwiki-platform-core/xwiki-platform-legacy/xwiki-platform-legacy-oldcore/src/main/aspect/com/xpn/xwiki/doc/XWikiDocumentCompatibilityAspect.aj, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/XWiki.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/api/Document.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/api/XWiki.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/doc/XWikiDocument.java
JIRA: https://jira.xwiki.org/browse/XWIKI-11762
Deprecate all #displayTooltip and #addTooltip method and move them to legacy as they don't work since colibri according to @mflorea
=> XWIKI-11762: $displayTooltip method seem to be broken

xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-ui/src/main/resources/AppWithinMinutes/LiveTableViewSheet.xml
https://jira.xwiki.org/browse/XWIKI-20995
* Replaced the background image LESS with displayIcon macros in the link
* I needed to change the values of the icons for it to fit into the standard set of icons supported in XWiki. I think all icons fit their purpose both on the fontawesome and silk iconthemes.
=> XWIKI-20995: AWM livetable entry sheet view uses silk icons whatever the icon theme

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/javascript.vm, xwiki-platform-core/xwiki-platform-index/xwiki-platform-index-ui/src/main/resources/Main/Spaces.xml, xwiki-platform-core/xwiki-platform-panels/xwiki-platform-panels-ui/src/main/resources/Panels/Backlinks.xml, xwiki-platform-core/xwiki-platform-panels/xwiki-platform-panels-ui/src/main/resources/Panels/Spaces.xml, xwiki-platform-core/xwiki-platform-tag/xwiki-platform-tag-ui/src/main/resources/Main/Tags.xml, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/informationinline.vm, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/macros.vm, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/xwikivars.vm, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/js/xwiki/compatibility.js
JIRA: https://jira.xwiki.org/browse/XWIKI-14787
$blacklistedSpaces is an old variable that should have been deprecated a long time ago in favor of the hidden property of documents. Apparently it never was and we still have a few occurrences of it in the code. 
This PR is about cleaning those. 
Get rid of the $blacklistedSpaces variable defined in xwikivars.vm and remove remaining occurences. Uses XWikiDocument#isHidden in the few places where it wasn't yet the case.
Note that I kept the $blacklistedSpaces parameter of the macro `displayDocumentList` since it could still be used but the condition now check both that parameter and the hidden property.
=> XWIKI-14787: $blacklistedSpaces are not working anymore

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/js/xwiki/widgets/modalPopup.css, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/js/xwiki/widgets/modalPopup.js
https://jira.xwiki.org/browse/XWIKI-21650
* Updated style of the title section of the xdialog
* Added the class btn-xs to the close button (avoid it being way too large )
* Replaced the content with a cross icon (no need for alternative because there's a title on the button)
I decided to review a bit the style of this dialog header: replaced the `X` in the close button with a proper icon, made the text larger than regular instead of smaller, added padding and replaced float positioning with a flex, replaced the gradient background with a flat color
Here are a few screenshots of the close button in different use cases. We can see that it looks okay now, whether it's inside a xdialog-title container or not:
Here are the screenshots of those same UIs, before the PR, for reference (taken from …
=> XWIKI-21650: The XModal close button new style does not fit in its context

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-docker/src/test/it/org/xwiki/flamingo/test/docker/EditIT.java, xwiki-platform-core/xwiki-platform-panels/xwiki-platform-panels-test/xwiki-platform-panels-test-pageobjects/src/main/java/org/xwiki/panels/test/po/PageLayoutTabContent.java
https://jira.xwiki.org/browse/XWIKI-21370
* Fixed test regressions introduced in https://github.com/xwiki/xwiki-platform/commit/92c46a63a954990fb64e95b78a4a4e112cb1583a
Passed successfully :
* `mvn clean install -f xwiki-platform-core/xwiki-platform-panels/xwiki-platform-panels-test -Pdocker -Dxwiki.checkstyle.skip=true -Dxwiki.enforcer.skip=true -Dxwiki.revapi.skip=true` ([failure reference](https://ci.xwiki.org/job/XWiki%20Environment%20Tests/job/xwiki-platform/job/master/413/testReport/org.xwiki.panels.test.ui.docker/AllIT$NestedPanelsAdministrationIT/MariaDB_10_11__Tomcat_9_jdk17__Firefox___Docker_tests_for_xwiki_platform_panels___Build_for_MariaDB_10_11__Tomcat_9_jdk17__Firefox___Docker_tests_for_xwiki_platform_panels___resetPanels/))
*  `mvn clean install -f …
=> XWIKI-21370: Header structure uses too many H1

xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-api/pom.xml, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-api/src/test/java/org/xwiki/search/internal/SearchSuggestSourceObjectEvaluatorTest.java
This should fix the coverage check for xwiki-platform-search-api.
However, on its own, this doesn't test much.
I will also include another test for VelocityObjectPropertyEvaluator for actual coverage, but in the meantime feel free to merge this first if it's enough to fix the CI.
=> Add Component Test for SearchSuggestSourceObjectEvaluatorTest

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/drawer.less
https://jira.xwiki.org/browse/XWIKI-21702
* Refined the selector for style of the avatar in order to avoid unexpected collision with the new icon in the close drawer button (when it's an image, using Silk)
Button with the silk icon theme, before the PR
Button with the silk icon theme, after the PR
We can see that the button is much smaller after the PR, it's indeed of a similar size to the button when using font awesome:
Since this is just a style change on a very specific element, I did not proceed to further testing than the checks available in the screenshots above.
=> XWIKI-21702: Too big button for closing the drawer in a minimal distribution

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/layout.less
Jira: https://jira.xwiki.org/browse/XWIKI-21112
- The left and right border of the main content area and extra panes are not blurry anymore
- this is a consequence of https://github.com/xwiki/xwiki-platform/pull/2166 and must not be kept.
=> XWIKI-21112: Borders around the docextrapanes look fuzzy

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/variablesInit.vm, xwiki-platform-core/xwiki-platform-invitation/xwiki-platform-invitation-ui/src/main/resources/Invitation/InvitationCommon.xml
https://jira.xwiki.org/browse/XWIKI-21583
* Updated variablesInit to overwrite the default value got from bootstrap even when there's no theme
* Updated InvitationCommon.xml to match the changes made previously in InvitationConfig.xml
Running `mvn clean install -f xwiki-platform-core/xwiki-platform-invitation/xwiki-platform-invitation-test -Dxwiki.test.ui.wcag=true -Pdocker` now only returns two WCAG violations, that are unrelated to contrast, and not the 9 or so extra that are currently returned in CI.
Here is a demonstration of this link on an instance without a theme. We can see that unlike before, the link is correctly initialized to the expected value and not to the one from bootstrap.
=> XWIKI-21583: Invitation decline link lacks contrast

xwiki-platform-distribution/xwiki-platform-distribution-flavor/xwiki-platform-distribution-flavor-test/pom.xml
https://jira.xwiki.org/browse/XWIKI-21721
* Added back the removed tests.
The tests added in this PR did pass successfully `mvn clean install -f xwiki-platform-distribution/xwiki-platform-distribution-flavor/xwiki-platform-distribution-flavor-test/xwiki-platform-distribution-flavor-test-webstandards -Dxwiki.enforcer.skip=true`.
Since this is not a critical test, I don't think it's worth the risk to backport it. IMO it should just be merged on master (as of writing, 16.0.0-SNAPSHOT).
=> XWIKI-21721: Add back tests for Import and Export pages

xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/doc/XWikiDocument.java, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/doc/XWikiDocumentTest.java
* Add the wrapping HTML macro for any special character.
Jira issue: https://jira.xwiki.org/browse/XWIKI-20465
=> XWIKI-20465: AWM short text field ~ display bug

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/layout.less
https://jira.xwiki.org/browse/XWIKI-21756
Introduce back a border at the bottom of docextrapane.
- Visit of various pages with various amounts of content.
- `mvn clean install -Pquality -pl :xwiki-platform-flamingo-skin-resources`
=> XWIKI-21756: Missing border at the bottom of docextrapanes

xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/store/migration/AbstractDataMigrationManager.java
JIRA: https://jira.xwiki.org/browse/XWIKI-21783
* Fail the data migration manager initialization if two migrations are found with same version.
=> XWIKI-21783: Add a check to ensure we don't have two migrations with same DB version

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/drawer.less
https://jira.xwiki.org/browse/XWIKI-21785
* Added back style lost when removing the drawer dependency
* Removed some useless style
* Increased specificity for the padding-left of the submenu items so that they would be correctly offset
Before the regression vvv
Before the PR vvv
After the fix vvv
=> XWIKI-21785: Bullets are displayed next to flag icons in the Languages List in Drawer

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/drawer.less
https://jira.xwiki.org/browse/XWIKI-21784
* Removed the max-width set on the avatar that allowed it to get squished down
This relies on the fix provided in https://github.com/xwiki/xwiki-platform/pull/2748. Without this fix, only the default icon will be fixed, which is to say, the change will not have any influence.
We can see on this screenshot that the user name is wrapped in the middle of the word.
=> XWIKI-21784: Long names cause avatar to disappear from Drawer and the 'Close the drawer' button to be shifted out of view

xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/web/PropAddAction.java, xwiki-platform-core/xwiki-platform-xclass/xwiki-platform-xclass-test/xwiki-platform-xclass-test-docker/src/test/it/org/xwiki/xclass/test/ui/ClassSheetIT.java
https://jira.xwiki.org/browse/XWIKI-21807
* Don't rely on the status message which is not supported since jetty 10.x (https://github.com/jetty/jetty.project/issues/3225)
* Instead, set the status message as the response body and stop the action there (return false)
```bash
mvn clean install -Pquality,integration-tests,docker,legacy -pl :xwiki-platform-oldcore,:xwiki-platform-xclass-test-docker,:xwiki-platform-legacy-oldcore -Dit.test=ClassSheetIT
```
* stable-15.5.x
=> XWIKI-21807: Error when adding two properties of the same name not properly displayed in class editor

xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-macro/xwiki-platform-notifications-macro-ui/src/main/resources/XWiki/Notifications/Code/Macro/NotificationsMacro.xml
https://jira.xwiki.org/browse/XWIKI-21791
* Added back the JS class addition removed in XWIKI-18880
* Fixed a couple comments
* The changes for XWIKI-18880 are only about putting the button at the right place, not about knowing if the state of the event is read or not, which is still done in the JS.
We can see that after the PR, all unread notifications have the proper class, even those loaded via the `Load more` button.
Manual tests on a local distribution (see screenshots).
This behavior was an obvious regression so I doubt any test would have been changed to fit the regression. Moreover, I can't see any tests changed in [the commit where the regression was introduced](https://github.com/xwiki/xwiki-platform/pull/2335/files#diff-df6b621d8b03f4a097acf7d488c8f1d0f0a564637113d346c58b0da1983 …
=> XWIKI-21791: The background of unread events displayed with "Load older notifications" is not grey anymore, but white

xwiki-platform-core/xwiki-platform-model/xwiki-platform-model-validation/xwiki-platform-model-validation-ui/src/main/resources/XWiki/EntityNameValidation/Administration.xml, xwiki-platform-distribution/xwiki-platform-distribution-flavor/xwiki-platform-distribution-flavor-test/pom.xml
https://jira.xwiki.org/browse/XWIKI-21775
* Fixed the `for` attribute of a label
* Removed the comment from the test for WYSIWYG
* The label must have been copy/pasted too fast and not properly tested afterwards, because it pointed towards the same input field as its predecessor. Once the cause of this error was figured out, it was a pretty straightforward fix.
* Successfully passed `mvn clean install -f xwiki-platform-distribution/xwiki-platform-distribution-flavor/xwiki-platform-distribution-flavor-test/xwiki-platform-distribution-flavor-test-webstandards -Dxwiki.test.startXWiki=false` after updating the live distribution with the changes in this PR.
* Only on master.
=> XWIKI-21775: Admin section: make the name strategy section pass webstandard tests

xwiki-platform-core/xwiki-platform-export/xwiki-platform-export-pdf/xwiki-platform-export-pdf-ui/src/main/resources/XWiki/PDFExport/ConfigurationSheet.xml, xwiki-platform-distribution/xwiki-platform-distribution-flavor/xwiki-platform-distribution-flavor-test/pom.xml
https://jira.xwiki.org/browse/XWIKI-21777
* Added a missing space between attributes in the pdf generator select
* Replaced the comment with an actual test for the export PDF section
No visual change.
* Successfully passed `mvn clean install -f xwiki-platform-distribution/xwiki-platform-distribution-flavor/xwiki-platform-distribution-flavor-test/xwiki-platform-distribution-flavor-test-webstandards -Dxwiki.test.startXWiki=false` after updating the live distribution with the changes in this PR.
* Merge only on master.
=> XWIKI-21777: Admin section: make the PDF export section pass webstandard tests

xwiki-platform-core/xwiki-platform-panels/xwiki-platform-panels-ui/src/main/resources/Panels/PanelWizard.xml, xwiki-platform-distribution/xwiki-platform-distribution-flavor/xwiki-platform-distribution-flavor-test/pom.xml
https://jira.xwiki.org/browse/XWIKI-21774
* Replaced inline styling with regular style for the panel wizard tooltip
* Removed the comment from the test for the panel wizard
* The inline styling was unecessary, and could easily be replaced with some default styling. This default styling is overrode. Note that later on, inline styling is still added with javascript, but the main objective of this PR is to pass the test.
* Successfully passed `mvn clean install -f xwiki-platform-distribution/xwiki-platform-distribution-flavor/xwiki-platform-distribution-flavor-test/xwiki-platform-distribution-flavor-test-webstandards -Dxwiki.test.startXWiki=false`
* With manual test, I made sure that the functionnality still works. The tooltip still appears and disappears without any unexpected behavior.
* …
=> XWIKI-21774: Admin section: make the panel wizard section pass webstandard tests

xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-test/xwiki-platform-administration-test-pageobjects/src/main/java/org/xwiki/administration/test/po/LocalizationAdministrationSectionPage.java
* Fixed a test that should have been updated with [the fixes for XWIKI-13967](https://github.com/xwiki/xwiki-platform/pull/2770)
* When loading the page, the driver is waiting on all elements to be visible. In some conditions, we decided that one of those would not be visible. Therefore it blocked the driver and [failed the test](https://ci.xwiki.org/job/XWiki%20Environment%20Tests/job/xwiki-platform/job/master/447/testReport/junit/org.xwiki.localization.test.ui/AllIT$NestedLocalizationIT/PostgreSQL_16__Tomcat_9_jdk17__Chrome___Docker_tests_for_xwiki_platform_localization___Build_for_PostgreSQL_16__Tomcat_9_jdk17__Chrome___Docker_tests_for_xwiki_platform_localization___changeLanguageInMonolingualModeUsingTheAdministrationPreference_TestUtils__TestReference_/). Added an alternative to the …
=> XWIKI-13967: Confusion between Supported Languages and Default Languages when multilingual is set to no

xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-test/xwiki-platform-administration-test-docker/pom.xml, xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-test/xwiki-platform-administration-test-docker/src/test/it/org/xwiki/administration/test/ui/UsersGroupsRightsManagementIT.java
* Add necessary dependencies and missing programming rights, following https://github.com/xwiki/xwiki-platform/commit/cf8d5b73a911199be8ac91a98a3ec2e3e8d7529f.
N/A
N/A
The tests in UsersGroupsRightsManagementIT now pass locally.
* stable-14.10.x
* stable-15.5.x
* stable-16.0.x
=> [Misc] Fix UsersGroupsRightsManagementIT failing test

xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/LivedataBottombar.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/layouts/cards/LayoutCards.vue, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/layouts/table/LayoutTable.vue
https://jira.xwiki.org/browse/XWIKI-21849
* Introduce the pagination at the bottom of the table and cards layouts
* Add a `LivedataPagination` in the `LivedataBottombar` of `LayoutCards` and `LayoutTable`.
```
-Pquality,integration-tests,docker \
-pl :xwiki-platform-livedata-webjar -amd -f xwiki-platform-core/xwiki-platform-livedata
```
=> XWIKI-21849: No link to next page at the bottom of LiveData

xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-ui/src/main/resources/AppWithinMinutes/WizardStep.xml
https://jira.xwiki.org/browse/XWIKI-21618
* Replaced the hard coded character with an icon from the iconTheme
Before the changes proposed in this PR:
After the changes proposed in this PR:
Font Awesome icon theme
Silk icon theme
Only manual checks. From what I can see, there's no test covering elements related to .step-done .
* EDIT: after discussing on the chat, it seems like it's better to backport small bugfixes like this one to 15.10.X
=> XWIKI-21618: The wizard step-done icons are hard coded

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/export_modal.vm, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/locationPicker_macros.vm
https://jira.xwiki.org/browse/XWIKI-21600
* Replaced hard coded characters in locationPicker and export modals by iconTheme icons.
Before PR vvv
After PR - Font Awesome vvv
After PR - Silk vvv
Only manual testing, see the screenshots above.
This only changes the content of a couple elements. I doubt this would fail any test.
* EDIT: after discussing on the chat, it seems like it's better to backport small bugfixes like this one to 15.10.X
=> XWIKI-21600: Various close button modals do not use icons

xwiki-platform-core/xwiki-platform-tree/xwiki-platform-tree-webjar/pom.xml
https://jira.xwiki.org/browse/XWIKI-21869
* Updated version.
The webjar upgrade is done, so now this can safely be merge (see https://github.com/webjars/jstree/issues/29#event-11754385658)
Successfully passed `mvn clean install -amd -f xwiki-platform-core/xwiki-platform-tree -pl :xwiki-platform-tree-webjar  -Pquality,integration-tests,docker` :)
* 15.10.X (blocking fix for https://jira.xwiki.org/browse/XWIKI-21851 which should be backported )
=> XWIKI-21869: Upgrade to jstree 3.3.16

xwiki-platform-core/xwiki-platform-tree/xwiki-platform-tree-webjar/src/main/webjar/finder.js
https://jira.xwiki.org/browse/XWIKI-21851
* Updated the default option (introduced in JSTree 3.3.16) to allow reactivation of a link that's already selected.
[Video demo](https://youtu.be/tyoQDWhFdVY)
Properly passed `mvn clean install -amd -f xwiki-platform-core/xwiki-platform-tree -pl :xwiki-platform-tree-webjar  -Pquality,integration-tests,docker` after updating the .pom with the correct version of jstree.
Manual tests were conducted and did end up successful, see video demo. I had some issues getting my local distribution to get the updated jar, in the end I realized it was pulling it from cache...
* 15.10.X (regression introduced when updating to jstree 3.3.15 in 15.2-rc1)
=> XWIKI-21851: Found page in the Page Tree macro with a Solr field cannot be opened by left-clicking

xwiki-platform-distribution/xwiki-platform-distribution-flavor/xwiki-platform-distribution-flavor-test/pom.xml, xwiki-platform-tools/xwiki-platform-tool-standards-validator/src/main/java/org/xwiki/validator/HTML5DutchWebGuidelinesValidator.java
https://jira.xwiki.org/browse/XWIKI-21772
* Fixed the input label validation to allow another standard HTML way to link the label to its input.
* Removed the comment from the test for WYSIWYG
* The dutchwebguideline rule implementation did not take into account all possibilities for binding a label and an input, as defined in https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#examples
* Successfully passed `mvn clean install -f xwiki-platform-distribution/xwiki-platform-distribution-flavor/xwiki-platform-distribution-flavor-test/xwiki-platform-distribution-flavor-test-webstandards`
* Only on master.
=> XWIKI-21772: Admin section: make user directory pass webstandard tests

xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-api/src/main/java/org/xwiki/notifications/filters/internal/DefaultNotificationFilterPreferenceManager.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-api/src/test/java/org/xwiki/notifications/filters/internal/DefaultNotificationFilterPreferenceManagerTest.java
https://jira.xwiki.org/browse/XWIKI-21880
* Refactor DefaultNotificationFilterPreferenceManager to never throw immediately an exception thrown by a provider, but to only do it if all providers failed
* Provide a new test covering this behaviour
Use same pattern in every method of DefaultNotificationFilterPreferenceManager to always check if at least one provider managed to process a call, and to only throw the exception if all of them failed. 
Run of `mvn clean install -Pquality` in module `xwiki-platform-notification-filters-api`. 
=> XWIKI-21880: Cannot delete user defined filters

xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-fontawesome/src/main/resources/IconThemes/FontAwesome.xml
## JIRA
https://jira.xwiki.org/browse/XWIKI-21894
Use double quotes for `aria-hidden` attribute value. I.e.: `aria-hidden="true"`.
The single quotes leads to error for example with tour extension:
```
xwiki:Tour.WebHome:17:78: ERROR - [JSC_PARSE_ERROR] Parse error. ',' expected
17|       $('<a class="action actionLaunch"><span class="fa fa-play" aria-hidden='true'></span> Launch</a>')
^
1 error(s), 0 warning(s)
```
`./mvnw -e install -f xwiki-platform-core/xwiki-platform-icon/pom.xml`
=> XWIKI-21894: JSC_PARSE_ERROR in Tour.WebHome

xwiki-platform-core/xwiki-platform-tour/xwiki-platform-tour-ui/src/main/resources/Tour/WebHome.xml
https://jira.xwiki.org/browse/XWIKI-21894
* Added proper escaping to the icon
* The icon was not escaped, which explains the fail. The previous commit fixed the error, but didn't tackle the root cause.
Manual tests. Changes are not about front-end API.
* No, same as https://github.com/xwiki/xwiki-platform/pull/2895
=> XWIKI-21894: JSC_PARSE_ERROR in  Tour.WebHome

xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-server/src/main/java/org/xwiki/rest/internal/resources/BaseAttachmentsResource.java, xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-server/src/test/java/org/xwiki/rest/internal/resources/attachments/AttachmentsResourceImplTest.java
https://jira.xwiki.org/browse/XWIKI-21884
* check if the document where the current attachment is created is actually a new document and set the creator in this case
* for more context on when the issue can occur, there is https://jira.xwiki.org/browse/XWIKI-16476 and https://jira.xwiki.org/browse/XWIKI-16476 . These introduced the bug on Office Viewer Macro, but it is the reproducible for other macros that use the attachment picker as a parameter
**Before:**
**After:**
Run  `mvn clean install -Pquality,integration-tests,docker` in module `xwiki-platform-rest`.
=> XWIKI-21884: Uploading files during page creation step will mark XWikiGuest as creator

xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-rest/src/main/java/org/xwiki/notifications/rest/NotificationsResource.java
Hello 👋🏻 
I am an active contributor at Checkstyle.
We've had a failing CI of workflow related to `xwiki`
Investigation of the issue led me to this error :
```
[INFO] Starting audit...
[ERROR] /home/circleci/project/.ci-temp/xwiki-platform/xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-rest/src/main/java/org/xwiki/notifications/rest/NotificationsResource.java:131: Line is longer than 120 characters (found 123). [LineLength] Audit done.
[INFO] There is 1 error reported by Checkstyle 10.14.0-SNAPSHOT with checkstyle.xml ruleset. [ERROR] src/main/java/org/xwiki/notifications/rest/NotificationsResource.java:[131] (sizes) LineLength: Line is longer than 120 characters (found 123).
```
I have updated specific description comments belonging to file …
=> Update NotificationsResource description to comply with Checkstyle

xwiki-platform-core/xwiki-platform-eventstream/xwiki-platform-eventstream-api/src/main/java/org/xwiki/eventstream/internal/AbstractAsynchronousEventStore.java, xwiki-platform-core/xwiki-platform-eventstream/xwiki-platform-eventstream-api/src/test/java/org/xwiki/eventstream/internal/AsynchronousEventStoreTest.java
https://jira.xwiki.org/browse/XWIKI-21809
Some task output is Optional and we never want the Optional in the notification data: we do want what the Optional contains.
This PR provides a test to expose the bug and a naive fix.
I've not been able to provide a better fix as it would involve breaking APIs to not return Optional. On the long run I'm not sure it was really necessary to have Optional for the APIs here: it's basically only used to support backward compatibility with the legacy store AFAICS, so the Optional is never empty with the new store... 
`mvn clean install -Pquality` on `xwiki-platform-eventstream`
* 15.10.x
* 14.10.x (?)
=> XWIKI-21809: ClassCastException in DefaultEventConverterManager on a cluster environment

xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-profile/xwiki-platform-user-profile-ui/src/main/resources/XWiki/XWikiUserSheet.xml
https://jira.xwiki.org/browse/XWIKI-14054
* Added an alternative condition to allow direct edit of the profile picture to improve consistency of the UI for admins and people with right on profile pages
We can see on this screenshot that the PR allows the Administrator to edit directly the avatar of another user from the view mode, just like what is possible when viewing your own profile.
=> XWIKI-14054: Don't have the option to Edit users avatar from view mode as Admin (only my own)

xwiki-platform-core/xwiki-platform-dashboard/xwiki-platform-dashboard-ui/src/main/resources/Dashboard/XWikiUserDashboardSheet.xml, xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-profile/xwiki-platform-user-profile-ui/src/main/resources/XWiki/XWikiUserPreferencesSheet.xml, xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-profile/xwiki-platform-user-profile-ui/src/main/resources/XWiki/XWikiUserProfileSheet.xml, xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-profile/xwiki-platform-user-profile-ui/src/main/resources/XWiki/XWikiUserSheet.xml
https://jira.xwiki.org/browse/XWIKI-20435
* Replaced the custom color mappings with a bootstrap standard class for the action button
* It's still possible to display the pencil icon in white over white, but at least now it breaks contrast with the same conditions as any other `btn-default` (e.g. action buttons for page editing and creation).
* I also took the opportunity to remove a duplicated non color related style: ` div.editProfileCategory { float: right;}` and fix the codestyle in the CSS block where those changes are done
=> XWIKI-20435: Pencil icon in user profile can be displayed white over white and thus not be visible

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/forms.less
Jira: https://jira.xwiki.org/browse/XWIKI-21506
=> XWIKI-21506: Both customize buttons in XWiki Preferences > Themes don't have top padding

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-theme/xwiki-platform-flamingo-theme-ui/src/main/resources/FlamingoThemesCode/WebHomeSheet.xml
https://jira.xwiki.org/browse/XWIKI-21599
* Replaced the silk icon reference with a tangible iconset icon
Before the PR
After the PR
=> XWIKI-21599: Theme creation form uses a silk icon

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/action-menus.less
https://jira.xwiki.org/browse/XWIKI-21842
* Replaced the ScaleX transition with a width + padding one.
* This is a heavier implementation because layout needs to be recalculated multiple times (at multiple ), but we actually want layout to move around depending on the state of the search toggle, so it's worth it.
[Here is a demo of the changes brought in this PR](https://youtu.be/EjNdrz491JU), highlighted by following the steps described in the ticket.
No maven command ran. Changes are only styles. Moreover, this is a followup on https://github.com/xwiki/xwiki-platform/pull/2163/files, which did not change any tests beyond some webstandards (https://github.com/xwiki/xwiki-platform/pull/2193, unrelated to the changes in this PR).
* 15.10.X …
=> XWIKI-21842: The search bar takes too much width when folded

xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-test/xwiki-platform-administration-test-pageobjects/src/main/java/org/xwiki/administration/test/po/AdministrationMenu.java
* Updated selectors in the Administration pageobject
* The merge of https://github.com/xwiki/xwiki-platform/pull/2774 broke administration tests. It ended up being because the content of a selector was added some newlines. I decided to add a `normalize-space` call on this content to pass the test again with minimal changes.
None, test only PR.
Successfully passed `mvn clean install -f xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-test/xwiki-platform-administration-test-docker -Pdocker -Dit.test=AdministrationIT -Dgradle.cache.local.enabled=false -Dgradle.cache.remote.enabled=false`. Note that when building I get a massive chunk of logs for `java.lang.RuntimeException: Failed to get [role = [interface org.xwiki.search.solr.internal.api.SolrIndexer] hint = …
=> XWIKI-14873: Accordeon in the Administration misses an indicator to show they are expandable

xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/displayers/LivedataDisplayer.vue
https://jira.xwiki.org/browse/XWIKI-21935
https://forum.xwiki.org/t/annotate-live-data-entries-with-a-class-corresponding-to-the-entry-id/14153
* Add a class corresponding to the entry id at the root of each displayer
Below is the html of a cell presenting an attachment file size. Before, the only element allowing to specifically identify the cell by its property type was the `data-title`, which is translated.
The `filesize` class is now added aside the `livedata-displayer`.
```html
<td data-title="File size" class="cell">
<div class="livedata-displayer" data-livedata-property-id="filesize">
<div data-tippy-component-trigger="" tabindex="0">
<div class="view">
<div>
<div class="html-wrapper"> <span class="size" data-size="44816">43.8 KB</span>
</div>
</div>
</div>
</div>
</div>
</td>
``` …
=> XWIKI-21935: Annotate Live Data entries with a data property corresponding to the entry id

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/rating_macros.vm, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/uicomponents/rating/rating.css, xwiki-platform-distribution/xwiki-platform-distribution-flavor/xwiki-platform-distribution-flavor-test/pom.xml
https://jira.xwiki.org/browse/XWIKI-21778
* Replaced inline styling with a use of the meter element
* Added the webstandard test for the extension section.
* The meter style options are not standard HTML yet, so multiple style need to be used for webkit based browsers and Firefox. Changes have been tested manually with Firefox 121 and Chrome 120
* Regarding accessibility, it seems like the doc about meter on the Aria Practice Guide is [not up to date](https://github.com/w3c/aria-practices/issues/2905)
No UI Change expected.
before vvv
after (Firefox) vvv
after (Chrome) vvv
Successfully passed `mvn clean install -f xwiki-platform-distribution/xwiki-platform-distribution-flavor/xwiki-platform-distribution-flavor-test/xwiki-platform-distribution-flavor-test-webstandards …
=> XWIKI-21778: Admin section: make the Extension section pass webstandard tests

xwiki-platform-core/xwiki-platform-annotation/xwiki-platform-annotation-test/xwiki-platform-annotation-test-docker/src/test/it/org/xwiki/annotation/test/ui/AnnotationsIT.java, xwiki-platform-core/xwiki-platform-annotation/xwiki-platform-annotation-test/xwiki-platform-annotation-test-pageobjects/src/main/java/org/xwiki/annotation/test/po/AnnotatableViewPage.java, xwiki-platform-core/xwiki-platform-annotation/xwiki-platform-annotation-ui/src/main/resources/AnnotationCode/Script.xml, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/po/CommentsTab.java
https://jira.xwiki.org/browse/XWIKI-17702
* Listen for the clicks on the quotes of annotations in the comments sections.
* fetch the annotations if needed
* make the annotations visible
* go to the anchor
TODO:
```
-Pquality,integration-tests,docker \
-pl :xwiki-platform-annotation-test-docker,:xwiki-platform-annotation-test-pageobjects,:xwiki-platform-test-ui
```
* stable-16.1.x
=> XWIKI-17702: Annotation anchor not working when "show annotations" is off

xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-ui/src/main/resources/Main/SolrSearch.xml
https://jira.xwiki.org/browse/XWIKI-21747
* L720-721: Fixed the display of the facet header when zooming,now using flex instead of inline. Thanks to those changes, the wrapping will not affect the dropdown button.
* L722 + L729 + L732 : improved styling on the separator line under the header to avoid it breaking UI with high zoom levels where there's wrapping in the headers
* L764: Added a transition to smoothen out a state transition that was quite harsh
* L766: removed an incorrect style
* L820: set the text color on the toggler inside facets, that were a different shade of grey before.
* L720-721 are the solution to this issue, others are small improvements close to this issue.
beforePR (Firefox 180% zoom)
afterPR (Firefox 180% zoom)
afterPR (Firefox 210% zoom - 3 lines wrapped) We can …
=> XWIKI-21747: Some filters cannot be activated on the Solr search results page when resizing the browser tab

xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-test/xwiki-platform-administration-test-pageobjects/src/main/java/org/xwiki/administration/test/po/GlobalRightsAdministrationSectionPage.java, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/po/EditRightsPane.java
https://jira.xwiki.org/browse/XWIKI-21597
* Updated tests: 
* EditRightsPane used a custom class to hold the state of the icon. Replaced the reliance on the icon URL with the class on the button. Renamed everything in this class to let go off the icon, which is just a style thing and should not be based upon for such logic. 
* Changed the GlobalRightsAdministrationSectionPage object to fit the new attributes used on the checkbox.
None, test only modifications.
This PR solves two sets of regressions seen on CI:
* Successfully passed `mvn clean install -f xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-test/xwiki-platform-administration-test-pageobjects; mvn clean install -f xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platfor …
=> XWIKI-21597: Make the rights UI use icon themes

xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-profile/xwiki-platform-user-profile-ui/src/main/resources/XWiki/XWikiUserSheet.xml
https://jira.xwiki.org/browse/XWIKI-21969
* Added back bold on the title
* See ticket content on Jira
Before PR
After PR
None, because it's a low scope style to solve a regression that was not found in CI.
* 15.10.X
=> XWIKI-21969: User Sheet headers are not bold as expected

xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/api/Document.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/criteria/impl/RevisionCriteriaFactory.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/doc/XWikiDocument.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/store/XWikiHibernateVersioningStore.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/store/XWikiVersioningStoreInterface.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/store/hibernate/query/VersioningStoreQueryFactory.java, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/store/XWikiVersioningStoreInterfaceTest.java, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/store/hibernate/query/VersioningStoreQueryFactoryTest.java
https://jira.xwiki.org/browse/XWIKI-21922
* Introduce two new methods to `XWikiVersioningStoreInterface`: `getXWikiDocVersions` and `getXWikiDocVersionsCount`, both taking an instance of `RevisionCriteria` as parameter. They both have a default implementation that work by using the existing `getXWikiDocVersions` and filtering the results.
* Introduce an implementations for both methods in `XWikiHibernateVersioningStore`.
* Add the methods `XWikiDocument.getRevisionsCount` and `Document.getRevisionsCount` to expose the new count method.
* Edit `XWikiDocument.getRevisions(RevisionCriteria)` to use the new fetch method. The existing filtering was used as a basis for the default implementation of `XWikiVersioningStoreInterface.getXWikiDocVersions`.
* Move hibernate queries from …
=> XWIKI-21922: Introduce methods to fetch a subset of revisions in XWikiVersioningStoreInterface

xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-api/src/main/java/org/xwiki/livedata/LiveDataActionDescriptor.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-api/src/main/java/org/xwiki/livedata/LiveDataAsyncActionDescriptor.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-test/xwiki-platform-livedata-test-docker/pom.xml, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-test/xwiki-platform-livedata-test-docker/src/test/it/org/xwiki/livedata/test/ui/LiveDataIT.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/displayers/DisplayerActions.vue
https://jira.xwiki.org/browse/XWIKI-21944
https://forum.xwiki.org/t/introduce-the-notion-of-async-action-in-live-data/14155
* All actions to be executed asynchronously
* Livetable has a loosely defined notion of async action, allowing to make an action asynchronous
* This is a first step toward the same for LD in simple cases where a get action with no specific error handling is required
1. prevent the default click behavior
2. show a loading notification message
3. send a get request to the configured action URL
4. in case of success, replace the loading with a success notification message
5. in case of failure, replace the loading with a success notification message
```
-pl :xwiki-platform-livedata-api,:xwiki-platform-livedata-webjar \
-f …
```
=> XWIKI-21944: Allow live data action to be async

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/historyinline.vm
This requires merging https://github.com/xwiki/xwiki-platform/pull/2925 first.
https://jira.xwiki.org/browse/XWIKI-9961
* Stop loading the complete history from DB to get the history size.
Parts of the performance issues are already fixed by https://github.com/xwiki/xwiki-platform/pull/2925.
N/A
This patch was applied on an instance and displaying the history for a document of around 200k revisions was substantially faster. The pagination worked as expected, both with minor revisions shown and hidden.
=> XWIKI-9961: Improve performances for displaying the history tab

xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-api/src/main/java/org/xwiki/livedata/BaseDescriptor.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-api/src/main/java/org/xwiki/livedata/LiveDataPropertyDescriptor.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-api/src/main/java/org/xwiki/livedata/WithParameters.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-livetable/src/main/java/org/xwiki/livedata/internal/livetable/LiveTableLiveDataPropertyStore.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-livetable/src/test/java/org/xwiki/livedata/internal/livetable/LiveTableLiveDataPropertyStoreTest.java
https://jira.xwiki.org/browse/XWIKI-21971
* Provide a list of maps of label / values in case of LevelsClass
* Selectize is expecting a list of entries value/labels to create the options, and not a list of strings
N/A
Ran `mvn clean install -Pquality` on module livedata.
* 15.10.x
=> XWIKI-21971: No options when using LiveData with a LevelsClass column

xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-api/src/main/resources/liveDataConfiguration.json, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-api/src/test/resources/DefaultLiveDataConfigurationResolver.test, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-api/src/test/resources/withInitialize.json, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-livetable/src/main/java/org/xwiki/livedata/internal/livetable/LiveTableLiveDataPropertyStore.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-livetable/src/test/java/org/xwiki/livedata/internal/livetable/LiveTableLiveDataPropertyStoreTest.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/filters/FilterList.vue
https://jira.xwiki.org/browse/XWIKI-21972
* Fallback on  the default operator in FilterList instead of forcing using contains.
* Provide default operator for all base filters
* Prevent LiveTable source to override operators for the filter list defined in a property descriptor: we only want to override the operator in the specific case of a StringList for which we only equals and empty
* It's possible that a filter descriptor defines another default operator than contains (e.g. equals) and that the custom LD entry store expects the operator to never be contains: it's quite surprising to always obtain a contains whenever it's not even described in the filter descriptor... 
Ran `mvn clean install -Pquality,integration-tests,docker` on xwiki-platform-livedata
* Backport …
=> XWIKI-21972: FilterList shouldn't force using a contains operator in LiveData

xwiki-platform-core/xwiki-platform-eventstream/xwiki-platform-eventstream-api/src/main/java/org/xwiki/eventstream/internal/AbstractAsynchronousEventStore.java, xwiki-platform-core/xwiki-platform-eventstream/xwiki-platform-eventstream-api/src/test/java/org/xwiki/eventstream/internal/AsynchronousEventStoreTest.java
* Provide mocks to wait for notification event in AsynchronousEventStoreTest#mailentity
* stable-14.10.x
=> XWIKI-21970: AsynchronousEventStoreTest#mailentity is flickering

xwiki-platform-core/xwiki-platform-container/xwiki-platform-container-servlet/src/main/java/org/xwiki/container/servlet/filters/internal/SetCharacterEncodingFilter.java, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/WEB-INF/web.xml
https://jira.xwiki.org/browse/XWIKI-12674
* Set a default encoding for the response as Jersey doesn't seem to set one.
* Tomcat uses ISO-8859-1 by default which means that any response that doesn't explicitly set the character set will have broken UTF-8 characters. As XWiki basically always uses UTF-8 it makes sense to set a default to UTF-8.
`mvn clean install -U -Pdocker,legacy,integration-tests,snapshotModules -pl :xwiki-platform-container-servlet,:xwiki-platform-office-test-docker -Dmaven.test.failure.ignore -Dmaven.build.dir=target/mysql-8.3-pom-tomcat-9-jdk17-chrome -Dxwiki.checkstyle.skip=true -Dxwiki.surefire.captureconsole.skip=true -Dxwiki.revapi.skip=true -Dxwiki.spoon.skip=true -Dxwiki.enforcer.skip=true -Dxwiki.test.ui.database=mysql -Dxwiki.test.ui.databaseTag=8.3 …
=> XWIKI-12674: Replace Restlet with Jersey

xwiki-platform-core/xwiki-platform-legacy/xwiki-platform-legacy-oldcore/src/main/aspect/com/xpn/xwiki/XWikiCompatibilityAspect.aj
https://jira.xwiki.org/browse/XWIKI-13915
* Change implementation of legacy XWiki#getConfiguredSyntaxes to rely on ExtendedRenderingConfiguration#getConfiguredSyntaxes
N/A
Ran `mvn clean install -Pquality` on `xwiki-platform-legacy-oldcore`
* None
=> XWIKI-13915: $xwiki.getConfiguredSyntaxes() not equals to $services.rendering.getConfiguredSyntaxes()

xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/store/XWikiHibernateVersioningStore.java, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/store/XWikiHibernateVersioningStoreTest.java
This requires merging https://github.com/xwiki/xwiki-platform/pull/2925 first.
https://jira.xwiki.org/browse/XWIKI-9046
* Only load the last node when updating the document archive instead of the whole history.
N/A
N/A
Renaming a document with around 200k revisions was tested on an instance running this patch and it worked fine. Also, the saving process only took around 150ms instead of 1s without the patch applied (with HSQLDB).
=> XWIKI-9046: Renaming a document holding a lot of revisions can lead to an OutOfMemory exception

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-docker/src/test/it/org/xwiki/flamingo/test/docker/PagePickerIT.java, xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-server/src/main/java/org/xwiki/rest/internal/resources/BaseSearchResult.java, xwiki-platform-core/xwiki-platform-rest/xwiki-platform-rest-test/xwiki-platform-rest-test-tests/src/test/it/org/xwiki/rest/test/WikisResourceIT.java
https://jira.xwiki.org/browse/XWIKI-20632
* Search only in the actual page name, not in the space hierarchy.
* As explained in the comments on the issue, the search was never supposed to take the space hierarchy into account. This changes the code to follow the specification.
No UI change except that the search results are different now.
Manually tested the change, still need to see if we have any existing tests.
=> XWIKI-20632: Page searched by its exact name is not found in a page picker for a macro parameter when its subtree is larger than 10 pages

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/rightsUI.vm
https://jira.xwiki.org/browse/XWIKI-22010
* Renamed the r variable to a more explicit name : guestRights
* Replaced the string value when calling MSCheckbox for guest users with an int value, like it is done for any other user
* Indented blocks with a wrong indentation
This regression is caused because the MSCheckbox instantiation is done with a state of "1" (string) instead of 1 (int) for unregistered users.
This is inconsistent with the regular user/group MSCheckbox instantiation that used a numeric value. Beforehand it passed successfully because we used it as a list index. Now the check on the value doesn't pass and it's initialized with the default state : none.
___
I could think of 2 solutions:
1. Fix the state selector to accept int and string as a state.
2. Fix the MSCheckbox call …
=> XWIKI-22010: The rights buttons for Unregistered Users do not display anymore the value set after page refresh

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/rightsUI.vm
* Added incentation where it was missing
* Renamed a template variable to be more explicit and understandable
See https://github.com/xwiki/xwiki-platform/pull/3006
* None
=> [Misc] rightsUI code style change

xwiki-platform-core/xwiki-platform-attachment/xwiki-platform-attachment-api/src/test/java/org/xwiki/attachment/MoveStatusPagesTest.java, xwiki-platform-core/xwiki-platform-attachment/xwiki-platform-attachment-api/src/test/java/org/xwiki/attachment/RefactoringMacrosPageTest.java, xwiki-platform-core/xwiki-platform-attachment/xwiki-platform-attachment-ui/src/test/java/org/xwiki/attachment/AttachmentSelectorPageTest.java, xwiki-platform-core/xwiki-platform-help/xwiki-platform-help-ui/src/test/java/org/xwiki/help/XWikiSyntaxMacrosListPageTest.java, xwiki-platform-core/xwiki-platform-image/xwiki-platform-image-style/xwiki-platform-image-style-ui/src/test/java/org/xwiki/image/style/AdministrationPageTest.java, xwiki-platform-core/xwiki-platform-panels/xwiki-platform-panels-ui/src/test/java/org/xwiki/panels/CreatePanelTest.java, xwiki-platform-core/xwiki-platform-ratings/xwiki-platform-ratings-ui/src/test/java/org/xwiki/ratings/RatingsTest.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-ui/src/test/java/org/xwiki/refactoring/RefactoringConfigurationTest.java, xwiki-platform-core/xwiki-platform-wiki/xwiki-platform-wiki-ui/xwiki-platform-wiki-ui-mainwiki/src/test/java/org/xwiki/wiki/WikiManagerPageTest.java
https://jira.xwiki.org/browse/XCOMMONS-2276
* Remove all usages of ControlCharacterFilter as it's been removed in xwiki-commons-xml as part of the upgrade
* PR to be merged only after https://github.com/xwiki/xwiki-commons/pull/799 as it depends on it
* N/A
=> XCOMMONS-2276: Upgrade to HtmlCleaner 2.29

xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-api/pom.xml, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-api/src/main/java/org/xwiki/livedata/internal/StringLiveDataConfigurationResolver.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-api/src/main/resources/liveDataConfiguration.json, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-api/src/test/java/org/xwiki/livedata/internal/StringLiveDataConfigurationResolverTest.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-api/src/test/resources/DefaultLiveDataConfigurationResolver.test, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-api/src/test/resources/StringLiveDataConfigurationResolver.test, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-api/src/test/resources/withInitialize.json, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/attachment_macros.vm
https://jira.xwiki.org/browse/XWIKI-21982
There is an ongoing discussion https://forum.xwiki.org/t/allow-colors-for-live-data-action-icons/14237/14
We need to decide if we want to have colors on action icons on LD before merging this PR.
* Delete action icon are now red (`text-danger`) by default.
* Introduce a `extraClasses` property for the icons description. Those extra classes are merged with the classes coming from the icon resolution (through the icon set API).
* Also add a `text-danger` class on the span wrapping the delete action icon of the attachments LD as it generates its own html.
```
-pl :xwiki-platform-livedata-api \
-amd \
-f xwiki-platform-core/xwiki-platform-livedata \
-Pquality,integration-tests,docker
```
* Backport on …
=> XWIKI-21982: Live Data delete actions does not have a red icon

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/notification/email/macros.vm
https://jira.xwiki.org/browse/XWIKI-18802
* Removed the limit on the size of the breadcrumb displayed in the HTML notification mail.
Before the changes proposed in this PR:
After the changes proposed in this PR:
We can see here that the breadcrumb that had an ellipsis before is no longer ellipsed. Instead, it spans upon multiple lines.
(ignore the slight changes in color in between the two screenshots, they are caused by a change specific to my distribution, related to my work on https://github.com/xwiki/xwiki-platform/pull/3037)
It doesn't seem like this limit was covered in tests: https://github.com/search?q=repo%3Axwiki%2Fxwiki-platform+%22padding%3A+4px+8px%3B%22&type=code
Successfully passed `mvn clean install -f xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/ …
=> XWIKI-18802: Display the whole breadcrumb of the pages in the notification email

xwiki-platform-core/pom.xml, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-default/src/checkstyle/checkstyle-suppressions.xml, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-default/src/main/java/org/xwiki/notifications/filters/migration/R151002000XWIKI21448DataMigration.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-default/src/main/java/org/xwiki/notifications/filters/migration/R160100000XWIKI21738DataMigration.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-default/src/main/java/org/xwiki/notifications/filters/migration/R160300000XWIKI17243DataMigration.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-default/src/main/java/org/xwiki/notifications/filters/migration/WatchListObjectsRemovalTaskConsumer.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-default/src/main/resources/META-INF/components.txt
https://jira.xwiki.org/browse/XWIKI-22101
* Ensure to use proper WikiReference when resolving user document reference
* Provide some more logs to perform migration of users
* Move the migration so that it's executed in recent version of XS
* Put forgotten unstable annotations on migrations
*
N/A
None
* N/A
=> XWIKI-22101: WatchListClass is not properly migrated for subwiki users

xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-test/xwiki-platform-livedata-test-pageobjects/src/main/java/org/xwiki/livedata/test/po/TableLayoutElement.java
None, development change only, related to https://jira.xwiki.org/browse/XWIKI-21009
This PR aims at fixing [this failure on CI](https://ci.xwiki.org/job/XWiki%20Environment%20Tests/job/xwiki-platform/job/master/525/testReport/junit/org.xwiki.platform.notifications.test.ui/AllIT$NestedNotificationsSettingsIT/PostgreSQL_16__Tomcat_9_jdk17__Chrome___Docker_tests_for_xwiki_platform_notifications___Build_for_PostgreSQL_16__Tomcat_9_jdk17__Chrome___Docker_tests_for_xwiki_platform_notifications___customFiltersAndLiveData_TestUtils_/). 
* Fixed the sorting function to focus the new event handler itself
* I couldn't reproduce the CI fail locally unfortunately (matter of display size)... however the changes did not break tests so they should be correct.
* This does not pose an issue elsewhere …
=> Misc: Fix livedata sorting in docker tests

xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins/src/main/webjar/xwiki-filter/plugin.js, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-test/xwiki-platform-ckeditor-test-docker/src/test/it/org/xwiki/ckeditor/test/ui/FilterIT.java
https://jira.xwiki.org/browse/XWIKI-22024
* Fix a bug where erasing text using backspace would add more text in a list item.
* Add a Functional test for said bug.
* See attachments to the Jira issue: The bug seems to happen on chrome and not on firefox because the two browsers split the text nodes differently. On Firefox, after entering the reported triggering text, there is one text node before the caret, and one text node after the caret. Hence the order of the text nodes before the caret has no incidence. On Chrome, there are multiple text nodes before the caret. They get inserted in the wrong order, on the wrong text node.
* `mvn clean install -Dxwiki.test.ui.browser=chrome` in `xwiki-platform/xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-tests/xwiki-platform-cked …
=> XWIKI-22024: Strange Behaviour With "/" Completion in Lists

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/htmlheader.vm, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/general.less, xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-profile/xwiki-platform-user-profile-test/xwiki-platform-user-profile-test-pageobjects/src/main/java/org/xwiki/user/test/po/PreferencesUserProfilePage.java
https://jira.xwiki.org/browse/XWIKI-21492
* Fixed the xpaths to account for the new preference category
* Adding the `accessibility settings` section changed some of the xpaths (that are not very robust, they rely on order only, but unfortunately there's no other easy way)
* The selectors on the `PreferencesEditPage` page are not broken because their definition is more sturdy :)
None, development changes only.
None.
I don't have a build with the changes from XWIKI-21492 yet. However the issue here is quite easy to understand and fix.
Fixes https://ci.xwiki.org/job/XWiki%20Environment%20Tests/job/xwiki-platform/job/master/527/testReport/org.xwiki.user.test.ui/AllIT$NestedUserProfileIT/Oracle_19_3_0_se2__Jetty_10_jdk21__Firefox___Docker_tests_for_xwiki_platform_user_profile___Build_for_Oracl …
=> XWIKI-21492: Underline inline links

xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins/src/main/webjar/xwiki-filter/plugin.js, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-test/xwiki-platform-ckeditor-test-docker/src/test/it/org/xwiki/ckeditor/test/ui/ImageIT.java
https://jira.xwiki.org/browse/XWIKI-22073
* introduce a  `toHtml` event handler removing `data-widget` attributes from images
```
-Pquality,integration-tests,docker \
-pl :xwiki-platform-ckeditor-plugins,:xwiki-platform-ckeditor-test-docker
```
* stable-14.10.x
=> XWIKI-22073: Image specific syntax with data-widget causes CKEditor to freeze

xwiki-platform-core/xwiki-platform-panels/xwiki-platform-panels-ui/src/main/resources/Panels/IncludedPagesDocumentInformation.xml
https://jira.xwiki.org/browse/XWIKI-22108
* Make all HTML macros standalone to avoid wrapping in paragraphs
* Replace multiple dd tags by a single dd with a nested unordered list as otherwise we cannot avoid that the XWiki syntax content is wrapped inside a paragraph
* An alternative is to just move all HTML macros on their own lines to be standalone and accept that there is now some space between the items. The spacing could also be removed with custom CSS but to me this doesn't seem clean.
* I did not change the edit icon to use the icon theme to not introduce additional changes apart from what's really required to fix this issue.
Alternative with spacing between items:
Previous state:
```
mvn clean install -Pintegration-tests,docker,legacy,standalone,quality -pl …
```
=> XWIKI-22108: Extra empty paragraph and spacing in the information panel in edit mode

xwiki-platform-core/xwiki-platform-panels/xwiki-platform-panels-ui/src/main/resources/Panels/Applications.xml
https://jira.xwiki.org/browse/XWIKI-22118
* Updated the solution to use flex properties
* This flex property is more robust than what was used, and we can reduce the number of styles :)
Here is what this UI looks like with the changes proposed here, on Firefox and Chrome respectively:
Only manual (see screenshots) on FF and Chrome. Style change only.
* 15.10.X , to follow the commits for XWIKI-20843 (cause of this regression)
=> XWIKI-22118: Application panel "more applications" dropdown display is wrong on Chrome

xwiki-platform-core/xwiki-platform-attachment/xwiki-platform-attachment-picker/xwiki-platform-attachment-picker-ui/src/main/resources/Attachment/Picker/Code/CKEditorImagePlugin.xml
https://jira.xwiki.org/browse/XWIKI-22123
* replace the Javascript event name with the proper JQuery one
This is caused by the wrong event being used.
`keypress` is a Javascript event.
`keyup` is its JQuery equivalent.
We used JQuery in the fix for [XWIKI-19965](https://jira.xwiki.org/browse/XWIKI-19965).
When testing with Firefox, I guess the browser fixes things and the event handler is properly run. However it's not the case with Chromium and the feature is broken on these browsers.
None
Manual tests on Chrome, Edge and Firefox. Everything lines up now
* 16.3.0
=> XWIKI-22123: Pressing "Enter" key does not validate the image choice in Gallery on Chrome and Edge

xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-default/src/main/java/org/xwiki/notifications/filters/internal/livedata/custom/NotificationCustomFiltersLiveDataConfigurationProvider.java
https://jira.xwiki.org/browse/XWIKI-22119
* remove a custom definition of the delete icon to let the default one be used instead (therefore, using its default color).
`mvn clean install -pl :xwiki-platform-notifications-filters-default -Pquality`
* stable-16.3.x
=> XWIKI-22119: Live Data Delete actions from Notifications Custom Filters do not have red icons as other Live Data tables

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/uicomponents/suggest/xwiki.selectize.css
https://jira.xwiki.org/browse/XWIKI-22082
* always add enough padding on the selectize fields to avoid a change of width on load
**Limitation**
Empty
With content
Vertical space is always reserved for the spinner, even when the field is not loading.
As a consequence, the red square above is always there, preventing the field to get any smaller.
Note: as you can see the reserved space is also visible when some content is selected, making the minimal space between the selected value and the right caret always at least what you can see in the "with content" screenshot above.
I don't think this is an issue in practice as it only noticeable when the field is really constrained in its allowed horizontal space. 
=> XWIKI-22082: Some LiveData tables flicker on page refresh

xwiki-platform-core/xwiki-platform-model/xwiki-platform-model-api/src/main/java/org/xwiki/model/reference/DocumentReference.java, xwiki-platform-core/xwiki-platform-model/xwiki-platform-model-api/src/main/java/org/xwiki/model/reference/LocalPageReference.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/api/XWiki.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/events/DocumentUpdatedEventDescriptor.java
typo fix: "an Document" -> "a Document"
=> Typo "an Document"

xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins/src/main/webjar/xwiki-filter/plugin.js
https://jira.xwiki.org/browse/XWIKI-22146
* It is now possible to paste/drag-n-drop images
```
mvn clean install -Pquality,integration-tests,docker \
-pl :xwiki-platform-ckeditor-plugins -amd -f xwiki-platform-core/xwiki-platform-ckeditor
````
* Backport on branches: 
* stable-16.3.x
* stable-15.10.x (manually, as part of XWIKI-22073 since not released yet)
* stable-14.10.x (manually, as part of XWIKI-22073 since not released yet)
=> XWIKI-22146: Black square when drag-and-dropping an image in WYSIWYG

xwiki-platform-core/xwiki-platform-tree/xwiki-platform-tree-webjar/src/main/webjar/tree.js
This reverts xwiki/xwiki-platform#3015
Jira issue: https://jira.xwiki.org/browse/XWIKI-22151
Our code seems to heavily rely on the broken id values. We first need to decide how to continue from here, if we continue escaping the id values or if we replace the id values by a data attribute which sounds safer in the long run as it also avoids duplicate ids. I propose a simple revert for now until we have more carefully examined all places that are affected by this change.
=> XWIKI-22151: Impossible to move a page to a space with spaces in the name

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/macros.vm, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/test/java/org/xwiki/web/MacrosTest.java
https://jira.xwiki.org/browse/XWIKI-22152
Add support for variable like `$macro.myvar` in `setVariable` velocity macro.
So to fix the described issue, the idea is to improve the `setVariable` macro to be able to set correctly the value when the caller pass a parameter to set with something like this `$macro.xxx`.
For this we need the `$macro.parent` which give access to the `$macro` dict of the caller. Note that we need to call `$macro.parent.parent` because `$macro.parent` return the macro which is calling `setVariable` and so we want to call the parent of this one.
To test this we can use this small code
```velocity
#macro(myChildMacro $return)
#set($return = $NULL)
#setVariable("$return" "my new value")
#end
#macro(myParentMacro)
#myChildMacro($macro.childResult)
$macro.childResult …
```
=> XWIKI-22152 In velocity, can't use $macro.myVar with setVariable macro

xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-test/xwiki-platform-ckeditor-test-docker/src/test/it/org/xwiki/ckeditor/test/ui/ImageIT.java
https://jira.xwiki.org/browse/XWIKI-22041
* Added an alt in the copied content
* The image-alt WCAG violation happened when the viewpage where we copy the image was opened (during test setup). I updated the HTML to add an alt, and updated the result to match this change. 
* Now the assertion will fail if the alt is not kept through the pasting+editing process.
None, development issue only
Passed `mvn clean install -f xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-test -P docker,integration-tests,quality -Dxwiki.test.ui.wcag=true` successfully. In the wcagWarnings, there is no image-alt rule violation anymore.
With the more specific `mvn clean install -f xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-test -P docker,integration-tests,quality …
=> XWIKI-22041: Image pasted during tests has no alternative

xwiki-platform-core/xwiki-platform-tour/xwiki-platform-tour-ui/src/main/resources/TourCode/StepSheet.xml
https://jira.xwiki.org/browse/XWIKI-22040
* Paired the label with its select
No visual changes
Built change with `mvn clean install -f xwiki-platform-core/xwiki-platform-tour/xwiki-platform-tour-ui`.
Afterward successfully ran `mvn clean install -f xwiki-platform-core/xwiki-platform-tour/xwiki-platform-tour-test/ -Pdocker,quality,integration-tests -Dxwiki.test.ui.wcag=true`. There, no WCAG violation of the rule `select-name` were found.
[Here is the content of the resulting wcagWarnings.txt file](https://up1.xwikisas.com/#hvOiI7CpyJ1SyggMhiJyeA)
We can see that the violations for which this issue were reported are not here anymore.
* 15.10.x , pretty safe changes with a limited scope and coverage tests ran successfully.
=> XWIKI-22040: Select tour step order has no name

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/action-menus.less
https://jira.xwiki.org/browse/XWIKI-22148
* Define a css selector for the search results when the focus is out of the search field
* Define a transition when the search results get hidden (I'm not really satisfied of the result for now, if somebody has a suggestion for improvement, @tkrieck maybe?)
[Screencast from 06-05-2024 15:44:39.webm](https://github.com/xwiki/xwiki-platform/assets/327856/b4d385f6-8106-4baf-bed0-88d66d532264)
Manual tests.
* stable-16.3.x
=> XWIKI-22148: The search results are not hidden when the focus moves out of the quick search field

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/javascript.vm, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-ui/src/main/resources/XWiki/SearchSuggestCode.xml, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-ui/src/main/resources/XWiki/SearchSuggestSourceSheet.xml, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-webjar/src/main/webjar/searchSuggest.js
https://jira.xwiki.org/browse/XWIKI-22155
* Refactor `searchSuggest.js` by moving its Velocity code to `XWiki.SearchSuggestCode`
The Velocity code that returns the sources for search suggest can't work properly from a webjar because the context user is not propagated. The refactor fixes this issue.
N/A
The patch was applied manually to an instance with the main wiki private.
=> XWIKI-22155: Search suggest not working in private wikis

xwiki-platform-core/xwiki-platform-query/xwiki-platform-query-manager/src/main/java/org/xwiki/query/Query.java, xwiki-platform-core/xwiki-platform-query/xwiki-platform-query-manager/src/main/java/org/xwiki/query/WrappingQuery.java, xwiki-platform-core/xwiki-platform-query/xwiki-platform-query-manager/src/main/java/org/xwiki/query/internal/DefaultQuery.java, xwiki-platform-core/xwiki-platform-query/xwiki-platform-query-manager/src/main/java/org/xwiki/query/internal/ScriptQuery.java, xwiki-platform-core/xwiki-platform-query/xwiki-platform-query-manager/src/test/java/org/xwiki/query/internal/WrappingQueryTest.java
https://jira.xwiki.org/browse/XWIKI-22176
- `bindValue` and `bindValues` families of methods now return `this` in `WrappingQuery` to honor the documented behavior from the JavaDoc of the implemented interface `Query`
- I also renamed parameters called `var` in `Query` and its implemented interfaces
- I also made some fields `final` (but I can remove this commit if not wanted)
* Prefers squash: No (because there are Misc commits)
* Backport on branches: I'm not sure whether we want to backport this.  Probably.
=> XWIKI-22176: WrappingQuery's bindValue(s) methods unexpectedly return the wrapped query

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/general.less
https://jira.xwiki.org/browse/XWIKI-22138
* Replaced the classic CSS class selector with a `class contains` selector
* The subwiki add their IDs before all of the panel specific classes. There's no other robust way to select the Tips Panel than using this class. In order to still use it, I decided to go for an attribute selector based on class. This allows to use a `contains` boolean that would not be possible to do with the `.` notation.
* In the new class selector, I added a space after the `HelpTipsPanel`. This makes sure we don't match any panel in a wiki that would have `HelpTipsPanel` for ID. I think the selector as it is now is robust enough. It's not perfect and could still be matched unexpectedly in some very niche situations e.g., using a panel with an ID which contains the …
=> XWIKI-22138: Tips panel does not have underline style for links in subwiki

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-docker/src/test/it/org/xwiki/flamingo/test/docker/RenamePageIT.java, xwiki-platform-core/xwiki-platform-store/xwiki-platform-store-filesystem-oldcore/src/main/java/org/xwiki/store/legacy/store/internal/FilesystemAttachmentVersioningStore.java
https://jira.xwiki.org/browse/XWIKI-22183
* Ensure to not update the dirty flag when setting the attachment doc in #loadArchive
* New integration test to ensure renaming a document with an attachment doesn't mess up history
N/A
N/A
`mvn clean install -Dit.test=RenamePageIT#renamePageWithObjectAndAttachmentsPreserveHistory`
* 16.4.x
* Probably 15.10.x, to be confirmed
=> XWIKI-22183: FilesystemAttachmentVersioningStore#loadArchive leads to a switch of metadata dirty flag

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-docker/src/test/it/org/xwiki/flamingo/test/docker/VersionIT.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/store/XWikiHibernateVersioningStore.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/store/XWikiVersioningStoreInterface.java, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/store/XWikiVersioningStoreInterfaceTest.java
* apply the criteria over the archive in cache when possible instead of always loading it from database
* add an integration test to test that there's no regression on getRevision API even if the document is not stored
* For the fix I actually took back and improved code that was removed in https://github.com/xwiki/xwiki-platform/pull/2925/files#diff-bb23b7b80163e5c6cac4ba4592802e30d01ac1d463466454d47e8eaa5bf021d9L2678-L2716
N/A
Manually tested with the reproduction steps provided in jira ticket, and then executed `mvn clean install -Dit.test=VersionIT` and `mvn clean install -Pquality` in oldcore and legacy-oldcore. 
* 15.10.x
* 16.4.x
=> XWIKI-22187: Cannot get revisions with a criteria on a document not stored in DB

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/general.less
https://jira.xwiki.org/browse/XWIKI-22184
* Reduced the specificity of the underlining preference selector so that it's matched even during docker testing.
* The selector for the underlining preference rules was very specific. In this case it was too specific. It relied on the `.content` class, which is somehow related only to the state of the columns. In docker tests, there is no side panels, and the .content class is not on the body. This caused the automated tests to unexpectedly sill fail on all the link that were supposed to be fixed by the new underlining defaults. The fix reduces specificity on the style rule. This should not have any negative impact. AFAIR this rule was not here out of necessity, I just added it to avoid matching too wide. I should have considered the origin of …
=> XWIKI-22184: Change the underlining inline links behavior on a minimal install

xwiki-platform-tools/xwiki-platform-tool-jetty/xwiki-platform-tool-jetty-resources/src/main/resources/start_xwiki.bat, xwiki-platform-tools/xwiki-platform-tool-jetty/xwiki-platform-tool-jetty-resources/src/main/resources/start_xwiki_debug.bat
[https://jira.xwiki.org/browse/XWIKI-22200](https://jira.xwiki.org/browse/XWIKI-22200)
The files `start_xwiki.bat` and `start_xwiki_debug.bat` are missing a 'set' argument.
- Prefers squash: Yes
- Backport on branches: `stable-16.4.x`
=> XWIKI-22200: Missing `set` from .bat scripts causes 'XWIKI_OPTS' to not be recognized

xwiki-platform-core/xwiki-platform-legacy/xwiki-platform-legacy-events-hibernate/xwiki-platform-legacy-events-hibernate-api/src/test/java/org/xwiki/notifications/sources/internal/AbstractQueryGeneratorTest.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-api/src/main/java/org/xwiki/notifications/filters/NotificationFilterPreference.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-api/src/main/java/org/xwiki/notifications/filters/internal/scope/ScopeNotificationFilterPreference.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-default/src/main/java/org/xwiki/notifications/filters/internal/DefaultFilterPreferencesModelBridge.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-default/src/main/java/org/xwiki/notifications/filters/internal/DefaultNotificationFilterPreference.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-default/src/main/java/org/xwiki/notifications/filters/internal/migrators/NotificationFilterPreferencesMigrator.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-watch/src/main/java/org/xwiki/notifications/filters/watch/WatchedLocationReference.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-watch/src/main/java/org/xwiki/notifications/filters/watch/WatchedUserReference.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-watch/src/test/java/org/xwiki/notifications/filters/watch/WatchedLocationReferenceTest.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-sources/src/main/java/org/xwiki/notifications/sources/internal/QueryExpressionGenerator.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-sources/src/main/java/org/xwiki/notifications/sources/internal/TagNotificationFilterPreference.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-sources/src/test/java/org/xwiki/notifications/sources/internal/AbstractQueryGeneratorTest.java
https://jira.xwiki.org/browse/XWIKI-22209
* Ensure to not use anymore isActive and setActive
N/A
N/A
`mvn clean install -Pquality,integration-tests,docker` on module `xwiki-platform-notifications` and on `xwiki-platform-legacy-notifications`
* Backport on branches: No
=> XWIKI-22209: Deprecate NotificationFilterPreference#isActive

xwiki-platform-core/xwiki-platform-tour/xwiki-platform-tour-ui/src/main/resources/TourCode/TourJS.xml
https://jira.xwiki.org/browse/XWIKI-22137
* Removed the json escaping from the button text content
* AFAIK there's no easy string substitution function in Javascript (no way to easily add the translation after it's been serialized)
* Before the changes brought in XWIKI-21475, this string was not escaped at all. I suppose it's okay to remove escaping from it.
before PR vvv
after PR vvv
Manual test only, the changes causing this did not come with any test update: https://github.com/xwiki/xwiki-platform/pull/2585
* 15.10.X
=> XWIKI-22137: Tour button on the bottom right in French doesn't display properly characters with accents 

xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-macro/pom.xml, xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-macro/src/main/java/org/xwiki/icon/macro/internal/DisplayIconMacro.java, xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-macro/src/test/java/org/xwiki/icon/macro/IntegrationTests.java, xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-macro/src/test/java/org/xwiki/icon/macro/internal/DisplayIconMacroTest.java, xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-macro/src/test/resources/macrodisplayicon5.test
https://jira.xwiki.org/browse/XWIKI-22056
* Ensure that icon themes that output inline HTML are wrapped in a paragraph when the macro is standalone.
* An alternative would be to change the FontAwesome icon theme to enable cleaning in the HTML macro, this would fix the problem, too. But this would fix only this single icon theme.
The syntax that was provided in the issue now displays correctly:
```
mvn clean install -Pintegration-tests,docker,legacy,standalone,quality -pl :xwiki-platform-icon-macro
```
=> XWIKI-22056: Inserted icons on each line via Quick Actions are merged into one line in view mode

xwiki-platform-core/xwiki-platform-edit/xwiki-platform-edit-ui/src/main/resources/XWiki/InplaceEditing.xml, xwiki-platform-core/xwiki-platform-realtime/pom.xml, xwiki-platform-core/xwiki-platform-realtime/xwiki-platform-realtime-api/pom.xml, xwiki-platform-core/xwiki-platform-realtime/xwiki-platform-realtime-api/src/main/java/org/xwiki/realtime/internal/DefaultRealtimeEditorManager.java, xwiki-platform-core/xwiki-platform-realtime/xwiki-platform-realtime-api/src/main/java/org/xwiki/realtime/internal/RealtimeEditorManager.java, xwiki-platform-core/xwiki-platform-realtime/xwiki-platform-realtime-api/src/main/java/org/xwiki/realtime/internal/XWikiRealtimeDocumentLockEditConfirmationChecker.java, xwiki-platform-core/xwiki-platform-realtime/xwiki-platform-realtime-api/src/main/resources/META-INF/components.txt, xwiki-platform-core/xwiki-platform-realtime/xwiki-platform-realtime-api/src/test/java/org/xwiki/realtime/internal/DefaultRealtimeEditorManagerTest.java, xwiki-platform-core/xwiki-platform-realtime/xwiki-platform-realtime-api/src/test/java/org/xwiki/realtime/internal/XWikiRealtimeDocumentLockEditConfirmationCheckerTest.java, xwiki-platform-core/xwiki-platform-realtime/xwiki-platform-realtime-ui/pom.xml, xwiki-platform-core/xwiki-platform-realtime/xwiki-platform-realtime-wysiwyg/xwiki-platform-realtime-wysiwyg-test/xwiki-platform-realtime-wysiwyg-test-docker/src/test/it/org/xwiki/realtime/wysiwyg/test/ui/AllIT.java, xwiki-platform-core/xwiki-platform-realtime/xwiki-platform-realtime-wysiwyg/xwiki-platform-realtime-wysiwyg-test/xwiki-platform-realtime-wysiwyg-test-docker/src/test/it/org/xwiki/realtime/wysiwyg/test/ui/RealtimeWYSIWYGMultiUserIT.java
https://jira.xwiki.org/browse/XWIKI-21625
This PR adds an EditConfirmationChecker to the Realtime extension, allowing it to bypass the default XWikiDocumentLockEditConfirmationChecker which handles reporting locked pages warning.
Locked pages won't generate a warning when edited if a realtime session is active.
This PR also include new tests for this bug, they are located in `xwiki-platform-realtime-wysiwyg-test-docker`.
`xwiki-platform-realtime-wysiwyg-test-docker` using `mvn clean install` in the project directory.
Results: 
```
[ERROR] Failures: 
[ERROR]   AllIT$NestedRealtimeWYSIWYGEditorIT>RealtimeWYSIWYGEditorIT.inplaceEditableMacro:362 expected: <my info message
one two three> but was: <my info two three message>
[ERROR] Errors: 
[ERROR] …
```
=> XWIKI-21625: You shouldn't have to force the page lock to enter a realtime editing session

xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-api/pom.xml, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-api/src/main/java/org/xwiki/livedata/internal/DefaultLiveDataConfigurationResolver.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-api/src/main/java/org/xwiki/livedata/internal/LiveDataRendererConfiguration.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-api/src/test/java/org/xwiki/livedata/internal/LiveDataRendererConfigurationTest.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-api/src/test/resources/DefaultLiveDataConfigurationResolver.test, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-macro/src/test/java/org/xwiki/livedata/internal/macro/LiveDataMacroTest.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-test/xwiki-platform-livedata-test-docker/src/test/it/org/xwiki/livedata/test/ui/LiveDataIT.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-test/xwiki-platform-livedata-test-pageobjects/src/main/java/org/xwiki/livedata/test/po/LiveDataElement.java
https://jira.xwiki.org/browse/XWIKI-20650
* Change the LiveDataConfigurationResolver so that it adds the limit to the list of page sizes if it's not already there
* Refactor a bit existing LiveDataMacroTest so that it uses the real components for configuration resolver to have a better coverage 
* N/A
N/A
`mvn clean install -Pquality,integration-tests,docker` on module `xwiki-platform-livedata`
* No
=> XWIKI-20650: Impossible to switch back to 10 entries per page in LiveData after going to 15

xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-macros/xwiki-platform-rendering-macro-gallery/src/main/java/org/xwiki/rendering/internal/macro/gallery/GalleryMacro.java, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-macros/xwiki-platform-rendering-macro-gallery/src/test/resources/macrogallery1.test, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-macros/xwiki-platform-rendering-macro-gallery/src/test/resources/macrogallery2.test, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-macros/xwiki-platform-rendering-macro-gallery/src/test/resources/macrogallery3.test
https://jira.xwiki.org/browse/XWIKI-22304
* disable lightbox for the gallery macro
[IntegrationTests](https://github.com/xwiki/xwiki-platform/blob/master/xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-macros/xwiki-platform-rendering-macro-gallery/src/test/java/org/xwiki/rendering/macro/gallery/IntegrationTests.java)
* stable-16.5.x
=> XWIKI-22304: Do not trigger the lightbox feature for images from the Gallery macro

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/js/xwiki/compatibility.js, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/js/xwiki/xwiki.js
None
* Just moving some deprecated stuff from xwiki.js to compatibility.js
N/A
N/A
`mvn clean install -Pquality` on the module of the changes.
* No
=> [Misc] Clean up a bit xwiki.js to move deprecated stuff

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/hierarchy_macros.vm
https://jira.xwiki.org/browse/XWIKI-22287
* Extract code to variable to avoid mixing strings wrapped in the same type of quotes. 
None.
None.
* 15.10.x
=> XWIKI-22287: Error in attribute in XWiki Search (Search Facets > Location)

xwiki-platform-core/xwiki-platform-index/xwiki-platform-index-ui/src/main/resources/XWiki/DeletedDocuments.xml
https://jira.xwiki.org/browse/XWIKI-22261
* When javascript is deactivated, the list of Livetable of the deleted pages of the index is replace with a static table.
* The delete actions of this table are not well-formed (it contains two unescaped question marks)
```
mvn clean install -Pquality,integration-test,docker -f /home/mleduc/xwiki/master/xwiki-platform/xwiki-platform-core/xwiki-platform-index -pl :xwiki-platform-index-ui -amd
```
=> XWIKI-22261: Deleted pages table of the page index generates invalid links to permanently delete pages

xwiki-platform-core/xwiki-platform-model/xwiki-platform-model-api/src/main/java/org/xwiki/model/reference/DocumentReference.java, xwiki-platform-core/xwiki-platform-model/xwiki-platform-model-api/src/test/java/org/xwiki/model/reference/DocumentReferenceTest.java, xwiki-platform-core/xwiki-platform-ratings/xwiki-platform-ratings-api/src/main/java/org/xwiki/ratings/internal/SolrRatingsManager.java, xwiki-platform-core/xwiki-platform-ratings/xwiki-platform-ratings-api/src/main/java/org/xwiki/ratings/script/AbstractScriptRatingsManager.java, xwiki-platform-core/xwiki-platform-ratings/xwiki-platform-ratings-api/src/main/java/org/xwiki/ratings/script/RatingsScriptService.java, xwiki-platform-core/xwiki-platform-ratings/xwiki-platform-ratings-api/src/test/java/org/xwiki/ratings/internal/SolrRatingsManagerTest.java, xwiki-platform-core/xwiki-platform-ratings/xwiki-platform-ratings-ui/src/main/resources/XWiki/Ratings/RatingsUIX.xml
https://jira.xwiki.org/browse/XWIKI-18047
* Check server side if the page exists before adding a rating
* Hide the rating UI when the page does not exist
* N/A
N/A
```
mvn clean install -f xwiki-platform-core/xwiki-platform-ratings -Pquality,integration-tests,docker
mvn clean install -f xwiki-platform-core/xwiki-platform-like -Pquality,integration-tests,docker
```
=> XWIKI-18047: Non existing pages can be rated

xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-ui/src/main/resources/XWiki/Notifications/Code/NotificationsApplicationsPreferencesMacro.xml
https://jira.xwiki.org/browse/XWIKI-15049
* Changed the SSX type to LESS
* Replaced the former hard coded colors with values from the colorTheme.
* Added codestyle updates for the SSX - one empty line between adjacent style blocks.
* I decided to use the `@breadcrumb-bg` color here. Even if it's not semantically  exactly what we want,  it's still better than hard coding and should be correct contrast with the base text color.
Before PR (dark theme):
After PR:
Darkly
Iceberg
Kitty
Changes are style only, so I only checked manually. See screenshots above:
* 15.10.X , this change is fairly safe.
=> XWIKI-15049: NotificationsApplicationsPreferencesMacro stylesheet not using Color Themes variables

xwiki-platform-core/xwiki-platform-tree/xwiki-platform-tree-webjar/src/main/less/jstree/base.less, xwiki-platform-core/xwiki-platform-tree/xwiki-platform-tree-webjar/src/main/less/jstree/main.less, xwiki-platform-core/xwiki-platform-tree/xwiki-platform-tree-webjar/src/main/less/jstree/mixins.less, xwiki-platform-core/xwiki-platform-tree/xwiki-platform-tree-webjar/src/main/less/jstree/responsive.less
https://jira.xwiki.org/browse/XWIKI-20616
* Update files provided by `jstree` to use the ones provided in version `3.3.16` (version of `jstree` referenced in the `pom.xml`).
* Comment out the reference to `throbber.gif` in `jstree` `mixins.less` file as the gif file is no part of `xwiki-platform-tree-webjar` and rule is override in `tree.less` to use `spinner.gif`.
* By looking at files such as [`xwiki-platform-core/xwiki-platform-tree/xwiki-platform-tree-webjar/src/main/less/jstree/mixins.less`](https://github.com/xwiki/xwiki-platform/blob/52e78eb4d31a8b449cd9422412edb947df0f71c1/xwiki-platform-core/xwiki-platform-tree/xwiki-platform-tree-webjar/src/main/less/jstree/mixins.less) it appears they were part of version `3.3.5` or earlier (see for example this …
=> XWIKI-20616: Update jstree files and remove reference to throbber.gif

xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins/src/main/webjar/xwiki-realtime/plugin.js, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-ui/src/main/resources/CKEditor/Translations.xml, xwiki-platform-core/xwiki-platform-realtime/xwiki-platform-realtime-wysiwyg/xwiki-platform-realtime-wysiwyg-test/xwiki-platform-realtime-wysiwyg-test-docker/src/test/it/org/xwiki/realtime/wysiwyg/test/ui/RealtimeWYSIWYGEditorIT.java
https://jira.xwiki.org/browse/XWIKI-20191
* This PR brings the Source button back in the Realtime WYSIWYG Editor.
* When editing alone, the behavior is similar to how the source button behaved in the non-realtime ckeditor.
* When multiple users are involved, the realtime editing session is aborted when switching to source to prevent data loss.
* This PR also provides a functional test for the behavior of the source button in realtime context.
* When switching to source mode in the iframe based CKEditor, realtime collaboration cannot continue because the DOM on witch the patches are applied to is destroyed. The realtime collaboration needs to be interrupted while the user is in source mode. This has some implications.
* The source mode is always read-write.
* The decision whether to join …
=> XWIKI-20191: Add the Source button for the Realtime editor

xwiki-platform-distribution/xwiki-platform-distribution-flavor/xwiki-platform-distribution-flavor-data/pom.xml, xwiki-platform-distribution/xwiki-platform-distribution-flavor/xwiki-platform-distribution-flavor-test/xwiki-platform-distribution-flavor-test-ui/src/test/it/org/xwiki/test/ui/MandatoryDocInitializedTest.java, xwiki-platform-distribution/xwiki-platform-distribution-flavor/xwiki-platform-distribution-flavor-test/xwiki-platform-distribution-flavor-test-ui/src/test/it/org/xwiki/test/ui/XClassDeclaredTest.java
https://jira.xwiki.org/browse/XWIKI-22368
* Provide a test to check that mandatory document initializers are properly declared for the demo package
This PR is only about the test to add. I'm not sure it deserves to be added in other branches even if the actual fix of the ticket was backported.
Note that I put it in flavor-test-ui and not flavor-test-misc because that one apparently doesn't support yet using AbstractTest which is needed to use PO. 
N/A
`mvn clean install -Dpattern=XClassDeclaredTest` in `xwiki-platform-distribution-flavor-test-ui` but note that right now it exposes a few problems.
* None (check the description)
=> XWIKI-22368: UIExtensionClass imported properties removed after editing and rolling back

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/general.less
https://jira.xwiki.org/browse/XWIKI-22392
* Fixed the typo introduced in the commit for XWIKI-22120 and broke the improvements added for XWIKI-22120 and XWIKI-22214
* I probably added this typo when moving the changes from my local distribution to the repository on which the PR was based. The screenshots on the PR for XWIKI-22120 looked okay...
Screenshots of a distribution with the updated content of general.less : 
On both of those, the improvements that should have been added with XWIKI-22120 and XWIKI-22214 were not seen before updating the file. On both of those, we can see that there's no longer useless underlining.
Manual, see above.
* 16.4.X, same as https://github.com/xwiki/xwiki-platform/pull/3085
=> XWIKI-22392: Some Live Data links are still underlined although 'Underline links' setting is set to 'Only Inline Links'

xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-ui/src/main/resources/CKEditor/EditSheet.xml
https://jira.xwiki.org/browse/XWIKI-22334
* Overrode the inline style added by CKEditor for the tables.
* The selector is quite large, but it matches and takes priority over all the ckeditor table styles.
* This new style might decrease contrast with Dark Themes since this is one of the few colors we bring in the editor and it could clash. IMO this PR is good to merge as is, but we should consider the question of getting CKEditor to match the color theme (eg. not having a white background when you edit on a dark colortheme is quite huge for consistency and usability of dark colorthemes).
On the left, a default table before the changes proposed here, on the right it's the same table with the style proposed here applied:
None except for manual, see screenshot above.
* …
=> XWIKI-22334: Improve contrast of the CKEditor tables

xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins/src/main/webjar/xwiki-realtime/plugin.js, xwiki-platform-core/xwiki-platform-realtime/xwiki-platform-realtime-wysiwyg/xwiki-platform-realtime-wysiwyg-test/xwiki-platform-realtime-wysiwyg-test-docker/src/test/it/org/xwiki/realtime/wysiwyg/test/ui/RealtimeWYSIWYGEditorIT.java, xwiki-platform-core/xwiki-platform-realtime/xwiki-platform-realtime-wysiwyg/xwiki-platform-realtime-wysiwyg-test/xwiki-platform-realtime-wysiwyg-test-pageobjects/src/main/java/org/xwiki/realtime/wysiwyg/test/po/RealtimeWYSIWYGEditPage.java
https://jira.xwiki.org/browse/XWIKI-22367
Disable the "Allow Realtime" checkbox when in source mode.
Realtime editing is not supported when the user is editing the xwiki syntax source view within the WYSIWYG editor.
Thus, the user should not be able to join the realtime session when in source mode. 
This PR also changes the functional tests related to the source mode to ensure the user can't join the realtime editing session while in source mode.
`mvn clean install` in `xwiki-platform-realtime-wysiwyg-test-docker`
* stable-16.6.x
=> XWIKI-22367: Clicking on Allow Realtime Collaboration in Source mode leads to unexpected result

xwiki-platform-core/xwiki-platform-realtime/xwiki-platform-realtime-wysiwyg/xwiki-platform-realtime-wysiwyg-test/xwiki-platform-realtime-wysiwyg-test-docker/src/test/it/org/xwiki/realtime/wysiwyg/test/ui/RealtimeWYSIWYGEditorIT.java
https://jira.xwiki.org/browse/XWIKI-21452
This PR fixes the realtime WYSIWYG Editor tests.
*
The changes brought by the info box macro changes the behavior of XWiki, which needs to be taken into account in the tests.
*
`mvn clean install -Dxwiki.test.ui.browserTag=128.0` in `xwiki-platform-realtime-wysiwyg-test-docker`
```
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 605.9 s -- in org.xwiki.realtime.wysiwyg.test.ui.AllIT
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 17, Failures: 0, Errors: 0, Skipped: 0
```
* None.
=> XWIKI-21452: Macros info, success, warning and error are only distinguished by colors

xwiki-platform-core/xwiki-platform-index/xwiki-platform-index-ui/src/main/resources/XWiki/DeletedDocuments.xml, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/recyclebinlist.vm
https://jira.xwiki.org/browse/XWIKI-22448
* Removed the link if the deleted document batch id is null
We can see in the previous code that those links to the batch have an empty text only when the id of the batch is this empty text. In my opinion, having such a link when we don't have a proper batch id is not correct (probably coded with this intention anyways, but the way it was done does not work the best by today's standards).
test on a fresh distribution with the changes proposed in this PR
After building the changes with `mvn clean install -f xwiki-platform-core/xwiki-platform-web`, the WCAG build `mvn clean install -f xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-test/xwiki-platform-administration-test-docker/ …
=> XWIKI-22448: Batch id link for document restoration does not have any text

xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins/src/main/webjar/xwiki-image/imageSelector.js, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-ui/src/main/resources/CKEditor/ImageSelectorServiceUIX/Upload.xml
https://jira.xwiki.org/browse/XWIKI-21227
* Added a listener to reset the state of the upload input
* Added a reset of the modal state when reloading it.
This video displays the new behavior of the image selector (specifically the Upload tab) with the changes proposed in this PR:
https://github.com/user-attachments/assets/74653685-fe84-4ab6-846f-1fa88a310027
None excect manual (see video example above), this is specific enough of a use case to not fit any existing test.
* None
=> XWIKI-21227: Gray out the "Select" button when uploading an image through the image modal for the second time

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/misc.less
https://jira.xwiki.org/browse/XWIKI-22347
* Added a condition on the style to keep it working even when the state of the UI changes.
* In normal conditions, the right button is pushed to the far right by `justify-content: space-between;`. When it's the only child, this does not push it to the right anymore but keep it on the left by default. The CSS selector just makes sure that we update this style when the left button is not here to push as expected.
Video demonstration of the changes proposed in this PR.
https://github.com/user-attachments/assets/0b8013e8-071a-41b5-b39f-566ea12ce224
We can see that the UI is consistent whatever the number of buttons in the top part.
None except for manual (see video above), minimal scope style changes only. Moreover, the elements moved should still …
=> XWIKI-22347: Diff view misplaced button when there's no previous version

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/general.less
https://jira.xwiki.org/browse/XWIKI-22348
* Added underlining to the author of the comment currently getting written.
After the changes proposed in this PR: 
None, except manual on a local distrib (see screenshot above).
* 16.4.X - like XWIKI-21492
=> XWIKI-22348: Underlining of usernames is inconsistent between comment form and displayed comments

xwiki-platform-core/xwiki-platform-oldcore/src/main/resources/ApplicationResources.properties, xwiki-platform-core/xwiki-platform-ratings/xwiki-platform-ratings-api/src/test/java/org/xwiki/ratings/internal/SolrRatingsManagerTest.java, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/uicomponents/widgets/upload.css, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/uicomponents/widgets/upload.js
https://jira.xwiki.org/browse/XWIKI-15065
* Added icons to the generated nodes and removed their unsemantic counterpart from css backgrounds
I decided to go with a CSS only logic: instead of creating and deleting the icons based on the status, we use the logic already in place to hide/show the icons (all created at the start). There's only 4 of them, and they are not generated on every page load, so I think this is an appropriate solution.
Here is a screenshot from the issue report on Jira:
Hereafter is a screeenshot of the same UI after the changes proposed in this PR
=> XWIKI-15065: Replace Silk icons with Icon Themes values in attachments Upload component

xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-ui/src/main/resources/XWiki/AdminSheet.xml, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/rightsUI.vm
https://jira.xwiki.org/browse/XWIKI-18046
(also fixes https://jira.xwiki.org/browse/XWIKI-21539 )
* Unset the vertical align of radio buttons to pick user/group that caused a weird display due to an unexpected collision
* Limited the size of the first column of the table when there's not many rights along it
* Removed auto wrapping on some elements where it created inconsistencies in UI (still looks good without it)
* Overrode an unexpected collision between xform and the rights table (only for extension rights)
* Moved the line for the unregistered user rights to be just above the actual table lines (looks more consistent than regular line (almost) -> filter -> regular line)
* Tweaked colspans on filter elements to have them display side to side using the whole length of the table
This …
=> XWIKI-18046: Layout issues on Administration's Rights section

xwiki-platform-core/xwiki-platform-tree/xwiki-platform-tree-webjar/src/main/less/jstree/responsive.less
https://jira.xwiki.org/browse/XWIKI-22314
* Removed the unexpected style taken from jstree.
* This style uses a hard coded color, on mobile only. We can only see this inconsistency when testing on low width screens AND dark color themes. We don't have any automated testing with these conditions.
before the PR
after the PR
I built `mvn clean install -f xwiki-platform-core/xwiki-platform-tree/xwiki-platform-tree-webjar` successfully and replaced the jar in my test ditribution to get the screenshot above. Nothing more, since this is a rather specific scope style change.
* None
=> XWIKI-22314: Navigation tree items have an unexpected shadow with a mobile and dark theme.

xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-fontawesome/src/main/resources/IconThemes/FontAwesome.xml, xwiki-platform-core/xwiki-platform-panels/xwiki-platform-panels-ui/src/main/resources/Panels/WebHome.xml
https://jira.xwiki.org/browse/XWIKI-22131
* Added mapping in FontAwesome for the wand icon
* Replaced the xwiki syntax icon with a call to the icon velocity service.
* Since the wand icon is not standard, and not used anywhere else, I figured it didn't need to be added to the icon theme. I just added a mapping in the `Silk backward compatibility` section of the FontAwesome used by wikis by default. On other icon themes, if the wand icon is not defined, it will fall back to Silk, and have the exact same rendering :)
After the changes proposed in this PR: 
Manual tests only, low scope changes of the DOM structure. The changed element is non interactive, it does not appear at all in the docker tests for the panel module.
* 15.10.X
* 16.4.X
=> XWIKI-22131: Update the wand icon used in the Panel Application

xwiki-platform-core/xwiki-platform-menu/xwiki-platform-menu-ui/src/main/resources/Menu/MenuMacro.xml
https://jira.xwiki.org/browse/XWIKI-21966
* Added an event listener to close the currently navigated dropdown with `Escape`
* When focusing menu dropdown, pressing escape will collapse it and focus the toggler.
* Handling the focus `manually` is a thing to avoid. In this case:
* the focus is on an element that got hidden, so we should move it to somewhere where it makes sense to have it 
* we don't move it far from the context we were in (only a couple tabs away in most cases)
* we move it to an known and expected node
[Video demo to highlight the new behaviour](https://youtu.be/AmmzWLpd6gk)
Manual tests, see the video demo.
This component is not automatically tested (see changes in https://github.com/xwiki/xwiki-platform/pull/2078, which did not break any test), so no further testing.
* …
=> XWIKI-21966: Cannot exit horizontal drop-down menu using accessibility tools

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/headers.less
https://jira.xwiki.org/browse/XWIKI-22166
* Increased alpha on the icon, so that it would be visible enough even when not focused or hovered.
* Added a selector for the :focus pseudo class to benefit from the style already implemented for the :hover pseudo class (and improve consistency)
* Added padding around the icon so that the focus border is nice and square, not sticking on the side edges of the icon.
before changes in this PR, default and focused states:
after changes in this PR, default and focused states:
Manual tests, see above. Style change only so no test should be impacted.
* 15.10.X - pretty safe style changes.
=> XWIKI-22166: Contrast of paragraph edit buttons is too low

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/breadcrumbs.less, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/hierarchy_macros.vm
https://jira.xwiki.org/browse/XWIKI-22169
* Changed the nature of the dropdown toggler so that it can be keyboard focused
* Updated the style of this toggler so that focus is visible
* Reduced line height to avoid increasing the whole breadcrumb height by adding the 2px of margin (to fit the border) on the buttons.
* The dropdown togglers already rely on a common logic to handle their behavior (could use it with a mouse). All we had to do here was to make sure the toggler was keyboard accessible. The whole dropdown experience behind that is a regular xwiki tree, we do not need to update anything.
Here is a video illustrating the new behavior of the togglers:
https://github.com/xwiki/xwiki-platform/assets/28761965/160b13c6-8f0a-4fb7-a8f9-c740260b2a3b
Manual tests, see video above. 
* …
=> XWIKI-22169: Breadcrumb dropdowns for navigation should be keyboard accessible

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/commentsinline.vm
https://jira.xwiki.org/browse/XWIKI-22177
* Removed the login button from the guest comment UI.
* Didn't add any hint to replace this button. It seems to me like the UI is already clear enough about the user being a guest. See screenshots below.
* This button was added after a recent update for https://jira.xwiki.org/browse/XWIKI-12471 .
This is what a logged out user commenting on a wiki will see after the changes brought in this PR:
Step 1
Step 2
None, changes only concern content added for XWIKI-12471. We can see that no test goes with it: https://github.com/xwiki/xwiki-platform/commit/92d8ef004554730bb4b0b355f8aa2578f432a1ee
Only manual testing, see screenshot above.
* None
=> XWIKI-22177: Remove the login button for guest users commenting

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/diff_macros.vm
https://jira.xwiki.org/browse/XWIKI-22204
* Fixed missing underlining on the inline links in the diff boxes.
* Since this is a specific UI and structure around the anchor, I decided to go with the solution that's the least generic and just add the helper class to this element.
Before the PR on the ticket report itself.
Here is what it looks like after the PR:
We can see that all the inline links in the `From version` and `To version` blocks are properly underlined.
Manual tests only, see above.
* None
=> XWIKI-22204: Underline inline links on the change viewer

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/macros.vm
https://jira.xwiki.org/browse/XWIKI-22269
* Updated the user display macro according to what was discussed and approved in the proposal.
* This PR is related to the discussion that happened on https://forum.xwiki.org/t/proposal-update-the-structure-of-the-user-display-macro/14723 
None.
None, I could not find any test related to the specific content of this macro. Searching `-avatar-wrapper` in the project only returns a few results in style sheets and templates.
* None. This is a DOM change, so this could theorically break some extensions and should not be backported.
=> XWIKI-22269: Update the structure of the User display macro

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/uicomponents/viewers/comments.js
https://jira.xwiki.org/browse/XWIKI-22106
* Added startupFocus for the comment editor
Properly passed `mvn clean install -f xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-docker` after building the changes with `mvn clean install -f xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war` :+1: 
* None
=> XWIKI-22106: The comment button doesn't focus the WYSIWYG editor that gets inserted

xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-ui/src/main/resources/XWiki/Notifications/Code/NotificationsApplicationsPreferencesMacro.xml
https://jira.xwiki.org/browse/XWIKI-21766
* Reworked the way hiding sections work to make it easier to handle with CSS (and also avoid inline styling...)
* Added style for the rotation
* Used mvn xar:format to escape properly the new content added in the .xml
* Removing the custom way to hide the categories also simplifies the javascript. Now we can just use CSS `:has` to define the relation between button and dropdown, while before we had to call events on all the eventType events.
Demo of the Notification preference UI with the changes in this PR:
https://github.com/user-attachments/assets/5932733f-8a34-447f-bc9f-c0bc889a1299
Successfully passed 
```
mvn clean install -f xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-test/xwiki-platform-notifications-test-d …
```
=> XWIKI-21766: Notification preferences dropdown carets are not animated

xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/utilities/XWikiIcon.vue
https://jira.xwiki.org/browse/XWIKI-21878
* Reduced line length to match quality requirement imposed by eslint.
The build was failing with
`11:53:11,890 [INFO] /root/workspace/XWiki_xwiki-platform_master/xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/target/vue/utilities/XWikiIcon.vue
11:53:11,890 [INFO] 89:1 error This line has a length of 130. Maximum allowed is 120 max-len`
This PR goal is to fix this regression introduced in https://github.com/xwiki/xwiki-platform/pull/2888. 
Successfully ran the quality build that was failing:
`mvn clean install -f xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar -Pquality`
* None, which is the same as https://github.com/xwiki/xwiki-platform/pull/2888
=> XWIKI-21878: Various close button modals do not use intended icons

xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins/src/main/webjar/xwiki-link/plugin.js
https://jira.xwiki.org/browse/XWIKI-22508
* Ensure to use the defined name strategy before providing a link default value when selecting a text
*
Result with the preformatted name strategy: 
`mvn clean install -Pquality,integration-tests,docker` on `xwiki-platform-ckeditor`
* stable-16.8.x (once the RC is released)
=> XWIKI-22508: Creating a link in WYSIWYG by selecting text should follow the name strategy

xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-xwiki/src/main/java/org/xwiki/rendering/internal/wiki/XWikiWikiModel.java
https://jira.xwiki.org/browse/XWIKI-20546
* In XWikiWikiModel, if parsing CSS exception occurs, includes the exception in SLF4J call to get the full stack trace in the logs. This should help investigation of [XWIKI-20546](https://jira.xwiki.org/browse/XWIKI-20546) issue.
* Root cause of the issue might be related to thread safety issue with `CSSOMParser`.
`mvn -f xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-xwiki/pom.xml clean install` with Java 17 in Linux environment.
* Backport on branches: No
=> XWIKI-20546: Log CSS exception details

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-docker/src/test/it/org/xwiki/flamingo/test/docker/AttachmentIT.java, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-docker/src/test/resources/AttachmentIT/<strong>EscapedAttachment.txt, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-pageobjects/src/main/java/org/xwiki/flamingo/skin/test/po/AttachmentsPane.java
`<strong>EscapedAttachment.txt` is no longer stored on the repository. Instead, a file containing the `<strong>` tag is created during the test that requires it.
This change requires adding to the page object an upload method supporting local files, which is done through Selenium's  [LocalFileDetector](https://www.selenium.dev/selenium/docs/api/java/org/openqa/selenium/remote/LocalFileDetector.html).
`AttachmentIT` was run locally with the included changes.
=> [Misc] Fix repository clone error on NTFS filesystems

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/drawer.vm
[XWIKI-17873](https://jira.xwiki.org/browse/XWIKI-17873)
* Reuse URL `xredirect` parameter value if already set.
Currently, being, for example, on http://localhost:8080/xwiki/bin/view/Help/ and clicking on `Log-in` in the drawer load http://localhost:8080/xwiki/bin/login/XWiki/XWikiLogin?xredirect=%2Fxwiki%2Fbin%2Fview%2FHelp%2F&loginLink=1
Going again in the drawer and clicking on `Log-in` will load http://localhost:8080/xwiki/bin/login/XWiki/XWikiLogin?xredirect=%2Fxwiki%2Fbin%2Flogin%2FXWiki%2FXWikiLogin%3Fxredirect%3D%252Fxwiki%252Fbin%252Fview%252FHelp%252F%26loginLink%3D1&loginLink=1 and so on.
URL will indefinitely grow. That can be an issue when using crawler or when bots visit the wiki.
Same issue exists with register link.
This pull request will reuse value of `xredirect` if …
=> Fix the redirect URL growing indefinitely

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/messages.less
https://jira.xwiki.org/browse/XWIKI-22458
* Updated style to get back the margin next to the icon on inline blocks.
* Updated style of standalone boxes to both:
* fit the design agreed upon earlier
* avoid style regression on old hard-coded boxes
* See comments in the code
The style changes on inline messages are quick easy to test. However making sure that we did not break backward compatibility while making the new design was a bit more complicated. The first example shows various uses of the updated macro. The second and third example display some hard coded boxes that we can find in the UI: the second one contains a specific HTML content that did not work well with the style changes (one of the reasons to make the selector for new styles specific) -- the third one contains a hard …
=> XWIKI-22458: Message boxes variant style does not match initial design

xwiki-platform-distribution/xwiki-platform-distribution-debian/xwiki-platform-distribution-debian-xjetty/xwiki-platform-distribution-debian-xjetty-common/src/deb/resources/lib/systemd/system/xwiki.service, xwiki-platform-tools/xwiki-platform-tool-jetty/xwiki-platform-tool-jetty-resources/src/main/resources/start_xwiki.sh
This is related to [XWIKI-21211](https://jira.xwiki.org/browse/XWIKI-21211).
I have installed `xwiki-xjetty-mariadb` and it was failing "silently" at startup because I was using Java 8 by default (systemd was happy due to exit code being `0`).
Fixes:
- https://jira.xwiki.org/browse/XWIKI-22554
- https://jira.xwiki.org/browse/XWIKI-22555
- https://jira.xwiki.org/browse/XWIKI-22556
- https://jira.xwiki.org/browse/XWIKI-22552
- `start_xwiki.sh` wasn't performing any test regarding Java version available when running in non interactive mode. Now Java version verification is performed even in non interactive mode.
- `start_xwiki.sh` exit code is now `1` when:
- Java version is not found
- when Java version is lower then the minimal requirement
- when Java version is not yet fully supported and …
=> XWIKI-22552: The minimum supported Java version is not accurate in the XJetty startup script

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/uicomponents/widgets/upload.css
https://jira.xwiki.org/browse/XWIKI-22501
* Removed the opacity that was here without a specific good reason. This solves the contrast issue and AFAIK wasn't necessary for anything
* Added a border radius to improve consistency of the skin style since `XWIKI-21334: Uniformize the rounded edges of visual elements`
Before the PR:
After the PR:
I tried to execute tests with `mvn clean install -f xwiki-platform-core/xwiki-platform-attachment/xwiki-platform-attachment-test/xwiki-platform-attachment-test-docker -Pdocker -Dxwiki.test.ui.wcag=true` in order to check that the cotnrast issues reported by auto test are solved. It always failed halfway through though. It failed with the error message :
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.5.0:enforce …
```
=> XWIKI-22501: Attachment progress info is lacking contrast

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/accessdenied.vm
https://jira.xwiki.org/browse/XWIKI-20782
* Added the hierarchy template at the usual place.
* The position of the breadcrumb is the same as [the one from view.vm](https://github.com/xwiki/xwiki-platform/blob/8ea02b48f840f0c0ec3174daa38b48ac638427aa/xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/view.vm#L40)
before the PR:
after the changes proposed in this PR:
None
* None, low priority improvement.
=> XWIKI-20782: Display the breadcrumb on access denied pages

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/uicomponents/widgets/upload.css
https://jira.xwiki.org/browse/XWIKI-22501
____
Cherry pick with merge conflict resolution for https://github.com/xwiki/xwiki-platform/pull/3534
=> XWIKI-22501: Attachment progress info is lacking contrast -- 15.10.x cherry pick

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/uicomponents/widgets/upload.css
https://jira.xwiki.org/browse/XWIKI-22501
____
Cherry pick with merge conflict resolution for https://github.com/xwiki/xwiki-platform/pull/3534
=> XWIKI-22501: Attachment progress info is lacking contrast -- 16.4.x cherry pick

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/misc.less, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/login.vm
https://jira.xwiki.org/browse/XWIKI-18816
* Updated the DOM of the login form to be valid HTML
after the changes in the PR, manual tests did not show any change in the visual interface:
The selector for the submit button is here:
https://github.com/xwiki/xwiki-platform/blob/9ab12902498f0e5fa1e0355f9e57bee576d6803a/xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/po/LoginPage.java#L45
It shouldn't stop working with the changes. 
I could not find any element selector for the recovery links in this file or by searching `.xAdditional`.
* 15.10.X, 16.4.X since this is a small bugfix
=> XWIKI-18816: Useless and somewhat invalid <dt> markup on the login form

xwiki-platform-distribution/xwiki-platform-distribution-war-legacydependencies/pom.xml
https://jira.xwiki.org/browse/XCOMMONS-3174
* Move org.xwiki.cache.util.AbstractCache#AbstractCache() to legacy
*    introduce the cache-api legacy module (in a separate PR https://github.com/xwiki/xwiki-commons/pull/1128 on xwiki-commons)
*    add the new module to the legacy-war dependencies
Built the distribution module with the legacy profile.
* N/A
=> XCOMMONS-3174: Move org.xwiki.cache.util.AbstractCache#AbstractCache() to legacy

xwiki-platform-distribution/xwiki-platform-distribution-war-legacydependencies/pom.xml
https://jira.xwiki.org/browse/XCOMMONS-3175
* Move LocalInfinispanCacheFactory to legacy
* Introduce xwiki-commons-legacy-cache-infinispan and move LocalInfinispanCacheFactory (in a separate commons PR https://github.com/xwiki/xwiki-commons/pull/1129)
* add xwiki-commons-legacy-cache-infinispan to legacy war dependencies 
Build commons with profile legacy
* N/A
=> XCOMMONS-3175: Move LocalInfinispanCacheFactory to legacy

xwiki-platform-core/xwiki-platform-websocket/src/main/java/org/xwiki/websocket/script/WebSocketScriptService.java, xwiki-platform-core/xwiki-platform-websocket/src/test/java/org/xwiki/websocket/script/WebSocketScriptServiceTest.java
https://jira.xwiki.org/projects/XWIKI/issues/XWIKI-22547
* Add a check if the webapppath
is empty, as in set to `/` and exclude it from the URL building.
* Exclude the edge-case
and keep the generic code.
New test case was added.
✅ Checked with upstream code without fix to detect this issue.
✅ Run test locally
✅ Deploy fixed module to formerly faulty XWiki instance and observe the issue being fixed.
*
=> XWIKI-22547: Make websocket work with root servlet context

xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-ui/src/main/resources/XWiki/AdminPageUIX.xml, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/menus_content.vm, xwiki-platform-core/xwiki-platform-like/xwiki-platform-like-ui/src/main/resources/XWiki/Like/LikeViewersMenuUIX.xml
https://jira.xwiki.org/browse/XWIKI-12629
* Removed all items from the tmMoreActions menu when the page is not created yet, except for the `Children` view which actually does something (see XWIKI-12628)
* The `Page Rights` did have an unexpected side effect.
* The two other view displays were not included in the ticket initially, but I figured it'd be better to remove them in the same way when the page is not created. They would just display the same template as the view action.
Before the PR vvv
After the PR vvv
None except for manual tests. This is purely templating and I doubt any integration test tried to use those actions in this specific context.
* 16.4.X
* 15.10.X
=> XWIKI-12629: Page Right is shown when administering inexistent WebHome page

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/menus_content.vm
https://jira.xwiki.org/browse/XWIKI-14073
* Disabled the display of the copy action when the wiki server is in readonly mode.
* We cannot use directly the edit right here, because it might be allowed to edit onto the target space (and it'd be costly to check every possible target). However the readOnly mode would disable this feature in all cases (all possible targets are also readOnly because it's a wiki server parameter and not a wiki parameter). 
After the PR:
Quick manual test only (see screenshot above). The changes are minimal and I doubt a functional test tries out functionalities in the readonly mode.
* 16.4.x
* 15.10.x
=> XWIKI-14073: Hide the Copy action when the wiki is in readonly mode

xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-macros/xwiki-platform-rendering-macro-code/src/main/java/org/xwiki/rendering/internal/parser/pygments/DefaultPygmentsParserConfiguration.java, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-macros/xwiki-platform-rendering-macro-code/src/main/resources/pygments/code.py
https://jira.xwiki.org/browse/XWIKI-21387
* Updated the default style value for easier understanding
* Updated the documentation to be more precise
None, code quality change only.
None.
* None, similarly to https://github.com/xwiki/xwiki-platform/pull/3052
=> XWIKI-21387: The syntax highlighting done by the Code Macro lacks contrast

xwiki-platform-core/xwiki-platform-model/xwiki-platform-model-api/src/main/java/org/xwiki/model/reference/EntityReference.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/doc/XWikiDocument.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/internal/doc/BaseObjects.java
https://jira.xwiki.org/browse/XWIKI-22577
Trying to speed up the xobjects part of the document cloning.
* speed up DocumentReference#compareTo implementation, which is used when accessing xobjects
* optimize xobject cloning to avoid going through public add for each xobject and especially skip the manipulation of "null entries"
Not really any new test, since xobject cloning is well covered already, and it's not easy to test performances through automated testing.
* Backport on branches: 15.10.x, 16.10.x
=> XWIKI-22577: Cloning documents with many XObjects and high object numbers is slow

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/export_modal.vm
https://jira.xwiki.org/browse/XWIKI-22293
Use the `!` silencer on the velocity variable to prevent displaying the code in the resulting HTML.
* In the list of `$exportFormatsUIXs`, there are 2 types of data: `java.util.LinkedHashMap` and `org.xwiki.uiextension.internal.WikiUIExtension`. 
* Calling `java.util.LinkedHashMap#execute()` will not produce any result and `$services.rendering.render($uix.execute(), 'html/5.0')` will be displayed in the resulting HTML.
Before:
After:
N/A
* 16.4.x
* 15.10.x
=> XWIKI-22293: HTML error and non-rendered Velocity in export modal

xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/pom.xml, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/TestUtils.java, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/test/java/org/xwiki/test/ui/TestUtilsTest.java
https://jira.xwiki.org/browse/XWIKI-22625
* Improve getBaseBinURL so that it fallbacks on currentWiki if this one is provided
* Add a new getURL API taking into account the wiki name
* Extract the wiki from the entityReference when using getURL with a reference
* Provide new unit test for TestUtils
*
`mvn clean install -Pquality` on  the module
=> XWIKI-22625: TestUtils#getURL doesn't take the wiki into account

xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-ui/src/main/resources/XWiki/QuickSearchUIX.xml, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-webjar/src/main/webjar/searchSuggest.js, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/uicomponents/suggest/suggest.js
https://jira.xwiki.org/browse/XWIKI-21729
* Fired an event that was overwise unused
* Fixed its listener
* Added an optional argument for the suggest resetTimeout function (to allow a more precise control of the suggest panel)
Video demo: https://youtu.be/_XcDOmUG870
None, because 'cause changes' in [XWIKI-16140](https://jira.xwiki.org/browse/XWIKI-16140) and/or [XWIKI-20733](https://jira.xwiki.org/browse/XWIKI-20733) did not impact any tests (except webstandards, for reasons unrelated to the changes in this PR).
* 15.10.X to match with XWIKI-16140 and XWIKI-20733. IMO this is quite a low risk backport.
=> XWIKI-21729: Bad interaction between quick search and the drawer

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/messages.less
https://jira.xwiki.org/browse/XWIKI-22590
* Removed the overwrite of the default value for the messageBox colors. Usually those values are equal or very close. Without a colorTheme, one set of those values was not properly initialized.
* This change was added initially in https://github.com/xwiki/xwiki-platform/commit/beaeb18d3aaf1028f40cbfcf2a958f0c1c459b8d#diff-4c3b8ac56f692179aec4802811ccc197ac6055484d096a0570e808f7472d3d8c 
* This was squashed from the commit https://github.com/xwiki/xwiki-platform/pull/3023/commits/6c0b9e2701f805fa2b809982a259c7237f446e18 on the PR branch. I failed to see that this extra definition of the background-color was 1. superfluous because already defined in the mixin 2. incorrect in some situations.
* Bootstrap natively uses `@alert-<type>-bg` instead of …
=> XWIKI-22590: Links in message boxes lack contrast

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/breadcrumbs.less
https://jira.xwiki.org/browse/XWIKI-21116
* Updated the color used by the links in the breadcrumb dropdown.
Screenshot of the sandbox breadcrumb dropdown after the changes proposed in this PR. The color `@dropdown-link-color` has been set to pink. We can see that the links inside of the breadcrumb dropdown have the same color as the ones in the action buttons on the right. This color is different from the color of other "regular" links on the page.
Manual test only, see above. This is a style change that should not impact at all the UI for automated tests.
* 15.10.X
* 16.4.X
=> XWIKI-21116: `@dropdown-link-color` doesn't apply to breadcrumb's dropdown links

xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/java/org/xwiki/search/solr/internal/job/DiffDocumentIterator.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-test/xwiki-platform-search-test-docker/src/test/it/org/xwiki/search/test/ui/SolrIndexerIT.java
https://jira.xwiki.org/browse/XWIKI-22635
* Use an internal comparator that reproduces the order of Solr/the database.
* Add an integration test to verify that the sort order corresponds to the used comparator.
* This also improves the test to give more helpful errors in case the sorting order is different between database and Solr.
```
mvn clean install -Pquality,integration-tests,docker -pl :xwiki-platform-search-test-docker,:xwiki-platform-search-solr-api
```
* No idea, but might be a good idea to backport.
=> XWIKI-22635: On restart, documents to re-index aren't correctly computed

xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-ui/src/main/resources/XWiki/Registration.xml, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/uicomponents/widgets/validation/livevalidation_prototype.js
https://jira.xwiki.org/browse/XWIKI-22121
* Improved maintainability reported by SonarCloud, see https://sonarcloud.io/project/issues?id=org.xwiki.platform%3Axwiki-platform&assignees=Sereza7%40github&createdAt=2024-11-06T20%3A17%3A57%2B0000
* Fixed a regression caused by a typo in `Registration.xml`
None
Tested the regression fix manually locally. I do not expect any test suite to fail because of these changes. 
* None, like https://github.com/xwiki/xwiki-platform/pull/3155
=> XWIKI-22121: Improve the registration experience

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-docker/src/test/it/org/xwiki/flamingo/test/docker/RenamePageIT.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/XWiki.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/internal/render/DefaultOldRendering.java, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/XWikiTest.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/checkstyle/checkstyle-suppressions.xml, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/main/java/org/xwiki/refactoring/ReferenceRenamer.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/main/java/org/xwiki/refactoring/internal/ReferenceUpdater.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/main/java/org/xwiki/refactoring/internal/job/AbstractCopyOrMoveJob.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/main/java/org/xwiki/refactoring/internal/job/AbstractEntityJobWithChecks.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/main/java/org/xwiki/refactoring/internal/job/CopyJob.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/main/java/org/xwiki/refactoring/internal/job/InternalCopyOrMoveJobException.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/main/java/org/xwiki/refactoring/internal/job/MoveJob.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/main/java/org/xwiki/refactoring/internal/listener/BackLinkUpdaterListener.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/main/java/org/xwiki/refactoring/job/question/EntitySelection.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/test/java/org/xwiki/refactoring/internal/job/MoveJobTest.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/test/java/org/xwiki/refactoring/internal/job/RenameJobTest.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/test/java/org/xwiki/refactoring/internal/listener/BackLinkUpdaterListenerTest.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-default/src/main/java/org/xwiki/refactoring/internal/DefaultMacroRefactoring.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-default/src/main/java/org/xwiki/refactoring/internal/DefaultReferenceRenamer.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-default/src/main/java/org/xwiki/refactoring/internal/DefaultReferenceUpdater.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-default/src/main/java/org/xwiki/refactoring/internal/ResourceReferenceRenamer.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-default/src/test/java/org/xwiki/refactoring/internal/DefaultMacroRefactoringTest.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-default/src/test/java/org/xwiki/refactoring/internal/DefaultModelBridgeTest.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-default/src/test/java/org/xwiki/refactoring/internal/DefaultReferenceUpdaterTest.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-default/src/test/java/org/xwiki/refactoring/internal/ResourceReferenceRenamerTest.java, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-macros/xwiki-platform-rendering-macro-include/src/main/java/org/xwiki/rendering/internal/macro/include/IncludeMacroRefactoring.java, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-macros/xwiki-platform-rendering-macro-include/src/test/java/org/xwiki/rendering/internal/macro/include/IncludeMacroRefactoringTest.java, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-xwiki/src/main/java/org/xwiki/rendering/macro/MacroRefactoring.java, xwiki-platform-core/xwiki-platform-wiki/xwiki-platform-wiki-test/xwiki-platform-wiki-test-docker/src/test/it/org/xwiki/wiki/test/ui/SubWikiIT.java
https://jira.xwiki.org/browse/XWIKI-12987
The idea of this work is to:
1. Change the way `AbstractCopyOrMoveJob` works to perform computation of couple source/target documents before processing them
2. Provide a way to access that map source/target documents
3. Use that information when performing a call to `ReferenceRenamer` to define if a relative untyped link should be handled or not
The PR provides mainly:
- new APIs in `ReferenceRenamer` and `MacroRefactoring` to integrate the map of references that have been moved as part of same job
- refactorings of `AbstractCopyOrMoveJob`:
* specific computation of `getEntities` to actually visit the hierarchy and populate the entities with the couple of source/target documents
* new abstract methods to avoid duplications (not strictly needed for …
=> XWIKI-12987: Relative links are made absolute or even broken after moving a page

xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-test/xwiki-platform-administration-test-docker/src/test/it/org/xwiki/administration/test/ui/PageTemplatesIT.java, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-docker/src/test/it/org/xwiki/flamingo/test/docker/CreatePageAndSpaceIT.java, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/po/CreatePagePage.java, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/po/ViewPage.java, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/createinline.vm
https://jira.xwiki.org/browse/XWIKI-22659
* Compute proper reference in case of top level page
* Provide a new integration test covering the bug
* Change a bit existing PO for CreatePagePage to allow using it also
for the modal
N/A
N/A
Ran integration tests on flamingo-skin, administration and panel modules.
* 15.10.x
* 16.4.x
* 16.10.x
=> XWIKI-22659: createinline template error when clicking on a link to missing top level page

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/menus_content.vm, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/hierarchy_macros.vm
* Added type=`button` on the edit form buttons
* Those buttons were added recently for semantics.
* The breadcrumb caret was non semantic, it became a button when reworking the accessibility of the breadcrumb.
* The moreAction was a link, it got modified to a button in https://github.com/xwiki/xwiki-platform/commit/d5bc04d328a870ec14a3e35d6e48034f05b40be9
* Those butttons without a type were triggered instead of the default form action. Adding a type on both of them ensured that pressing enter on a form input would correctly submit the form.
None, no visual change.
Manual tests to reproduce the bug reported. With the changes, pressing enter properly started the preview mode.
* 15.10.X
* 16.4.X
Both of the causes got merged on both of those …
=> XWIKI-22523: Hitting the Enter key in fields on XWiki pages opens the hamburger content menu

xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-test/xwiki-platform-administration-test-pageobjects/src/main/java/org/xwiki/administration/test/po/ResetPasswordCompletePage.java, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/po/AbstractRegistrationPage.java, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/po/FormContainerElement.java, xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-profile/xwiki-platform-user-profile-test/xwiki-platform-user-profile-test-pageobjects/src/main/java/org/xwiki/user/test/po/ChangePasswordPage.java
https://jira.xwiki.org/browse/XWIKI-22680
related to the regression introduced yesterday: https://ci.xwiki.org/job/XWiki/job/xwiki-platform/job/stable-16.10.x/7/testReport/junit/org.xwiki.administration.test.ui/AllIT$NestedRegisterIT/Platform_Builds___main___integration_tests___IT_for_xwiki_platform_core_xwiki_platform_administration_xwiki_platform_administration_test_xwiki_platform_administration_test_docker___Build_for_IT_for_xwiki_platform_core_xwiki_platform_administration_xwiki_platform_administration_test_xwiki_platform_administration_test_docker___registerExistingUser_boolean__boolean__boolean__TestUtils__2_/
* Fixed the wait condition at the end of the formFilling function
* The wait was done on the password2 field. However, in the new testing conditions, this wait was incorrect …
=> XWIKI-22680: Regression on createAndDeleteUser

xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-ui/src/main/resources/XWiki/Registration.xml, xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-ui/src/main/resources/XWiki/RegistrationConfig.xml, xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-ui/src/main/resources/XWiki/TemplateProviderTranslations.zh.xml, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/menus_macros.vm, xwiki-platform-core/xwiki-platform-oldcore/pom.xml, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/org/xwiki/internal/authentication/LoginLinkUIExtension.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/org/xwiki/internal/authentication/RegisterLinkUIExtension.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/resources/META-INF/components.txt, xwiki-platform-core/xwiki-platform-oldcore/src/main/resources/templates/loginLink.vm, xwiki-platform-core/xwiki-platform-oldcore/src/main/resources/templates/registerLink.vm, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/internal/template/TemplateManagerTest.java, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-upgrade/src/main/java/org/xwiki/test/ui/UpgradeTest.java
https://jira.xwiki.org/browse/XWIKI-22695
Inject the login and register links from a UI extension implemented in Java rather than in a wiki page so they are available in a wiki page or when upgrading from a previous XWiki version before running the Distribution Wizard.
``xwiki-platform-distribution-flavor-test-upgrade-1510``
=> XWIKI-22695: Login and Registration links are missed in template

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-theme/xwiki-platform-flamingo-theme-test/xwiki-platform-flamingo-theme-test-pageobjects/src/main/java/org/xwiki/flamingo/test/po/ThemeApplicationWebHomePage.java, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-theme/xwiki-platform-flamingo-theme-ui/src/main/resources/FlamingoThemesCode/WebHomeSheet.xml
https://jira.xwiki.org/browse/XWIKI-22631
* Updated the layout
* Simplified the architecture of the page content (notably replaced a clearfix hack with a flex)
* Updated the pageobject to account for the small changes in HTML
Comparison of displays. There are minor changes, but IMO these are slight improvements.
Manual tests, see above. Checking the new style with the same conditions, I could not reproduce the weird out of line overflow that happenned before.
After building the changes with `mvn clean install -f xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-theme/xwiki-platform-flamingo-theme-ui` and `mvn clean install -f xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-theme/xwiki-platform-flamingo-theme-test/xwiki-platform-flamingo-theme-test-page …
=> XWIKI-22631: color theme list disorganized after changing color theme

xwiki-platform-core/xwiki-platform-bootstrap/src/main/less/dropdowns.less, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/tests/unit/LivedataDropdownMenu.spec.js, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/LivedataDropdownMenu.vue
https://jira.xwiki.org/browse/XWIKI-22485
* Updated the structure of the LiveData dropdown (namely, removed separator <li>s and grouped links together)
* Updated bootstrap dropdown styles to account for this new kind of separator in dropdowns.
* Updated the tests to work on this updated architecture
* Using separator list items can cause weird experiences for AT users, so instead of this I decided to just nest sublists inside the main list to make a semantic separation between the items.
* I brought the style changes directly on our fork of bootstrap because it made the most sense here. I could have added this style in the liveData code, but this change is generic so I thought it would be best as an update of our design system.
* I decided to keep the changes on the tests minimal. I could …
=> XWIKI-22485: Livedata option dropdown has no grouping semantics

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/tables.less
https://jira.xwiki.org/browse/XWIKI-22135
* Reduced visibility of the separators between fields
* This allows to spot out the entry separators more easily. 
* I usually don't like using color theme values with transparency (a dotted line from far away is the same as a semi transparent solid line...). However here
* We don't have any other color in the theme that would make sense to use here. No variation similar to `@table-border-muted` exists.
* This is a very specific use case. It's the only place in the UI we want this specific color semantic, and it's only for low width screens.
* It could be argued that the table displayed like that does not need any separator between the fields. The layout already conveys the structure corrrectly. Even with a bad combination of color, it's not a …
=> XWIKI-22135: Separations between Live Data entries are not visible enough on mobile`

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/action-menus.less
https://jira.xwiki.org/browse/XWIKI-13987
* Removed the space used by the left navbar when it has no children (xwiki standard's default)
I decided to be extra precise with the selector to not degrade the state of the navbar-left elements when there's some inside. I didn't test in this case, but the selector should avoid that this change have any unexpected effects.
The screens for the state before the PR are on the ticket itself. 
Here is what this UI looks like with the changes proposed in this PR:
https://github.com/user-attachments/assets/c340391a-9288-4bd1-a044-b9cd2c6e96ed
We can see that there's not a middle step anymore. The only two states of the navbar are: everything on one line, icon on one line and actions on the next one. 
Manual tests for style changes. See the video above. …
=> XWIKI-13987: Navbar height is increased by 5px on small device (<768px)

xwiki-platform-core/xwiki-platform-model/xwiki-platform-model-api/src/main/java/org/xwiki/model/internal/reference/AbstractReferenceEntityReferenceResolver.java, xwiki-platform-core/xwiki-platform-model/xwiki-platform-model-api/src/main/java/org/xwiki/model/internal/reference/AbstractStringEntityReferenceResolver.java, xwiki-platform-core/xwiki-platform-model/xwiki-platform-model-api/src/main/java/org/xwiki/model/reference/EntityReference.java, xwiki-platform-core/xwiki-platform-model/xwiki-platform-model-api/src/test/java/org/xwiki/model/internal/reference/DefaultReferenceEntityReferenceResolverTest.java, xwiki-platform-core/xwiki-platform-model/xwiki-platform-model-api/src/test/java/org/xwiki/model/internal/reference/RelativeStringEntityReferenceResolverTest.java, xwiki-platform-core/xwiki-platform-model/xwiki-platform-model-api/src/test/java/org/xwiki/model/internal/reference/WithParametersTest.java, xwiki-platform-core/xwiki-platform-model/xwiki-platform-model-api/src/test/java/org/xwiki/model/internal/reference/converter/EntityReferenceConverterTest.java, xwiki-platform-core/xwiki-platform-model/xwiki-platform-model-api/src/test/java/org/xwiki/model/reference/EntityReferenceSetTest.java, xwiki-platform-core/xwiki-platform-model/xwiki-platform-model-api/src/test/java/org/xwiki/model/reference/EntityReferenceTest.java
https://jira.xwiki.org/browse/XWIKI-22702
* Provide EntityReference#getParentType
* Use it in AbstractReferenceEntityReferenceResolver
* Provide a new test
*
*
=> XWIKI-22702: Provide parentType information in EntityReference

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-docker/src/test/it/org/xwiki/flamingo/test/docker/DeletePageIT.java, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-docker/src/test/it/org/xwiki/flamingo/test/docker/RenamePageIT.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-default/src/main/java/org/xwiki/refactoring/internal/ResourceReferenceRenamer.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-default/src/test/java/org/xwiki/refactoring/internal/DefaultReferenceUpdaterTest.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-default/src/test/java/org/xwiki/refactoring/internal/ResourceReferenceRenamerTest.java
https://jira.xwiki.org/browse/XWIKI-22571
* Use default serializer if the wiki is present in a link, not the compact serializer
* Provide unit test and integration test to cover this
* Right now the oracle to guess if the link contains a wiki is by using a regex, but I'm not very happy with this, we should probably find a better way for detecting it.
Run tests in modules:
* xwiki-platform-flamingo-skin-test-docker: 
* xwiki-platform-refactoring-default
* 16.10.x only
=> XWIKI-22571: Backlinks update changes an absolute reference to the moved page into one relative to the current wiki

xwiki-platform-core/xwiki-platform-oldcore/src/main/resources/ApplicationResources.properties, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/uicomponents/widgets/gallery/gallery.css, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/uicomponents/widgets/gallery/gallery.js
https://jira.xwiki.org/browse/XWIKI-22581
* Replaced the FocusCatcher artificial input.
* Updated the style of the gallery to use css grid instead of hackish solutions all around.
* Improved accessibility by changing the div interactive controllers with buttons.
* Improved consistency of the UI by adding standard round corners to the component.
* The solution picked had to go around a layout issue with the picture overflowing off the grid when wrapped and in full screen See the comment for more details on this issue.
Video demo:
https://github.com/user-attachments/assets/9e352d7c-f303-42fa-8830-5e1b0c9fd606
The gallery controls are tested both with the mouse and the keyboard.
Before:
After:
I tried to keep the visuals as close as possible as what was here before. The only differences I …
=> XWIKI-22581: FocusCatcher input has no label

xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-ui/src/main/resources/Main/SolrSearch.xml
https://jira.xwiki.org/browse/XWIKI-22675
* Removed the extra line
* The extra line was added through an `:after` pseudo element. It was its only purpose, we can remove this pseudo element without any side effect on the layout.
Before the changes proposed in this PR:
After the changes proposed in this PR:
We can see that the lines are removed, and the layout is substantially the same. Note that these screenshots have been made on an instance where change for [XWIKI-22674](https://github.com/xwiki/xwiki-platform/pull/3758) were already made, it's slightly different from the default today. However, the difference between the before and after screenshots highlights that the changes proposed here have the expected effect.
Manual test only. See screenshots above. The affected UI was just a …
=> XWIKI-22675: Extra line below facet items

xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-ui/src/main/resources/AppWithinMinutes/LiveTableViewSheet.xml
https://jira.xwiki.org/browse/XWIKI-22723
* Removed the extra icon.
* There are two other uses of `$services.icon.render` in this XML's templates. However, those are for hardcodded box. Those will be removed at the same time as the boxes are moved to a standard macro use, see [XWIKI-22433](https://github.com/xwiki/xwiki-platform/pull/3555)
After the changes. We can see on the picture below that the duplicated icon is no more and things still look alright.
None, this is a minor UI change on a non interactive element. Moreover, this regression on UI was found "by hand" and not reported by automated tests, so there's a high chance that the tests for this element are strict enough to be broken by this change.
* 16.10.X
=> XWIKI-22723: Warning message for application move has duplicated icons

xwiki-platform-core/xwiki-platform-tour/xwiki-platform-tour-ui/src/main/resources/TourCode/StepSheet.xml, xwiki-platform-core/xwiki-platform-tour/xwiki-platform-tour-ui/src/main/resources/TourCode/StepsListing.xml
https://jira.xwiki.org/browse/XWIKI-21629
* Removed the operation on the order number that caused confusion
* Removed similar operations, I searched in the module all uses of `mathtool`.
On this first screenshot, we can see that the list displayed now starts as expected with the order 0.
One of the annex changes is to make sure the options when creating and editing a step are displayed from 0 too. Just changing the displayed order does not break anything, those options had a non visible order that was used programatically and contained the correct value already.
After building the changes, successfully built the docker tests `mvn clean install -f xwiki-platform-core/xwiki-platform-tour/xwiki-platform-tour-test/xwiki-platform-tour-test-docker` …
=> XWIKI-21629: The step order displayed in inline edit is not consistent with the order from objects editor

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/uicomponents/widgets/notification.js
https://jira.xwiki.org/browse/XWIKI-22709
* Added the `alert` role to xnotifications.
Using browserStack with Chrome 130 + NVDA ->
https://github.com/user-attachments/assets/4dc4287c-3654-4302-921d-54d25af46ea7
We can see that the content of the xnotifications for saving are now read out.
None, except manual tests (see above). As far as I could see, the new attribute would not impact any test checking things on this element: https://github.com/search?q=repo%3Axwiki%2Fxwiki-platform%20xnotification&type=code 
* 16.10.X
=> XWIKI-22709: XNotifications should have the alert role

xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins/src/main/webjar/xwiki-link/plugin.js
https://jira.xwiki.org/browse/XWIKI-22496
* Updated the HTML of the button
* Added this button in the focusList
* Removed weird listeners that would come with this focusList
https://github.com/user-attachments/assets/072b09e1-9cd6-463b-b739-2c776ca2dd5a
Note that there's still issues with the pagepicker mode dropdown, but this PR's goal is not to fix this.
Successfully built `mvn clean install -f xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins ;mvn clean install -f xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-webjar/` and tested manually these changes on a live instance (see video above)
* 16.10.X
=> XWIKI-22496: Link dialog option button is not keyboard operable

xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins/src/main/webjar/xwiki-source/plugin.js, xwiki-platform-core/xwiki-platform-display/xwiki-platform-display-api/src/main/java/org/xwiki/display/internal/DocumentContentAsyncExecutor.java
https://jira.xwiki.org/browse/XWIKI-22738
* Set the target syntax on the transformation context, when displaying the document content, based on the display parameters
* Fix the URL used by the WYSIWYG editor to convert the HTML
* I'm worried by the fact that I had to update the HTML Converter URL to remove the ``outputSyntax=plain``. This parameter is used in lots of places in conjunction with the ``get`` action, so I'm worried there might be other regressions...
None
=> XWIKI-22738: Target syntax is not set on the transformation context when the document content is rendered

xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-notifiers/xwiki-platform-notifications-notifiers-default/src/main/java/org/xwiki/notifications/notifiers/internal/email/AbstractMimeMessageIterator.java
* https://jira.xwiki.org/browse/XWIKI-20109
*  Added common headers to notification emails to prevent autoresponses from various emails autoreply
* This PR replaces https://github.com/xwiki/xwiki-platform/pull/1907
N/A
TBD
* 16.10.x
=> XWIKI-20109: Notification headers for autoreplies

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/messages.less
https://jira.xwiki.org/browse/XWIKI-22800
* Cleaned up selectors. With the new improved DOM, there's no need for selectors specific to CKeditor
* Added `flex-grow` on the content+title+image element. This way, whatever is in it, it will use all the available space in the macro.
NA
Before the PR:
After the PR:
Style change only. We don't have automatic tests to check their validity. I ran manual tests on my local instance. AFAICS these changes did not break the style and only fixed the place that was faulty. The most dangerous thing is that I removed the CKEditor specific selectors. From what I can remember, we needed them at first because the structure was different. With the current structure, in standard WYSIWYG mode as well as in inline mode, these new selectors seem to be enough.
* …
=> XWIKI-22800: Message boxes content doesn't extend to the right of the box

xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-ui/src/main/resources/XWiki/Notifications/Code/NotificationsSystemFiltersPreferencesMacro.xml
https://jira.xwiki.org/browse/XWIKI-22801
* Add missing dependency to xwiki-bootstrap-switch in the javascript of NotificationSystemFilterPreferences
* N/A
mvn clean install -Pquality,integration-tests,docker on notification module
* 17.0.x
* 16.10.x
* 16.4.x
=> XWIKI-22801: Toggles aren't displayed as expected when using "Notifications System Filters Preferences" macro

xwiki-platform-core/xwiki-platform-annotation/xwiki-platform-annotation-rest/src/main/java/org/xwiki/annotation/rest/internal/AnnotationsRESTResource.java, xwiki-platform-core/xwiki-platform-annotation/xwiki-platform-annotation-rest/src/main/java/org/xwiki/annotation/rest/internal/AnnotationsTranslationRESTResource.java, xwiki-platform-core/xwiki-platform-annotation/xwiki-platform-annotation-rest/src/main/java/org/xwiki/annotation/rest/internal/SingleAnnotationRESTResource.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-rest/src/main/java/org/xwiki/livedata/internal/rest/DefaultLiveDataEntriesResource.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-rest/src/main/java/org/xwiki/livedata/internal/rest/DefaultLiveDataEntryPropertyResource.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-rest/src/main/java/org/xwiki/livedata/internal/rest/DefaultLiveDataEntryResource.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-rest/src/main/java/org/xwiki/livedata/internal/rest/DefaultLiveDataPropertiesResource.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-rest/src/main/java/org/xwiki/livedata/internal/rest/DefaultLiveDataPropertyResource.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-rest/src/main/java/org/xwiki/livedata/internal/rest/DefaultLiveDataPropertyTypeResource.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-rest/src/main/java/org/xwiki/livedata/internal/rest/DefaultLiveDataPropertyTypesResource.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-rest/src/main/java/org/xwiki/livedata/internal/rest/DefaultLiveDataSourceResource.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-rest/src/main/java/org/xwiki/livedata/internal/rest/DefaultLiveDataSourcesResource.java, xwiki-platform-core/xwiki-platform-netflux/xwiki-platform-netflux-rest/src/main/java/org/xwiki/netflux/internal/rest/DefaultPageChannelsResource.java, xwiki-platform-core/xwiki-platform-repository/xwiki-platform-repository-server-api/src/main/java/org/xwiki/repository/internal/resources/ExtensionRESTResource.java, xwiki-platform-core/xwiki-platform-repository/xwiki-platform-repository-server-api/src/main/java/org/xwiki/repository/internal/resources/ExtensionVersionFileRESTResource.java, xwiki-platform-core/xwiki-platform-repository/xwiki-platform-repository-server-api/src/main/java/org/xwiki/repository/internal/resources/ExtensionVersionRESTResource.java, xwiki-platform-core/xwiki-platform-repository/xwiki-platform-repository-server-api/src/main/java/org/xwiki/repository/internal/resources/ExtensionVersionsRESTResource.java, xwiki-platform-core/xwiki-platform-repository/xwiki-platform-repository-server-api/src/main/java/org/xwiki/repository/internal/resources/ExtensionsRESTResource.java, xwiki-platform-core/xwiki-platform-repository/xwiki-platform-repository-server-api/src/main/java/org/xwiki/repository/internal/resources/RepositoryRESTResource.java, xwiki-platform-core/xwiki-platform-repository/xwiki-platform-repository-server-api/src/main/java/org/xwiki/repository/internal/resources/SearchRESTResource.java
https://jira.xwiki.org/browse/XWIKI-22807
* race condition when several livedata requests are executed concurrently
* remove all the `@Singleton` annotations from children of XWikiResource, in particular on `DefaultLiveDataEntriesResource`, to prevent `org.xwiki.rest.XWikiResource#uriInfo` to be shared between requests.
N/A
- run all the functional tests from annotation, livedata, netflux and repository server
* stable-17.0.x
=> XWIKI-22807: Livedata REST result have inconsistent results when called concurrently

xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-ui/src/main/resources/XWiki/Registration.xml
https://jira.xwiki.org/browse/XWIKI-22706
* Trimmed the output of the validation script so that it doesn't disturb the layout when there's no error message.
* See comments in the code.
The state before the PR was buggy, see Jira ticket. 
Here is the form before any submission:
Here is the form after a submission done as described in the ticket def:
Here is the form with an error returned by the serverside validation (for the sake of ease of testing, I simulated such an error message by updating the `register_macros.vm` template a bit):
I wanted to make sure everything was alright here since my change somehow went against the previous comment.
The content impacted here looked definitely buggy. If this content had been tested in automatic tests, it would have been caught by CI, but it …
=> XWIKI-22706: The text on registration page is cut after applying invalid input

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/uicomponents/dashboard/dashboard.js
https://jira.xwiki.org/browse/XWIKI-22814
* Fixed the layout construction to make sure everything is fine if there's a warning box.
* Removed typos
* Instead of placing the buttons after the warning message if there's one, we should have placed their container. Should have been done when adding this container in [XWIKI-11043](https://github.com/xwiki/xwiki-platform/pull/2648).
Before the PR:
After the PR:
Successfully built the changes with `mvn clean install -f xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war -Pquality`.
Manual tests as seen in the screenshots above.
* 16.10.X
=> XWIKI-22814: Dashboard buttons layout is broken when there's a warning message

xwiki-platform-tools/xwiki-platform-tool-jetty/xwiki-platform-tool-jetty-resources/src/main/resources/start_xwiki_debug.sh
https://jira.xwiki.org/browse/XWIKI-22829
Call ./start-xwiki.sh with bash to avoid running into a permission denied error.
* Backport on branches: all the supported branches would be good but this is not a huge issue, so none is fine too
=> XWIKI-22829: ./start_xwiki_debug.sh: Permission denied when running ./start_xwiki.sh

xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-test/xwiki-platform-administration-test-docker/src/test/it/org/xwiki/administration/test/ui/AdministrationIT.java, xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-test/xwiki-platform-administration-test-pageobjects/src/main/java/org/xwiki/administration/test/po/PresentationAdministrationPage.java, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/po/InformationPane.java
https://jira.xwiki.org/browse/XWIKI-22409
* add a functional test for the "show information" setting in the Presentation section of the administration
* add a new test in `AdministrationIT`
* Introduce `PresentationAdministrationPage` in xwiki-platform-administration-test-pageobjects
* Add new methods in `InformationPane` (`xwiki-platform-test-ui`) to check whether the panel exists or does not
Execution of `xwiki-platform-administration-test-docker`
* 16.4.x
* 15.10.x
=> XWIKI-22409: Add automated test for "Show Page Information Tab (No)"

xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-server/xwiki-platform-search-solr-server-core-search/src/main/resources/conf/managed-schema.xml
https://jira.xwiki.org/browse/XWIKI-22820
* Configure the "string" field type with docValues="true" as in the default configuration. In tests, this eliminates all fields in the field cache apart from the caches for title_sort and author_display_sort, which seem small in comparison.
* I don't know if we could or should also eliminate the field caches for the sorting caches, which seems to be the [lowercase](https://github.com/xwiki/xwiki-platform/blob/b4ca3da6a7eeaafba99e4076c708a3ea71a4a246/xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-server/xwiki-platform-search-solr-server-core-search/src/main/resources/conf/managed-schema.xml#L636-L642) field type.
* I'm not sure if we should do anything for performing an automatic …
=> XWIKI-22820: Solr field cache uses a lot of RAM

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/macros.vm, xwiki-platform-core/xwiki-platform-livetable/xwiki-platform-livetable-ui/src/main/resources/XWiki/LiveTableResultsMacros.xml, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/macros.vm
https://jira.xwiki.org/browse/XWIKI-22791
This PR makes the computation of the Live Table tag happen only when requested rather than systematically.
`mvn clean install -Pquality,integration-tests,docker` ran on modules: 
- xwiki-platform-web
- xwiki-platform-flamingo-skin-resources
- xwiki-platform-livetable
Ran specific docker tests:
- LiveTableGeneratorIT
- AppsLiveTableIT
=> XWIKI-22791: Costly and unconditional tag cloud computation done for all live table requests using the default source

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/uicomponents/widgets/gallery/gallery.css
https://jira.xwiki.org/browse/XWIKI-22865
* Fixed the issue specific to chromiums. This fix has no impact on the Firefox styles.
* Tried out this fix because of https://stackoverflow.com/questions/50542629/make-image-fit-css-grid
* Since the value is non limitative and it was not set anywhere else for this element, this has no effect on the Firefox display, and only "expected" effects on Chrome/Edge.
* From what I can understand, this is just a quirk of using an image directly in a grid layout.
Here is a video demo showcasing the effect of the change. Made on Edge latest on browserstack.
https://github.com/user-attachments/assets/ffde77ca-eef5-4241-86b9-fd1c215fa2e1
Manual tests only, on Chrome, Edge and Firefox. The layout is now the same on the three browsers. Took the opportunity to …
=> XWIKI-22865: Gallery Macro does not display correctly images anymore on Chrome and Edge

xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-requiredrights/xwiki-platform-security-requiredrights-default/src/main/java/org/xwiki/platform/security/requiredrights/internal/analyzer/DefaultMacroBlockRequiredRightAnalyzer.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-requiredrights/xwiki-platform-security-requiredrights-default/src/main/resources/ApplicationResources.properties, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-requiredrights/xwiki-platform-security-requiredrights-default/src/test/java/org/xwiki/platform/security/requiredrights/internal/analyzer/DefaultMacroBlockRequiredRightAnalyzerTest.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-requiredrights/xwiki-platform-security-requiredrights-macro/pom.xml, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-requiredrights/xwiki-platform-security-requiredrights-macro/src/main/java/org/xwiki/platform/security/requiredrights/MacroParameterRequiredRightsAnalyzer.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-requiredrights/xwiki-platform-security-requiredrights-macro/src/main/java/org/xwiki/platform/security/requiredrights/internal/MacroContentSourceReferenceMacroParameterRequiredRightsAnalyzer.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-requiredrights/xwiki-platform-security-requiredrights-macro/src/main/java/org/xwiki/platform/security/requiredrights/internal/WikiSyntaxMacroParameterRequiredRightsAnalyzer.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-requiredrights/xwiki-platform-security-requiredrights-macro/src/main/resources/ApplicationResources.properties, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-requiredrights/xwiki-platform-security-requiredrights-macro/src/main/resources/META-INF/components.txt, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-requiredrights/xwiki-platform-security-requiredrights-macro/src/test/java/org/xwiki/platform/security/requiredrights/internal/MacroContentSourceReferenceMacroParameterRequiredRightsAnalyzerTest.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-requiredrights/xwiki-platform-security-requiredrights-macro/src/test/java/org/xwiki/platform/security/requiredrights/internal/WikiSyntaxMacroParameterRequiredRightsAnalyzerTest.java
https://jira.xwiki.org/browse/XWIKI-22821
* Add a new MacroParameterRequiredRightsAnalyzer role.
* Add implementations for wiki content and macro content source references.
* This eliminates the need for #3810.
* As this fixes the bug of the missing required rights analyzer for the code macro, I propose backporting this improvement to the LTS branches.
* I put the parameter type as type parameter of the new role, but this type isn't used in the role anywhere so I added an explicit ignore for the warnings this causes. I don't know if we have a better solution for this.
Example analysis of the following content:
```
{{code language="none" source="script:foo"}}{{/code}}
{{info title="{{groovy~}~}
println(~"Hello from Title~")
{{/groovy~}~}"}}
Type your information message here.
{{/info}}
``` …
=> XWIKI-22821: Allow having generic analyzers for different types of macro arguments

xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/doc/XWikiDocument.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/internal/store/hibernate/HibernateConfiguration.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/objects/BaseCollection.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/objects/BaseElement.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/objects/BaseObject.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/objects/BaseProperty.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/objects/classes/BaseClass.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/objects/classes/PropertyClass.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/store/XWikiHibernateStore.java, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/doc/XWikiDocumentMockitoTest.java, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/store/XWikiHibernateStoreTest.java
https://jira.xwiki.org/browse/XWIKI-22782
* added a flag to track if a BaseObject was modified
* made sure that any modification of something in that BaseObject (properties, direct metadata of that object) update this flag
* when saving the document skip any BaseObject which indicate that it was not modified
* had to do some `Serializable` cleanup (revapi was getting a bit lost). It's not even clear to me why `BaseElement` and its derivatives are `Serializable` in the first place, but that's another story…
The general idea is to try to reduce the useless requests during document save. This pull request is focusing in making sure we don't re-save xobject which are identical to what's in the database already.
The save side of things is the easy part, most of the changes in the pull request …
=> XWIKI-22782: Only save modified xobjects

xwiki-platform-core/xwiki-platform-panels/xwiki-platform-panels-ui/src/main/resources/PanelsCode/NavigationConfigurationSheet.xml
https://jira.xwiki.org/browse/XWIKI-22904
* Fixed the two accessibility regressions that were brought in previous PRs for this ticket.
```
WCAG fails in the test class [org.xwiki.panels.test.ui.docker.AllIT]:
__________
Validation in the test method [verifyPanelCaching]
Check for [org.xwiki.panels.test.po.NavigationPanelAdministrationPage] at [http://xwikiweb:8080/xwiki/bin/admin/XWiki/XWikiPreferences?form_token=MDyIPXPlyu0M6tkNYcRvEg&editor=globaladmin&forceEdit=true&section=panels.navigation&force=true&].
Found [2] items
1: Certain ARIA roles must contain particular children
Description: Ensure elements with an ARIA role that require child roles contain them
Help URL: https://dequeuniversity.com/rules/axe/4.10/aria-required-children?application=axeAPI
Help: Certain ARIA roles must …
```
=> XWIKI-22904: WCAG not complied in navigation panel administration

xwiki-platform-core/xwiki-platform-annotation/xwiki-platform-annotation-core/src/main/java/org/xwiki/annotation/internal/renderer/AnnotationGeneratorChainingListener.java
Waiting for 16.10.x to be released before merging.
- Replace & with && in if
- Remove superfluous generics definitions
- Use new API for maps manipulation
=> [Misc] Improve AnnotationGeneratorChainingListener code style

xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/src/main/java/org/xwiki/mentions/internal/analyzer/UpdatedDocumentMentionsAnalyzer.java
https://jira.xwiki.org/browse/XWIKI-22913
* Don't do a linear search for finding the object with the correct number.
* `getId()` also just uses the object type and number from what I can see, so I don't think the linear search did anything more than the direct access that I'm using now.
No UI changes.
`mvn -f pom.xml clean verify -Pdocker,legacy,integration-tests,snapshotModules,quality` in `xwiki-platform-core/xwiki-platform-mentions`.
=> XWIKI-22913: Analyzing mentions on a document with a huge number of objects takes very long

xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/java/org/xwiki/search/solr/internal/DefaultSolrConfiguration.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/java/org/xwiki/search/solr/internal/api/SolrConfiguration.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/java/org/xwiki/search/solr/internal/job/AbstractDocumentIterator.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/java/org/xwiki/search/solr/internal/job/DatabaseDocumentIterator.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/java/org/xwiki/search/solr/internal/job/SolrDocumentIterator.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/test/java/org/xwiki/search/solr/internal/DefaultSolrConfigurationTest.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/test/java/org/xwiki/search/solr/internal/job/DatabaseDocumentIteratorTest.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/test/java/org/xwiki/search/solr/internal/job/SolrDocumentIteratorTest.java, xwiki-platform-tools/xwiki-platform-tool-configuration-resources/src/main/resources/xwiki.properties.vm
https://jira.xwiki.org/browse/XWIKI-22926
* Add a new configuration property for configuring the batch size of the initial Solr indexing synchronization.
* Update and add tests.
* I'm not sure caching the limit is a good idea/useful.
* I propose to backport the configuration on the LTS versions as this is for fixing important performance problems on big instances.
No UI changes.
```
mvn clean install -Pquality,integration-tests,docker -pl :xwiki-platform-search-solr-api,:xwiki-platform-search-test-docker
```
=> XWIKI-22926: Make it possible to configure the batch size in the Solr index synchronization on startup

xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-livetable/src/main/java/org/xwiki/livedata/internal/livetable/LiveTableLiveDataConfigurationResolver.java
This PR suppresses the ClassFanOutComplexity Checkstyle rule for the relevant module, as the issue was previously discussed and addressed in [PR #1243](https://github.com/xwiki/xwiki-commons/pull/1243).
Suppressed the ClassFanOutComplexity check for `LiveTableLiveDataConfigurationResolver.java`
This PR should be merged after we release the new Checkstyle version and xwiki upgrades to it. Without this change, existing code that was previously compliant may fail validation checks.
=> applied checkstyle suppression

xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/java/org/xwiki/search/solr/internal/DefaultSolrIndexer.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/java/org/xwiki/search/solr/internal/metadata/AbstractSolrMetadataExtractor.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/java/org/xwiki/search/solr/internal/metadata/AttachmentSolrMetadataExtractor.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/java/org/xwiki/search/solr/internal/metadata/DocumentSolrMetadataExtractor.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/java/org/xwiki/search/solr/internal/metadata/LengthSolrInputDocument.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/java/org/xwiki/search/solr/internal/metadata/ObjectPropertySolrMetadataExtractor.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/java/org/xwiki/search/solr/internal/metadata/ObjectSolrMetadataExtractor.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/java/org/xwiki/search/solr/internal/metadata/SolrMetadataExtractor.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/java/org/xwiki/search/solr/internal/metadata/XWikiSolrInputDocument.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/test/java/org/xwiki/search/solr/internal/metadata/XWikiSolrInputDocumentTest.java
https://jira.xwiki.org/browse/XWIKI-22917
* Use a HashSet to compute unique values instead of a linear search.
* Use LengthSolrInputDocument in more places to use the new method.
* Adding the index with the `HashSet` seemed to be the easiest solution, an alternative would have been to sort and remove duplicates at the end but that would have required much deeper changes.
No UI changes.
`LANG=C.UTF-8 mvn clean install -Pdocker,legacy,integration-tests,quality` in `xwiki-platform-core/xwiki-platform-search`.
* stable-16.4.7
* stable-16.10.5
=> XWIKI-22917: Solr indexing takes very long when there are many objects with different values

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-docker/src/test/it/org/xwiki/flamingo/test/docker/ViewersIT.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/main/java/org/xwiki/refactoring/internal/job/AbstractCopyOrMoveJob.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/main/java/org/xwiki/refactoring/internal/job/AbstractEntityJob.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/main/java/org/xwiki/refactoring/internal/job/AbstractEntityJobWithChecks.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/main/java/org/xwiki/refactoring/internal/job/MoveJob.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-api/src/test/java/org/xwiki/refactoring/internal/job/MoveJobTest.java, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/TestUtils.java, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/po/RefactoringStatusPage.java
* https://jira.xwiki.org/browse/XWIKI-22787
* Start work to have specific handling of WebPreferences in case of move/rename/copy of a full space
* WIP: needs to add tests
*
TBD
* 16.10.x
* 16.4.x but needs to ensure that previous work on refactoring has been backported first (see https://jira.xwiki.org/browse/XWIKI-12987)
=> XWIKI-22787: Pinned Pages are lost on space move for non admin user

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/messages.less
https://jira.xwiki.org/browse/XWIKI-22934
* Updated the CSS rule to fit the latest DOM 
* See ticket.
Video demo of the changes proposed here on the UI:
https://github.com/user-attachments/assets/7246523c-3af7-4120-9f28-536891945ffd
See video above. This style change behaves as expected when adding a title or an image to the box.
* 16.10.X (same as https://jira.xwiki.org/browse/XRENDERING-768 which is the cause)
=> XWIKI-22934: Bottom padding too large in box/message macros

xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authorization/xwiki-platform-security-authorization-api/pom.xml, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authorization/xwiki-platform-security-authorization-api/src/main/java/org/xwiki/security/authorization/AuthorizationManager.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authorization/xwiki-platform-security-authorization-api/src/main/java/org/xwiki/security/authorization/DefaultAuthorizationManager.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authorization/xwiki-platform-security-authorization-api/src/test/java/org/xwiki/security/authorization/DefaultAuthorizationManagerTest.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authorization/xwiki-platform-security-authorization-script/src/main/java/org/xwiki/security/authorization/script/SecurityAuthorizationScriptService.java, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/xwikivars.vm
https://jira.xwiki.org/browse/XWIKI-22815
* generalize the condition for `$isSuperAdmin` to make it work on sub-wikis.
Duplicated/inconsistent definitions of `isSuperAdmin`:
* the current implementation stays on string comparison. Let me know if using a proper entity reference comparison is preferable (couldn't find an existing script API).
N/A
* Build of `xwiki-platform-web-templates`
* Manual tests on sub-wikis
* Also, I found the condition `$isAdvancedUser || $isSuperAdmin` in at least 16 places, but afaiu `$isSuperAdmin` implies `$isAdvancedUser`, making the right hand side of the OR condition superfluous
=> XWIKI-22815: Variable $isSuperAdmin is not computed correctly on subwikis

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/docextra.vm, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/informationinline.vm
* https://jira.xwiki.org/browse/XWIKI-22877
* Send skin extensions in the X-XWIKI-HTML-HEAD header.
* Remove the duplicate loading of skin extensions from docextra.vm
* I basically copied the code from `attachmentsinline.vm` which is used in the same ways so even though it seems strange to always send them (and not just when the template is loaded dynamically) I guess it should be fine.
No UI changes.
I ran the tests of the two modules, but they're not affected. I've manually tested the changed files, and I couldn't see any changes.
* stable-16.10.x?
=> XWIKI-22877: UIX in the information tab cannot load JavaScript and CSS resources

xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/pom.xml, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/src/main/java/org/xwiki/mentions/internal/analyzer/UpdatedDocumentMentionsAnalyzer.java, xwiki-platform-core/xwiki-platform-mentions/xwiki-platform-mentions-default/src/test/java/org/xwiki/mentions/internal/analyzer/UpdatedDocumentMentionsAnalyzerTest.java
https://jira.xwiki.org/browse/XWIKI-22974
* Change the test to @OldcoreTest to use actual documents and objects.
* Fix generating notifications for null anchors (which is covered by the test now).
* The existing test didn't detect the problem because the XObject that was supposed to be changed was returned with different XClass references, so the content was detected as new and not as changed.
No UI change.
```
LANG=C.UTF-8 mvn clean install -Pdocker,legacy,integration-tests,snapshotModules,quality -pl :xwiki-platform-mentions-default,:xwiki-platform-mentions-test-docker
```
=> XWIKI-22974: Mentions without an anchor in changed content don't trigger notifications

xwiki-platform-core/xwiki-platform-panels/xwiki-platform-panels-test/xwiki-platform-panels-test-docker/src/test/it/org/xwiki/panels/test/ui/docker/NavigationPanelAdministrationIT.java, xwiki-platform-core/xwiki-platform-panels/xwiki-platform-panels-test/xwiki-platform-panels-test-docker/src/test/it/org/xwiki/panels/test/ui/docker/NavigationPanelIT.java, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/WCAGContext.java
https://jira.xwiki.org/browse/XWIKI-22904
* Disabled WCAG validation for the page with pins.
NA
NA. Test changes only.
Tested the update with `mvn clean install -f xwiki-platform-core/xwiki-platform-panels/xwiki-platform-panels-test/xwiki-platform-panels-test-docker -Dxwiki.test.ui.wcag=true`. The tests failed as expected on 
```
AllIT$NestedNavigationPanelAdministrationIT>NavigationPanelAdministrationIT.navigationPanelAdministration:157 » NoSuchElement Unable to locate element: (.//li[contains(@class, 'jstree-node')]/a[. = 'Bob']/following-sibling::div[contains(@class, 'jstree-action')]/button)
```
However, contrary to what's currently on CI, there's no WCAGFailure reported anymore here.
* 16.4.X
* 16.10.X (similarly to other PRs for this …
=> XWIKI-22960: WCAG not complied in navigation panel administration

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-docker/src/main/java/org/xwiki/test/SecurityCachePerformanceTestScriptService.java, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-docker/src/main/resources/META-INF/components.txt, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-docker/src/test/it/org/xwiki/flamingo/test/docker/AllIT.java, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-docker/src/test/it/org/xwiki/flamingo/test/docker/SecurityCacheStressIT.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authorization/xwiki-platform-security-authorization-api/src/main/java/org/xwiki/security/authorization/cache/internal/DefaultSecurityCache.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authorization/xwiki-platform-security-authorization-api/src/main/java/org/xwiki/security/authorization/cache/internal/DefaultSecurityCacheLoader.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authorization/xwiki-platform-security-authorization-api/src/main/java/org/xwiki/security/authorization/cache/internal/SecurityCache.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authorization/xwiki-platform-security-authorization-api/src/test/java/org/xwiki/security/authorization/cache/internal/DefaultSecurityCacheLoaderTest.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-authorization/xwiki-platform-security-authorization-api/src/test/java/org/xwiki/security/authorization/cache/internal/DefaultSecurityCacheTest.java
https://jira.xwiki.org/browse/XWIKI-22979
* Remove the read lock of the security cache to avoid blocking read access during cache writes.
* Switch from a ReadWriteLock to a simple write lock as ReadWriteLocks might be slow, and we don't really need it anymore.
* Remove the useless check of the internal entries for security access entries to avoid needlessly acquiring the write lock.
* Improve the concurrency behavior of upgrading entries to user entries to ensure that removing the read lock is safe.
* Replace the invalidation lock used to prevent loading outdated data by an invalidation counter. This avoids holding any locks in the security cache while a document is potentially loaded from the database. Before that, it could happen that while a remove operation is waiting on the lock, a …
=> XWIKI-22979: Access to pages is slow under high load on the security cache

xwiki-platform-core/xwiki-platform-appwithinminutes/xwiki-platform-appwithinminutes-test/xwiki-platform-appwithinminutes-test-docker/src/test/it/org/xwiki/appwithinminutes/test/ui/UserClassFieldIT.java, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/internal/objects/classes/UsedValuesListQueryBuilder.java, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/internal/objects/classes/UsedValuesListQueryBuilderTest.java
https://jira.xwiki.org/browse/XWIKI-23019
* Expose the bug in `UserClassFieldIT`
* Refactor the query in `UsedValuesListQueryBuilder` to not order results based on number of occurences but only based on the actual values lexicographical order, avoiding a group by on a clob which is not allowed in oracle
The value field defined in hibernate schema for list is of type clob. This type cannot be used in quite a few operations in Oracle DB, including using this type of field in `group by` clauses. 
The value field is currently used in a `group by` clause in `UsedValuesListQueryBuilder` for ordering the result based on the number of occurrences. 
AFAIU the only purpose of having this ordering is to present the most commonly used values when opening the suggester, or when performing a REST API …
=> XWIKI-23019: Oracle inconsistent datatypes error when using user suggest for multiple users

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/commentsinline.vm, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-docker/src/test/it/org/xwiki/flamingo/test/docker/CommentsIT.java, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/po/CommentElement.java, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/po/CommentsTab.java, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/comments2.vm
https://jira.xwiki.org/browse/XWIKI-22978
Provide a quickfix for ordering the comments directly in commentsinline.vm. Since we cannot call directly $collectiontool.sort because the Object property cannot be accessed by beanutils, we build a map indexed by date and we perform the ordering manually, taking into account the rare possibility that 2 comments have been added at exact same date.
Also all this work is duplicated in comments2.vm for fixing it in old PDF export.
Note that ideally all this work should be refactored with a proper Java API for comments, see also XWIKI-23049.
*
Manual tests performed by creating comments objects and changing their dates, using some colliding dates and also setting the commentsorder value.  …
=> XWIKI-22978: Comments are not ordered by date

xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-macro/src/main/java/org/xwiki/icon/macro/internal/DisplayIconMacro.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-macro/src/main/java/org/xwiki/livedata/internal/macro/LiveDataMacro.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-macro/src/test/java/org/xwiki/livedata/internal/macro/LiveDataMacroTest.java, xwiki-platform-core/xwiki-platform-localization/xwiki-platform-localization-macro/src/main/java/org/xwiki/localization/macro/internal/TranslationMacro.java, xwiki-platform-core/xwiki-platform-office/xwiki-platform-office-macro/src/main/java/org/xwiki/rendering/internal/macro/office/OfficeMacro.java, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-macros/xwiki-platform-rendering-macro-code/src/main/java/org/xwiki/rendering/internal/macro/code/CodeMacro.java, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-macros/xwiki-platform-rendering-macro-gallery/src/main/java/org/xwiki/rendering/internal/macro/gallery/GalleryMacro.java, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-wikimacro/xwiki-platform-rendering-wikimacro-store/src/main/java/org/xwiki/rendering/wikimacro/internal/DefaultWikiMacro.java, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-wikimacro/xwiki-platform-rendering-wikimacro-store/src/main/java/org/xwiki/rendering/wikimacro/internal/WikiMacroClassDocumentInitializer.java, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-wikimacro/xwiki-platform-rendering-wikimacro-store/src/main/java/org/xwiki/rendering/wikimacro/internal/WikiMacroConstants.java, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-wikimacro/xwiki-platform-rendering-wikimacro-store/src/main/java/org/xwiki/rendering/wikimacro/internal/WikiMacroContentMacro.java, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-wikimacro/xwiki-platform-rendering-wikimacro-store/src/main/java/org/xwiki/rendering/wikimacro/internal/WikiMacroParameterMacro.java, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-wikimacro/xwiki-platform-rendering-wikimacro-store/src/main/resources/ApplicationResources.properties, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-wikimacro/xwiki-platform-rendering-wikimacro-store/src/test/java/org/xwiki/rendering/wikimacro/internal/DefaultWikiMacroFactoryTest.java
https://jira.xwiki.org/browse/XRENDERING-778
* Introduce the concept of isolated execution in wiki macros.
* Mark many macros as isolated.
* This needs xwiki/xwiki-rendering#330.
```
LANG=C.UTF-8 mvn clean install -Pdocker,legacy,integration-tests,snapshotModules,quality,distribution,flavor-integration-tests -pl $(git diff --name-only --merge-base origin/master | awk -F'/' '{for(i=NF-1; i>0; i--){if($i ~ /src$/){printf(":%s\n", $(i-1)); break;}}}' | sort -u | paste -sd "," -)
```
* None for now, probably later.
=> XRENDERING-778: Rendering a page with thousands of macros is slow

xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/store/XWikiCacheStore.java, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/store/XWikiCacheStoreTest.java, xwiki-platform-core/xwiki-platform-oldcore/src/test/java/com/xpn/xwiki/test/MockitoOldcore.java
https://jira.xwiki.org/browse/XWIKI-23055
* Use CacheLoader to synchronize cache loads.
* Add tests for the scenario in the issue and some more scenarios.
* Mock com.xpn.xwiki.store.XWikiStoreInterface.saveXWikiDoc( com.xpn.xwiki.doc.XWikiDocument, com.xpn.xwiki.XWikiContext, boolean) in
MockitoOldcore to make testing of the cache store easier.
* This depends on https://github.com/xwiki/xwiki-commons/pull/1282
No UI changes.
```
mvn clean install -Pquality,integration-tests,docker -pl :xwiki-platform-flamingo-skin-test-docker,,:xwiki-platform-oldcore -Dit.test=SecurityCacheStressIT
```
* stable-17.2.x
=> XWIKI-23055: The document cache may not be properly invalidated in case of concurrent loads

xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-ui/src/main/resources/IconThemesCode/IconPicker.xml
https://jira.xwiki.org/browse/XWIKI-22930
For reference, caused by the commit from: https://github.com/xwiki/xwiki-platform/pull/3800
* Updated the overflow-y value so that the scroll control only appears for elements whose name actually overflows.
* On my firefox installation, this style does not make much difference. But on Chrome and other firefox installs, this small change revert the regression on style.
Before the changes, on Chrome:
After the changes, on Chrome:
We can see that the scroll indicators are no longer displayed everywhere but only for the names that can be scrolled.
This is the expected behaviour.
Manual tests as seen above, tested only on Firefox and Chrome on Debian.
No automatic tests. This regression wasn't caught by any automatic tests and the solution we picked is …
=> XWIKI-22930: Scroll bars appear in the right side of each icon

xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/java/org/xwiki/search/solr/internal/metadata/DefaultLinkStore.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/test/java/org/xwiki/search/solr/internal/metadata/DefaultLinkStoreTest.java
https://jira.xwiki.org/browse/XWIKI-23081
* Use cursor-based pagination to fetch all documents instead of setting a high query limit.
* Add a test to verify that the pagination works.
* Solr allocates memory for storing some values that is proportional to the requested limit. According to what I found, it seems to be around 18 bytes per requested document. The limit is decreased to the total number of indexed items, but if that is high, like 37 million, this could result in 700MB memory per backlink query.
* I initially considered doing a first query with a low limit to fetch the number of results and then doing a second query with that number of results as limit. However, the total number of results might not be exact for large sets of documents. Therefore, I chose this approach based on …
=> XWIKI-23081: Fetching backlinks is slow and consumes a lot of memory on large instances

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/flamingo.js
https://jira.xwiki.org/browse/XWIKI-22727
https://github.com/xwiki/xwiki-platform/pull/3957 contained a regression on codestyle that is reported by JSHint on our CI.
from https://ci.xwiki.org/blue/organizations/jenkins/XWiki%2Fxwiki-platform/detail/master/7870/pipeline
* Fixed codestyle regarding JSHint (missing semicolons on the javascript I added after the initial changes, which I forgot to properly build)
None, codestyle changes only. 
Built with JSHint: `mvn -f xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources clean install -Plegacy,integration-tests,snapshot -U -Dmaven.test.failure.ignore -Dxwiki.checkstyle.skip=true -Dxwiki.surefire.captureconsole.skip=true -Dxwiki.revapi.skip=true -DskipITs` . I could reproduce the CI …
=> XWIKI-22727: Make the width of panel column flexible

xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-server/xwiki-platform-search-solr-server-core-search/src/main/resources/conf/managed-schema.xml, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-server/xwiki-platform-search-solr-server-plugin/src/main/java/org/xwiki/search/solr/LowerCaseStrField.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-server/xwiki-platform-search-solr-server-plugin/src/test/java/org/xwiki/search/solr/LowerCaseStrFieldTest.java
https://jira.xwiki.org/browse/XWIKI-23052
* Introduce a new LowerCaseStrField field type.
* Change the lowercase field type in the search schema to use LowerCaseStrField.
I unfortunately couldn't find much documentation on how to create custom Solr field types. This implementation is based on an initial implementation suggested by GPT-4o that I've adapted to actually work and remove parts that obviously weren't needed. As the custom field type is only slightly modifying `StrField` I believe it should be fine, but I don't know. Looking at [UUIDField](https://github.com/apache/solr/blob/main/solr/core/src/java/org/apache/solr/schema/UUIDField.java) that also extends `StrField`, it seems similar. The part where I'm least sure is the `createFields` method but from reading the code, it seems …
=> XWIKI-23052: Solr still uses a lot of field related RAM

xwiki-platform-core/xwiki-platform-alerts/xwiki-platform-alerts-ui/src/main/resources/XWiki/Alerts/Code/AlertsMenuUIX.xml
https://jira.xwiki.org/browse/XWIKI-22998
* Added the parameter in the initial template.
Tested manually on a local instance:
We can see on this screenshot that the attribute is here as soon as the page is loaded.
None, minor attribute change on DOM. I checked selectors used in the BaseElement for this UI (NotificationsTrayPage) and none were broken by the changes.
* None.
=> XWIKI-22998: Notification topbar toggle should use the `aria-expanded` attribute from the start

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/general.less
https://jira.xwiki.org/browse/XWIKI-22995
* Added an exception for the Page creator link.
Before the PR:
After the PR:
Manual test only. This is a style change only, it doesn't impact the results of our current test framework. Additionally, this link is only here when the creator of a page is not the superadmin but an actual user, which does not happen in automatic tests (the automatic accessibility tests would have highlighted this violation before if it happened).
* 16.10.X, small bugfix that is pretty safe to merge.
=> XWIKI-22995: Underline inline link for the document original author

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/menus_content.vm, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-ui/src/main/resources/XWiki/Notifications/Code/NotificationsWatchUIX.xml, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/po/BasePage.java
https://jira.xwiki.org/browse/XWIKI-22996
* Changed the tag used for the list of action buttons.
* Updated the vtl macro and use of the UIX to generate proper list items.
* Updated test object selectors.
* Searched for XWiki Standard uses of this UIX with `org.xwiki.plaftorm.menu.content`
* Searched for the test object breaks with the IDs of the different buttons. As we can see here, in the end the only place where changes were needed was the BasePage object.
Surprisingly, the styles did not change at all despite the change of HTML tag.
For the sake of demonstration, I left the Notification Menu use of the UIX unchanged for this screenshot. As we can see, it's still styled properly, but it returns an accessibility error. With the full PR applied, this WCAG violation in XWiki Standard …
=> XWIKI-22996: The contentmenu list of buttons should be coded as a list

xwiki-platform-core/xwiki-platform-legacy/xwiki-platform-legacy-rendering/xwiki-platform-legacy-rendering-wikimacro/xwiki-platform-legacy-rendering-wikimacro-api/pom.xml, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-wikimacro/xwiki-platform-rendering-wikimacro-api/pom.xml, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-wikimacro/xwiki-platform-rendering-wikimacro-api/src/main/java/org/xwiki/rendering/macro/wikibridge/WikiMacroParameterDescriptor.java, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-wikimacro/xwiki-platform-rendering-wikimacro-store/pom.xml, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-wikimacro/xwiki-platform-rendering-wikimacro-store/src/main/java/org/xwiki/rendering/wikimacro/internal/DefaultWikiMacroFactory.java, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-wikimacro/xwiki-platform-rendering-wikimacro-store/src/main/java/org/xwiki/rendering/wikimacro/internal/WikiMacroConstants.java, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-wikimacro/xwiki-platform-rendering-wikimacro-store/src/main/java/org/xwiki/rendering/wikimacro/internal/WikiMacroParameterClassDocumentInitializer.java, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-wikimacro/xwiki-platform-rendering-wikimacro-store/src/main/resources/ApplicationResources.properties, xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-wikimacro/xwiki-platform-rendering-wikimacro-store/src/test/java/org/xwiki/rendering/wikimacro/internal/DefaultWikiMacroFactoryTest.java
https://jira.xwiki.org/browse/XWIKI-22804
* Add the various needed property in xclass
* Add missing fields and getter/setters in WikiMacroParameterDescriptor
* Properly build the WikiParameterDescriptor based on the object properties
* Provide translation keys
* Add unit test for building parameter descriptors
WIP: we should probably provide parameter hints
* I decided to be consistent with what we have with java, meaning that wikimacro also allows to specify a list of groups even we never really use that possibility
Ran `mvn clean install -Pquality` on both `xwiki-platform-rendering-wikimacro` and `xwiki-platform-legacy-rendering-wikimacro` 
* 16.10.x
=> XWIKI-22804: Improve consistency of wiki macro parameters by being able to define them advanced, hidden, or deprecated

xwiki-platform-core/xwiki-platform-alerts/xwiki-platform-alerts-ui/src/main/resources/XWiki/Alerts/Code/AlertsMenuUIX.xml, xwiki-platform-core/xwiki-platform-oldcore/src/main/resources/ApplicationResources.properties
https://jira.xwiki.org/browse/XWIKI-22997
* Added a specific translation for this toggle. I tried to keep it as short and precise as possible.
After the changes in this PR:
None, this is a minor translation value switch.
* 16.10.X (very safe bugfix)
=> XWIKI-22997: Header notification toggle has an imprecise name

xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-test/xwiki-platform-administration-test-docker/src/test/it/org/xwiki/administration/test/ui/RegisterIT.java, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-docker/src/test/it/org/xwiki/flamingo/test/docker/DeletePageIT.java, xwiki-platform-core/xwiki-platform-sharepage/xwiki-platform-sharepage-test/xwiki-platform-sharepage-test-pageobjects/src/main/java/org/xwiki/sharepage/test/po/ShareResultDialog.java, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/po/AbstractRegistrationPage.java, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui/src/main/java/org/xwiki/test/ui/po/RefactoringStatusPage.java, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/job/question/ExtensionBreakingQuestion.form.vm, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/job/question/XClassBreakingQuestion.form.vm, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/macros.vm, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/test/java/org/xwiki/web/JobStatusJSONPageTest.java
https://jira.xwiki.org/browse/XWIKI-22433
* Updated the velocimacro to avoid colliding variables
* Updated the docker test tools to not retrieve the icon name that's now in the messages
*
Built the changes with:
-     mvn clean install -f xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-ui + mvn clean install -f xwiki-platform-core/xwiki-platform-test/
-     mvn clean install -f xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/ + mvn clean install -f xwiki-platform-core/xwiki-platform-web/
-      mvn clean install -f xwiki-platform-core/xwiki-platform-sharepage/xwiki-platform-sharepage-test/xwiki-platform-sharepage-test-pageobjects
Then I succesfully ran docker tests:
-     mvn clean install -f xwiki-platform-core/xwiki-platform-index/xwiki-platform-index-test …
=> XWIKI-22433: Provide consistency in info / warning / error class usages in templates

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-docker/src/test/it/org/xwiki/flamingo/test/docker/RenamePageIT.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-default/src/main/java/org/xwiki/refactoring/internal/ResourceReferenceRenamer.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-default/src/test/java/org/xwiki/refactoring/internal/DefaultReferenceUpdaterTest.java, xwiki-platform-core/xwiki-platform-refactoring/xwiki-platform-refactoring-default/src/test/java/org/xwiki/refactoring/internal/ResourceReferenceRenamerTest.java, xwiki-platform-core/xwiki-platform-wiki/xwiki-platform-wiki-test/xwiki-platform-wiki-test-docker/src/test/it/org/xwiki/wiki/test/ui/SubWikiIT.java
(cherry picked from commit aed29a8dbced7264408b31ba4e368caed9595a6d)
https://jira.xwiki.org/browse/XWIKI-23107
* Cherry pick of changes performed in master
* don't check if the link is relative or not for refactoring it as it's a bad criteria
* cover with tests in both single and multi wikis
*
*
=> XWIKI-23107: Moving a page with a relative link from one wiki to another breaks the link

xwiki-platform-core/xwiki-platform-extension/xwiki-platform-extension-distribution/src/main/java/org/xwiki/extension/distribution/internal/DefaultDistributionManager.java, xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-api/src/main/java/org/xwiki/user/UserManager.java, xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-default/src/main/java/org/xwiki/user/internal/DefaultUserManager.java, xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-default/src/main/java/org/xwiki/user/internal/document/CurrentUserManager.java, xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-default/src/main/java/org/xwiki/user/internal/document/DocumentUserManager.java, xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-default/src/main/java/org/xwiki/user/internal/document/UserCache.java, xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-default/src/main/java/org/xwiki/user/internal/document/UserListener.java, xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-default/src/main/resources/META-INF/components.txt, xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-default/src/test/java/org/xwiki/user/internal/document/DocumentUserManagerTest.java, xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-default/src/test/java/org/xwiki/user/internal/document/UserListenerTest.java
https://jira.xwiki.org/browse/XWIKI-23122
and as a bonus (it was actually the end goal): https://jira.xwiki.org/browse/XWIKI-23073
The idea if to provide a new API to check if a wiki contains any user. The result is also cached.
The name of the API is still negotiable, if you have a better idea…
Add various unit tests.
* Backport on branches: No
=> XWIKI-23122: Add an API to check if a wiki contains any user

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/uicomponents/widgets/notification.js
* Removed the harmful role from the notifications themselves. The role is already on the container and handles notifying non visual users.
* Added comments to avoid repeating the mistake I did in XWIKI-22709
* When [implementing XWIKI-22709](https://github.com/xwiki/xwiki-platform/pull/3707), I wasn't aware that the container itself was an alert. I was also probably tricked by the fact that this .js is stored in the `xwiki.bundle.min.js`, which makes edits after the first patch more complex. When checking the demo video, it seems I was testing on an unpatched version :/
Before the changes:
https://github.com/user-attachments/assets/4d47c5de-5a35-4abb-8a76-2e41249dffae
After the changes:
https://github.com/user-attachments/assets/d8b4c784-f24d-41f4-b350-596f1a8f88c6
Manual tests only. This …
=> XWIKI-23101: XWiki Notifications alert too often

xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/java/org/xwiki/search/solr/internal/job/IndexerJob.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/test/java/org/xwiki/search/solr/internal/job/IndexerJobTest.java
https://jira.xwiki.org/browse/XWIKI-23188
* Double-check that a document actually doesn't exist anymore before requesting its deletion from the index.
* Add a unit test for IndexerJob.
* In theory, there is still the possibility of a race condition where the document is deleted again between the check and the addition to the index queue. I decided to ignore this possibility as the probability seems very small and the only scenario where this would matter is if a document is created and immediately deleted again while the index synchronization is running.
* This is primarily an attempt at fixing a flickering test than a problem that was actually observed in practice.
* The additional check could slow down the job a bit but in practice this should be rare as actual synchronization activity …
=> XWIKI-23188: Race condition in Solr index synchronization can delete existing documents from the index

xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-api/src/main/java/org/xwiki/livedata/LiveDataConfiguration.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-api/src/main/java/org/xwiki/livedata/LiveDataEntryDescriptor.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-api/src/main/java/org/xwiki/livedata/LiveDataMeta.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-api/src/main/java/org/xwiki/livedata/LiveDataPaginationConfiguration.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-api/src/main/java/org/xwiki/livedata/LiveDataQuery.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-api/src/main/java/org/xwiki/livedata/LiveDataSelectionConfiguration.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-api/src/test/java/org/xwiki/livedata/internal/DefaultLiveDataConfigurationResolverTest.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-livetable/src/main/java/org/xwiki/livedata/internal/livetable/LiveTableLiveDataConfigurationResolver.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-livetable/src/test/java/org/xwiki/livedata/internal/livetable/LiveTableLiveDataConfigurationResolverTest.java
* The upgrade of jackson changed the order when serializing objects to json strings. As this is not support to have an impact on tests, I fixed the tests by moving to objects comparison instead of the current string comparison approach.
*
All of the tests of the live data module.
* N/A
=> XCOMMONS-3321: Upgrade to Jackson 2.19.0

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/leftpanels.vm, xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/rightpanels.vm
https://jira.xwiki.org/browse/XWIKI-12824
* Changed the nature of the hint for panel toggles.
This is one part of the changes initially proposed in https://github.com/xwiki/xwiki-platform/pull/3881 .
* [Here's a really interesting discussion I found around the error found on CI](https://github.com/validator/validator/issues/1332#issuecomment-1065956220) , with a clear answer from a reknowned and involved standard specialist :)
None. This does not have any impact on the UI because these elements are hidden visually with `.sr-only`.
* None, same as https://github.com/xwiki/xwiki-platform/pull/2831
=> XWIKI-12824: Add buttons to hide/show panels

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/uicomponents/suggest/suggest.js
https://jira.xwiki.org/browse/XWIKI-23097
* Added the alert role to the container of suggestions.
* The component is already pretty accessible, but nothing was conveyed to notice the users that some new content has been queried and displayed. This attribute is enough to fulfill this lack of info.
* There is a lot of info read out when the dropdown is activated. This is an issue for clarity, but I guess it's not that important and it's better than no information at all.
Video demo with the changes proposed here applied:
https://github.com/user-attachments/assets/7a5f65c3-1c90-4a48-b9e2-b12fa58c3f6a
Made using browserStack, Chrome 136 + NVDA
Note that before the changes in here were applied, all that would be read out to the user are the letters they added to the input:
```
p
a
g
e
```
Now, …
=> XWIKI-23097: Quicksearch: no alert when results are shown

xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins/src/main/webjar/xwiki-link/plugin.js, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins/src/main/webjar/xwiki-resource/entityResourceSuggester.js, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins/src/main/webjar/xwiki-resource/plugin.js, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins/src/main/webjar/xwiki-resource/resource.js, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins/src/main/webjar/xwiki-resource/resourcePicker.js, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-ui/src/main/resources/CKEditor/LinkNameStrategyHelper.xml, xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-ui/src/main/resources/CKEditor/Translations.xml
https://jira.xwiki.org/browse/XWIKI-23154
* Revert the original commit that was automatically putting a computed reference in the selection since it appears to be bad in terms of usability
* Define the type of resources that must be selected and not just
typed in the input field
* Perform a check to ensure that the value is not just typed but is
actually selected
* Provide an initial value at setup which is considered as a typed
value
* Provide translation for the error message
* Improve LinkStrategyHelper to also performs validation of inputs 
Before 16.8 it was possible to insert a link without any validation of the input, leading to use the actual selected word in the input field of the link dialog. This was changed to ensure that the name strategy was enforced when creating a link, by …
=> XWIKI-23154: Link creation dialog shouldn't allow to be validated without selecting a suggestion value

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-docker/src/test/it/org/xwiki/flamingo/test/docker/AllIT.java, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-docker/src/test/it/org/xwiki/flamingo/test/docker/ServletEnvironmentCacheIT.java
https://jira.xwiki.org/browse/XCOMMONS-3348
* Add an integration test to ensure that the cache in the servlet environment has actually been initialized (a missing cache doesn't cause any problems except for slower performance).
* As it is hard to detect if the cache is active or not (it just slightly increases the loading time of pages), I thought it would be good to add a test to ensure that the initialization is actually working.
* This depends on https://github.com/xwiki/xwiki-commons/pull/1346
No UI changes.
```
LANG=C.UTF-8 mvn clean install -Pdocker,legacy,integration-tests,snapshotModules,quality,distribution,flavor-integration-tests -pl :xwiki-platform-flamingo-skin-test-docker -Dit.test=ServletEnvironmentCacheIT
``` …
=> XCOMMONS-3348: The servlet environment triggers a second load of the xwiki.properties configuration

xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/java/org/xwiki/search/solr/internal/DefaultSolrIndexer.java
https://jira.xwiki.org/browse/XWIKI-23239
* Collect indexed documents and submit them in batches to Solr for more
efficient processing and less overhead due to repeated calls to Solr.
* Move all Solr client requests into a separate executor to allow the
next batch to be prepared while the previous one is committed.
* I'm not sure regarding the `ExecutorService` design, I felt that going with another custom queue would be more overhead, but it might have fit better into the existing design.
* I fear test coverage for this code is relatively low. The change in the first commit feels quite safe, the second one more dangerous. We could also decide to split them into separate Jira issues and backport the first one to LTS branches.
* With these changes, re-indexing the whole wiki with just the …
=> XWIKI-23239: Improve Solr indexing speed through parallelization and batch processing

xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-requiredrights/xwiki-platform-security-requiredrights-default/src/main/java/org/xwiki/platform/security/requiredrights/internal/analyzer/SkinExtensionObjectRequiredRightAnalyzer.java, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-requiredrights/xwiki-platform-security-requiredrights-default/src/main/resources/ApplicationResources.properties, xwiki-platform-core/xwiki-platform-security/xwiki-platform-security-requiredrights/xwiki-platform-security-requiredrights-default/src/test/java/org/xwiki/platform/security/requiredrights/internal/analyzer/SkinExtensionObjectRequiredRightAnalyzerTest.java, xwiki-platform-core/xwiki-platform-skin/xwiki-platform-skin-skinx/src/main/java/com/xpn/xwiki/plugin/skinx/AbstractDocumentSkinExtensionPlugin.java, xwiki-platform-core/xwiki-platform-skin/xwiki-platform-skin-skinx/src/test/java/com/xpn/xwiki/plugin/skinx/CssSkinExtensionPluginTest.java
https://jira.xwiki.org/browse/XWIKI-12285
* Check for wiki admin instead of programming right.
* Adapt the required rights analyzer.
* Also warn about the possibly required programming right for parsed skin extensions.
* Add new translations for parsed skin extensions and adapted the existing translations (they weren't translated so far, so changing them shouldn't be a problem).
* I've decided to update the existing translations as so far we don't have any translations for them (we probably forgot adding the module in Weblate).
Compiled all changed modules with `quality` profile. Manuel tests on a demo instance.
* None, this is an improvement, not a bug fix.
=> XWIKI-12285: Should be able to register wiki-level JSX with wiki-level admin right (not PR)

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/menus_content.vm
https://jira.xwiki.org/browse/XWIKI-22990
* If the label of the menu button is not shown, still put it in the DOM, but visually hidden with `sr-only`.
* Updated comments
* Technically I updated this velocimacro API to make the meaning of `$titleAsLabel` a bit more specific. I think it'd alright to do because most users won't even see the difference here, and for those who do, for any use of this macro I can think of, this will be an improvement. I guess this can be a regression if the user already has some custom script to inject a proper text alternative in there, but IMO it's quite unlikely, and easy to fix as long as they know where their custom script is.
After the changes proposed in this PR were applied on my local instance, I could see that the more action button had a proper …
=> XWIKI-22990: The `More actions` button currently relies only on the title for its alternative text

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/commentfield.vm, xwiki-platform-core/xwiki-platform-oldcore/src/main/resources/ApplicationResources.properties
https://jira.xwiki.org/browse/XWIKI-23168
* Added a unique translation for the comment editor label
* Updated the comment on commentfield.vm description to be more explicit
* Made the label sr-only. 
* Given the issue description, sighted users have enough context by this point to not need a visible label. However we don't want to remove it completely for accessibility reasons.
* In XS, the `commentfield.vm` template is used only in this specific context. We can update it without worrying about regressing in another place in the UI.
Manual tests (see above). I tried out with the two available default editors and it looked okay while passing accessibility tests.
Successfully passed `mvn clean install -f xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform- …
=> XWIKI-23168: The word "Comment" is displayed in bold above the editor box when editing a comment

xwiki-platform-core/xwiki-platform-display/xwiki-platform-display-api/src/main/java/org/xwiki/display/internal/AbstractDocumentTitleDisplayer.java, xwiki-platform-core/xwiki-platform-display/xwiki-platform-display-api/src/main/java/org/xwiki/display/internal/DocumentContentDisplayer.java, xwiki-platform-core/xwiki-platform-display/xwiki-platform-display-api/src/main/java/org/xwiki/display/internal/DocumentReferenceDequeContext.java, xwiki-platform-core/xwiki-platform-display/xwiki-platform-display-api/src/main/resources/META-INF/components.txt, xwiki-platform-core/xwiki-platform-display/xwiki-platform-display-api/src/test/java/org/xwiki/display/internal/DocumentContentDisplayerTest.java, xwiki-platform-core/xwiki-platform-display/xwiki-platform-display-api/src/test/java/org/xwiki/display/internal/DocumentTitleDisplayerTest.java, xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-page/src/main/java/org/xwiki/test/page/PageComponentList.java
https://jira.xwiki.org/browse/XWIKI-23303
* Extract the code for managing the document reference stack from the title displayer into a separate component.
* Set a limit of five recursions with the same document for the document content.
* For now, the main cause of infinite recursion seems to be document inclusion so I think a fix there should be enough for now.
The document from the Jira issue displays the following error now:
Apart from that, there shouldn't be any UI changes.
Built the changed module with quality profile.
* stable-17.4.x
=> XWIKI-23303: Insufficient protection against stack overflows

xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-default/pom.xml, xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-default/src/main/java/org/xwiki/icon/internal/DefaultIconRenderer.java, xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-default/src/main/java/org/xwiki/icon/internal/IconTemplateRenderer.java, xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-default/src/main/java/org/xwiki/icon/internal/IconTemplateRendererManager.java, xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-default/src/main/java/org/xwiki/icon/internal/VelocityRenderer.java, xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-default/src/main/resources/META-INF/components.txt, xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-default/src/test/java/org/xwiki/icon/internal/DefaultIconManagerComponentList.java, xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-default/src/test/java/org/xwiki/icon/internal/DefaultIconRendererTest.java, xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-default/src/test/java/org/xwiki/icon/internal/DefaultIconSetCacheTest.java, xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-default/src/test/java/org/xwiki/icon/internal/IconTemplateRendererManagerTest.java, xwiki-platform-core/xwiki-platform-icon/xwiki-platform-icon-default/src/test/java/org/xwiki/icon/internal/VelocityRendererTest.java, xwiki-platform-core/xwiki-platform-url/xwiki-platform-url-api/src/main/java/org/xwiki/url/internal/AbstractExtendedURLResourceReferenceSerializer.java
https://jira.xwiki.org/browse/XWIKI-11112
* Introduce the internal concept of an `IconTemplateRenderer`.
* Add an internal IconTemplateRendererManager that provides icon template renderers and caches them.
* Cache parsed Velocity code.
* Add special cases for the most commonly used Velocity scripts to avoid expensive Velocity execution for those cases.
* Adapt and add tests.
* Decrease the expected code coverage to 0.96 as 0.97 is just unrealistic.
* Don't ask for non-existing components in the extended URL reference serializer. Instead, check if the component exists, first. This speeds up getting the WebJar URL for Font Awesome by about a factor of 5.
* The last item/second commit could also be a separate Jira or a [Misc] commit, let me know if you want that more formal approach.
* I …
=> XWIKI-11112: Adding a rendering cache to the Icon Theme Application

xwiki-platform-core/xwiki-platform-index/xwiki-platform-index-test/xwiki-platform-index-test-docker/src/test/it/org/xwiki/index/test/ui/docker/AllIT.java, xwiki-platform-core/xwiki-platform-index/xwiki-platform-index-test/xwiki-platform-index-test-docker/src/test/it/org/xwiki/index/test/ui/docker/DocumentTreeMacroIT.java, xwiki-platform-core/xwiki-platform-index/xwiki-platform-index-test/xwiki-platform-index-test-docker/src/test/it/org/xwiki/index/test/ui/docker/DynamicTestConfigurationExtension.java, xwiki-platform-core/xwiki-platform-index/xwiki-platform-index-tree/xwiki-platform-index-tree-api/src/main/java/org/xwiki/index/tree/internal/nestedpages/query/QueryRegistrationHandler.java, xwiki-platform-core/xwiki-platform-index/xwiki-platform-index-tree/xwiki-platform-index-tree-api/src/main/resources/org/xwiki/index/tree/internal/nestedpages/query/queries.hbm.xml.vm, xwiki-platform-core/xwiki-platform-index/xwiki-platform-index-tree/xwiki-platform-index-tree-api/src/main/resources/org/xwiki/index/tree/internal/nestedspaces/query/queries.hbm.xml, xwiki-platform-tools/xwiki-platform-tool-configuration-resources/src/main/resources/xwiki.properties.vm
https://jira.xwiki.org/browse/XWIKI-23324
* Add a new configuration option to configure the collation used for sorting.
* Dynamically modify the named queries to use the configured collation.
* Configure a collation in the index tree docker test.
* Add unit and integration tests to ensure that sorting with collation is working.
* Recent Hibernate versions add support for specifying collations in order by expressions, too, so when we upgrade to a more recent Hibernate version that doesn't need the named queries anymore, we can keep collation support. Further, we could add collations in more places.
* The supported collations depend completely on the used database engine, this stays true with official Hibernate support. Therefore, it's not really possible to have a nice default collation - …
=> XWIKI-23324: In the Navigation Panel, the German umlauts are sorted after Z

xwiki-platform-core/xwiki-platform-index/xwiki-platform-index-tree/xwiki-platform-index-tree-api/src/main/java/org/xwiki/index/tree/internal/nestedspaces/SpaceTreeNode.java
[https://jira.xwiki.org/browse/XWIKI-23354](https://jira.xwiki.org/browse/XWIKI-23354)
Updated the alias of the `XWikiSpace` table to `spaces` instead of `page`, to match the alias used in the filters.
When we do not want to show terminal documents, we reach [this else branch](https://github.com/xwiki/xwiki-platform/blob/28991f7cd8fb1c949277c12dfc405fad13720b0e/xwiki-platform-core/xwiki-platform-index/xwiki-platform-index-tree/xwiki-platform-index-tree-api/src/main/java/org/xwiki/index/tree/internal/nestedspaces/SpaceTreeNode.java#L137). The query created is:
```sql
select reference, 0 as terminal from XWikiSpace page order by lower(name), name
```
where the alias of `XWikiSpace` is `page`. Below, we add [some filters](https://github.com/xwiki/xwiki-platform/blob/28991f7cd8fb1c949277c12dfc …
=> XWIKI-23354: The #documentTree($option) is broken when using the showTerminalPages=false

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/variables.less, xwiki-platform-core/xwiki-platform-menu/xwiki-platform-menu-ui/src/main/resources/Menu/MenuMacro.xml
https://jira.xwiki.org/browse/XWIKI-15629
* Created a few LESS variables to match the need that was highlighted in the design.
* Used those LESS variables to control the display of menus.
* Updated the menu layout:
* Reduced the height (1.5lh~=30px instead of 24px proposed in the initial design)
* Changed the background color
* Removed the drop shadow from the navbar above.
* Removed padding around the menu toggle so that it would fit on a line of similar height.
* I didn't provide a CSS variable alternative yet. IMO these variables could be internal (not API) because they are very similar semantically and in practice to their `@navbar-<...>` alternatives.
Here is a video demo of an instance with the changes applied. In this demo, I go through a range of zoom levels, screen widths and …
=> XWIKI-15629: Menus background-color should differ from the actionmenu background-color

xwiki-platform-core/xwiki-platform-invitation/xwiki-platform-invitation-ui/src/main/resources/Invitation/InvitationConfig.xml, xwiki-platform-core/xwiki-platform-invitation/xwiki-platform-invitation-ui/src/main/resources/Invitation/WebHome.xml, xwiki-platform-core/xwiki-platform-invitation/xwiki-platform-invitation-ui/src/main/resources/Invitation/WebPreferences.xml, xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/internal/mandatory/XWikiPreferencesDocumentInitializer.java, xwiki-platform-distribution/xwiki-platform-distribution-ui/xwiki-platform-distribution-ui-base/src/main/resources/XWiki/XWikiPreferences.xml
[XWIKI-23273:"SMTP PASSWORD" in Invitation configuration page is not masked](https://jira.xwiki.org/browse/XWIKI-23273)
* Replace `com.xpn.xwiki.objects.classes.StringClass` classtype for `smtp_server_password` with `com.xpn.xwiki.objects.classes.PasswordClass`
* Used same approach for password field from Mail configuration.
Initial issue
After fix
Manual performed tests in UI.
* 16.10.X (low bugfix)
=> XWIKI-23273: "SMTP PASSWORD" in Invitation configuration page is not masked

xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-api/src/main/java/org/xwiki/notifications/filters/internal/scope/ScopeNotificationFilterPreference.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-api/src/main/java/org/xwiki/notifications/filters/internal/scope/ScopeNotificationFilterPreferencesHierarchy.java
https://jira.xwiki.org/browse/XWIKI-23254
* Don't compare all preferences with each other but only compare potential parents with potential children. This should help for the very likely case that users have primarily (or exclusively) inclusive notification filters.
* I haven't tested this much yet, but it seems quite straightforward that this should be correct and help a lot for the likely case that a user simply watches a lot of individual pages.
No UI changes.
Built the module with quality profile.
* stable-17.4.x
=> XWIKI-23254: Page loads are slow for users with many watched pages

xwiki-platform-core/xwiki-platform-bootstrap/src/main/less/dropdowns.less, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/node/src/components/LivedataDropdownMenu.vue, xwiki-platform-core/xwiki-platform-tree/xwiki-platform-tree-webjar/src/main/less/jstree/base.less
https://jira.xwiki.org/browse/XWIKI-23413
~~* Provided the fix as a hard-coded exception to the updated bootstrap~~
<EDIT> The solution prooposed in this PR now is completely different to what was done initially </EDIT>
With the changes in the PR applied:
Note that before applying that patch, I could reproduce the problem reported on this local instance. The state of this UI without the fix is available as an attachment to the equivalent jira ticket.
Manual tests only. The issue was reported after manual tests and style changes only hardly ever impact automated tests.
Built the jar with the quality profile successfully:
`mvn clean install -f xwiki-platform-core/xwiki-platform-tree/xwiki-platform-tree-webjar -Pquality`
* 17.4.X
* 16.10.X
=> XWIKI-23413: Separators in navigation tree dropdown

xwiki-platform-core/xwiki-platform-attachment/xwiki-platform-attachment-ui/src/main/resources/XWiki/AttachmentSelector.xml
https://jira.xwiki.org/browse/XWIKI-23201
* Removed all the hard-coded icons from the AttachmentSelector UI
* Updated the layout styles to be more stable and fit in today's context.
* Added underscores before internal velocimacro names.
* I did a few small style changes, barely noticeable IMO:
* Updated the border-radius from 8px to the standard CSS property `--border-radius-base` which has a default value of 7px
* Removed the 1px large low contrast and dotted border between the title+action buttons and the image itself. On my screen, even knowing it was here, on a default zoom, I could barely see it... 
* For the action links, I decided to style them like buttons, because they act like some. I removed all the custom opacity styles, those buttons classes already come with all the styles …
=> XWIKI-23201: Replace the Silk icons in Attachment Selector with the Icon Theme ones

xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/java/org/xwiki/search/solr/AbstractSolrCoreInitializer.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/java/org/xwiki/search/solr/SolrCoreInitializer.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/java/org/xwiki/search/solr/SolrUtils.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/java/org/xwiki/search/solr/internal/EmbeddedSolr.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/java/org/xwiki/search/solr/internal/SolrIndexInitializeListener.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/java/org/xwiki/search/solr/internal/SolrSchemaUtils.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/java/org/xwiki/search/solr/internal/api/FieldUtils.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/java/org/xwiki/search/solr/internal/job/DatabaseDocumentIterator.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/java/org/xwiki/search/solr/internal/job/IndexerJob.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/java/org/xwiki/search/solr/internal/job/IndexerRequest.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/java/org/xwiki/search/solr/internal/job/SolrDocumentIterator.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/java/org/xwiki/search/solr/internal/metadata/AbstractSolrMetadataExtractor.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/java/org/xwiki/search/solr/internal/metadata/DocumentSolrMetadataExtractor.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/java/org/xwiki/search/solr/internal/search/AbstractSearchCoreMigration.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/java/org/xwiki/search/solr/internal/search/SearchCoreInitializer.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/java/org/xwiki/search/solr/internal/search/SearchCoreMigration.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/java/org/xwiki/search/solr/internal/search/SearchCoreMigrationManager.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/java/org/xwiki/search/solr/internal/search/V170700000SearchCoreMigration.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/resources/META-INF/components.txt, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/test/java/org/xwiki/search/solr/internal/DefaultSolrTest.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/test/java/org/xwiki/search/solr/internal/job/DatabaseDocumentIteratorTest.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/test/java/org/xwiki/search/solr/internal/job/IndexerJobTest.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-server/xwiki-platform-search-solr-server-core-search/src/main/resources/conf/managed-schema.xml, xwiki-platform-distribution/xwiki-platform-distribution-flavor/xwiki-platform-distribution-flavor-test/xwiki-platform-distribution-flavor-test-upgrade/xwiki-platform-distribution-flavor-test-upgrade-1610/pom.xml
* [XWIKI-15166: SOLR reindexation job cause serious perfomance issues on large database](https://jira.xwiki.org/browse/XWIKI-15166)
* [XWIKI-23318: Add the doc id in the Solr search core index](https://jira.xwiki.org/browse/XWIKI-23318)
* [XWIKI-23319: Index the document fullName for attachment and objects too in the Solr search core](https://jira.xwiki.org/browse/XWIKI-23319)
* [XWIKI-23428: Add a case insensitive Solr field for all StringProperty and ListProperty fields](https://jira.xwiki.org/browse/XWIKI-23428)
* Start indexing the `docId` long from XWikiDocument#getId() in the Solr search core (for all types, not just documents)
* Index fullName in all entries (instead of just DOCUMENT entries)
* Start copying automatically all `*_string` fields into a corresponding …
=> XWIKI-15166: SOLR reindexation job cause serious perfomance issues on large database

xwiki-platform-core/xwiki-platform-extension/xwiki-platform-extension-security/xwiki-platform-extension-security-api/src/main/java/org/xwiki/extension/security/internal/livedata/ExtensionSecurityLiveDataConfigurationResolver.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-api/src/main/java/org/xwiki/livedata/AbstractLiveDataConfigurationResolver.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-api/src/main/java/org/xwiki/livedata/internal/JSONMerge.java, xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-livetable/src/main/java/org/xwiki/livedata/internal/livetable/DefaultLiveDataConfigurationResolver.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-default/src/main/java/org/xwiki/notifications/filters/internal/livedata/custom/NotificationCustomFiltersLiveDataConfigurationResolver.java, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-filters/xwiki-platform-notifications-filters-default/src/main/java/org/xwiki/notifications/filters/internal/livedata/system/NotificationSystemFiltersLiveDataConfigurationResolver.java
https://jira.xwiki.org/browse/XWIKI-22130
* Define a common abstraction for all LiveDataConfigurationResolvers that are using LiveDataConfiguration to ensure that the ID is properly set and that the merge is used in the right way
* Use that new common abstraction in all existing resolvers
*
`mvn clean install -Pquality,integration-tests,docker` on `xwiki-platform-livedata`, `xwiki-platform-notifications`. Manual test performed to change the configuration of CustomNotificationFilterPreferences like illustrated in the ticket.
* 16.10.x
* 17.4.x
* 17.7.x
=> XWIKI-23451: Configuration of CustomNotificationFilterPreferences livedata cannot be overridden

xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-profile/xwiki-platform-user-profile-test/xwiki-platform-user-profile-test-docker/src/test/it/org/xwiki/user/test/ui/UserChangePasswordIT.java, xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-profile/xwiki-platform-user-profile-test/xwiki-platform-user-profile-test-pageobjects/src/main/java/org/xwiki/user/test/po/ChangePasswordPage.java
https://jira.xwiki.org/browse/XWIKI-20630
* Fixed the pageobject and the docker test that was failing.
* This is a fix for https://ci.xwiki.org/job/XWiki/job/xwiki-platform/job/stable-17.7.x/3/testReport/org.xwiki.user.test.ui/AllIT$NestedUserChangePasswordIT/Platform_Builds___main___integration_tests___IT_for_xwiki_platform_core_xwiki_platform_user_xwiki_platform_user_profile_xwiki_platform_user_profile_test_xwiki_platform_user_profile_test_docker___Build_for_IT_for_xwiki_platform_core_xwiki_platform_user_xwiki_platform_user_profile_xwiki_platform_user_profile_test_xwiki_platform_user_profile_test_docker___changePasswordWithWrongOriginalPassword/
None, test changes only
Built the changes with:
* `mvn clean install -f xwiki-platform-core/xwiki-platform-user/xwiki-platform-user-profile/xwik …
=> XWIKI-20630: Improve usability of the "Change Password" page

xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-war/src/main/webapp/resources/uicomponents/widgets/fullScreen.css
[XWIKI-17011](https://jira.xwiki.org/browse/XWIKI-17011)
* reset to 0 `margin-right`
*
Built with `mvn clean install xwiki-platform\xwiki-platform-core\xwiki-platform-web\xwiki-platform-web-war>` and tested manually with `fullScreen.css` and `fullScreen.min.css` on demo XWiki.
*
=> XWIKI-17011: Maximize link should be placed on the upper-right corner of a textarea

xwiki-platform-core/xwiki-platform-index/xwiki-platform-index-test/xwiki-platform-index-test-docker/src/test/it/org/xwiki/index/test/ui/docker/DynamicTestConfigurationExtension.java
https://jira.xwiki.org/browse/XWIKI-23463
* Compute the right mysql collation when forcing it to german for test purpose
*
* stable-17.7.x
=> XWIKI-23463: Errors with DocumentTreeMacroIT with Mysql UTF-8

xwiki-platform-core/xwiki-platform-bootstrap/src/main/less/dropdowns.less, xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-ui/src/main/resources/XWiki/Notifications/Code/NotificationsDisplayerUIX.xml
https://jira.xwiki.org/browse/XWIKI-22983
* Overridden the outline for focus of the notification toggle.
* Added a comment to keep track of this
* See comment on https://jira.xwiki.org/browse/XWIKI-22983 
With the changes in the PR applied:
We can see that the outline is displayed as expected.
Manual test only (see above), this is a minor style change so it doesn't impact docker tests.
* 17.4.X
=> XWIKI-22983: Focus highlight is not sufficient on topbar notifications button

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/companylogo.vm, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-theme/xwiki-platform-flamingo-theme-ui/src/main/resources/FlamingoThemesCode/ThemeClass.xml, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-theme/xwiki-platform-flamingo-theme-ui/src/main/resources/FlamingoThemesCode/ThemeSheet.xml, xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-theme/xwiki-platform-flamingo-theme-ui/src/main/resources/FlamingoThemesCode/Translations.xml
https://jira.xwiki.org/browse/XWIKI-22602
* Updated the flamingo theme class to add a text alternative
* Updated the theme editor
* Used the new variable in the template (default is the value used previously)
* Note that AFAIK this has no impact for sighted users. When hovering the picture, since it's part of the anchor with a title, the title of the anchor is shown ("Home"). However it's useful information for screen reader users and any assistive tech users :)
* I just took the first unused number for the `logo-description` field of the theme class. This means that in the class editor it's far from the `logo` field, but since this class has a custom editor it doesn't matter much. I'd rather do that than increment the numbers of all the fields after `logo`...
Here is a view of the …
=> XWIKI-22602: Provide a UI to easily customize the logo alternative text from the colorTheme

xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/java/org/xwiki/search/solr/internal/SolrIndexEventListener.java, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/test/java/org/xwiki/search/solr/internal/SolrIndexEventListenerTest.java
https://jira.xwiki.org/browse/XWIKI-23529
* Always index all translations when a document is created.
* Add a unit test.
* I'm not sure if this is the right fix, i.e., if we're ever supposed to be in the situation where a translation exists without the root locale document.
* It is not clear to me when this started, I couldn't find any test failures on 16.10.x even though the test is part of that branch.
No UI changes.
* built the changed module with the quality profile
* executed `xwiki-platform-search-test-docker` with the changes and some debug logs in the configuration with MySQL in which I previously reproduced the failure. The debug logs and the test confirm that now the document is indexed correctly.
* stable-17.4.x
* …
=> XWIKI-23529: Translated pages sometimes aren't indexed during extension installation

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/layout.less
https://jira.xwiki.org/browse/XWIKI-23551
* Added a transition on opacity
Local test.
`mvn clean install -f xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources -Pquality` successfully built.
* None
=> XWIKI-23551: Panel handle appearing is distracting

xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/action-menus.less, xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-webjar/src/main/webjar/searchSuggest.js
https://jira.xwiki.org/browse/XWIKI-23552
* Added wrap on the place where it was missing.
* Added optional chaining for sturdiness of the searchSuggest code.
* The searchSuggest line was erroring on my local instance. Adding [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) here prevented the error. Since the behaviour was working as expected, I figured it'd be a good enough fix.
Here's a demo of the responsiveness added by the new styles, focused on very low screen widths :)
https://github.com/user-attachments/assets/71563e58-234c-4fc2-9e08-3118b06d3a44
Manual tests on my local instance, as seen above.
Built the modules with quality checks successfully: 
* `mvn clean install -f …
=> XWIKI-23552: Search input outside viewport on small mobile devices

xwiki-platform-core/xwiki-platform-repository/xwiki-platform-repository-server-ui/src/main/resources/ExtensionCode/ExtensionSheet.xml
https://jira.xwiki.org/browse/XWIKI-23577
* Reverted the regressing change done in the context of XCOMMONS-3051
* See `https://github.com/xwiki/xwiki-platform/commit/c91ee943a20ac60f65de2c3901e8a7fc6cdc6167#r167248772`
None
The archive and current state of extension.xwiki.org shows that there's a regression. Adding this style back into the sheet locally fixed that regression.
* 17.4.X, 16.10.X
=> XWIKI-23577: Extension Sheet buttons have their icon displayed next to the button
